// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "FlightComponent.generated.h"

UCLASS( ClassNoGenerateOptions, meta = (BlueprintType, Category = "Flight") )
class CHIMERA_API UFlightComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UFlightComponent(const FObjectInitializer& ObjectInitializer);

protected:
	UPROPERTY(EditDefaultsOnly, Category = "Flight")
	float ThrustAcceleration;

	UPROPERTY(EditDefaultsOnly, Category = "Flight", meta = (ClampMin = "0"))
	float MaxSpeed;

	UPROPERTY(EditDefaultsOnly, Category = "Flight", meta = (ClampMin = "0"))
	float TurnRateDegreesPerSec;

	UPROPERTY(EditDefaultsOnly, Category = "Flight", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float InertiaDamping;

	UPROPERTY(VisibleAnywhere, Category = "Flight")
	FVector CurrentVelocity;

	UPROPERTY(EditDefaultsOnly, Category = "Fuel")
	float FuelCapacityLiters;

	UPROPERTY(VisibleAnywhere, Category = "Fuel")
	float CurrentFuel;

	UPROPERTY(EditDefaultsOnly, Category = "Fuel", meta = (ClampMin = "0"))
	float FuelConsumptionRatePerKm;

	UPROPERTY(VisibleAnywhere, Category = "Quantum")
	bool bIsQuantumJumping;

	UPROPERTY(EditDefaultsOnly, Category = "Quantum", meta = (ClampMin = "0"))
	float QuantumFuelCostLiters;

	UPROPERTY(EditDefaultsOnly, Category = "Quantum", meta = (ClampMin = "0"))
	float QuantumTravelTimeSeconds;

	UPROPERTY(VisibleAnywhere, Category = "Quantum")
	float QuantumCooldownRemaining;

public:
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	UFUNCTION(BlueprintCallable, Category = "Flight|Quantum")
	bool InitiateQuantumJump(const FVector& TargetLocation);

	UFUNCTION(BlueprintCallable, Category = "Flight|Fuel")
	float GetRemainingFuel() const;

	UFUNCTION(BlueprintCallable, Category = "Flight|Speed")
	float GetCurrentSpeedCms() const;

	UFUNCTION(BlueprintCallable, Category = "Flight|Quantum")
	bool IsQuantumJumping() const;

	UFUNCTION(BlueprintCallable, Category = "Flight|Quantum")
	bool CanQuantumJump() const;
