// Generated by GameCodeGenerator
#include "FlightComponent.h"
#include "GameFramework/Actor.h"
#include "Kismet/KismetMathLibrary.h"

UFlightComponent::UFlightComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer), ThrustAcceleration(25.0f), MaxSpeed(33333.333333333336f), TurnRateDegreesPerSec(90f), InertiaDamping(0.85f), CurrentVelocity(FVector::ZeroVector), CurrentFuel(0.0f), FuelConsumptionRatePerKm(0.5f), bIsQuantumJumping(false), QuantumFuelCostLiters(2000.0f), QuantumTravelTimeSeconds(30.0f), QuantumCooldownRemaining(0.0f)
{
	PrimaryComponentTick.bCanEverTick = true;
}

void UFlightComponent::InitializeFromShip(float FuelCapacity, float ConsumptionRatePerKm, float QuantumFuelCost, float QuantumTravelTime)
{
	FuelCapacityLiters = FuelCapacity;
	CurrentFuel = FuelCapacity;
	FuelConsumptionRatePerKm = ConsumptionRatePerKm;
	QuantumFuelCostLiters = QuantumFuelCost;
	QuantumTravelTimeSeconds = QuantumTravelTime;
}

void UFlightComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	if (bIsQuantumJumping)
{
		QuantumCooldownRemaining -= DeltaTime;
		if (QuantumCooldownRemaining <= 0.0f)
		{
			bIsQuantumJumping = false;
			QuantumCooldownRemaining = 0.0f;
		}
		return;
}

	if (CurrentFuel <= 0.0f)
{
		// No fuel - ship drifts with current velocity
	}
else
{
		// Read thrust input from owning actor (simplified: assume 0-1 range)
		float ThrustInput = 0.0f;
	if (GetOwner())
	{
		// In a real implementation, this would read from EnhancedInput or player state
		ThrustInput = 0.5f; // Placeholder for thrust input
	}

	// Apply thrust
	if (GetOwner())
	{
		FVector ForwardVector = GetOwner()->GetActorForwardVector();
		FVector Acceleration = ForwardVector * ThrustAcceleration * ThrustInput;
		CurrentVelocity += Acceleration * DeltaTime;
}

	// Inertia damping when not thrusting
	if (ThrustInput <= 0.0f)
{
		CurrentVelocity *= (1.0f - (1.0f - InertiaDamping) * DeltaTime);
}

	// Clamp to max speed
	float Speed = CurrentVelocity.Size();
	if (Speed > MaxSpeed)
{
		CurrentVelocity = CurrentVelocity.GetSafeNormal() * MaxSpeed;
		Speed = MaxSpeed;
}

	// Update position if owner exists
	if (GetOwner())
{
		FVector NewLocation = GetOwner()->GetActorLocation() + CurrentVelocity * DeltaTime;
		GetOwner()->SetActorLocation(NewLocation);
}

	// Consume fuel based on distance traveled
	float DistanceTraveledCm = Speed * DeltaTime;
	float FuelUsed = FuelConsumptionRatePerKm * (DistanceTraveledCm / 100000.0f); // Convert cm to km
	CurrentFuel -= FuelUsed;
}

bool UFlightComponent::InitiateQuantumJump(const FVector& TargetLocation)
{
	if (!CanQuantumJump())
	{
		return false;
	}

	// Deduct fuel
	CurrentFuel -= QuantumFuelCostLiters;

	// Set quantum jumping state
	bIsQuantumJumping = true;
	QuantumCooldownRemaining = QuantumTravelTimeSeconds;

	// In a real implementation, this would move the ship to target after travel time
	// For now, we just set the state and let the tick handle it

	return true;
}

float UFlightComponent::GetRemainingFuel() const
{
	return CurrentFuel;
}

float UFlightComponent::GetCurrentSpeedCms() const
{
	return CurrentVelocity.Size();
}

bool UFlightComponent::IsQuantumJumping() const
{
	return bIsQuantumJumping;
}

bool UFlightComponent::CanQuantumJump() const
{
	if (bIsQuantumJumping)
	{
		return false;
	}
	if (CurrentFuel < QuantumFuelCostLiters)
{
		return false;
}
	return true;
}
