// Generated by GameCodeGenerator
#pragma once
#include "CoreMinimal.h"
#include "AIController.h"
#include "PirateAIController.generated.h"
UCLASS()
class CHIMERA_API APirateAIController : public AAIController{
GENERATED_BODY()
public:
APirateAIController(const FObjectInitializer& ObjectInitializer);virtual void TickController(float DeltaTime) override;};