#!/usr/bin/env python3
"""Quick test: run Forge stages on the already-applied Writer changes."""

import json
import sys
import time
import urllib.request
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

WORKER_URL = "http://127.0.0.1:8892"
CHRONICLE_DIR = Path("E:/PythonChimera/worker_bridge/chronicle")
LOGS = []

def log(msg):
    print(msg)
    LOGS.append(msg)

def bash(cmd):
    body = json.dumps({"command": cmd}).encode()
    req = urllib.request.Request(f"{WORKER_URL}/api/bash", data=body, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=300) as r:
        return json.loads(r.read().decode())

def prompt(msg):
    body = json.dumps({"message": msg}).encode()
    req = urllib.request.Request(f"{WORKER_URL}/api/prompt", data=body, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=600) as r:
        result = json.loads(r.read().decode())
    deadline = time.time() + 300
    while time.time() < deadline:
        try:
            resp = urllib.request.urlopen(f"{WORKER_URL}/api/get_state", timeout=5)
            s = json.loads(resp.read().decode())
            if not s.get("data",{}).get("isStreaming", True):
                break
        except: pass
        time.sleep(3)
    return result

def last_msg():
    resp = urllib.request.urlopen(f"{WORKER_URL}/api/get_messages", timeout=5)
    msgs = json.loads(resp.read().decode())
    for m in reversed(msgs.get("data",{}).get("messages",[])):
        if m.get("role") == "assistant" and m.get("content"):
            t = m["content"]
            if isinstance(t, list):
                return "".join(s.get("text","") for s in t if s.get("type")=="text")
            return t
    return ""

log("\n" + "="*60)
log("GAUSSIAN FOUNDRY — FORGE VERIFICATION")
log("="*60)

# Stage 2: Builder
log("\n--- STAGE 2: BUILDER ---")
log("[BUILDER] Running Python syntax check...")
r = bash(r'cd E:/PythonChimera/Chimera && python -c "import py_compile,glob; files=[f for f in glob.glob(\"**/*.py\",recursive=True) if \"node_modules\" not in f and \".git\" not in f and \"Intermediate\" not in f]; errs=[f for f in files if not py_compile.compile(f,doraise=False)]; print(f\"{len(files)} files, {len(errs)} errors\"); [print(f\"  FAIL: {f}\") for f in errs]; exit(len(errs)>0)"')
out = r.get("data",{}).get("output","")
ec = r.get("data",{}).get("exitCode", -1)
log(f"  {out}")
if ec == 0:
    log("[BUILDER] BUILD PASSED")
else:
    log(f"[BUILDER] BUILD FAILED (exit {ec})")
    log("[LOGS] " + "\n".join(LOGS))
    exit(1)

# Stage 3: Reviewer
log("\n--- STAGE 3: REVIEWER ---")

# Get diff
r = bash("cd E:/PythonChimera && git diff --stat")
diff_stat = r.get("data",{}).get("output","")
r = bash("cd E:/PythonChimera && git diff")
diff = r.get("data",{}).get("output","")
log(f"  Diff: {diff_stat.strip()}")

conventions = """
CONVENTIONS:
- All Python functions have docstrings
- Error messages reference the function raising them
- Constants are UPPER_CASE
- No hardcoded paths
- UUIDs are generated by uuid4(), not hardcoded
"""

review_prompt = f"""Review this diff against project conventions:

```diff
{diff[:6000]}
```

{conventions}

Return verdict as JSON:
{{"approved": true/false, "issues": [...], "blockers": [...]}}
"""

log("[REVIEWER] Asking worker to review...")
prompt(review_prompt)
time.sleep(5)
verdict_text = last_msg()
log(f"\n  Reviewer says:\n  {verdict_text[:1500]}")

# Stage 4: Beats (placeholder)
log("\n--- STAGE 4: BEATS ---")
log("[BEATS] Sleepwalker check...")
r = bash("cd E:/PythonChimera/Chimera && python -c \"print('BEATS: files present'); import os; print('fractal_zoom_sweep:', os.path.exists('core/fractal_zoom_sweep.py'))\"")
log(f"  {r.get('data',{}).get('output','')}")

log(f"\n{'='*60}")
log("FORGE VERIFICATION COMPLETE")
log(f"{'='*60}")
