"""walker — a body that MOVES. The objective that cannot be faked.

THE WHOLE POINT
---------------
Static geometry cannot specify "creature". Three degenerate optima proved it on
2026-07-14 — a LOLLIPOP (boulder on a pole), a BLOB ON STILTS (minimally compliant),
and a MAST WITH OUTRIGGERS (legs sprawled flat on the ground, huge support polygon,
no mass, while a heavy rod held the centre of gravity high). Each scored beautifully.
Each was biologically absurd.

    Three exploits in a row is not a message about your parameters.
    It is a message about your FRAME.

A creature is not defined by how it STANDS. It is defined by what it DOES. So the
objective here is DISTANCE TRAVELLED, under real rigid-body physics, and it cannot be
gamed — because outriggers do not walk. A lollipop cannot chase anything.

THE CONTROLLER IS A CPG, AND THAT IS NOT A METAPHOR
---------------------------------------------------
Locomotion in real animals is generated by a Central Pattern Generator in the SPINAL
CORD, not the brain. A decerebrate cat still steps on a treadmill; a lamprey's swimming
rhythm survives complete removal of its head. So:

    angle_j(t) = offset_d + amp_d * sin(2*pi*f*t + phase_d + (pi if right else 0))

Parameters are indexed by tree DEPTH — every bone at the same level of the body shares
a rhythm — and LEFT and RIGHT limbs run in ANTIPHASE, which is exactly the
contralateral coupling that produces a quadruped gait. The genome grows the BODY and
encodes the RHYTHM, and they co-evolve. Karl Sims, 1994.

THE SKELETON *IS* THE MULTIBODY
-------------------------------
Bone.parent already gives a tree. That is precisely a Bullet articulated multibody:
one bone -> one link, one parent -> one revolute joint. The hinge axis is the natural
flexion axis, cross(parent_dir, bone_dir) — the plane the limb actually bends in. And
because the mesh is GROWN from the skeleton, the rig comes free: we know which bone
made every vertex.

FACTS ONLY. What makes a walk GOOD lives in docs/objectives/walker.json.
"""

from __future__ import annotations

import math
import random
from dataclasses import asdict

from core.terrarium import Genome, grow, MAX_DEPTH
from core.terrarium import mutate as _tmutate

# --- sim settings (test conditions, NOT genome) -------------------------------
DT = 1.0 / 240.0
SETTLE_STEPS = 120           # let it fall and settle before the clock starts
SIM_STEPS = 1400             # ~5.8 s of gait
DENSITY = 800.0              # kg/m^3
MAX_LINKS = 40               # a body bigger than this is not a creature, it is a cost
EVAL_SEED = 7

# --- THE EXPLOIT THAT INVALIDATED THE FIRST RUN (2026-07-14) ------------------
# The mass floor used to be `max(0.05, pi*r*r*L*rho)`. It exists because a zero-mass
# link is treated as STATIC by Bullet. But a bone of r=0.001 m and L=0.01 m has a TRUE
# mass of 25 micrograms — and the floor handed it 50 grams, a density of ~1.6 million
# kg/m^3. That is not bone. That is neutron-star matter.
#
# Every bone in the winner was pinned at that floor, so they all weighed the SAME
# regardless of size. The physics was a lie, and the optimiser found it: it evolved a
# tiny, absurdly dense whip that buzzed at the maximum 5 Hz and RATCHETED along the
# ground on friction asymmetry. A bristlebot, not an animal.
#
# It also noticed that `distance` is measured in BODY LENGTHS — so SHRINKING YOURSELF
# inflates the score for free. It did not learn to walk. It learned to be small.
#
# Three fixes, and they must all hold:
MASS_FLOOR = 1e-3            # 1 gram. Enough to keep Bullet from freezing a link, small
                             # enough that it never dominates real geometry.
MIN_BONE_LEN = 0.05          # a bone shorter than 5 cm is a degenerate stub. The winner
                             # had TWO bones of length exactly 0.00.
MIN_BONE_RAD = 0.004         # and thinner than 4 mm is a hair, not a limb.
BODY_SIZE_MIN = 0.5          # body-length normalisation is the RIGHT metric (it is the
BODY_SIZE_MAX = 8.0          # standard in locomotion research) but it is only fair
                             # between COMPARABLE bodies. Gate the size, and the "shrink
                             # to win" exploit has nowhere to go.
                             #
                             # SIZE IS SPATIAL EXTENT, NOT TOTAL BONE LENGTH. Summing
                             # every bone gives a 20-limbed animal 18 METRES of skeleton
                             # while it is only 5 m nose-to-tail — that is MATERIAL, not
                             # SIZE, and gating on it rejected the seed quadruped
                             # outright. Measure the bounding box.

_CLIENT = None               # one physics client per worker PROCESS


def _client():
    global _CLIENT
    import pybullet as p
    if _CLIENT is None:
        _CLIENT = p.connect(p.DIRECT)
    return _CLIENT


# --- genome: a BODY plus a RHYTHM --------------------------------------------

def seed() -> dict:
    return {
        "body": asdict(Genome.quadruped()),
        "freq": 1.8,                                   # Hz — the gait's tempo
        "torque": 14.0,                                # N·m ceiling per joint
        # per-DEPTH (offset, amplitude, phase). Bones at the same level of the body
        # share a rhythm; left/right are driven in antiphase (see _target).
        "cpg": [[0.0, 0.55, i * 0.7] for i in range(MAX_DEPTH + 2)],
    }


def mutate(g: dict, rng: random.Random) -> dict:
    import copy
    d = copy.deepcopy(g)
    d["body"] = asdict(_tmutate(Genome(**d["body"]), rng))

    def jit(v, frac, lo, hi):
        return max(lo, min(hi, v * (1.0 + rng.uniform(-frac, frac))))

    d["freq"] = jit(d["freq"], 0.25, 0.2, 5.0)
    d["torque"] = jit(d["torque"], 0.25, 1.0, 60.0)
    for row in d["cpg"]:
        if rng.random() < 0.5:
            row[0] = max(-1.2, min(1.2, row[0] + rng.uniform(-0.25, 0.25)))   # offset
        if rng.random() < 0.5:
            row[1] = max(0.0, min(1.4, row[1] + rng.uniform(-0.2, 0.2)))      # amplitude
        if rng.random() < 0.5:
            row[2] = (row[2] + rng.uniform(-0.9, 0.9)) % (2.0 * math.pi)      # phase
    return d


# --- skeleton -> Bullet multibody ---------------------------------------------

def _perp(d):
    a = (0.0, 0.0, 1.0) if abs(d[2]) < 0.9 else (1.0, 0.0, 0.0)
    c = (d[1] * a[2] - d[2] * a[1], d[2] * a[0] - d[0] * a[2], d[0] * a[1] - d[1] * a[0])
    m = math.sqrt(sum(x * x for x in c)) or 1.0
    return (c[0] / m, c[1] / m, c[2] / m)


def _quat_from_z_to(d):
    """Rotate the capsule's local +Z onto the bone direction d."""
    z = (0.0, 0.0, 1.0)
    dot = max(-1.0, min(1.0, d[2]))
    if dot > 0.9999:
        return [0.0, 0.0, 0.0, 1.0]
    if dot < -0.9999:
        return [1.0, 0.0, 0.0, 0.0]
    ax = (z[1] * d[2] - z[2] * d[1], z[2] * d[0] - z[0] * d[2], z[0] * d[1] - z[1] * d[0])
    m = math.sqrt(sum(x * x for x in ax)) or 1.0
    ax = (ax[0] / m, ax[1] / m, ax[2] / m)
    ang = math.acos(dot)
    s = math.sin(ang * 0.5)
    return [ax[0] * s, ax[1] * s, ax[2] * s, math.cos(ang * 0.5)]


def _build(p, c, bones, lift):
    """One bone -> one link. One parent -> one revolute joint. The skeleton already
    IS an articulated body; nothing needs translating.

    All link frames sit AT THE JOINT (bone.p0) and are axis-aligned with the world in
    the rest pose, so `linkPositions[i]` is simply p0_i - p0_parent. The link's
    inertial frame is offset to the bone's MIDPOINT, which is where a bone's mass
    actually is — putting the mass at the hip instead would give a leg completely the
    wrong swing dynamics, and gait is exactly what we are measuring."""
    n = len(bones)
    dirs, lens, cols, masses = [], [], [], []
    for b in bones:
        v = (b.p1[0] - b.p0[0], b.p1[1] - b.p0[1], b.p1[2] - b.p0[2])
        L = max(math.sqrt(sum(x * x for x in v)), 1e-4)
        d = (v[0] / L, v[1] / L, v[2] / L)
        r = max((b.r0 + b.r1) * 0.5, MIN_BONE_RAD)
        dirs.append(d)
        lens.append(L)
        cols.append(p.createCollisionShape(
            p.GEOM_CAPSULE, radius=r, height=L,
            collisionFrameOrientation=_quat_from_z_to(d), physicsClientId=c))
        # HONEST MASS: proportional to actual volume. The floor is 1 gram, not 50.
        masses.append(max(MASS_FLOOR, math.pi * r * r * L * DENSITY))

    def mid(i):
        return [dirs[i][0] * lens[i] * 0.5, dirs[i][1] * lens[i] * 0.5,
                dirs[i][2] * lens[i] * 0.5]

    positions, axes, parents = [], [], []
    for i, b in enumerate(bones):
        par = b.parent if (0 <= b.parent < i) else -1
        anchor = bones[par].p0 if par >= 0 else (0.0, 0.0, 0.0)
        positions.append([b.p0[0] - anchor[0], b.p0[1] - anchor[1],
                          b.p0[2] - anchor[2]])

        # PARENT INDEX. Bone 0 IS the base, so bone b maps to pybullet link (b-1), and
        # linkParentIndices wants (link_index + 1) — i.e. the BONE index — with 0
        # meaning "the base". So it is `par`, not `par + 1`. Getting this wrong by one
        # made every index point past the end, pybullet silently dropped ALL 19 links,
        # and the body came out as a single floating capsule.
        parents.append(par if par >= 1 else 0)

        # THE HINGE AXIS is the natural FLEXION axis: perpendicular to both the bone
        # and its parent, i.e. the plane the limb actually bends in. A knee does not
        # hinge sideways.
        pd = dirs[par] if par >= 0 else (0.0, 0.0, 1.0)
        di = dirs[i]
        ax = (pd[1] * di[2] - pd[2] * di[1],
              pd[2] * di[0] - pd[0] * di[2],
              pd[0] * di[1] - pd[1] * di[0])
        m = math.sqrt(ax[0] ** 2 + ax[1] ** 2 + ax[2] ** 2)
        axes.append([ax[0] / m, ax[1] / m, ax[2] / m] if m > 1e-6
                    else list(_perp(di)))

    k = n - 1
    return p.createMultiBody(
        baseMass=masses[0], baseCollisionShapeIndex=cols[0],
        basePosition=[0.0, 0.0, lift],
        baseInertialFramePosition=mid(0),
        linkMasses=masses[1:],
        linkCollisionShapeIndices=cols[1:],
        linkVisualShapeIndices=[-1] * k,
        linkPositions=positions[1:],
        linkOrientations=[[0, 0, 0, 1]] * k,
        linkInertialFramePositions=[mid(i) for i in range(1, n)],
        linkInertialFrameOrientations=[[0, 0, 0, 1]] * k,
        linkParentIndices=parents[1:],
        linkJointTypes=[p.JOINT_REVOLUTE] * k,
        linkJointAxis=axes[1:],
        physicsClientId=c)


def _target(cpg, freq, depth, side, t):
    """THE CPG. Left and right run in ANTIPHASE — contralateral coupling, which is
    what turns a rhythm into a GAIT rather than a twitch."""
    o, a, ph = cpg[min(depth, len(cpg) - 1)]
    return o + a * math.sin(2.0 * math.pi * freq * t + ph + (math.pi if side else 0.0))


# --- measure: FACTS about a body that tried to move ---------------------------

def _measure_once(g: dict, lift_jitter: float = 0.0) -> dict:
    import pybullet as p
    dead = {"exploded": 1.0, "distance": 0.0, "meters": 0.0, "speed": 0.0,
            "straightness": 0.0, "airborne_frac": 1.0, "energy": 999.0,
            "bones": 0.0, "torso_z": 0.0, "body_size": 0.0, "degenerate": 1.0}

    bones = grow(Genome(**g["body"]), EVAL_SEED)
    if not (5 <= len(bones) <= MAX_LINKS):
        return dead

    # A body made of zero-length stubs and 1 mm hairs is not a creature, and pretending
    # it is one is how the last run produced a neutron-dense bristlebot.
    for b in bones:
        if (math.dist(b.p0, b.p1) < MIN_BONE_LEN
                or (b.r0 + b.r1) * 0.5 < MIN_BONE_RAD):
            return dead

    body_len = sum(math.dist(b.p0, b.p1) for b in bones)      # MATERIAL (for energy)
    pts = [b.p0 for b in bones] + [b.p1 for b in bones]
    body_size = max(max(q[i] for q in pts) - min(q[i] for q in pts)   # SIZE (extent)
                    for i in range(3))
    if not (BODY_SIZE_MIN <= body_size <= BODY_SIZE_MAX):
        return dead                              # no shrinking your way to a high score
    zmin = min(min(b.p0[2], b.p1[2]) for b in bones)

    c = _client()
    p.resetSimulation(physicsClientId=c)
    p.setGravity(0, 0, -9.81, physicsClientId=c)
    p.setTimeStep(DT, physicsClientId=c)
    ground = p.createCollisionShape(p.GEOM_PLANE, physicsClientId=c)
    gid = p.createMultiBody(0, ground, physicsClientId=c)
    p.changeDynamics(gid, -1, lateralFriction=1.0, physicsClientId=c)

    try:
        uid = _build(p, c, bones, lift=-zmin + 0.05 + lift_jitter)   # jitter = the restart
    except Exception:
        return dead

    nj = p.getNumJoints(uid, physicsClientId=c)
    if nj == 0:
        return dead

    # which side of the sagittal plane is each joint on? (drives the antiphase)
    side = [bones[j + 1].p0[0] < 0.0 for j in range(nj)]
    depth = [bones[j + 1].depth for j in range(nj)]
    for j in range(nj):
        p.changeDynamics(uid, j, lateralFriction=1.2, physicsClientId=c)
    p.changeDynamics(uid, -1, lateralFriction=1.2, physicsClientId=c)

    for _ in range(SETTLE_STEPS):                    # fall, settle, THEN start the clock
        p.stepSimulation(physicsClientId=c)

    start = p.getBasePositionAndOrientation(uid, physicsClientId=c)[0]
    if not all(math.isfinite(x) for x in start):
        return dead

    cpg, freq, torque = g["cpg"], g["freq"], g["torque"]
    energy = 0.0
    airborne = 0
    path = 0.0
    prev = start
    zsum = 0.0

    for step in range(SIM_STEPS):
        t = step * DT
        for j in range(nj):
            p.setJointMotorControl2(uid, j, p.POSITION_CONTROL,
                                    targetPosition=_target(cpg, freq, depth[j],
                                                           side[j], t),
                                    force=torque, physicsClientId=c)
        p.stepSimulation(physicsClientId=c)

        if step % 8 == 0:
            pos = p.getBasePositionAndOrientation(uid, physicsClientId=c)[0]
            if not all(math.isfinite(x) for x in pos) or abs(pos[2]) > 40.0:
                return dead                          # physics exploded
            path += math.dist(pos[:2], prev[:2])
            prev = pos
            zsum += pos[2]
            if not p.getContactPoints(bodyA=uid, bodyB=gid, physicsClientId=c):
                airborne += 1
            for j in range(nj):
                st = p.getJointState(uid, j, physicsClientId=c)
                energy += abs(st[3] * st[1]) * DT * 8   # |torque * omega| dt

    end = p.getBasePositionAndOrientation(uid, physicsClientId=c)[0]
    if not all(math.isfinite(x) for x in end):
        return dead

    net = math.dist(end[:2], start[:2])
    samples = SIM_STEPS // 8
    return {
        "exploded": 0.0,
        "degenerate": 0.0,
        "body_size": body_size,                      # SPATIAL EXTENT. Gated 0.5-8.0 m.
        "distance": net / body_size,                 # body lengths — fair now, because
        "meters": net,                               # sizes are gated to be comparable
        "speed": (net / body_size) / (SIM_STEPS * DT),
        "straightness": net / max(path, 1e-6),       # net over path: spinning pays nothing
        "airborne_frac": airborne / max(samples, 1),
        "energy": energy / max(body_len, 1e-6),      # cost per unit of MATERIAL
        "torso_z": (zsum / max(samples, 1)) / body_size,
        "bones": float(len(bones)),
    }


# ---------------------------------------------------------------------------
# HONEST EVALUATION — the doctrine, finally implemented here (2026-07-16)
# ---------------------------------------------------------------------------
# "One rollout is a coin toss, not a measurement... score every genome from N randomized
# starts and keep the WORST." It is in CLAUDE.md, in TRAINING_PROTOCOL.md §3.5, and it is
# the stated justification for the 16x eval cost and the entire GPU migration.
#
# N_RESTARTS existed in exactly ONE module in this repo: brain_gpu. walker.measure() was
# a SINGLE rollout from ONE exact pose — the precise thing the doctrine calls a coin toss
# — and its winner is not just any artifact: brain_cpu.py:80 loads walker.trained.json as
# "The FIXED body. Grown once, reused for every brain, forever." EVERY BRAIN THIS STUDIO
# HAS EVER TRAINED STANDS ON A BODY THAT WAS SELECTED BY A COIN TOSS.
#
# WHY IT MUST BE PAID HERE, ON THE CPU: morphology is NOT GPU-trainable — mujoco-warp
# batches N copies of ONE model, so evolving BODIES cannot leave the CPU (CLAUDE.md:
# "evolve bodies on CPU MuJoCo, brains on GPU"). The doctrine does not become optional
# because the hardware is inconvenient; the cost is simply real.
#
# N=4, not 16, and that is a DECLARED COMPROMISE rather than a silent one. 4 restarts
# catch gross luck at 4x the cost; 16 would be stricter and the CPU cannot afford it.
# That gap IS the argument for the GPU, and morphology cannot go there — so this is the
# honest ceiling, stated, not hidden.
N_RESTARTS = 4
LIFT_JITTER = 0.02          # +/-2 cm of start height, matching brain_gpu's perturbation


def measure(g: dict) -> dict:
    """WORST of N randomized starts. Reports `robustness` = worst/mean, the anti-lottery.

    A body that walks from one exact pose and falls over 2 cm higher has not learned to
    stand; it has learned that pose. Only the worst case survives contact with a player.
    """
    import random as _random
    rng = _random.Random(EVAL_SEED)
    runs = []
    for i in range(N_RESTARTS):
        jitter = 0.0 if i == 0 else rng.uniform(-LIFT_JITTER, LIFT_JITTER)
        runs.append(_measure_once(g, lift_jitter=jitter))

    # A single explosion or degenerate body condemns the genome — the worst case IS the
    # measurement, so any restart that died is the one that counts.
    if any(r.get("exploded", 0.0) >= 1.0 for r in runs):
        return dict(runs[0], exploded=1.0)
    if any(r.get("degenerate", 0.0) >= 1.0 for r in runs):
        return dict(runs[0], degenerate=1.0)

    def worst(k, hi_is_bad=False):
        v = [float(r.get(k, 0.0)) for r in runs]
        return max(v) if hi_is_bad else min(v)

    d = [float(r.get("distance", 0.0)) for r in runs]
    d_worst, d_mean = min(d), (sum(d) / len(d))
    out = dict(runs[0])                      # body facts (bones, body_size) are invariant
    out.update({
        "distance": d_worst,                 # THE HEADLINE IS THE WORST, per the rule
        "distance_worst": d_worst,
        "distance_mean": d_mean,
        "robustness": d_worst / max(d_mean, 1e-6),   # ~1.0 = a real gait; ~0 = a lottery
        "meters": worst("meters"),
        "speed": worst("speed"),
        "straightness": worst("straightness"),
        "torso_z": worst("torso_z"),
        "airborne_frac": worst("airborne_frac", hi_is_bad=True),
        "energy": worst("energy", hi_is_bad=True),
    })
    return out
