// Generated by GameCodeGenerator
#include "Player_PilotCharacterCharacter.h"
#include "GameplayAbilitySystemComponent.h"
#include "AttributeSet.h"

UPlayer_PilotCharacterCharacter::UPlayer_PilotCharacterCharacter(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	// Create and initialize GAS components
	AbilitySystemComponent = CreateDefaultSubobject<UGameplayAbilitySystemComponent>(TEXT('AbilitySystemComponent'));
	AttributeSet = CreateDefaultSubobject<UAttributeSet>(TEXT('AttributeSet'));
}
