// Generated by GameCodeGenerator - Erisaid Resonance Visual Effects Component
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "NiagaraComponent.h"
#include "NiagaraSystem.h"
#include "ErisaidResonanceVFXComponent.generated.h"

UCLASS(meta=(BlueprintType, Category="VFX|Erisaid"))
class CHIMERA_API UErisaidResonanceVFXComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UErisaidResonanceVFXComponent(const FObjectInitializer& ObjectInitializer);

protected:
	virtual void BeginPlay() override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

public:
	UPROPERTY(EditDefaultsOnly, Category = "VFX|Resonance")
	TObjectPtr<UNiagaraSystem> ResonanceVisualEffect;

	UPROPERTY(EditDefaultsOnly, Category = "VFX|Resonance")
	TObjectPtr<UNiagaraSystem> InterferenceShimmerEffect;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VFX|Intensity")
	float ResonanceIntensity;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VFX|Intensity", meta=(ClampMin="0.0", ClampMax="1.0"))
	float MinVisibilityThreshold;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VFX|Aesthetics")
	bool bEnableStandingWaveEdges;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VFX|Aesthetics")
	bool bEnableInterferenceShimmer;

	UFUNCTION(BlueprintCallable, Category = "VFX|Erisaid")
	void ActivateResonanceVisuals();

	UFUNCTION(BlueprintCallable, Category = "VFX|Erisaid")
	void DeactivateResonanceVisuals();

	UFUNCTION(BlueprintCallable, Category = "VFX|Erisaid")
	void SetResonanceIntensity(float NewIntensity);

private:
	TObjectPtr<UNiagaraComponent> ResonanceNiagaraComp;
	TObjectPtr<UNiagaraComponent> ShimmerNiagaraComp;

	bool bVisualsActive;

	void SetupNiagaraComponents();
	
	void UpdateVisualIntensity(float Intensity);
};
