// Generated by GameCodeGenerator
#include "AShip_Trader_Vessel_Alpha.h"
AAShip_Trader_Vessel_Alpha::AAShip_Trader_Vessel_Alpha(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer), FuelCapacityLiters(10000), CargoCapacityKg(50000), ShieldCapacity(1000.0), ShieldRegenRate(50.0), HullHealth(5000.0)
{
	PrimaryActorTick.bCanEverTick = true;
}

void AAShip_Trader_Vessel_Alpha::BeginPlay()
{
	Super::BeginPlay();

	// Create and attach flight component
	if (!FlightComponent)
	{
		FlightComponent = CreateDefaultSubobject<UFlightComponent>(TEXT('FlightComponent'));
	}

	// Initialize flight component with ship-specific parameters
	if (FlightComponent)
	{
		FlightComponent->InitializeFromShip(FuelCapacityLiters, 0.5f, 2000.0f, 30.0f);
	}

	// Create and attach combat components
	if (!WeaponComponent)
	{
		WeaponComponent = CreateDefaultSubobject<UWeaponComponent>(TEXT('WeaponComponent'));
	}

	if (!ShieldComponent)
	{
		ShieldComponent = CreateDefaultSubobject<UShieldComponent>(TEXT('ShieldComponent'));
	}

	if (!DamageComponent)
	{
		DamageComponent = CreateDefaultSubobject<UDamageComponent>(TEXT('DamageComponent'));
	}

	if (!SystemDamageComponent)
	{
		SystemDamageComponent = CreateDefaultSubobject<USystemDamageComponent>(TEXT('SystemDamageComponent'));
	}

	if (!CombatTargetComponent)
	{
		CombatTargetComponent = CreateDefaultSubobject<UCombatTargetComponent>(TEXT('CombatTargetComponent'));
	}

	// Initialize combat components with ship-specific values
	if (ShieldComponent)
	{
		ShieldComponent->InitializeFromShip(ShieldCapacity, ShieldRegenRate);
	}

	if (DamageComponent)
	{
		DamageComponent->InitializeFromShip(HullHealth);
	}

	// TODO: Add subsystem names from ship DSL systems for SystemDamageComponent initialization
	if (SystemDamageComponent)
{
	TArray<FName> SubsystemNames;
	SubsystemNames.Add("Engines");
	SubsystemNames.Add("Weapons");
	SubsystemNames.Add("LifeSupport");
	SystemDamageComponent->InitializeFromShip(SubsystemNames);
}

