// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "../Flight/FlightComponent.h"
#include "../Combat/WeaponComponent.h"
#include "../Combat/ShieldComponent.h"
#include "../Combat/DamageComponent.h"
#include "../Combat/SystemDamageComponent.h"
#include "../Combat/CombatTargetComponent.h"
#include "AShip_Trader_Vessel_Alpha.generated.h"

UCLASS()
class CHIMERA_API AAShip_Trader_Vessel_Alpha : public AActor
{
	GENERATED_BODY()

public:
	AAShip_Trader_Vessel_Alpha(const FObjectInitializer& ObjectInitializer);

protected:
	UPROPERTY(EditDefaultsOnly, Category = "Ship")
	FName ShipCategory;

	UPROPERTY(EditDefaultsOnly, Category = "Ship", meta = (ClampMin = "0"))
	float FuelCapacityLiters;

	UPROPERTY(EditDefaultsOnly, Category = "Ship", meta = (ClampMin = "0"))
	int32 CargoCapacityKg;

	UPROPERTY(EditDefaultsOnly, Category = "Combat")
	float ShieldCapacity;

	UPROPERTY(EditDefaultsOnly, Category = "Combat")
	float ShieldRegenRate;

	UPROPERTY(EditDefaultsOnly, Category = "Combat")
	float HullHealth;

	UPROPERTY(VisibleAnywhere, Category = "Components")
	UFlightComponent* FlightComponent;

	UPROPERTY(VisibleAnywhere, Category = "Combat Components")
	UWeaponComponent* WeaponComponent;

	UPROPERTY(VisibleAnywhere, Category = "Combat Components")
	UShieldComponent* ShieldComponent;

	UPROPERTY(VisibleAnywhere, Category = "Combat Components")
	UDamageComponent* DamageComponent;

	UPROPERTY(VisibleAnywhere, Category = "Combat Components")
	USystemDamageComponent* SystemDamageComponent;

	UPROPERTY(VisibleAnywhere, Category = "Combat Components")
	UCombatTargetComponent* CombatTargetComponent;

public:
	virtual void BeginPlay() override;
