// Generated by GameCodeGenerator
#include "FactionComponent.h"
#include <cmath>

UFactionComponent::UFactionComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}

void UFactionComponent::InitializeFromDSL()
{
	// Hostile: start at -50, Neutral: 0, Friendly: +25
	FactionRelationships.Add("Hostile");
	FactionRelationships.Add("Unfriendly");
	FactionRelationships.Add("Neutral");
	FactionRelationships.Add("Friendly");
	FactionRelationships.Add("Allied");
}

void UFactionComponent::ModifyStanding(FName FactionID, float Amount)
{
	if (!FactionStandings.Contains(FactionID))
	{
		FactionStandings.Add(FactionID, 0.0f);
	}
	float CurrentStanding = FactionStandings[FactionID] + Amount;
	CurrentStanding = FMath::Clamp(CurrentStanding, -100.0f, 100.0f);
	FactionStandings[FactionID] = CurrentStanding;

	// Recalculate relationship:
	if (CurrentStanding <= -75.0f)
		FactionRelationships[FactionID] = "Hostile";
	else if (CurrentStanding <= -25.0f)
		FactionRelationships[FactionID] = "Unfriendly";
	else if (CurrentStanding <= +24.0f)
		FactionRelationships[FactionID] = "Neutral";
	else if (CurrentStanding <= +74.0f)
		FactionRelationships[FactionID] = "Friendly";
	else
		FactionRelationships[FactionID] = "Allied";
}

float UFactionComponent::GetStanding(FName FactionID) const
{
	if (FactionStandings.Contains(FactionID)) return FactionStandings[FactionID];
	return 0.0f;
}

FString UFactionComponent::GetRelationship(FName FactionID) const
{
	if (FactionRelationships.Contains(FactionID)) return FactionRelationships[FactionID];
	return "Neutral";}

bool UFactionComponent::IsHostile(FName FactionID) const
{
	if (FactionRelationships.Contains(FactionID))
		return FactionRelationships[FactionID] == "Hostile";	return false;
}
