#!/usr/bin/env python3
"""MAT2-W09: render REPORT.md from the bound receipts.

No hand-transcribed numbers: every numeric literal rendered here comes from
a receipt artifact, and lint_report_numbers.py proves the report's numeric
literals trace to those receipts.

Run:  python -B make_report.py
Exit: 0 green / 2 refusal.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = Path(os.environ.get("CHIMERA_OUTPUT_DIR") or (HERE / "receipts"))


def load(name):
    """Read a bound receipt: the runner's declared-outputs directory first,
    then the contribution's own receipts directory (the assembled final
    package carries the bound bytes)."""
    for base in (OUT, HERE / "receipts"):
        p = base / name
        if p.exists():
            return json.loads(p.read_bytes().decode("utf-8"))
    raise SystemExit("REFUSAL: report_missing_receipt:" + name)
    raise SystemExit("REFUSAL: report_missing_receipt:" + name)


def main() -> int:
    main_r = load("out_of_envelope_receipt.json")
    checks = load("checks_receipt.json")
    falsifier = load("falsifier_receipt.json")
    capture = load("capture_receipt.json")
    pins = load("input_pins.json")
    arms = main_r["arms"]
    preds = main_r["predictions"]
    ident = main_r["identity"]

    def pf(key):
        return "PASS" if preds[key]["pass"] else "RED"

    a1 = arms["A1_unsupported_probe"]
    a2 = arms["A2_fall_injection"]
    a0 = arms["A0_baseline"]
    fb = main_r["falsifiers"]

    lines = []
    add = lines.append
    add("# REPORT — MAT2-W09 explicit out-of-envelope behavior\n")
    add("GENERATED by make_report.py from the bound receipts; every number "
        "is rendered at recorded precision and lint-verified "
        "(lint_report_numbers.py). Composed against CARD_STARTER v3; house "
        "standards IMPLEMENTER_CHECKLIST.md (G1-G9) and TOOLKIT.md (P1-P9) "
        "cited at the candidate commit. CPU-only; the capture is a "
        "record-space motion fixture of the executed arms' own telemetry, "
        "not a screenshot substitute (the profile numerical evidence is the "
        "receipt suite).\n")
    add("## 1. done_when verification (verbatim clause -> evidence)\n")
    add('done_when (verbatim): "Unsupported states and falls have a '
        'declared controller response; no concealed resets or forces"\n')
    add("| clause | execution | result |")
    add("| --- | --- | --- |")
    add("| unsupported states have a DECLARED controller response | the A1 "
        "declared probe produced %d unsupported intervals; the first "
        "opened at tick %d and ran %d ticks (the declared trip cascade: "
        "mp-pad zero-crossing entry spike trips BOTH legs -> halved phase "
        "rate stretches the window past the horizon); every pre-fall "
        "interval opened with a recorded R1_engage ledger event; on every "
        "pre-fall unsupported tick the applied stride channels equal the "
        "certified minimum drive %r (a_com = %r m/s^2 exactly); coverage "
        "audit: %d uncovered intervals | %s |"
        % (a1["interval_count"], a1["first_interval"][0],
           a1["first_interval_length"], 0.2,
           main_r["response_table"]["a_com_r1_m_s2"],
           len(a1["coverage_audit"]["uncovered_intervals"]),
           pf("P4_r1_coverage")))
    add("| falls have a DECLARED controller response | the declared trip "
        "cascade PRODUCES a sustained fall: the fall was declared "
        "NATURALLY at tick %d of the A1 arm (trips at the fall: %s); the "
        "R2 neutral response LATCHED to terminal (amendment A3, recovery "
        "not implemented); the declared A2 monitor-input injection "
        "additionally exercised the response on the certified line: R1 "
        "from tick %d, R2_fall_declared at tick %d, neutral commands "
        "latched, the fall event recorded ONCE, seam truth SUPPORTED "
        "throughout (labeled monitor_input_injection, never passed off as "
        "scene physics) | %s |"
        % (a1["fall_declared_tick"], a1["trips_at_fall"],
           a2["injection"]["t0"], a2["fall_declared_tick"],
           pf("P7_fall_injection")))
    add("| no concealed resets | the fresh-seed PCG64 draw-chain replay, "
        "the two-rate phase recursion and the velocity recursion hold with "
        "zero violations on every clean arm (A0/A1/A2 detector batteries "
        "all zero); the concealed-reset falsifier FIRES on the tampered arm "
        "(draw-chain + velocity + phase) while its clean control stays "
        "green; the only restart instrument is the declared "
        "COMPLETE-snapshot restore, ledgered, and none was performed | %s |"
        % pf("P8_no_concealed_reset_clean"))
    add("| no concealed forces | the velocity recursion identity (drive "
        "owner census: a_com from the recorded applied strides; d_eff from "
        "the declared warm recursion cross-checked against foot_forces on "
        "steady-contact ticks, worst steady residual %r) closes on every "
        "clean arm; the concealed-force falsifier FIRES at residual %r m/s "
        "on the tampered arm (window %r); removing support removes its "
        "force: both foot force channels exactly 0.0 on every unsupported "
        "tick | %s |"
        % (a1["detectors"]["warm_force_crosscheck"]["max_steady_residual"],
           fb["FB2_concealed_force"]["discriminator_residual_m_s"],
           a1["detectors"]["velocity_recursion"]["window_m_s"],
           pf("P5_inertia_law") + "/" + pf("P6_support_force_removed")))
    add("| inertia preserved (never freeze/cancel velocity) | velocity "
        "changed at every tick of A1 (never_frozen=true), moving ONLY by "
        "the declared equation v' = v + dt*(a_com - d_eff*v) within window "
        "%r m/s; during R1 the com coasts at the certified minimum drive "
        "with declared damping only | %s |"
        % (a1["detectors"]["velocity_recursion"]["window_m_s"],
           pf("P5_inertia_law")))
    add("| animation never substitutes for locomotion | every delivered "
        "record is byte-equal to the scene's own observation_record() on "
        "the clean arms; the animation-substitution falsifier FIRES "
        "(%d mismatch ticks) on the fabricated-delivery arm while its "
        "clean control is byte-equal | %s |"
        % (len(fb["FB3_animation_substitution"]["tamper"]["comparison"]
               ["mismatch_ticks"]), pf("P9_falsifiers_bite")))
    add("")

    add("## 2. The declared response table (registered BEFORE any run; the "
        "card's deliverable)\n")
    add("| observed state (seam) | response | declared action | physical "
        "accounting |")
    add("| --- | --- | --- | --- |")
    add("| SUPPORTED | R0 pass-through | frozen policy applied, identity | "
        "bounded applied; drive work only via stride channels; "
        "warm-coupled declared damping |")
    add("| UNSUPPORTED (streak < 90) | R1 drive cut | stride channels -> "
        "bounds_lo 0.2 (certified minimum; the limiter forbids zero) | "
        "a_com = %r m/s^2 exactly; v evolves ONLY by the declared equation "
        "(inertia preserved); pads report 0.0 force; warm decays by the "
        "declared law |"
        % (main_r["response_table"]["a_com_r1_m_s2"],))
    add("| FALL (streak >= 90) | R2 neutral + fall event (LATCHED) | all 8 "
        "channels -> manifest center; fall event once with pre-state hash; "
        "the neutral response holds until terminal; NO reset | commands "
        "carry no drive beyond neutral; the energy account keeps closing |")
    add("| terminal | R3 outcome declaration | outcome + final state hash; "
        "restart only via COMPLETE-snapshot restore (ledgered) | explicit "
        "post-failure behavior; recovery skill: none (optional per card "
        "observation) |")
    add("")

    add("## 3. Identity\n")
    add("- Card MAT2-W09 (planning id W09, slot 3), agent `wk-w09-envelope`, "
        "attempt `%s`." % main_r["attempt_id"])
    add("- Criteria sha256 `%s` (join == registry read-only re-read; "
        "registry revision %s, card state %s)."
        % (main_r["criteria_sha256"], pins["registry"]["registry_revision"],
           pins["registry"]["card_state"]))
    add("- Base: `%s` (the seeded `refs/remotes/origin/review/MAT2-W09`, "
        "the accepted astra/gait-capture tip; contains the MAT2-W07 merge, "
        "PR #301). Preregistration sha256 `%s` (sealed prereg-first; the "
        "implementation files never preceded it)."
        % (main_r["base_commit"], main_r["preregistration_sha256"]))
    add("- Certificate: the pinned W4 record re-validated VALID; deploy "
        "gate %s on the certified tuple; trained bundles loaded: %s; the "
        "W07 frozen anchor constants cross-read from the pinned bytes: %s."
        % (ident["deploy_decision"], ident["trained_bundles_loaded"],
           ident["w07_anchor_crosscheck"]["verdict"]))
    add("- Pins: %d/%d byte-exact at run time (store, tree-at-base, lane "
        "machinery, spike)."
        % (pins["pins_ok"], pins["pins_total"]))
    add("")

    add("## 4. The arms (all through the certified command channel)\n")
    add("| arm | outcome |")
    add("| --- | --- |")
    add("| A0 baseline (validity instrument) | the certified line "
        "reproduces the three anchors EXACT (%s) and the sealed 60-event "
        "chain byte-identical; the observation-only monitor recorded the "
        "line's OWN unsupported visits (%d ticks of 900 - a declared "
        "finding about the certified line, amendment A4) and emitted %d "
        "response events (observation-only by design) |"
        % ("/".join(v["verdict"] for v in a0["anchors"].values()),
           preds["P2_line_observation"]
           ["unsupported_ticks_on_the_certified_line"],
           a0["ledger_events"]))
    add("| A1 declared unsupported probe | %d unsupported intervals; the "
        "first opened at tick %d and ran %d ticks (the declared trip "
        "cascade); the fall was declared NATURALLY at tick %d (trips at "
        "the fall %s); R2 latched to terminal; coverage %s; max |v| %r m/s "
        "inside the derived envelope %r m/s |"
        % (a1["interval_count"], a1["first_interval"][0],
           a1["first_interval_length"], a1["fall_declared_tick"],
           a1["trips_at_fall"],
           "exact" if not a1["coverage_audit"]["uncovered_intervals"]
           else "GAPS", a1["max_abs_v_m_s"], a1["velocity_envelope_m_s"]))
    add("| A2 declared fall injection | R1 engaged at tick %d; "
        "R2_fall_declared at tick %d and LATCHED to terminal; seam truth "
        "SUPPORTED throughout (label: monitor_input_injection); terminal "
        "outcome %s |"
        % (a2["injection"]["t0"], a2["fall_declared_tick"],
           a2["terminal"]["outcome"]))
    add("")

    add("## 5. Falsifier proof (clean control FIRST, named guard, "
        "discriminator)\n")
    add("| arm | clean control | tampered | bites | discriminator |")
    add("| --- | --- | --- | --- | --- |")
    add("| FB1_concealed_reset | detectors all green; tick %d snapshot vs "
        "tick %d concealed restore inside the first produced window | draw "
        "chain + velocity + phase all fire | yes | the micro-terrain stream "
        "REPLAYS from the rewound state (the fresh-seed chain breaks at the "
        "restore tick) while the clean arm's chain holds to the declared "
        "window |"
        % (fb["FB1_concealed_reset"]["tamper"]["snapshot_tick"],
           fb["FB1_concealed_reset"]["tamper"]["restore_tick"]))
    add("| FB2_concealed_force | detectors all green | silent %r m/s "
        "impulse outside the command channel at tick %d | yes | velocity "
        "recursion residual %r m/s, orders of magnitude above the declared "
        "window %r m/s; the clean arm closes |"
        % (fb["FB2_concealed_force"]["tamper"]["dv_m_s"],
           fb["FB2_concealed_force"]["tamper"]["tick"],
           fb["FB2_concealed_force"]["discriminator_residual_m_s"],
           a1["detectors"]["velocity_recursion"]["window_m_s"]))
    add("| FB3_animation_substitution | delivered == solved byte-equal on "
        "every tick | stale-com_vel delivery from tick %d | yes | %d "
        "mismatch ticks; the scene keeps solving while the delivered "
        "'locomotion' is a frozen animation |"
        % (fb["FB3_animation_substitution"]["tamper"]["from_tick"],
           len(fb["FB3_animation_substitution"]["tamper"]["comparison"]
               ["mismatch_ticks"])))
    add("| FB4_stale_support | every unsupported interval opened with a "
        "declared R1 event | a stale verdict monitor (G07 FB5 class) keeps "
        "claiming support | yes | %d unsupported interval(s) left with no "
        "declared response |"
        % (len(fb["FB4_stale_support"]["tamper"]["audit"]
               ["uncovered_intervals"])))
    add("")
    add("F_all_green: %s (4 arms; every arm's clean control ran first; "
        "premature guards recorded per arm)."
        % str(falsifier["F_all_green"]))
    add("")

    add("## 6. Predictions (registered before the load; amendment a1 "
        "supersedes the pre-amendment algebra; all final-run values "
        "observed)\n")
    add("| prediction | observed |")
    add("| --- | --- |")
    for key in ("P1_anchors_exact", "P2_line_observation",
                "P3_natural_fall_produced", "P4_r1_coverage",
                "P5_inertia_law", "P6_support_force_removed",
                "P7_fall_injection", "P8_no_concealed_reset_clean",
                "P9_falsifiers_bite", "P10_structural_records"):
        add("| %s | %s |" % (key, pf(key)))
    add("")

    add("## 7. Structural records (amendment a1: the corrected cascade)\n")
    s = main_r["structural"]
    add("- %s: the sustained fall (>= %d consecutive unsupported ticks) is "
        "REACHABLE and was PRODUCED: first interval %s (length %d), fall "
        "declared at tick %d, trips at the fall %s — the declared cascade "
        "(mp zero-crossing entry spike -> both legs trip -> halved phase "
        "rate) is the produced mechanism. The pre-amendment "
        "unreachability claim was REFUTED and is disclosed in the "
        "amendment."
        % ("VERIFIED" if
           s["sustained_fall_reachable_and_produced"]["verdict"]
           else "REFUTED",
           s["sustained_fall_reachable_and_produced"]["fall_after_ticks"],
           s["sustained_fall_reachable_and_produced"]["first_interval"],
           s["sustained_fall_reachable_and_produced"]["first_interval_length"],
           s["sustained_fall_reachable_and_produced"]["fall_declared_tick"],
           s["sustained_fall_reachable_and_produced"]["trips_at_fall"]))
    add("- %s: the declared trip reflex is REACHABLE and was PRODUCED at "
        "the window entry (trips at the fall %s; trip counters at horizon "
        "end %s after the declared countdown; observed half-rate ticks: "
        "%s). The pre-amendment unreachability claim was REFUTED and is "
        "disclosed in the amendment."
        % ("VERIFIED" if s["trip_reflex_reachable_and_produced"]["verdict"]
           else "REFUTED",
           s["trip_reflex_reachable_and_produced"]["trips_at_fall"],
           s["trip_reflex_reachable_and_produced"]["trip_counters_at_horizon_end"],
           s["trip_reflex_reachable_and_produced"]["half_rate_ticks"]))
    add("")

    add("## 8. Named checks (G12 accounting)\n")
    add("- Suite: %s." % checks["suite"])
    add("- Accounting claim: **%s**; known skips: %s; pass: %s."
        % (checks["accounting_claim"], checks["known_skips"],
           str(checks["pass"]).lower()))
    add("")

    add("## 9. Capture identity (walking/motion profile)\n")
    add("- Honesty label: %s" % capture["honesty_label"])
    add("- FFV1 `-level 3 -g 1 -fflags +bitexact` mkv (bgr0), "
        "capture_sha256 %s; %s." % (capture["capture_sha256"],
                                    capture["ffmpeg"]))
    add("- Frames: %s declared snapshot ticks at 0.1 video seconds per "
        "frame; state (record) hash identical across each diagnostic/clean "
        "pair (view toggles preserve the physical state); tick axis real, "
        "tick_interval %s, one tick = 1/300 s."
        % (capture["frames"], capture["tick_interval"]))
    add("- G4: decode pixel-exact on the declared probe frames: %s."
        % capture["g4_pixel_exact"])
    add("- Validator: CAMERA_METADATA_STRUCTURE_ONLY; structurally_valid "
        "%s; visual_acceptance false (independent visual review remains "
        "the Sergeant's)." % str(capture["structurally_valid"]).lower())
    add("- This text-only worker inspected no pictures: pixel claims are "
        "MEASURED decode checks and image review is owned by the "
        "Sergeant/Lieutenant.")
    add("")

    add("## 10. Honest limitations\n")
    add("- The execution vehicle is the DECLARED SURROGATE scene "
        "(cpu-walk-scene/1.0.0, build %s); the adopted assembly is not a "
        "runtime body and the product engine has no live control path "
        "(W07 N1/N2/N3 carried, never re-opened)." % ident["build_id"])
    add("- Amendment a1 corrected this document's gap algebra BEFORE the "
        "final gated runs: the sustained fall and the trips are REACHABLE "
        "and were PRODUCED (the declared trip cascade, section 7); the "
        "superseded unreachability claims and the two development runs "
        "that refuted them are disclosed and preserved, never cited as "
        "final-run evidence. The A2 injection stays declared and labeled "
        "as such, never passed off as scene physics.")
    add("- No impact/landing accounting exists (no vertical body dynamics, "
        "gravity or floor body in the surrogate); impact traces stay "
        "downstream work exactly as the G07 record carries.")
    add("- No recovery skill is implemented or faked (card observation); "
        "R3's terminal declaration is the post-failure behavior.")
    add("")

    report = "\n".join(lines) + "\n"
    (OUT / "REPORT.md").write_bytes(report.encode("utf-8"))
    print("wrote", OUT / "REPORT.md")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except Exception as exc:
        print("REFUSAL: report_generation:" + str(exc), file=sys.stderr)
        raise SystemExit(2)
