# PCG Graph Asset Creation Script
# Generated by GameCodeGenerator

import unreal

def create_pcg_graph_assets():
    print("Starting PCG graph asset creation...")
    
    # Get asset tools
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    
    # Ensure the target directory exists
    target_folder = "/Game/ProceduralGenerated/PCG"
    if not unreal.EditorAssetLibrary.does_directory_exist(target_folder):
        unreal.EditorAssetLibrary.create_directory(target_folder)
        
    print(f"Creating PCG graph assets in {target_folder}...")
    
    # List of graphs to create (parsed from DSL data)
    # Each graph should be a UPCGGraph asset
    
    graphs_to_create = [
  {
    "name": "Environment_Clutter_Graph",
    "graph_type": "PCGGraphComponent",
    "data_collections": [
      {
        "collection_name": "Clutter_Collection",
        "cancel_execution_on_empty": false,
        "cancel_execution": false
      }
    ],
    "tagged_data_items": [
      {
        "tags": [
          "Clutter",
          "Rocks"
        ],
        "pin": "Output",
        "b_pinless_data": false,
        "b_is_used_multiple_times": true
      },
      {
        "tags": [
          "Clutter",
          "Debris"
        ],
        "pin": "Output",
        "b_pinless_data": false,
        "b_is_used_multiple_times": false
      }
    ],
    "metadata_domains": [
      "PCGMetadata",
      "LevelDesign"
    ],
    "attribute_selectors": [
      "Location",
      "Rotation",
      "Scale"
    ]
  },
  {
    "name": "Planet_Surface_Generation",
    "graph_type": "PCGGraphComponent",
    "data_collections": [
      {
        "collection_name": "Surface_Collection",
        "cancel_execution_on_empty": true,
        "cancel_execution": false
      }
    ],
    "tagged_data_items": [
      {
        "tags": [
          "Biome",
          "Vegetation"
        ],
        "pin": "SpawnPoints",
        "b_pinless_data": false,
        "b_is_used_multiple_times": true
      }
    ],
    "metadata_domains": [
      "PCGMetadata",
      "BiomeGeneration"
    ],
    "attribute_selectors": [
      "Location",
      "Rotation",
      "Scale",
      "Density"
    ]
  }
]
    
    for graph_info in graphs_to_create:
        graph_name = graph_info.get('name', '')
        if not graph_name:
            continue
            
        # Create asset name and path
        asset_name = f"UPCG_Graph_{graph_name}"
        asset_path = f"{target_folder}/{asset_name}.uasset"
        
        # Check if asset already exists
        if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
            print(f"Asset {asset_path} already exists, skipping...")
            continue
            
        print(f"Creating PCG graph asset: {asset_name} at {asset_path}")
        
        # Create the PCG Graph asset using the PCGGraphFactory
        try:
            # The factory for creating UPCGGraph assets
            factory = unreal.PCGGraphFactory()
            
            # Generate the asset path
            generated_paths = asset_tools.generate_new_assets(
                [unreal.ObjectPath(unreal.PackageName(asset_path), asset_name)],
                [asset_name],
                None,  # parent package
                factory
            )
            
            if generated_paths:
                print(f"Successfully created PCG graph asset: {asset_path}")
                
                # Load the created asset to configure it (if needed)
                loaded_asset = unreal.EditorAssetLibrary.load_asset(asset_path)
                if loaded_asset:
                    print(f"Loaded {asset_name} for configuration")
            else:
                print(f"Failed to create PCG graph asset: {asset_name}")
                
        except Exception as e:
            print(f"Error creating PCG graph asset {asset_name}: {e}")
            
    print("PCG graph asset creation complete.")

if __name__ == "__main__":
    create_pcg_graph_assets()
