// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataTableRow.h"
#include "FTradeRouteData.generated.h"

USTRUCT(BlueprintType)
struct FFTradeRouteData : public FTableRowBase
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintReadOnly, Category = "Economy")
	FName RouteName;

	UPROPERTY(BlueprintReadOnly, Category = "Economy")
	FString OriginSystem;

	UPROPERTY(BlueprintReadOnly, Category = "Economy")
	TArray<FString> DestinationSystems;

	UPROPERTY(BlueprintReadOnly, Category = "Economy")
	float RouteSafetyRating;
};
