// Generated by GameCodeGenerator
#include "MarketComponent.h"
#include "GameFramework/Actor.h"

UMarketComponent::UMarketComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}

void UMarketComponent::InitializeCommodityData(const TMap<FName, FCommodityEntry>& InitialData)
{
	CommodityData = InitialData;
	CurrentSupply.Reset();
	for (const auto& Entry : CommodityData)
	{
		FName CommodityID = Entry.Key;
		CurrentSupply.Add(CommodityID, Entry.Value.CurrentSupply);
	}
}

EBuyResult UMarketComponent::BuyCommodity(FName CommodityID, int32 Quantity, float& PlayerCredits)
{
	// Look up commodity data
	if (!CommodityData.Contains(CommodityID))
	{
		return EBuyResult::InvalidCommodity;
	}

	FCommodityEntry Commodity = CommodityData[CommodityID];

	// Calculate price with supply/demand modifier
	float ScarcityMultiplier = 1.0f + ((Commodity.SupplyCap - CurrentSupply[CommodityID]) / FMath::Max(Commodity.SupplyCap, 1.0f)) * Commodity.Volatility;
	float Price = Commodity.BaseBuyPrice * ScarcityMultiplier;
	float TotalCost = Price * Quantity;

	// Check credits
	if (PlayerCredits < TotalCost)
	{
		return EBuyResult::InsufficientCredits;
	}

	// Check supply
	if (CurrentSupply[CommodityID] < Quantity)
	{
		return EBuyResult::InsufficientSupply;
	}

	// Execute purchase
	PlayerCredits -= TotalCost;
	CurrentSupply[CommodityID] -= Quantity;

	return EBuyResult::Success;
}

ESellResult UMarketComponent::SellCommodity(FName CommodityID, int32 Quantity, float& PlayerCredits)
{
	// Look up commodity data
	if (!CommodityData.Contains(CommodityID))
	{
		return ESellResult::InvalidCommodity;
	}

	FCommodityEntry Commodity = CommodityData[CommodityID];

	float SellPrice = Commodity.BaseSellPrice;
	float TotalEarnings = SellPrice * Quantity;

	// Execute sale
	PlayerCredits += TotalEarnings;
	if (CurrentSupply.Contains(CommodityID))
	{
		CurrentSupply[CommodityID] += Quantity;
	}
	else
	{
		CurrentSupply.Add(CommodityID, (float)Quantity);
	}

	return ESellResult::Success;
}

float UMarketComponent::GetPrice(FName CommodityID) const
{
	if (!CommodityData.Contains(CommodityID))
	{
		return 0.0f;
	}

	const FCommodityEntry& Commodity = CommodityData[CommodityID];
	float ScarcityMultiplier = 1.0f + ((Commodity.SupplyCap - CurrentSupply[CommodityID]) / FMath::Max(Commodity.SupplyCap, 1.0f)) * Commodity.Volatility;
	return Commodity.BaseBuyPrice * ScarcityMultiplier;
}
