// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "EconomyTypes.h"
#include "MarketData.generated.h"

UCLASS()
class CHIMERA_API UMarketData : public UDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, Category = "Economy")
	TMap<FName, FCommodityEntry> CommodityDefinitions;

public:
	UFUNCTION(BlueprintCallable, Category = "Economy|MarketData")
	void InitializeCommodityData(TMap<FName, FCommodityEntry>& OutData) const;
