// Generated by GameCodeGenerator
#include "PlayerInventoryComponent.h"
#include "GameFramework/Actor.h"

UPlayerInventoryComponent::UPlayerInventoryComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer), CurrentCredits(0.0f), CargoCapacity(0)
{
}

int32 UPlayerInventoryComponent::GetCargoCount(FName CommodityID) const
{
	if (CargoContents.Contains(CommodityID))
	{
		return CargoContents[CommodityID];
	}
	return 0;
}

bool UPlayerInventoryComponent::AddCargo(FName CommodityID, int32 Quantity)
{
	if (Quantity <= 0) return false;

	int32 CurrentTotal = 0;
	for (TMap<FName, int32>::TIterator It(CargoContents); It; ++It)
	{
		CurrentTotal += It.Value();
	}

	if (CurrentTotal + Quantity > CargoCapacity)
	{
		return false;
	}

	if (CargoContents.Contains(CommodityID))
	{
		CargoContents[CommodityID] += Quantity;
	}
	else
	{
		CargoContents.Add(CommodityID, Quantity);
	}

	return true;
}

bool UPlayerInventoryComponent::RemoveCargo(FName CommodityID, int32 Quantity)
{
	if (Quantity <= 0) return false;

	if (!CargoContents.Contains(CommodityID))
	{
		return false;
	}

	int32 CurrentAmount = CargoContents[CommodityID];

	if (CurrentAmount < Quantity)
	{
		return false;
	}

	if (CargoContents[CommodityID] <= Quantity)
	{
		CargoContents.Remove(CommodityID);
	}
	else
	{
		CargoContents[CommodityID] -= Quantity;
	}

	return true;
}

float UPlayerInventoryComponent::BuyCommodity(FName CommodityID, int32 QuantityKg, float PricePerKg)
{
	float TotalCost = static_cast<float>(QuantityKg) * PricePerKg;

	if (CurrentCredits < TotalCost)
	{
		return -1.0f; // Not enough credits
	}

	if (!AddCargo(CommodityID, QuantityKg))
	{
		return -2.0f; // Cargo full or invalid quantity
	}

	CurrentCredits -= TotalCost;
	CurrentCredits = FMath::RoundToFloat(CurrentCredits);

	return TotalCost;
}

int32 UPlayerInventoryComponent::GetCurrentCargoWeight() const
{
	int32 TotalWeight = 0;
	for (TMap<FName, int32>::TConstIterator It(CargoContents); It; ++It)
	{
		TotalWeight += It.Value();
	}
	return TotalWeight;
}
