// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "PlayerInventoryComponent.generated.h"

UCLASS( ClassNoGenerateOptions, meta = (BlueprintType, Category = "Economy") )
class CHIMERA_API UPlayerInventoryComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UPlayerInventoryComponent(const FObjectInitializer& ObjectInitializer);

protected:
	UPROPERTY(EditDefaultsOnly, Category = "Inventory")
	float CurrentCredits;

	UPROPERTY(VisibleAnywhere, Category = "Inventory")
	TMap<FName, int32> CargoContents;

	UPROPERTY(EditDefaultsOnly, Category = "Inventory", meta = (ClampMin = "0"))
	int32 CargoCapacity;

public:
	UFUNCTION(BlueprintCallable, Category = "Inventory")
	float GetCredits() const { return CurrentCredits; }

	UFUNCTION(BlueprintCallable, Category = "Inventory")
	void SetCredits(float NewCredits) { CurrentCredits = FMath::Max(NewCredits, 0.0f); }

	UFUNCTION(BlueprintCallable, Category = "Inventory")
	int32 GetCargoCapacity() const { return CargoCapacity; }

	UFUNCTION(BlueprintCallable, Category = "Inventory")
	void SetCargoCapacity(int32 NewCapacity) { CargoCapacity = FMath::Max(NewCapacity, 0); }

	UFUNCTION(BlueprintCallable, Category = "Inventory")
	int32 GetCargoCount(FName CommodityID) const;

	UFUNCTION(BlueprintCallable, Category = "Inventory")
	bool AddCargo(FName CommodityID, int32 Quantity);

	UFUNCTION(BlueprintCallable, Category = "Inventory")
	bool RemoveCargo(FName CommodityID, int32 Quantity);
