// Generated by GameCodeGenerator
#include "CostlessLifeEndingDiagnostic.h"
#include "SacrificeLogComponent.h"

ACostlessLifeEndingDiagnostic::ACostlessLifeEndingDiagnostic()
{
	PrimaryActorTick.bCanEverTick = false;
	bHasSacrifices = false;
	bEndingSequenceTriggered = false;
}

void ACostlessLifeEndingDiagnostic::BeginPlay()
{
	Super::BeginPlay();
}

void ACostlessLifeEndingDiagnostic::CheckSacrificeLogAndTriggerEnding(USacrificeLogComponent* SacrificeLog)
{
	if (SacrificeLog)
	{
		bHasSacrifices = SacrificeLog->HasAnySacrifices();
		
		if (!bHasSacrifices && !bEndingSequenceTriggered)
		{
			// The discovery this law produced — the failure ending: it is possible to finish a run 
			// having risked everything and protected nothing at cost. Systems nominal. No Keeper comes.
			// The testament is witnessed by no one. The Erisaid, found, shows an empty mirror — 
			// the one moment the game comes close to explaining, and still says nothing.
			// Your star enters the sky so dim it barely registers. You did not die. You ended like 
			// the House of the Deathless: safe, complete, and unreceived. The game's bad ending is 
			// not death — it is a costless life.
			
			bEndingSequenceTriggered = true;
			TriggerDimStarEntry();
			TriggerEmptyMirrorErisaidDisplay();
		}
	}
	else
	{
		// No sacrifice log component - treat as empty (costless life)
		if (!bEndingSequenceTriggered)
		{
			bEndingSequenceTriggered = true;
			TriggerDimStarEntry();
			TriggerEmptyMirrorErisaidDisplay();
		}
	}
}

bool ACostlessLifeEndingDiagnostic::HasEmptySacrificeLog() const
{
	return !bHasSacrifices;
}

void ACostlessLifeEndingDiagnostic::TriggerDimStarEntry()
{
	// The star enters the sky so dim it barely registers. 
	// In the frozen sky, luminosity is not mass. It is what was paid.
	// The stars are bright because someone paid for them to be.
	UE_LOG(LogTemp, Warning, TEXT("Costless Life Ending: Dim star entry triggered - sacrifice log was empty"));
}

void ACostlessLifeEndingDiagnostic::TriggerEmptyMirrorErisaidDisplay()
{
	// The Erisaid shows an empty mirror — the one moment the game comes close to explaining, 
	// and still says nothing.
	UE_LOG(LogTemp, Warning, TEXT("Costless Life Ending: Empty mirror Erisaid display triggered"));
}
