// Copyright 2026 Chimera Project. All Rights Reserved.
// Generated by GameCodeGenerator (core/game_code_generator.py::generate_sacrifice_log_files).
#include "SacrificeLogComponent.h"

USacrificeLogComponent::USacrificeLogComponent(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
{
    PrimaryComponentTick.bCanEverTick = false;
}

void USacrificeLogComponent::BeginPlay()
{
    Super::BeginPlay();

    TotalSacrificesCount = 0;
}

void USacrificeLogComponent::RecordProtectionAtCost(const FString& Description, float CostPaid)
{
    if (!Description.IsEmpty())
    {
        ProtectedAtCostEntries.Add(Description);
        TotalSacrificesCount++;
    }
}

void USacrificeLogComponent::RecordTradeRefused(const FString& TradeDescription, float ValueAtRisk)
{
    FString Entry = FString::Printf(TEXT("Trade refused: %s (Value at risk: %.2f)"), *TradeDescription, ValueAtRisk);
    RecordProtectionAtCost(Entry, ValueAtRisk);
}

bool USacrificeLogComponent::HasAnySacrifices() const
{
    return TotalSacrificesCount > 0 && ProtectedAtCostEntries.Num() > 0;
}

int32 USacrificeLogComponent::GetSacrificeCount() const
{
    return TotalSacrificesCount;
}

TArray<FString> USacrificeLogComponent::GetSacrificeDescriptions() const
{
    return ProtectedAtCostEntries;
}

void USacrificeLogComponent::Record(const FString& Kind, const FString& Note, int32 Generation, int32 Day)
{
    const TMap<FString, float>& Weights = GetSacrificeWeights();
    const float* FoundWeight = Weights.Find(Kind);
    const float Weight = FoundWeight ? *FoundWeight : 0.0f;

    if (!FoundWeight)
    {
        // Fail-safe, never a crash: an unrecognized Kind still gets recorded
        // (weight 0) so the log never silently drops a call -- but it is
        // loudly surfaced, since it means a caller drifted from the 8
        // trained kinds (H-1: template/spec drift).
        UE_LOG(LogTemp, Warning,
            TEXT("[Sacrifice] Unknown kind '%s' -- recording with weight 0.0 (not one of the 8 trained SACRIFICE_WEIGHTS kinds)"),
            *Kind);
    }

    FSacrificeEntry NewEntry;
    NewEntry.Kind = Kind;
    NewEntry.Weight = Weight;
    NewEntry.Note = Note;
    NewEntry.Generation = Generation;
    NewEntry.Day = Day;
    Entries.Add(NewEntry);

    // H-21 witness marker: a verb needs behavior a beat can observe.
    UE_LOG(LogTemp, Log, TEXT("[Sacrifice] Recorded kind=%s weight=%.4f gen=%d"), *Kind, Weight, Generation);
}

float USacrificeLogComponent::WeightForGeneration(int32 Generation) const
{
    float Total = 0.0f;
    for (const FSacrificeEntry& Entry : Entries)
    {
        if (Entry.Generation == Generation)
        {
            Total += Entry.Weight;
        }
    }
    return Total;
}

const TMap<FString, float>& USacrificeLogComponent::GetSacrificeWeights()
{
    static TMap<FString, float> Weights;
    if (Weights.Num() == 0)
    {
        Weights.Add(TEXT("BURIED_STRANGER"), 2.375455f);
        Weights.Add(TEXT("GAVE_CARGO"), 1.225224f);
        Weights.Add(TEXT("GAVE_O2"), 3.096343f);
        Weights.Add(TEXT("HEIRLOOM_GIVEN"), 6.574969f);
        Weights.Add(TEXT("REFUSED_PROFIT"), 0.112672f);
        Weights.Add(TEXT("SPENT_TIME_UNPAYABLE"), 0.482805f);
        Weights.Add(TEXT("TOOK_RISK_FOR_OTHER"), 1.737400f);
        Weights.Add(TEXT("WEAPON_NEVER_FIRED"), 0.831799f);
    }
    return Weights;
}
