// Copyright 2026 Chimera Project. All Rights Reserved.
// Generated by GameCodeGenerator (core/game_code_generator.py::generate_star_memorial_files).
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "StarMemorialComponent.generated.h"

/**
 * One finished life, written into the sky. Brightness IS what that life
 * sacrificed (Design Law 2; the seed's FStar dataclass, CHIMERA_VISION.py:3745-
 * 3747); twinkle is regret it never resolved; the bearing places it on the
 * memorial band by the golden angle so no two stars crowd.
 */
USTRUCT(BlueprintType)
struct FStarEntry
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Memorial")
	FString LifeName;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Memorial")
	int32 Generation = 0;

	// 0..1, = 1 - exp(-SacrificeWeight / BrightnessK). A costless life -> ~0.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Memorial")
	float Brightness = 0.0f;

	// Unresolved phantom pains at death — the star flickers.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Memorial")
	bool bTwinkle = false;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, SaveGame, Category="Memorial")
	float BearingDeg = 0.0f;
};

/**
 * The sky above the Yard, accumulated across generations — the seed's
 * UStarMemorialSubsystem (CHIMERA_VISION.py:3750-3767), realized as an actor
 * component (H-34 runtime-attach via ChimeraMovementComponent::BeginPlay, the
 * project's live pattern; the same way UWeatherComponent realizes
 * UWeatherSubsystem — see SuitLifeSupportComponent.h's identical doc comment).
 * A UWorldSubsystem would auto-instantiate independently of that per-owner
 * attach and of the SaveGame array's per-pawn persistence contract below; see
 * this method's own docstring in core/game_code_generator.py for the research
 * + tradeoff record (mirrors generate_weather_subsystem_files' identical
 * reasoning).
 *
 * Every finished life becomes a star (AddLife); bright ancestors LITERALLY
 * light the night for the generations that follow (GetNightLightLevel). A
 * world full of costless lives stays dark — the ending taught wordlessly, in
 * the sky (Design Law 2).
 *
 * GENERATOR-OWNED (2026-07-18, tb-0158 — CWM rung 2, "trained data flows
 * top-down"): BrightnessK and BrightLightsYardThreshold below are READ from
 * docs/objectives/memorial.trained.json (score=0.839) at generation time — see core/trainables/memorial.py
 * (the domain) and docs/objectives/memorial.json (the objective this genome
 * was scored against). The full trained SACRIFICE_WEIGHTS genome (not yet
 * consumed by any shipped class — see this method's own docstring):
 *   BURIED_STRANGER = 2.3755
 *   GAVE_CARGO = 1.2252
 *   GAVE_O2 = 3.0963
 *   HEIRLOOM_GIVEN = 6.5750
 *   REFUSED_PROFIT = 0.1127
 *   SPENT_TIME_UNPAYABLE = 0.4828
 *   TOOK_RISK_FOR_OTHER = 1.7374
 *   WEAPON_NEVER_FIRED = 0.8318
 * DimThreshold is NOT a trained locus (no such threshold exists in the seed's
 * STAR dict or the trainer's genome) and stays a fixed design constant.
 *
 * Stars are UPROPERTY(SaveGame) so the memorial persists across lives even as
 * the pawn that carries this component is recreated each generation.
 *
 * Witness markers (H-21 — a verb needs behavior a beat can observe): AddLife
 * logs "[Memorial] StarAdded gen=%d brightness=%.4f kind=%s" (kind is
 * BRIGHT/QUIET by the SAME threshold GetNightLightLevel sums over) immediately
 * followed by "[Memorial] NightLight level=%.4f" — the only two moments in
 * this component's lifecycle that ever CHANGE the yard's light level, so
 * logging on that edge (not every tick — PrimaryComponentTick stays off,
 * matching the seed's own Tick(dt): pass) gives a beat something to assert on
 * without spam.
 */
UCLASS(ClassGroup=(Save), meta=(BlueprintSpawnableComponent))
class CHIMERA_API UStarMemorialComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UStarMemorialComponent(const FObjectInitializer& ObjectInitializer);

	// The whole sky so far. Persists across generations.
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, SaveGame, Category="Memorial")
	TArray<FStarEntry> Stars;

	// brightness = 1 - exp(-w / BrightnessK): diminishing returns on sacrifice,
	// never saturating — a life can always shine a little brighter.
	// TRAINED, see docs/objectives/memorial.trained.json (score=0.839).
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category="Memorial")
	float BrightnessK = 14.275037f;

	// At/above this a star is "bright" and contributes to lighting the Yard.
	// TRAINED, see docs/objectives/memorial.trained.json (score=0.839).
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category="Memorial")
	float BrightLightsYardThreshold = 0.455572f;

	// Below this a star "barely registers" — the costless-life dimness. NOT a
	// trained locus (fixed design constant; see class doc comment above).
	UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, Category="Memorial")
	float DimThreshold = 0.08f;

	/** Write a finished life into the sky. Returns the star it became. Logs
	 *  the two H-21 witness markers documented on the class. */
	UFUNCTION(BlueprintCallable, Category="Memorial")
	FStarEntry AddLife(const FString& LifeName, int32 Generation,
	                   float SacrificeWeight, int32 OpenPains);

	/** How much light the ancestors give the Yard tonight (0..0.5). Sums only
	 *  the bright stars — costless ancestors give nothing. */
	UFUNCTION(BlueprintCallable, Category="Memorial")
	float GetNightLightLevel() const;

	UFUNCTION(BlueprintCallable, Category="Memorial")
	int32 GetStarCount() const { return Stars.Num(); }

	/** Index of the brightest star, or INDEX_NONE if the sky is empty. */
	UFUNCTION(BlueprintCallable, Category="Memorial")
	int32 GetBrightestStarIndex() const;

	/** True if this life's star would barely register — the costless warning. */
	UFUNCTION(BlueprintCallable, Category="Memorial")
	bool IsCostless(float SacrificeWeight) const;
};
