// Generated by GameCodeGenerator
#pragma once
#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Projectile.generated.h"
UCLASS()
class CHIMERA_API AProjectile : public AActor{
GENERATED_BODY()
public:
AProjectile(const FObjectInitializer& ObjectInitializer);};