// Generated by GameCodeGenerator
#pragma once
#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "ShieldComponent.generated.h"
UCLASS( ClassNoGenerateOptions, meta = (BlueprintType, Category = "Combat") )
class CHIMERA_API UShieldComponent : public UActorComponent{
GENERATED_BODY()
public:
UShieldComponent(const FObjectInitializer& ObjectInitializer);void InitializeFromShip(float ShieldCapacity, float RegenRate);float AbsorbDamage(float IncomingDamage);};