// Generated by GameCodeGenerator
#pragma once
#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "WeaponComponent.generated.h"
UCLASS( ClassNoGenerateOptions, meta = (BlueprintType, Category = "Combat") )
class CHIMERA_API UWeaponComponent : public UActorComponent{
GENERATED_BODY()
public:
UWeaponComponent(const FObjectInitializer& ObjectInitializer);
};