// Generated by GameCodeGenerator
#include "DamageComponent.h"
#include "Components/ActorComponent.h"
#include "GameFramework/Actor.h"

UDamageComponent::UDamageComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer), MaxHullHealth(5000.0f), CurrentHullHealth(5000.0f), bIsDestroyed(false) {
	PrimaryComponentTick.bCanEverTick = true;
}

void UDamageComponent::BeginPlay() {
	Super::BeginPlay();
}

void UDamageComponent::InitializeFromShip(float HullHealth) {
	MaxHullHealth = HullHealth;
	CurrentHullHealth = HullHealth;
}

float UDamageComponent::GetHullPercent() const {
	return MaxHullHealth > 0.0f ? CurrentHullHealth / MaxHullHealth : 1.0f;
}

bool UDamageComponent::IsDestroyed() const {
	return CurrentHullHealth <= 0.0f || bIsDestroyed;
}

void UDamageComponent::ApplyDamage(float IncomingDamage, AActor* Instigator) {
	if (bIsDestroyed) return;

	// Route to ShieldComponent->AbsorbDamage()
	float RemainingDamage = IncomingDamage;

	if (RemainingDamage > 0.0f) {
		CurrentHullHealth -= RemainingDamage;
		if (CurrentHullHealth <= 0.0f) {
			bIsDestroyed = true;
			// Trigger destruction sequence
		}
	}

	// If Instigator is player and target is NPC, award credits
}