// Generated by GameCodeGenerator
#pragma once
#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "GameFramework/Actor.h"
#include "SystemDamageComponent.generated.h"

UCLASS(meta = (BlueprintType, Category = "Combat"))
class CHIMERA_API USystemDamageComponent : public UActorComponent {
GENERATED_BODY()
public:
	USystemDamageComponent(const FObjectInitializer& ObjectInitializer);

	UPROPERTY(EditDefaultsOnly, Category = "Subsystems")
	TMap<FName, float> SubsystemHealth;

	UPROPERTY(VisibleAnywhere, Category = "Subsystems")
	TMap<FName, float> SubsystemMaxHealth;

	UPROPERTY(EditDefaultsOnly, Category = "Damage", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float SubsystemDamageThreshold;

protected:
	virtual void BeginPlay() override;

public:
	UFUNCTION(BlueprintCallable, Category = "Subsystems")
	void InitializeFromShip(const TArray<FName>& SystemNames);

	UFUNCTION(BlueprintCallable, Category = "Subsystems")
	void ApplySystemDamage(float IncomingHullDamage);

	UFUNCTION(BlueprintCallable, Category = "Subsystems")
	void RepairSubsystem(FName SystemName, float Amount);

	UFUNCTION(BlueprintPure, Category = "Subsystems")
	float GetSubsystemHealth(FName SystemName) const;

	UENUM(BlueprintType)
	enum class ESubsystemStatus : uint8 {
		Operational,
		Damaged,
		Critical,
		Destroyed
	};

	UFUNCTION(BlueprintPure, Category = "Subsystems")
	ESubsystemStatus GetSubsystemStatus(FName SystemName) const;
};