// Generated by GameCodeGenerator
#pragma once
#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "GameFramework/Actor.h"
#include "WeaponComponent.generated.h"

USTRUCT(BlueprintType)
struct FWeaponSlotData {
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Weapon")
	FName Name;

	UPROPERTY(EditAnywhere, Category = "Weapon", meta = (DisplayName = "Size"))
	FString Size; // S1, S2, S3

	UPROPERTY(EditAnywhere, Category = "Weapon", meta = (ClampMin = "1"))
	int32 Count;

	UPROPERTY(EditAnywhere, Category = "Weapon", meta = (DisplayName = "Type"))
	FString Type; // fixed, gimbal, remote_turret

	UPROPERTY(EditAnywhere, Category = "Combat Stats")
	float FireRate;

	UPROPERTY(EditAnywhere, Category = "Combat Stats")
	float DamagePerShot;

	UPROPERTY(EditAnywhere, Category = "Combat Stats")
	float ProjectileSpeed;

	UPROPERTY(EditAnywhere, Category = "Combat Stats")
	float Range;
};

USTRUCT(BlueprintType)
struct FMissileRackData {
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, Category = "Missiles")
	FName RackName;

	UPROPERTY(EditAnywhere, Category = "Missiles", meta = (ClampMin = "1"))
	int32 Count;

	UPROPERTY(EditAnywhere, Category = "Missiles")
	FString MissileType;

	UPROPERTY(EditAnywhere, Category = "Combat Stats")
	float Damage;

	UPROPERTY(EditAnywhere, Category = "Combat Stats")
	float TrackingStrength;
};

UCLASS(meta = (BlueprintType, Category = "Combat"))
class CHIMERA_API UWeaponComponent : public UActorComponent {
GENERATED_BODY()
public:
	UWeaponComponent(const FObjectInitializer& ObjectInitializer);

	UPROPERTY(EditDefaultsOnly, Category = "Weapons")
	TArray<FWeaponSlotData> WeaponSlots;

	UPROPERTY(EditDefaultsOnly, Category = "Missiles")
	TArray<FMissileRackData> MissileRacks;

	UPROPERTY(Transient)
	AActor* CurrentTarget;

protected:
	UPROPERTY()
	TMap<FName, float> WeaponCooldowns;

public:
	UFUNCTION(BlueprintCallable, Category = "Weapons")
	void FireWeapon(FName SlotName);

	UFUNCTION(BlueprintCallable, Category = "Missiles")
	void FireMissile(FName RackName, AActor* Target);

	UFUNCTION(BlueprintPure, Category = "Weapons")
	TArray<FName> GetAvailableWeapons() const;

	UFUNCTION(BlueprintPure, Category = "Missiles")
	int32 GetMissileCount(FName RackName) const;
};