"""grow.py -- THE ENZYME. One file. It walks `story/` and grows it.

The story is the genome; this is only the chemistry that reads it. At every folder it does the
same three moves, which is what makes this GROWTH and not construction -- a cell does not consult
a blueprint of the finished body, it divides and differentiates from local signals, and its
POSITION determines its identity. Here that is literal: a folder's path IS its address, and its
parent's handed-down numbers ARE its signal.

Each folder holds three things and nothing else:
    story.md      the human story -- WHAT this membrane is          (the NODE, Alan's)
    physics.py    the law -- derive(parent, free) -> this membrane's numbers   (the EDGE, mine)
    trained.json  the free numbers this law leaves open, once fitted (optional)

Adding world means adding a paragraph and a law. It never means adding more of this file.

Run:  python story/grow.py
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent


def _load(py: Path):
    spec = importlib.util.spec_from_file_location(f"law_{py.parent.name}", py)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _fmt(v):
    if isinstance(v, float):
        return f"{v:.4g}"
    return str(v)


_PLAIN = "**In plain words —**"


def _summary(folder: Path) -> str:
    """A membrane's one-line self-description.

    EVERY CHAPTER OPENS WITH A PLAIN-WORDS LINE, before any equation -- the label that comes before
    the thing, so a reader knows what they are about to look at. It is also the chapter's own LOW-LOD
    version of itself, which is why the index harvests it: a parent's contents list is literally its
    children described at lower detail. One line, two jobs. Falls back to the first real sentence."""
    s = folder / "story.md"
    if not s.exists():
        return "(awaiting the human story)"
    text = s.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        t = line.strip()
        if t.startswith(_PLAIN):
            return t[len(_PLAIN):].strip().rstrip(".")
    for line in text.splitlines():
        t = line.strip()
        if t and not t.startswith(("#", ">", "*", "`", "|", "-")):
            return t.rstrip(".")[:96]
    return ""


def write_contents(folder: Path, nums: dict) -> None:
    """Write this membrane's INDEX -- generated, never typed.

    THE SPLIT that makes this maintainable: LISTING what a membrane contains is mechanical -- the
    folder tree already knows, so a machine writes it. DEFINING what it IS (story.md) and how it
    WORKS (physics.py) is the writing. If a human typed the contents list, every new membrane would
    require hand-editing every ancestor forever; generated, adding a chapter updates every index
    above it for free."""
    children = sorted(d for d in folder.iterdir()
                      if d.is_dir() and not d.name.startswith((".", "_")))
    serial = "/".join(p.name for p in list(folder.relative_to(ROOT).parts and
                                           [ROOT / Path(*folder.relative_to(ROOT).parts[:i + 1])
                                            for i in range(len(folder.relative_to(ROOT).parts))]))
    lines = [f"# {folder.name} — contents",
             "",
             "*Generated by `grow.py`. Do not edit: listing is mechanical, defining is not.*",
             "",
             f"**Serial** (its path from the seed, which is its compressed story)  ",
             f"`{serial or folder.name}`",
             ""]
    if children:
        lines += ["## Contains", "", "| membrane | what it is |", "|---|---|"]
        lines += [f"| `{c.name}` | {_summary(c)} |" for c in children]
    else:
        lines += ["## Contains", "", "*nothing yet — this is a leaf of the story as written*"]
    if nums:
        lines += ["", "## Hands down", "", "| number | value |", "|---|---|"]
        lines += [f"| `{k}` | {_fmt(v)} |" for k, v in nums.items()]
    (folder / "contents.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def grow(folder: Path, parent: dict | None = None, depth: int = 0) -> None:
    """Grow one membrane from its parent's numbers, then let it grow its children."""
    ind = "   " * depth
    story = folder / "story.md"
    law = folder / "physics.py"

    if not story.exists():
        print(f"{ind}{folder.name}/   -- awaiting the human story")
        return
    if not law.exists():
        print(f"{ind}{folder.name}/   -- story written, LAW MISSING (no edge reaches this membrane)")
        return

    free = {}
    tj = folder / "trained.json"
    if tj.exists():
        free = json.loads(tj.read_text())

    nums = _load(law).derive(parent, free)
    (folder / "numbers.json").write_text(json.dumps(nums, indent=2))
    write_contents(folder, nums)                       # the index -- generated every grow, never typed
    shown = ", ".join(f"{k}={_fmt(v)}" for k, v in list(nums.items())[:4])
    print(f"{ind}{folder.name}/   {shown}")

    for child in sorted(d for d in folder.iterdir() if d.is_dir() and not d.name.startswith((".", "_"))):
        grow(child, nums, depth + 1)

    if depth == 0:
        _density_guard()


def _density_guard() -> None:
    """After a full grow, ask whether any membrane's detail silently rotted.

    WHY IT IS HERE. `ChimeraEngine/test_density_regression.py` checks every term against the floor
    its surface class derives, and nothing called it -- so a membrane could lose its detail the way
    `_tree_buffers` did and the first thing to notice would be a human squinting at a render. A
    guard nobody runs is a guard that does not exist.

    WHY IT CAN BE SWITCHED OFF, and the number is the argument: the guard re-emits all 42 terms in
    a fresh process and takes 27 SECONDS. `grow.py` is not only run by a person at a prompt -- the
    live viewer's `/free` endpoint runs it synchronously every time the operator moves a slider,
    then reloads the scene. Wiring 27 s into that path would make the world's one interactive
    control unusable, and a guard that makes people avoid growing is worse than no guard.
    So: on by default, off for callers who say so.

        CHIMERA_SKIP_DENSITY_GUARD=1 python story/grow.py

    IT REPORTS AND DOES NOT RAISE. A density regression is a fact about detail, not a reason the
    world failed to derive; the numbers this grow just produced are correct either way.
    """
    import os
    if os.environ.get("CHIMERA_SKIP_DENSITY_GUARD", "").strip() not in ("", "0", "false"):
        return
    import subprocess, sys as _sys
    root = Path(__file__).resolve().parent.parent
    guard = root / "ChimeraEngine" / "test_density_regression.py"
    if not guard.exists():
        return
    try:
        r = subprocess.run([_sys.executable, str(guard)], capture_output=True, text=True,
                           cwd=str(root), timeout=600)
    except Exception as e:                          # a guard that breaks the grow is not a guard
        print(f"\n[DENSITY GUARD] could not run: {e}")
        return
    if r.returncode != 0:
        print("\n[DENSITY GUARD] regression detected after grow:")
        print((r.stdout or "")[-2000:])
    else:
        print("\n[DENSITY GUARD] every term is at or above its derived floor.")


def read(folder: Path, depth: int = 0, maxdepth: int = 99) -> None:
    """Read the story at a chosen level of detail.

    THE PLAIN-WORDS LINE IS NOT A SUMMARY OF THE CHAPTER -- AT THAT ZOOM IT *IS* THE CHAPTER.
    Zoom in and it becomes the equations; zoom in again and it becomes its children, each of which
    is again one sentence. So the same story can be read at any resolution and is complete at each
    one -- which is LOD of MEANING, the same law the matter obeys: every level is the level below,
    averaged."""
    if depth > maxdepth:
        return
    if (folder / "story.md").exists():
        pad = "   " * depth
        print(f"{pad}{folder.name} — {_summary(folder)}.")
        print()
    for child in sorted(d for d in folder.iterdir()
                        if d.is_dir() and not d.name.startswith((".", "_"))):
        read(child, depth + 1, maxdepth)


if __name__ == "__main__":
    import sys
    if "--read" in sys.argv:
        d = int(sys.argv[sys.argv.index("--depth") + 1]) if "--depth" in sys.argv else 99
        print(f"\nTHE STORY, read at depth {d}\n" + "=" * 72 + "\n")
        for top in sorted(x for x in ROOT.iterdir() if x.is_dir() and not x.name.startswith((".", "_"))):
            read(top, 0, d)
        raise SystemExit(0)
    print("\nGROWING THE STORY\n" + "=" * 60)
    for top in sorted(d for d in ROOT.iterdir() if d.is_dir() and not d.name.startswith((".", "_"))):
        grow(top)

    # THE EPOCH IS PART OF GROWING, not a separate errand. `derive()` knows nothing about the
    # timeline, so writing numbers.json from it alone STRIPS timeline_serial and t_since_seed_s off
    # every membrane -- silently, because the numbers stay right and every witness still passes.
    # It can only be stamped after the whole tree exists (it sums duration_s down each path), so it
    # belongs here, at the tail, rather than inside grow(). One writer, one pass.
    import timeline as _timeline
    n = _timeline.stamp()
    print(f"\nstamped the epoch into {n} membranes (timeline_serial + t_since_seed_s)")
    print()
