"""build_receipt.py -- assembles receipt_tick_cost.json from the analyzed
matrix data (receipt_data.json + receipt_data_interleaved.json).
Trailer Agent: tickcost."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
RAW = HERE / "raw"
fd = json.loads((RAW / "receipt_data_final_matrix.json").read_text(encoding="utf-8"))
fi = json.loads((RAW / "receipt_data_interleaved.json").read_text(encoding="utf-8"))
t = fd["attribution"]
cls = t["cls"]


def g(name):
    v = cls[name]
    return {"ms_per_tick": round(v["ms_per_tick"], 4),
            "share_of_loop": round(v["share_of_loop"], 4),
            "hits_per_tick": round(v["hits_per_tick"], 2)}


lat = fd["latency_us"]


def latfmt(k):
    v = lat[k]
    return {"n": v["n"], "p50_ms": round(v["p50_ns"] / 1e6, 3),
            "p95_ms": round(v["p95_ns"] / 1e6, 3),
            "p99_ms": round(v["p99_ns"] / 1e6, 3),
            "mean_ms": round((v.get("mean_ss_ns") or v.get("mean_ns")) / 1e6, 3)}


order = sorted(cls, key=lambda k: -cls[k]["ms_per_tick"])
table = [dict(cls_name=k, **g(k)) for k in order]

receipt = {
 "lane": "lane/tick-cost-attribution-20260920",
 "date": "2026-09-20 (lane clock; measurements 2026-09-22)",
 "agent": "tickcost",
 "base": "bd4bf630 (merge containing typeb-p1 receipt 272dc20b and the pinned walk bytes agent/gait-wave38-calendar-guard @ 30821ef7)",
 "prereg": "PREREG.md frozen at commit e62147de with Amendments 1-5 (2cb2ef4f); every amendment dated and frozen BEFORE the runs it governs",
 "question": "THE FALSIFIABLE QUESTION: ~23.3 ms/tick vs the 3.33 ms/300 Hz budget (~7x); can serialization-only / byte-neutral removals close it, and if not, WHERE inside the 98.4%-integration step does the cost live (bond/force evaluation, muscle/servo paths + moment arms, contact generation/resolution, reflex controller, observation assembly, sync, allocation, serialization)?",
 "hardware_context": {
  "cpu": "Intel Core i9-13900K (8P+16E, 24 cores / 32 logical, hybrid)",
  "ram_gb": 127.78, "os": "Windows 11 Pro 10.0.26200",
  "toolchains": ["MinGW g++ 15.2.0 -O2 -static-libstdc++ -static-libgcc",
                  "MSVC cmake Release /fp:precise (byte-identical stdout, Amendment 1 check)"],
  "machine_state_witness": "SHARED BOX, ~60-70% loaded by other tenants during all matrices (a game + fleet processes). Receipt-era typeb-p1 runs measured ~30 s/process on a quieter state; today's plain runs measured 46-100 s/process across matrices. Control: driver + gait_unit children pinned 0x5555 (one thread per P-core) at High priority. Shares were stable across every state; absolute ms/tick carry the state factor (~1.5-2x vs receipt era; instrument-independent evidence: plain-binary F-G5 span 3.57-4.6 s here vs the receipt's F-G5_s=2.418 s on the same 500 ticks)."
 },
 "pinned_bytes": {
  "scene_sha256": "f6844eeae3dc87170a572ccdeedf326a6cac4f73d1448941808bd8b25a8db342 (regenerated byte-exact by tools/science_funnel/gait_scene.py, re-verified per matrix)",
  "lane_fence_stdout_sha256": "8c537cdb7cb8c43cf9423cb50056787bcc31ee487d70d3c2a1e73ed5d60b06cc (bd4bf630 plain build; identical on MinGW and MSVC; PREREG Amendment 1)",
  "ancestor_fence_stdout_sha256": "71065ac54fa988704ce29cd79cfb5cdbe0d4e2eab3f7db69b10d4b8d94517592 (30821ef7 bytes; differs from the lane fence ONLY by merged wave-39/40 + F-G42 harness notes, +346 bytes; physics byte-faithful)",
  "physics_anchors_exact_on_this_machine": ["refusal_tick 302", "refusal_class gait_positional_correction_budget", "worst_moving_ledger_J 30.970714", "red_falsifiers 49", "checks 173"]
 },
 "determinism_guard_F2": "GREEN. 32 runs across 4 matrices (loaded, pinned x2, interleaved), timing ON and OFF: EVERY stdout sha256 == the lane fence 8c537cdb..., byte-for-byte. Timing collection does not change stepping bytes. The instrumented binary is the production text + trailing-marked timer insertions only (make_instrument.py manifest round-trip byte-exact; 29+28 marked lines, 3+1 replaced anchors; the tracked header/harness/scene bytes untouched all lane).",
 "baseline_remeasure": {
  "method": "plain gait_unit rebuilt from bd4bf630 tracked bytes, the receipts' frozen-ref invocation `gait_unit.exe <scene.json>`, 5 runs under the declared machine-state control",
  "final_matrix_plain_process_walls_s": fd["runs"]["plain"]["wall_s"],
  "receipt_era_process_walls_s": [30.060, 29.935, 30.053, 30.366, 31.725, 32.154],
  "steady_state_step_only_this_machine": "44.7 ms/tick mean (22.4 ticks/s) on the shared-box state; the receipt's 43.3-44.6 ticks/s band is NOT reproducible on today's state (F3(b) carried RED with the drift evidence); the instrument-invariant F-G5 span ratio (plain 3.57-4.6 s here vs 2.418 s receipt-era on the same 500 ticks) isolates the factor as machine state, not build"
 },
 "attribution_table_steady_state_walk": {
  "note": "median walk run (302 ticks, tick>=20 steady state), final pinned matrix; inclusive classes labeled; books (the 5 exclusive step() stages) close at 101.9% of the measured step wall",
  "full_loop_ms_per_tick": round(t["full_loop_ms_per_tick"], 3),
  "books": {k: (round(v, 4) if isinstance(v, float) else v) for k, v in t["books"].items()},
  "rows": table
 },
 "subsystem_reading": {
  "integration_step": "97.1% of the walk loop (step.integrate) -- the receipt's 98.4% confirmed from inside",
  "contact_force_field_generation_fk": "fk.evaluate = 87.9% of the loop INCLUSIVE (286.6 calls/tick): the Model::evaluate FK (frames, mass matrix, bias forces, contact rows/gaps -- the contact/force field + moment-arm Jacobians) is the SINGLE dominant leaf; it sits inside RK4's rate() x4 per free_step and inside every event-search bisection",
  "bond_force_constraint_solves": "the SOLVES are minor: adv.impact 12.0% inclusive (incl. its own FK), solver.inverse_spd 1.9%, solver.friction_solve 0.29%, solver.project_rows 0.09% -- the active-set/friction/impact projection machinery itself is NOT the cost",
  "muscle_servo_paths": "servo (PD + phase tables + fore/hind closed-form IK, 4 calls/tick) = 1.1%",
  "reflex_controller": "update_clock + fore_clock + hind step law stage = 0.34%; capture_reflex + support hull = 0.43%",
  "observation_assembly_serialization": "status() JSON = 1.7%; harness census 0.10%; dump 0.02%",
  "sync": "0.0 ms/tick -- single process, single thread; no synchronization point exists in this binary (the thin-client coupling lives outside it)",
  "allocation": "UNMEASURED (counted operator-new rejected, PREREG Amendment 2: its instrumentation overhead alone measured ~+12 ms/tick at ~157k allocs/tick); the tick-reset stage chrono scope measures 0.0004 ms/tick"
 },
 "F1_cost_gap": {
  "optimistic_removal_bound_ms_per_tick": round(t["bound"]["optimistic_removal_bound_ms_per_tick"], 3),
  "removable_classes_ms_per_tick": round(t["bound"]["removable_sum_ms_per_tick"], 4),
  "removable_classes": ["obs.status_json (1.7%)", "harness.census (0.1%)", "harness.dump (0.02%)", "step.reset_alloc (0.004%)", "sync (0)"],
  "budget_ms_per_tick": 3.333,
  "verdict": "COST-GAP FIRED (clause F1). The bound is 45.59 ms/tick on today's machine state -- 13.7x the budget. At the receipt's machine state (23.26 ms full loop) the same removals leave 22.40 ms/tick -- 6.7x the budget. THE VERDICT IS MACHINE-STATE-INDEPENDENT: no composition of byte-neutral removals reaches 300 Hz on this body.",
  "residual_named": "THE INTEGRATION CORE ITSELF: 97.1% of the tick is step.integrate -- 87.9% of the tick is Model::evaluate() (the 18-coordinate FK: frames, mass matrix, bias, contact rows) executed ~287 times/tick by (a) the RK4 (4 rate() calls per free_step, 29.4 free_steps/tick incl. the 42-iteration event-bisection free_steps) and (b) the impact/event machinery. The cost is the EQUATION COUNT of the derived physics (f64 FK Jacobians at 4 RK4 substages x ~11 advance calls/tick), not harness, not serialization, not sync, not allocation."
 },
 "F3_measurement_validity": {
  "a_production_path": "GREEN -- the profiled path is the production gait_controller.hpp GaitWalker::step at bd4bf630 (derived-copy instrument, manifest round-trip byte-exact, tracked bytes untouched); the plain rebuild reproduces the lane fence and every physics anchor exactly, on two toolchains",
  "b_throughput_band": "RED (carried) -- today's shared-box state measures 22.4 ticks/s steady-state vs the preregistered 40-48 band; the drift evidence (instrument-independent F-G5 span vs receipt-era F-G5_s) names machine state, not build, as the cause",
  "c_instrumentation_overhead": "GREEN -- analytic bound: 42.7-45.3 ns/Scope pair (timer_microbench, 1M pairs) x ~870 pairs/tick = 37-39 us/tick = ~0.11% of the receipt-state tick; MEASURED interleaved adjacent-pair A/B (4 pairs, same box minutes apart): +0.25 ms/tick mean pair delta (noise-dominated range -0.31..+0.85) = ~1.1% of the receipt-state tick; both far under the 10% budget",
  "d_books_closure": "GREEN -- the five exclusive step() stages sum to 101.9% of the same binary's measured step wall (45.56 vs 44.72 ms/tick)"
 },
 "prediction_grading": "PARTIALLY REFUTED (carried verbatim): PREDICTED bond/force-constraint evaluation largest, contact/FK field second, periphery <10%. MEASURED: the contact/force FIELD generation (Model::evaluate FK, 87.9% inclusive) is the dominant leaf and the constraint/bond SOLVES are minor (impact 12.0% inclusive, friction+projection <0.4%); the periphery claim held (everything outside integrate+its FK is ~3%; sync 0; serialization ~1.8%). The ranking call LOST; the rule-0 lesson: the 98.4% integration share is not 'the solver solves' -- it is the FK equation count feeding the solver.",
 "numeric_drift_F2_change_requests": {
  "note": "NO optimization was implemented in this lane. The named candidates below would change replay bytes and are recorded as physics-compatibility change requests, rejected here:",
  "candidates": [
   {"name": "cache/reuse the tick-start evaluate() across clock/reflex/census stages",
    "bytes_changed": "none by itself (read-only reuse) -- but the stage timers show these evaluates are ~0.5% of the tick; the dominant evaluate calls live INSIDE the RK4 where reuse changes the integration",
    "verdict": "rejected: sub-0.5% upside"},
   {"name": "reduce RK4 to semi-implicit Euler in free_step",
    "bytes_changed": "integration reduction order + every q/v byte downstream",
    "verdict": "rejected: F2"},
   {"name": "fewer event-bisection iterations (42) or wider bisection tolerance",
    "bytes_changed": "event localization ticks -> contact decisions",
    "verdict": "rejected: F2"},
   {"name": "reuse rate()/free_step temporaries (Dense/vector allocs)",
    "bytes_changed": "none (allocation reuse is FP-neutral) -- viable ONLY with a byte-identity fence per wave; allocation share unmeasured here (Amendment 2)",
    "verdict": "deferred with a mandatory byte-fence"},
   {"name": "hoist contact_row/tangent_row recomputation inside rate()",
    "bytes_changed": "row assembly is identical arithmetic -- byte-neutral IF the same rows are reused bitwise; requires the fence",
    "verdict": "deferred with a mandatory byte-fence"}
  ]
 },
 "interacting_scene_latency": {
  "requirement": "one coupled scene sustained >= 426 ticks, p50/p95/p99 tick time",
  "sustained_426_finding": "UNMET-BY-THE-PINNED-BYTES (a physics finding): the measured refusal ledger over every regime of the pinned scene -- walk 302 (gait_positional_correction_budget), F-G6 push walker 302 (expected-tip), stage-E stand 139 (pushed AND unpushed), power-off fold 129 (violent impact cascades). The pinned scene cannot run 426 ticks (1.42 simulated seconds) in ANY regime. For the server-authoritative decision this is itself a solver finding: survival, not only throughput, needs solver work.",
  "walk_302_ticks_refused_at_302": latfmt("walk"),
  "push426_302_ticks_expected_tip": latfmt("push426"),
  "fold426_129_ticks_refused_at_129": latfmt("fold426"),
  "note": "all windows instrumented per-tick on the instrumented binary; percentiles nearest-rank over all sampled ticks (steady-state variant tick>=20 in receipt_data); the absolute values carry the shared-box state factor (see hardware_context)"
 },
 "artifacts": {
  "prereg": "PREREG.md (Amendments 1-5)",
  "instrument": "make_instrument.py + tickcost_probe.hpp (derived-copy instrument; tracked bytes untouched)",
  "driver": "run_tickcost.py (--interleave for the overhead A/B)",
  "analyzer": "analyze_tickcost.py",
  "tests": "test_tick_cost_attribution.py (8 passing)",
  "raw": "raw/ (run indexes for all matrices, receipt_data for final+interleaved, stdout/stderr samples incl. the [tc] class blocks and [tc-ticks] arrays, timer_bench.txt)",
  "binaries": ".tmp/tickcost/bin (gitignored): gait_unit_plain.exe, gait_unit_tc.exe"
 },
 "falsifier_scoreboard": {
  "F1_COST_GAP": "FIRED (the finding: even byte-neutral removal of every peripheral class leaves 6.7-13.7x the 300 Hz budget; the residual is named: the FK equation count inside RK4/event machinery)",
  "F2_NUMERIC_DRIFT": "GREEN as a guard (32/32 runs byte-identical, instrument provably insertion-only); 5 optimization candidates recorded as physics-compatibility change requests, none implemented",
  "F3_MEASUREMENT_VALIDITY": "a GREEN, b RED (carried: shared-box machine state, drift evidence instrument-independent), c GREEN (0.11% bound, ~1.1% measured), d GREEN (101.9% closure)",
  "pre_committed_action": "every number carried verbatim; nothing tuned; no tracked engine byte modified; ship bytes restored/untouched throughout"
 }
}

out = HERE / "receipt_tick_cost.json"
out.write_text(json.dumps(receipt, indent=1), encoding="utf-8", newline="\n")
print("receipt written:", out, len(json.dumps(receipt)), "bytes")
