// Generated by GameCodeGenerator — values below come from the DSL economy_systems block
#include "EconomyInitializer.h"
#include "EconomyManager.h"
#include "CommodityData.h"
#include "StationTradingData.h"

void UEconomyInitializer::BuildEconomy(UEconomyManager* Manager)
{
	if (!Manager) return;

	{
		UCommodityData* C = NewObject<UCommodityData>(Manager);
		C->CommodityName = TEXT("Titanium");
		C->BasePrice = 62.5f;
		Manager->CommodityList.Add(C);
	}
	{
		UCommodityData* C = NewObject<UCommodityData>(Manager);
		C->CommodityName = TEXT("Iron_Ore");
		C->BasePrice = 30.0f;
		Manager->CommodityList.Add(C);
	}
	{
		UCommodityData* C = NewObject<UCommodityData>(Manager);
		C->CommodityName = TEXT("Synthetic_Food");
		C->BasePrice = 15.0f;
		Manager->CommodityList.Add(C);
	}
	{
		UCommodityData* C = NewObject<UCommodityData>(Manager);
		C->CommodityName = TEXT("Quantum_Cores");
		C->BasePrice = 5000.0f;
		Manager->CommodityList.Add(C);
	}

	{
		UStationTradingData* S = NewObject<UStationTradingData>(Manager);
		S->StationName = TEXT("Orbital_Hub_7");
		S->BuyPrices.Add(FName(TEXT("Titanium")), 80.0f);
		S->SellPrices.Add(FName(TEXT("Titanium")), 72.0f);
		S->BuyPrices.Add(FName(TEXT("Quantum_Cores")), 5000.0f);
		S->SellPrices.Add(FName(TEXT("Quantum_Cores")), 4200.0f);
		Manager->StationTradingList.Add(S);
	}
	{
		UStationTradingData* S = NewObject<UStationTradingData>(Manager);
		S->StationName = TEXT("Titan_Surface_Outpost");
		S->BuyPrices.Add(FName(TEXT("Titanium")), 45.0f);
		S->SellPrices.Add(FName(TEXT("Titanium")), 40.0f);
		Manager->StationTradingList.Add(S);
	}
	{
		UStationTradingData* S = NewObject<UStationTradingData>(Manager);
		S->StationName = TEXT("Ares_Market_Central");
		S->BuyPrices.Add(FName(TEXT("Iron_Ore")), 30.0f);
		S->SellPrices.Add(FName(TEXT("Iron_Ore")), 25.0f);
		S->BuyPrices.Add(FName(TEXT("Synthetic_Food")), 15.0f);
		S->SellPrices.Add(FName(TEXT("Synthetic_Food")), 12.0f);
		Manager->StationTradingList.Add(S);
	}
}
