import re
from typing import Dict, List, Any

try:
    from core.graphify_interface import query as g_query, load_dna_graph
except ImportError:
    try:
        from graphify_interface import query as g_query, load_dna_graph
    except ImportError:
        def g_query(*args, **kwargs): return None
        def load_dna_graph(): return {"nodes": [], "edges": []}

def classify_text(text: str) -> dict:
    """Phase 1: Classifier - reads text, categorizes statements into five categories."""
    physical_objects = []
    systems = []
    behaviors = []
    environments = []
    interactions = []
    
    # Split text into sentences/lines for analysis
    sentences = re.split(r'(?<=[.!?])\s+', text)
    
    object_keywords = ['station', 'ship', 'market', 'commodity', 'goods', 'infrastructure', 'platform', 'port', 'facility', 'structure']
    system_keywords = ['economy', 'trade', 'system', 'network', 'protocol', 'mechanism', 'framework', 'exchange', 'pricing', 'supply', 'demand']
    behavior_keywords = ['trades', 'buys', 'sells', 'negotiates', 'transports', 'delivers', 'stores', 'manufactures', 'exports', 'imports']
    environment_keywords = ['space', 'station', 'planet', 'orbit', 'sector', 'zone', 'region', 'system', 'void', 'nebula', 'hub']
    interaction_keywords = ['exchange', 'trade', 'interact', 'connect', 'link', 'route', 'supply', 'demand', 'transaction', 'deal', 'agreement']
    
    for sentence in sentences:
        sentence_lower = sentence.lower()
        
        # Check for physical objects
        for obj_kw in object_keywords:
            if obj_kw in sentence_lower and obj_kw not in [x.get('keyword', '') for x in physical_objects]:
                # Extract potential object name
                match = re.search(r'(?:the\s+|a\s+)([a-zA-Z_\-]+(?:\s+[a-zA-Z_\-]+)*?)\s+(?:station|ship|market|commodity|infrastructure|platform|port|facility)', sentence_lower)
                if match:
                    physical_objects.append({'keyword': obj_kw, 'context': sentence.strip(), 'extracted_name': match.group(1).strip()})
                else:
                    physical_objects.append({'keyword': obj_kw, 'context': sentence.strip()})
        
        # Check for systems
        for sys_kw in system_keywords:
            if sys_kw in sentence_lower and sys_kw not in [x.get('keyword', '') for x in systems]:
                systems.append({'keyword': sys_kw, 'context': sentence.strip()})
                
        # Check for behaviors
        for beh_kw in behavior_keywords:
            if beh_kw in sentence_lower and beh_kw not in [x.get('keyword', '') for x in behaviors]:
                behaviors.append({'keyword': beh_kw, 'context': sentence.strip()})
                
        # Check for environments
        for env_kw in environment_keywords:
            if env_kw in sentence_lower and env_kw not in [x.get('keyword', '') for x in environments]:
                environments.append({'keyword': env_kw, 'context': sentence.strip()})
                
        # Check for interactions
        for int_kw in interaction_keywords:
            if int_kw in sentence_lower and int_kw not in [x.get('keyword', '') for x in interactions]:
                interactions.append({'keyword': int_kw, 'context': sentence.strip()})
    
    return {
        "physical_objects": list(dict.fromkeys([x['keyword'] for x in physical_objects])),
        "systems": list(dict.fromkeys([x['keyword'] for x in systems])),
        "behaviors": list(dict.fromkeys([x['keyword'] for x in behaviors])),
        "environments": list(dict.fromkeys([x['keyword'] for x in environments])),
        "interactions": list(dict.fromkeys([x['keyword'] for x in interactions]))
    }

def translate_to_dsl_skeleton(classified: dict) -> str:
    """Phase 2: Translator - converts classified text into .chimera_ai intermediate format."""
    
    skeleton = f"""# CHIMERA_AI DSL SKELETON
# Generated by the Chimera Ether
# Three-Layer Knowledge Translation System

## LAYER 1: THE KNOWN (Deterministic Extraction)
# These facts are extracted from source text and cannot be changed.

@SYSTEMS
"""
    for sys in classified.get("systems", []):
        skeleton += f"- {sys}\n"
        
    skeleton += """
@PHYSICAL_OBJECTS
"""
    for obj in classified.get("physical_objects", []):
        skeleton += f"- {obj}\n"

    skeleton += """
@ENVIRONMENTS
"""
    for env in classified.get("environments", []):
        skeleton += f"- {env}\n"

    skeleton += """
@BEHAVIORS
"""
    for beh in classified.get("behaviors", []):
        skeleton += f"- {beh}\n"

    skeleton += """
@INTERACTIONS
"""
    for int_kw in classified.get("interactions", []):
        skeleton += f"- {int_kw}\n"

    skeleton += """
## LAYER 2: THE SUGGESTED (Graphify Patterns)
# Verified UE5 and Chimera DSL patterns applied as defaults.

# GRAPHIFY PATTERNS
"""
    
    # Phase 3: Graphify Integration
    categories = classified.get("systems", []) + classified.get("physical_objects", []) + \
                 classified.get("environments", []) + classified.get("behaviors", []) + \
                 classified.get("interactions", [])
                 
    for category in set(categories):
        try:
            pattern_result = g_query("pattern", category)
            if pattern_result:
                skeleton += f"\n@PATTERN {category}:\n"
                skeleton += "# Pattern defaults injected from Graphify\n"
        except Exception:
            pass  # Skip patterns not found in Graphify
        
    skeleton += """
@DEFAULTS
# Standard parameters applied based on pattern matching.
"""

    skeleton += """
## LAYER 3: THE CREATIVE (AI Generation Zone)
# Everything below this line is for AI to generate. Prices, events, dialogue, flavor.
# Creative work within deterministic bounds.

@GENERATE: MARKET_PRICES
# Generate commodity pricing table with min/max values based on supply/demand patterns.

@GENERATE: TRADE_EVENTS
# Generate dynamic market events that affect pricing and availability.

@GENERATE: NPC_DIALOGUE
# Generate faction-specific dialogue for market interactions and trade negotiations.

@GENERATE: FLAVOR_TEXT
# Generate descriptive text for stations, markets, and trading environments.

"""
    return skeleton


def test_ether():
    """Phase 4: Test - Feed the Ether a Wikipedia excerpt about space stations or markets."""
    
    wiki_excerpt = """
A space station is a spacecraft capable of supporting crew members in orbit for extended periods of time. 
Space stations are distinct from temporary manned spacecraft because they do not include a main propulsion or 
descent vehicle, but rather have provision for crew transfer. Space stations can be used as commercial markets, 
trade hubs, and economic centers where goods and commodities are exchanged. The economy of a space station 
involves supply and demand mechanisms, with pricing determined by market forces. Stations typically engage in 
buying and selling activities, negotiating trade routes and establishing exchanges with other facilities.
"""
    
    print("=== CHIMERA ETHER TEST ===\n")
    
    classified = classify_text(wiki_excerpt)
    print("--- LAYER 1: CLASSIFIED TEXT ---")
    for key, values in classified.items():
        print(f"{key}: {values}")
    print("\n--- LAYER 2 & 3: DSL SKELETON ---")
    
    skeleton = translate_to_dsl_skeleton(classified)
    print(skeleton)
    
    return skeleton

if __name__ == "__main__":
    test_ether()
