"""generate_economy_descriptions.py — Educational descriptions for EconomyInitializer.

The CommodityData struct has a Description field that is never populated
by the DSL generator. This script generates the educator-reviewed descriptions
that should be added to EconomyInitializer.cpp.

Output: formatted C++ code ready for paste-in to EconomyInitializer.cpp
"""

COMMODITY_DESCRIPTIONS = {
    "Titanium": (
        "Titanium is a lightweight, corrosion-resistant metal. "
        "On Titan, titanium compounds may exist in the crust, leached "
        "by cryovolcanic ammonia-water melts over geological time. "
        "Earth mines titanium from ilmenite and rutile ores; Titan's "
        "version would be locked in icy regolith, requiring processing "
        "similar to terrestrial refining."
    ),
    "Iron_Ore": (
        "Iron is the most common element by mass on Earth, forming "
        "the planet's core. On Titan, iron is likely present in its "
        "rocky core beneath the ice shell, inaccessible without deep "
        "mining. Surface iron would arrive via meteorite impacts — "
        "the same process that delivered Earth's early iron. Each "
        "ingot carries the story of planetary formation."
    ),
    "Synthetic_Food": (
        "Synthetic food is produced through controlled biological "
        "or chemical processes rather than agriculture. On Titan, "
        "where no soil exists, settlers would rely on hydroponics, "
        "cellular agriculture, and methane-fertilized microbial "
        "protein reactors — real technologies being developed today "
        "by NASA for long-duration space missions."
    ),
    "Quantum_Cores": (
        "Quantum cores exploit quantum mechanical properties for "
        "computation and energy storage. Unlike classical bits, "
        "quantum bits (qubits) exist in superposition, enabling "
        "calculations impossible on conventional computers. On Titan, "
        "the cryogenic environment naturally supports the near-zero "
        "temperatures required for stable quantum state coherence."
    ),
}

STATION_DESCRIPTIONS = {
    "Orbital_Hub_7": (
        "Orbital Hub 7 is the primary trade nexus in Titan orbit, "
        "processing cargo between surface outposts and deep-space "
        "vessels. Its position in low Titan orbit provides efficient "
        "transfer orbits to Saturn's other moons."
    ),
    "Titan_Surface_Outpost": (
        "Titan Surface Outpost is the first permanent human settlement "
        "on an extraterrestrial surface, situated near cryovolcanic "
        "vents for geothermal power and access to subsurface liquid water."
    ),
    "Ares_Market_Central": (
        "Ares Market Central serves as the economic heart of interplanetary "
        "trade, connecting Titan's hydrocarbon exports with the inner solar "
        "system's demand for volatiles and rare earth elements."
    ),
}


def generate_cpp_code():
    """Generate C++ code with educational descriptions for EconomyInitializer."""
    lines = []
    lines.append("// === Educational descriptions for each commodity ===")
    lines.append("// Generated by generate_economy_descriptions.py")
    lines.append("// Place these in EconomyInitializer.cpp after CommodityName = ...")
    lines.append("")
    
    for commodity, desc in COMMODITY_DESCRIPTIONS.items():
        cpp_desc = desc.replace('"', '\\"')
        lines.append(f'        C->Description = TEXT("{cpp_desc}");')
    
    lines.append("")
    lines.append("// === Station descriptions ===")
    lines.append("")
    for station, desc in STATION_DESCRIPTIONS.items():
        cpp_desc = desc.replace('"', '\\"')
        lines.append(f'        // S->Description = TEXT("{cpp_desc}");')
        lines.append(f'        // Note: StationTradingData has no Description field yet')
    
    return "\n".join(lines)


def generate_educational_report():
    """Print formatted report of all economic educational content."""
    print("=== ECONOMIC EDUCATIONAL CONTENT ===")
    print()
    print("Commodities with educational descriptions:")
    for name, desc in COMMODITY_DESCRIPTIONS.items():
        print(f"\n### {name}")
        print(f"{desc}")
        ref = COMMODITY_SOURCES.get(name, "VERIFY: needs source")
        print(f"*Source: {ref}*")
    
    print()
    print("---")
    print(f"Total commodities: {len(COMMODITY_DESCRIPTIONS)}")
    print(f"Total stations: {len(STATION_DESCRIPTIONS)}")
    print()


COMMODITY_SOURCES = {
    "Titanium": "USGS Titanium Statistics; NASA In-Situ Resource Utilization reports",
    "Iron_Ore": "USGS Iron Ore; NASA Planetary Science Division",
    "Synthetic_Food": "NASA CELSS (Controlled Ecological Life Support System) research; ESA MELiSSA Project",
    "Quantum_Cores": "VERIFY: general quantum computing principles — no specific Titan application source",
}


if __name__ == "__main__":
    import sys
    if "--cpp" in sys.argv:
        print(generate_cpp_code())
    elif "--report" in sys.argv:
        generate_educational_report()
    else:
        print("Usage: python generate_economy_descriptions.py [--cpp|--report]")
        print()
        generate_educational_report()
