"""
Restore Deleted Files Orchestrator — Regenerates deleted source files from git history context.

This script uses the CodeGenerationOrchestrator to regenerate deleted C++ and TypeScript files
based on their file names and project context from git history.
"""

import sys
from pathlib import Path

# Ensure UTF-8 encoding for stdout
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Add project root to path for imports
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from core.code_generation_orchestrator import CodeGenerationOrchestrator


def restore_cpp_file():
    """Restore MCPVisualTileVerification.cpp from Planet/Tests directory."""
    print("\n[1] Restoring: Source/ChimeraSpace/Planet/Tests/MCPVisualTileVerification.cpp")
    
    orchestrator = CodeGenerationOrchestrator(project_root=str(project_root))
    
    prompt = "Create a C++ test file MCPVisualTileVerification.cpp for Planet landscape tile verification using MCP (Model Context Protocol) visual tile verification. The file should verify planet tiles, landscape managers, and tile coordinates with UE5 testing frameworks."
    
    result = orchestrator.generate_cpp_code(
        prompt=prompt,
        model_id='qwen-agentworld-35b-a3b-nvfp4',
        temperature=0.1,
        max_tokens=2048,
        timeout=180
    )
    
    if result.get("success"):
        saved_file = orchestrator.save_generated_code(result, target_dir=str(project_root / "RestoredCode/C++/Planet/Tests"))
        print(f"  SUCCESS: Saved to {saved_file}")
        return True
    else:
        error_msg = str(result.get('error', 'Unknown error')).encode('utf-8', 'ignore').decode('utf-8')
        print(f"  FAILED: {error_msg}")
        return False


def restore_typescript_files():
    """Restore TypeScript files from SpaceGame/src and SpaceGame/tests directories."""
    ts_files = [
        ("SpaceGame/src/asteroid-belt.ts", "Create a TypeScript module for asteroid belt generation and management in a space game. Include asteroid spawning, positioning, physics simulation, and collision detection."),
        ("SpaceGame/src/features/mining/index.ts", "Create a TypeScript index file for the mining features module in a space game. Export mining systems, resource collection, and ore processing functions."),
        ("SpaceGame/tests/dynamic-events.test.ts", "Create a Jest test file for dynamic events system in a space game. Test event triggers, timeline management, and event resolution."),
        ("SpaceGame/tests/marketplace.test.ts", "Create a Jest test file for marketplace system in a space game. Test item listings, pricing, transactions, and inventory updates."),
        ("SpaceGame/tests/mining-system.test.ts", "Create a Jest test file for mining system in a space game. Test ore extraction, resource yield calculations, and tool durability."),
        ("SpaceGame/tests/monetization-ethics.test.ts", "Create a Jest test file for monetization ethics validation in a space game. Test fair pricing, no predatory mechanics, and ethical microtransactions."),
        ("SpaceGame/tests/salvage-system.test.ts", "Create a Jest test file for salvage system in a space game. Test debris collection, item recovery rates, and salvage value calculations."),
        ("SpaceGame/tests/wave2-phases-4-8.spec.ts", "Create a Playwright/E2E test specification for wave 2 phases 4-8 in a space game. Test gameplay phases, UI transitions, and system integrations.")
    ]
    
    orchestrator = CodeGenerationOrchestrator(project_root=str(project_root))
    success_count = 0
    
    for file_path, prompt in ts_files:
        print(f"\n[2] Restoring TypeScript/TS: {file_path}")
        
        result = orchestrator.generate_typescript_code(
            prompt=prompt,
            model_id='qwen-agentworld-35b-a3b-nvfp4',
            temperature=0.1,
            max_tokens=2048,
            timeout=180
        )
        
        if result.get("success"):
            # Save with .ts extension
            code = result.get("code", "")
            if not code:
                print(f"  WARNING: No code content generated for {file_path}")
            
            filename_hint = file_path.split('/')[-1] if '/' in file_path else file_path
            
            # Determine output directory based on whether it's a test or src file
            if 'tests/' in file_path or '.test.ts' in file_path or '.spec.ts' in file_path:
                target_dir = project_root / "RestoredCode/TypeScript/tests"
            else:
                target_dir = project_root / "RestoredCode/TypeScript/src"
            
            target_dir.mkdir(parents=True, exist_ok=True)
            output_file = target_dir / filename_hint
            
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write("// Generated by RestoreDeletedFilesOrchestrator\n")
                f.write(f"// Original path: {file_path}\n")
                f.write("//\n")
                if code:
                    f.write(code)
                else:
                    f.write("// [No code content generated]\n")
            
            print(f"  SUCCESS: Saved to {output_file}")
            success_count += 1
        else:
            error_msg = str(result.get('error', 'Unknown error')).encode('utf-8', 'ignore').decode('utf-8')
            print(f"  FAILED: {error_msg}")
            
    return success_count == len(ts_files)


def run_restore_workflow():
    """Run the complete restored files workflow."""
    print("=" * 70)
    print("RESTORE DELETED FILES WORKFLOW")
    print("=" * 70)
    
    # Restore C++ file
    cpp_success = restore_cpp_file()
    
    # Restore TypeScript files
    ts_success = restore_typescript_files()
    
    print("\n" + "=" * 70)
    print("[COMPLETED] Restore deleted files workflow finished.")
    print(f"Restored code files are available in: {project_root / 'RestoredCode'}")
    print("=" * 70)


if __name__ == "__main__":
    run_restore_workflow()
