// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "PCGVolumeManager.generated.h"

UCLASS()
class CHIMERA_API APCGVolumeManager : public AActor
{
	GENERATED_BODY()

public:
	APCGVolumeManager();

protected:
	virtual void BeginPlay() override;

public:
	UFUNCTION(BlueprintCallable, Category = "PCG")
	void SpawnPCGVolumeForGraph(FString GraphAssetPath, FVector Location, FVector Extent, FName VolumeName);

};

