// Generated by GameCodeGenerator from tests/dsl_grammar (satellite specs)
// source spec: planet_generation.chimera
#pragma once
#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "PlanetGenerationSpecComponent.generated.h"

UCLASS(meta = (BlueprintType, Category = "SpecBindings"))
class CHIMERA_API UPlanetGenerationSpecComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UPlanetGenerationSpecComponent(const FObjectInitializer& ObjectInitializer);

	// spec: generator_type
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	FString GeneratorType = TEXT("procedural_terrain");
	// spec: base_biomes
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	TArray<FString> BaseBiomes;
	// spec: cloud_layers
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	int32 CloudLayers = 5;
	// spec: cluster_density_per_cubic_km
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float ClusterDensityPerCubicKm = 0.5f;
	// spec: color_gradients
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	TArray<FString> ColorGradients;
	// spec: composition_types
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	TArray<FString> CompositionTypes;
	// spec: has_ring_system
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	bool bHasRingSystem = false;
	// spec: size_variation_meters
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float SizeVariationMeters = 10.0f;
	// spec: spawn_resource_nodes
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	bool bSpawnResourceNodes = true;
	// spec: supports_dynamic_weather
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	bool bSupportsDynamicWeather = true;
	// spec: terrain_detail_levels
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	int32 TerrainDetailLevels = 3;
	// spec: terrain_roughness
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float TerrainRoughness = 0.3f;
	// spec: tree_height_range_meters
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	FVector2D TreeHeightRangeMeters = FVector2D(15.0f, 45.0f);
	// spec: turbulence_factor
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float TurbulenceFactor = 0.85f;
	// spec: weather_systems
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	TArray<FString> WeatherSystems;
	// spec: wildlife_spawns
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	TArray<FString> WildlifeSpawns;

	UFUNCTION(BlueprintCallable, Category = "Spec")
	float TerrainAmplitude() const;
	UFUNCTION(BlueprintCallable, Category = "Spec")
	float TreeHeightAt(float T01) const;
	UFUNCTION(BlueprintCallable, Category = "Spec")
	bool WeatherAllowed() const;

	UFUNCTION(BlueprintCallable, Category = "Spec")
	bool ValidateSpec() const;
};
