// Generated by GameCodeGenerator from tests/dsl_grammar (satellite specs)
#include "PlanetGenerationSpecComponent.h"

UPlanetGenerationSpecComponent::UPlanetGenerationSpecComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	BaseBiomes = { TEXT("forest"), TEXT("desert"), TEXT("tundra"), TEXT("ocean") };
	ColorGradients = { TEXT("brown"), TEXT("tan"), TEXT("white") };
	CompositionTypes = { TEXT("rocky"), TEXT("metallic"), TEXT("icy") };
	WeatherSystems = { TEXT("rain"), TEXT("snow"), TEXT("dust_storms") };
	WildlifeSpawns = { TEXT("avian_flock"), TEXT("ground_forager") };
}

float UPlanetGenerationSpecComponent::TerrainAmplitude() const
{
	return TerrainRoughness * (float)TerrainDetailLevels * (1.0f + TurbulenceFactor);
}

float UPlanetGenerationSpecComponent::TreeHeightAt(float T01) const
{
	return FMath::Lerp(TreeHeightRangeMeters.X, TreeHeightRangeMeters.Y, FMath::Clamp(T01, 0.0f, 1.0f));
}

bool UPlanetGenerationSpecComponent::WeatherAllowed() const
{
	return bSupportsDynamicWeather && WeatherSystems.Num() > 0;
}

bool UPlanetGenerationSpecComponent::ValidateSpec() const
{
	// every spec property is read here — a value nothing reads is
	// metadata, not a feature (H-21).
	const bool bNamed = !GeneratorType.IsEmpty() && BaseBiomes.Num() >= 0 && ColorGradients.Num() >= 0 && CompositionTypes.Num() >= 0 && WeatherSystems.Num() >= 0 && WildlifeSpawns.Num() >= 0;
	const float NumericTouch = (float)CloudLayers + (float)ClusterDensityPerCubicKm + (bHasRingSystem ? 1.0f : 0.0f) + (float)SizeVariationMeters + (bSpawnResourceNodes ? 1.0f : 0.0f) + (bSupportsDynamicWeather ? 1.0f : 0.0f) + (float)TerrainDetailLevels + (float)TerrainRoughness + TreeHeightRangeMeters.Size() + (float)TurbulenceFactor;
	return bNamed && FMath::IsFinite(NumericTouch);
}
