// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "UChimeraAttunementComponent.generated.h"

UCLASS( meta = (BlueprintType, Category = "AudioAttunement") )
class CHIMERA_API UChimeraAttunementComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UChimeraAttunementComponent(const FObjectInitializer& ObjectInitializer);
};
