// Generated by GameCodeGenerator
#include "UChimeraAttunementComponent.h"

UChimeraAttunementComponent::UChimeraAttunementComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}
