// Generated by GameCodeGenerator
#pragma warning(disable: 5038)
#pragma warning(disable: 4996)
#include "UChimeraAttunementComponent.h"

UChimeraAttunementComponent::UChimeraAttunementComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}
