// Generated by GameCodeGenerator
#include "DropActor.h"
#include "Components/SceneComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/BoxComponent.h"

ADropActor::ADropActor()
{
	PrimaryActorTick.bCanEverTick = true;

	RootScene = CreateDefaultSubobject<USceneComponent>(TEXT("RootScene"));
	RootComponent = RootScene;

	DropMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("DropMesh"));
	DropMesh->SetupAttachment(RootScene);

	CollisionComponent = CreateDefaultSubobject<UBoxComponent>(TEXT("CollisionComponent"));
	CollisionComponent->SetupAttachment(DropMesh);
	CollisionComponent->SetBoxExtent(FVector(50.0f, 50.0f, 50.0f));
	CollisionComponent->SetGenerateOverlapEvents(true);

	DropState = EDropActorState::Dropped;

	bIsStackable = false;
	MaxStackSize = 1;
	CurrentStackSize = 1;

	DropVelocity = FVector(0.0f, 0.0f, -500.0f);
	Bounciness = 0.3f;
	Friction = 0.5f;
}

void ADropActor::BeginPlay()
{
	Super::BeginPlay();

	// Enable physics simulation on the drop mesh
	if (DropMesh)
	{
		DropMesh->SetSimulatePhysics(true);

		// Apply initial drop velocity
		DropMesh->AddImpulse(DropVelocity, NAME_None, true);
	}
}

void ADropActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	if (DropState == EDropActorState::PhysicsSimulating)
	{
		// Check if physics has stabilized (velocity below threshold)
		if (DropMesh && DropMesh->IsSimulatingPhysics())
		{
			float Speed = DropMesh->GetPhysicsLinearVelocity().Size();

			if (Speed < 10.0f)
			{
				// Item has stabilized, transition to Stabilized state
				Stabilize();
			}
		}
	}
}

void ADropActor::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
}

EDropActorState ADropActor::GetDropState() const
{
	return DropState;
}

void ADropActor::EnablePhysicsSimulation()
{
	if (DropMesh && !DropMesh->IsSimulatingPhysics())
	{
		DropMesh->SetSimulatePhysics(true);

		DropState = EDropActorState::PhysicsSimulating;

		// Apply initial drop velocity if provided
		if (DropVelocity.SizeSquared() > 0.0f)
		{
			DropMesh->AddImpulse(DropVelocity, NAME_None, true);
		}
	}
}

void ADropActor::Stabilize()
{
	if (DropMesh && DropMesh->IsSimulatingPhysics())
	{
		DropMesh->SetSimulatePhysics(false);
		DropMesh->SetEnableGravity(true);
		
		// Lock all transforms to prevent further movement
		DropMesh->SetWorldLocationAndRotation(DropMesh->GetComponentLocation(), DropMesh->GetComponentRotation(), false, nullptr, ETeleportType::None);

		DropState = EDropActorState::Stabilized;
	}
}
