// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "DropActor.generated.h"

UENUM(BlueprintType)
enum class EDropActorState : uint8
{
	Dropped UMETA(DisplayName = "Dropped"),
	PhysicsSimulating UMETA(DisplayName = "Physics Simulating"),
	Stabilized UMETA(DisplayName = "Stabilized")
};

UCLASS()
class CHIMERA_API ADropActor : public AActor
{
	GENERATED_BODY()

public:
	ADropActor();

protected:
	virtual void BeginPlay() override;

public:	
	virtual void Tick(float DeltaTime) override;

	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Drop|Components")
	class USceneComponent* RootScene;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Drop|Components")
	class UStaticMeshComponent* DropMesh;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Drop|Components")
	class UBoxComponent* CollisionComponent;

	/** Interaction state of the drop actor */
	UPROPERTY(BlueprintReadOnly, Category = "Drop|State")
	EDropActorState DropState;

	/** Name or display name of the dropped item */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Drop|Item")
	FText ItemName;

	/** Whether this drop item can be picked up multiple times (stackable) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Drop|Item")
	bool bIsStackable;

	/** Maximum stack size for stackable items */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Drop|Item", meta = (EditCondition = "bIsStackable"))
	int32 MaxStackSize;

	/** Current stack count */
	UPROPERTY(BlueprintReadOnly, Category = "Drop|Item")
	int32 CurrentStackSize;

	/** Initial drop velocity for physics simulation */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Drop|Physics")
	FVector DropVelocity;

	/** Physics bounce factor (0.0 to 1.0) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Drop|Physics")
	float Bounciness;

	/** Physics friction (0.0 to 1.0) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Drop|Physics")
	float Friction;

	/** Called when the drop item is picked up by a player */
	UFUNCTION(BlueprintImplementableEvent, Category = "Drop|Events")
	void OnPickedUp();

	/** Get the current drop state */
	EDropActorState GetDropState() const;

	/** Enable physics simulation on the drop mesh */
	void EnablePhysicsSimulation();

	/** Stabilize the drop item (disable further physics movement) */
	void Stabilize();
};
