// Generated by GameCodeGenerator
#pragma warning(disable: 5038)
#pragma warning(disable: 4996)
#include "PickupActor.h"
#include "Components/SceneComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/BoxComponent.h"
#include "Engine/StaticMesh.h"
#include "UObject/ConstructorHelpers.h"

APickupActor::APickupActor()
{
	PrimaryActorTick.bCanEverTick = true;

	RootScene = CreateDefaultSubobject<USceneComponent>(TEXT("RootScene"));
	RootComponent = RootScene;

	PickupMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("PickupMesh"));
	PickupMesh->SetupAttachment(RootScene);

	// Default visual: reuse the project's existing weapon mesh so a spawned
	// pickup reads clearly as a real, held-able item rather than an invisible
	// collision box. Individual spawns may override PickupMesh afterward.
	static ConstructorHelpers::FObjectFinder<UStaticMesh> MeshFinder(TEXT("/Game/Tools/Geometry/SM_Weapon.SM_Weapon"));
	if (MeshFinder.Succeeded())
	{
		PickupMesh->SetStaticMesh(MeshFinder.Object);
	}

	CollisionComponent = CreateDefaultSubobject<UBoxComponent>(TEXT("CollisionComponent"));
	CollisionComponent->SetupAttachment(RootScene);
	CollisionComponent->SetBoxExtent(FVector(50.0f, 50.0f, 50.0f));
	CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
	CollisionComponent->SetCollisionObjectType(ECC_WorldDynamic);
	CollisionComponent->SetCollisionResponseToAllChannels(ECR_Overlap);

	InteractionState = EPickupActorState::Ready;
	bIsStackable = false;
	MaxStackSize = 1;
	CurrentStackSize = 1;
}

void APickupActor::BeginPlay()
{
	Super::BeginPlay();
}

void APickupActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

void APickupActor::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
}

EPickupActorState APickupActor::GetInteractionState() const
{
	return InteractionState;
}

void APickupActor::PickUp()
{
	if (InteractionState != EPickupActorState::Ready)
	{
		return;
	}

	InteractionState = EPickupActorState::PickedUp;
	OnPickedUp();

	if (GetRootComponent())
	{
		GetRootComponent()->SetVisibility(false, true);
	}

	Destroy();
}
