// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "PickupActor.generated.h"

UENUM(BlueprintType)
enum class EPickupActorState : uint8
{
	Ready UMETA(DisplayName = "Ready"),
	Interacting UMETA(DisplayName = "Interacting"),
	PickedUp UMETA(DisplayName = "Picked Up")
};

UCLASS()
class CHIMERA_API APickupActor : public AActor
{
	GENERATED_BODY()

public:
	APickupActor();

protected:
	virtual void BeginPlay() override;

public:	
	virtual void Tick(float DeltaTime) override;

	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Pickup|Components")
	class USceneComponent* RootScene;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Pickup|Components")
	class UStaticMeshComponent* PickupMesh;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Pickup|Components")
	class UBoxComponent* CollisionComponent;

	/** Interaction state of the pickup actor */
	UPROPERTY(BlueprintReadOnly, Category = "Pickup|State")
	EPickupActorState InteractionState;

	/** Name or display name of the pickup item */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Pickup|Item")
	FText ItemName;

	/** Whether this pickup can be picked up multiple times (stackable) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Pickup|Item")
	bool bIsStackable;

	/** Maximum stack size for stackable items */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Pickup|Item", meta = (EditCondition = "bIsStackable"))
	int32 MaxStackSize;

	/** Current stack count */
	UPROPERTY(BlueprintReadOnly, Category = "Pickup|Item")
	int32 CurrentStackSize;

	/** Called when the pickup is picked up by a player */
	UFUNCTION(BlueprintImplementableEvent, Category = "Pickup|Events")
	void OnPickedUp();

	/** Get the current interaction state */
	EPickupActorState GetInteractionState() const;

	/** Mark the pickup as picked up and destroy or hide it */
	void PickUp();
};
