// Generated by GameCodeGenerator
#include "PickupInteractionComponent.h"
#include "PickupActor.h"
#include "Components/PrimitiveComponent.h"
#include "Kismet/KismetMathLibrary.h"

UPickupInteractionComponent::UPickupInteractionComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer),
	  InteractionRadius(200.0f),
	  TraceType(0),
	  CurrentState(EPickupInteractionState::PickupReady)
{
	PrimaryComponentTick.bCanEverTick = false;
}

void UPickupInteractionComponent::BeginPlay()
{
	Super::BeginPlay();

	UPrimitiveComponent* RootPrimitive = Cast<UPrimitiveComponent>(GetOwner()->GetRootComponent());
	if (RootPrimitive)
	{
		RootPrimitive->OnComponentBeginOverlap.AddDynamic(this, &UPickupInteractionComponent::OnOverlapBegin);
		RootPrimitive->OnComponentEndOverlap.AddDynamic(this, &UPickupInteractionComponent::OnOverlapEnd);
	}
}

void UPickupInteractionComponent::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	Super::EndPlay(EndPlayReason);

	UPrimitiveComponent* RootPrimitive = Cast<UPrimitiveComponent>(GetOwner()->GetRootComponent());
	if (RootPrimitive)
	{
		RootPrimitive->OnComponentBeginOverlap.RemoveDynamic(this, &UPickupInteractionComponent::OnOverlapBegin);
		RootPrimitive->OnComponentEndOverlap.RemoveDynamic(this, &UPickupInteractionComponent::OnOverlapEnd);
	}
}

void UPickupInteractionComponent::OnOverlapBegin(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	if (OtherActor && OtherActor->IsA(APickupActor::StaticClass()))
	{
		APickupActor* Pickup = Cast<APickupActor>(OtherActor);
		if (Pickup /*&& Pickup->GetInteractionState() == EPickupActorState::EPickupActorState::Ready*/)
		{
			if (!OverlappingPickups.Contains(Pickup))
			{
				OverlappingPickups.Add(Pickup);
				OnPickupReady(Pickup);
			}
		}
	}
}

void UPickupInteractionComponent::OnOverlapEnd(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	if (OtherActor && OtherActor->IsA(APickupActor::StaticClass()))
	{
		APickupActor* Pickup = Cast<APickupActor>(OtherActor);
		if (Pickup && OverlappingPickups.Contains(Pickup))
		{
			OverlappingPickups.Remove(Pickup);
		}
	}
}

APickupActor* UPickupInteractionComponent::GetClosestPickup() const
{
	APickupActor* ClosestPickup = nullptr;
	float MinDistance = FLT_MAX;

	for (APickupActor* Pickup : OverlappingPickups)
	{
		if (Pickup /*&& Pickup->GetInteractionState() == EPickupActorState::EPickupActorState::Ready*/)
		{
			if (GetOwner())
			{
				float Distance = UKismetMathLibrary::Vector_Distance(GetOwner()->GetActorLocation(), Pickup->GetActorLocation());
				if (Distance < MinDistance)
				{
					MinDistance = Distance;
					ClosestPickup = Pickup;
				}
			}
		}
	}

	return ClosestPickup;
}

void UPickupInteractionComponent::TryInteract()
{
	if (CurrentState != EPickupInteractionState::PickupReady)
	{
		// Ready state not reached yet or already processing
	}

	APickupActor* ClosestPickup = GetClosestPickup();
	if (ClosestPickup)
	{
		CurrentState = EPickupInteractionState::PickupInteracting;
		OnPickupInteract(ClosestPickup);
	}
}
