// Generated by GameCodeGenerator
// Acceptance tests measuring the BUILT systems (result-grading correctness evidence).
// Names are prefixed "ChimeraTests.Acceptance." — run: Automation RunTests ChimeraTests

#include "CoreMinimal.h"
#include "Misc/AutomationTest.h"
#include "Kismet/GameplayStatics.h"
#include "../Economy/CommodityData.h"
#include "../Factions/FactionComponent.h"
#include "../Missions/MissionComponent.h"
#include "../Missions/MissionData.h"
#include "../Save/DeepSpaceTraderSaveGame.h"
#include "../Save/SaveGameComponent.h"
#include "../Inventory/InventoryTradeComponent.h"
#include "../Economy/EconomyManager.h"
#include "../Economy/EconomyInitializer.h"
#include "../Economy/StationTradingData.h"
#include "../Combat/ShieldComponent.h"
#include "../Combat/DamageComponent.h"
#include "Engine/Engine.h"
#include "Engine/World.h"

#if WITH_DEV_AUTOMATION_TESTS

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FEconomyPriceRespondsToSupplyDemand,
	"ChimeraTests.Acceptance.EconomyPriceRespondsToSupplyDemand",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FEconomyPriceRespondsToSupplyDemand::RunTest(const FString& Parameters)
{
	UCommodityData* Commodity = NewObject<UCommodityData>();
	Commodity->BasePrice = 100.0f;

	Commodity->CurrentSupply = 1000.0f;
	Commodity->CurrentDemand = 1000.0f;
	const float Baseline = Commodity->CalculateCurrentPrice();
	TestTrue(TEXT("Balanced market prices near base"), FMath::IsNearlyEqual(Baseline, 100.0f, 1.0f));

	Commodity->CurrentDemand = 2000.0f;
	const float ScarcityPrice = Commodity->CalculateCurrentPrice();
	TestTrue(TEXT("Higher demand raises price"), ScarcityPrice > Baseline);

	Commodity->CurrentDemand = 500.0f;
	Commodity->CurrentSupply = 2000.0f;
	const float GlutPrice = Commodity->CalculateCurrentPrice();
	TestTrue(TEXT("Oversupply lowers price"), GlutPrice < Baseline);

	Commodity->CurrentDemand = 1000000.0f;
	Commodity->CurrentSupply = 1.0f;
	TestTrue(TEXT("Price clamps at 4x base"), Commodity->CalculateCurrentPrice() <= 400.0f + KINDA_SMALL_NUMBER);

	Commodity->CurrentDemand = 1.0f;
	Commodity->CurrentSupply = 1000000.0f;
	TestTrue(TEXT("Price clamps at 0.25x base"), Commodity->CalculateCurrentPrice() >= 25.0f - KINDA_SMALL_NUMBER);

	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FFactionStandingSafeAndLadderExact,
	"ChimeraTests.Acceptance.FactionStandingSafeAndLadderExact",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FFactionStandingSafeAndLadderExact::RunTest(const FString& Parameters)
{
	UFactionComponent* Factions = NewObject<UFactionComponent>();

	// Regression guard: standing change on a never-seeded faction must not assert
	Factions->ModifyStanding(FName(TEXT("faction_never_seeded")), -10.0f);
	TestTrue(TEXT("Unseeded faction standing recorded"),
		FMath::IsNearlyEqual(Factions->GetStanding(FName(TEXT("faction_never_seeded"))), -10.0f));

	// Ladder boundaries: Hostile <= -75 < Unfriendly <= -25 < Neutral <= 24 < Friendly <= 74 < Allied
	struct FLadderCase { float Standing; const TCHAR* Expected; };
	const FLadderCase Cases[] = {
		{ -75.0f, TEXT("Hostile") }, { -25.0f, TEXT("Unfriendly") },
		{ 24.0f, TEXT("Neutral") }, { 74.0f, TEXT("Friendly") }, { 75.0f, TEXT("Allied") },
	};
	for (const FLadderCase& Case : Cases)
	{
		const FName Faction(*FString::Printf(TEXT("ladder_%d"), (int32)Case.Standing));
		Factions->ModifyStanding(Faction, Case.Standing);
		TestEqual(FString::Printf(TEXT("Standing %.0f maps to %s"), Case.Standing, Case.Expected),
			Factions->GetRelationship(Faction), FString(Case.Expected));
	}

	// DSL seeding: pirates start hostile
	Factions->InitializeFromDSL();
	TestTrue(TEXT("Pirate syndicate seeded hostile"),
		Factions->IsHostile(FName(TEXT("faction_pirate_syndicate"))));

	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FSaveGameRoundtripPersistsState,
	"ChimeraTests.Acceptance.SaveGameRoundtripPersistsState",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FSaveGameRoundtripPersistsState::RunTest(const FString& Parameters)
{
	const FString Slot = TEXT("AcceptanceTestSlot");
	UDeepSpaceTraderSaveGame* Save = Cast<UDeepSpaceTraderSaveGame>(
		UGameplayStatics::CreateSaveGameObject(UDeepSpaceTraderSaveGame::StaticClass()));
	if (!TestNotNull(TEXT("Save object created"), Save)) return false;

	Save->PlayerCredits = 1234.5f;
	Save->PlayerCargo.Add(FName(TEXT("Titanium")), 7);
	Save->FactionStandings.Add(FName(TEXT("faction_pirate_syndicate")), -75.0f);
	FMissionData Mission;
	Mission.MissionID = FName(TEXT("Deliver_Titanium"));
	Mission.CurrentObjectiveIndex = 2;
	Mission.RewardCredits = 25000.0f;
	Save->ActiveMissions.Add(Mission);
	Save->PlayerLocation = FVector(1.0f, 2.0f, 3.0f);

	TestTrue(TEXT("SaveGameToSlot succeeds"), UGameplayStatics::SaveGameToSlot(Save, Slot, 0));

	UDeepSpaceTraderSaveGame* Loaded = Cast<UDeepSpaceTraderSaveGame>(
		UGameplayStatics::LoadGameFromSlot(Slot, 0));
	if (!TestNotNull(TEXT("Loaded save object"), Loaded)) return false;

	TestTrue(TEXT("Credits survive roundtrip"), FMath::IsNearlyEqual(Loaded->PlayerCredits, 1234.5f));
	TestEqual(TEXT("Cargo survives roundtrip"), Loaded->PlayerCargo.FindRef(FName(TEXT("Titanium"))), 7);
	TestTrue(TEXT("Faction standing survives roundtrip"),
		FMath::IsNearlyEqual(Loaded->FactionStandings.FindRef(FName(TEXT("faction_pirate_syndicate"))), -75.0f));
	if (TestEqual(TEXT("Active mission survives roundtrip"), Loaded->ActiveMissions.Num(), 1))
	{
		TestEqual(TEXT("Mission id intact"), Loaded->ActiveMissions[0].MissionID, FName(TEXT("Deliver_Titanium")));
		TestEqual(TEXT("Objective progress intact"), Loaded->ActiveMissions[0].CurrentObjectiveIndex, 2);
	}
	TestTrue(TEXT("Player location survives roundtrip"),
		Loaded->PlayerLocation.Equals(FVector(1.0f, 2.0f, 3.0f)));

	UGameplayStatics::DeleteGameInSlot(Slot, 0);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FMissionAcceptMovesToActive,
	"ChimeraTests.Acceptance.MissionAcceptMovesToActive",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FMissionAcceptMovesToActive::RunTest(const FString& Parameters)
{
	UMissionComponent* Missions = NewObject<UMissionComponent>();

	FMissionData Mission;
	Mission.MissionID = FName(TEXT("T1"));
	Mission.Status = TEXT("Available");
	Missions->AvailableMissions.Add(Mission);

	Missions->AcceptMission(FName(TEXT("T1")));
	TestEqual(TEXT("Mission moved to active"), Missions->ActiveMissions.Num(), 1);
	TestEqual(TEXT("Mission left the board"), Missions->AvailableMissions.Num(), 0);
	if (Missions->ActiveMissions.Num() == 1)
	{
		TestEqual(TEXT("Accepted mission is T1"), Missions->ActiveMissions[0].MissionID, FName(TEXT("T1")));
	}

	// Unknown id must be a no-op, never a crash
	Missions->AcceptMission(FName(TEXT("does_not_exist")));
	TestEqual(TEXT("Unknown id changes nothing"), Missions->ActiveMissions.Num(), 1);

	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FMissionObjectiveProgressionAndCompletion,
	"ChimeraTests.Acceptance.MissionObjectiveProgressionAndCompletion",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FMissionObjectiveProgressionAndCompletion::RunTest(const FString& Parameters)
{
	UMissionComponent* Missions = NewObject<UMissionComponent>();

	FMissionData Mission;
	Mission.MissionID = FName(TEXT("OBJ1"));
	FMissionObjective Deliver;
	Deliver.Type = TEXT("Deliver");
	Deliver.Commodity = FName(TEXT("Titanium"));
	FMissionObjective Dock;
	Dock.Type = TEXT("Dock");
	Mission.Objectives.Add(Deliver);
	Mission.Objectives.Add(Dock);
	Missions->AvailableMissions.Add(Mission);
	Missions->AcceptMission(FName(TEXT("OBJ1")));

	Missions->UpdateObjective(TEXT("Deliver"), TEXT("Titanium"));
	if (TestEqual(TEXT("Mission still active after first objective"), Missions->ActiveMissions.Num(), 1))
	{
		TestEqual(TEXT("Objective index advanced"), Missions->ActiveMissions[0].CurrentObjectiveIndex, 1);
	}
	TestEqual(TEXT("Not completed early"), Missions->CompletedMissions.Num(), 0);

	Missions->UpdateObjective(TEXT("Dock"), TEXT(""));
	TestTrue(TEXT("Mission completed after final objective"),
		Missions->CompletedMissions.Contains(FName(TEXT("OBJ1"))));
	TestEqual(TEXT("Completed mission left active list"), Missions->ActiveMissions.Num(), 0);

	// Completion must pay out exactly once — a repeat event cannot re-complete it
	Missions->UpdateObjective(TEXT("Dock"), TEXT(""));
	int32 Count = 0;
	for (const FName& Id : Missions->CompletedMissions) { if (Id == FName(TEXT("OBJ1"))) Count++; }
	TestEqual(TEXT("Mission completed exactly once"), Count, 1);

	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FSaveGameComponentRoundtripOnActor,
	"ChimeraTests.Acceptance.SaveGameComponentRoundtripOnActor",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FSaveGameComponentRoundtripOnActor::RunTest(const FString& Parameters)
{
	// Exercises the REAL integration path: SaveGameComponent reading and restoring
	// sibling components via FindComponentByClass (previously zero executed coverage).
	// World via GEngine (no UnrealEd dependency for a game module).
	UWorld* World = nullptr;
	if (GEngine)
	{
		for (const FWorldContext& Context : GEngine->GetWorldContexts())
		{
			if (Context.World()) { World = Context.World(); break; }
		}
	}
	if (!TestNotNull(TEXT("World available"), World)) return false;
	AActor* Actor = World->SpawnActor<AActor>();
	if (!TestNotNull(TEXT("Actor spawned"), Actor)) return false;

	UInventoryTradeComponent* Inv = NewObject<UInventoryTradeComponent>(Actor);
	Inv->RegisterComponent();
	UMissionComponent* Missions = NewObject<UMissionComponent>(Actor);
	Missions->RegisterComponent();
	UFactionComponent* Factions = NewObject<UFactionComponent>(Actor);
	Factions->RegisterComponent();
	USaveGameComponent* Saver = NewObject<USaveGameComponent>(Actor);
	Saver->RegisterComponent();

	Inv->SetCredits(500.0f);
	TMap<FName, int32> Cargo;
	Cargo.Add(FName(TEXT("Titanium")), 3);
	Inv->SetCargo(Cargo);
	Factions->ModifyStanding(FName(TEXT("faction_titan_miners")), 25.0f);
	FMissionData Mission;
	Mission.MissionID = FName(TEXT("RT1"));
	Missions->ActiveMissions.Add(Mission);

	const FName Slot(TEXT("ComponentPathSlot"));
	TestTrue(TEXT("Component SaveGame succeeds"), Saver->SaveGame(Slot));

	// Mutate everything, then restore
	Inv->SetCredits(0.0f);
	Inv->SetCargo(TMap<FName, int32>());
	Missions->ActiveMissions.Empty();
	Factions->ModifyStanding(FName(TEXT("faction_titan_miners")), -100.0f);

	TestTrue(TEXT("Component LoadGame succeeds"), Saver->LoadGame(Slot));
	TestTrue(TEXT("Credits restored through component path"), FMath::IsNearlyEqual(Inv->GetCredits(), 500.0f));
	TestEqual(TEXT("Cargo restored through component path"), Inv->GetCargoQuantity(FName(TEXT("Titanium"))), 3);
	TestEqual(TEXT("Active mission restored through component path"), Missions->ActiveMissions.Num(), 1);
	TestTrue(TEXT("Faction standing restored through component path"),
		FMath::IsNearlyEqual(Factions->GetStanding(FName(TEXT("faction_titan_miners"))), 25.0f));

	UGameplayStatics::DeleteGameInSlot(TEXT("ComponentPathSlot"), 0);
	Actor->Destroy();
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FEconomyInitializerAppliesDSLPrices,
	"ChimeraTests.Acceptance.EconomyInitializerAppliesDSLPrices",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FEconomyInitializerAppliesDSLPrices::RunTest(const FString& Parameters)
{
	UEconomyManager* Manager = NewObject<UEconomyManager>();
	UEconomyInitializer::BuildEconomy(Manager);

	TestTrue(TEXT("Commodities loaded from DSL"), Manager->CommodityList.Num() >= 4);
	TestNotNull(TEXT("Titanium exists in-engine"), Manager->GetCommodityByName(TEXT("Titanium")));

	UStationTradingData* Titan = nullptr;
	UStationTradingData* Hub = nullptr;
	for (UStationTradingData* S : Manager->StationTradingList)
	{
		if (!S) continue;
		if (S->StationName == TEXT("Titan_Surface_Outpost")) Titan = S;
		if (S->StationName == TEXT("Orbital_Hub_7")) Hub = S;
	}
	if (TestNotNull(TEXT("Titan outpost station loaded"), Titan))
	{
		TestTrue(TEXT("DSL: Titanium buys at 45 at the mine"),
			FMath::IsNearlyEqual(Titan->GetBuyPriceForCommodity(TEXT("Titanium"), 0.0f), 45.0f));
		TestTrue(TEXT("DSL: Titanium sells at 40 at the mine"),
			FMath::IsNearlyEqual(Titan->GetSellPriceForCommodity(TEXT("Titanium"), 0.0f), 40.0f));
	}
	if (TestNotNull(TEXT("Orbital hub station loaded"), Hub))
	{
		TestTrue(TEXT("DSL: Titanium buys at 80 at the hub"),
			FMath::IsNearlyEqual(Hub->GetBuyPriceForCommodity(TEXT("Titanium"), 0.0f), 80.0f));
	}
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FMissionBoardLoadsDSLMissions,
	"ChimeraTests.Acceptance.MissionBoardLoadsDSLMissions",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FMissionBoardLoadsDSLMissions::RunTest(const FString& Parameters)
{
	UMissionComponent* Missions = NewObject<UMissionComponent>();
	Missions->InitializeMissionBoardFromDSL();

	TestEqual(TEXT("All DSL missions on the board"), Missions->AvailableMissions.Num(), 3);
	auto FindReward = [&](const TCHAR* Id) -> float
	{
		for (const FMissionData& M : Missions->AvailableMissions)
			if (M.MissionID == FName(Id)) return M.RewardCredits;
		return -1.0f;
	};
	TestTrue(TEXT("Delivery reward exact (25000)"), FMath::IsNearlyEqual(FindReward(TEXT("Delivery_Titanium_Batch_1")), 25000.0f));
	TestTrue(TEXT("Smuggling reward exact (100000)"), FMath::IsNearlyEqual(FindReward(TEXT("Smuggle_Quantum_Cores")), 100000.0f));
	TestTrue(TEXT("Escort reward exact (50000)"), FMath::IsNearlyEqual(FindReward(TEXT("Escort_Convoy")), 50000.0f));

	Missions->AcceptMission(FName(TEXT("Delivery_Titanium_Batch_1")));
	TestEqual(TEXT("DSL mission acceptable"), Missions->ActiveMissions.Num(), 1);
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FFactionStandingChangesFromGameplay,
	"ChimeraTests.Acceptance.FactionStandingChangesFromGameplay",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FFactionStandingChangesFromGameplay::RunTest(const FString& Parameters)
{
	// World-free notifies
	UFactionComponent* Factions = NewObject<UFactionComponent>();
	Factions->NotifyTradeCompleted(FName(TEXT("faction_titan_miners")), 2000.0f);
	TestTrue(TEXT("Trade moves standing (+2 for 2000cr)"),
		FMath::IsNearlyEqual(Factions->GetStanding(FName(TEXT("faction_titan_miners"))), 2.0f));
	Factions->NotifyPirateKilled(FName(TEXT("faction_pirate_syndicate")));
	TestTrue(TEXT("Pirate kill applies -10"),
		FMath::IsNearlyEqual(Factions->GetStanding(FName(TEXT("faction_pirate_syndicate"))), -10.0f));

	// Mission completion drives standing through the owner wiring
	UWorld* World = nullptr;
	if (GEngine)
	{
		for (const FWorldContext& Context : GEngine->GetWorldContexts())
		{
			if (Context.World()) { World = Context.World(); break; }
		}
	}
	if (!TestNotNull(TEXT("World available"), World)) return false;
	AActor* Actor = World->SpawnActor<AActor>();
	UMissionComponent* Missions = NewObject<UMissionComponent>(Actor);
	Missions->RegisterComponent();
	UFactionComponent* OwnerFactions = NewObject<UFactionComponent>(Actor);
	OwnerFactions->RegisterComponent();

	FMissionData Mission;
	Mission.MissionID = FName(TEXT("FACT1"));
	Mission.FactionID = FName(TEXT("faction_orbital_council"));
	Mission.StandingChange = 10.0f;
	FMissionObjective Dock;
	Dock.Type = TEXT("Dock");
	Mission.Objectives.Add(Dock);
	Missions->AvailableMissions.Add(Mission);
	Missions->AcceptMission(FName(TEXT("FACT1")));
	Missions->UpdateObjective(TEXT("Dock"), TEXT(""));

	TestTrue(TEXT("Mission completion moved faction standing by +10"),
		FMath::IsNearlyEqual(OwnerFactions->GetStanding(FName(TEXT("faction_orbital_council"))), 10.0f));

	Actor->Destroy();
	return true;
}

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FShipStateSaveRoundtrip,
	"ChimeraTests.Acceptance.ShipStateSaveRoundtrip",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter)
bool FShipStateSaveRoundtrip::RunTest(const FString& Parameters)
{
	UWorld* World = nullptr;
	if (GEngine)
	{
		for (const FWorldContext& Context : GEngine->GetWorldContexts())
		{
			if (Context.World()) { World = Context.World(); break; }
		}
	}
	if (!TestNotNull(TEXT("World available"), World)) return false;
	AActor* Actor = World->SpawnActor<AActor>();
	UShieldComponent* Shield = NewObject<UShieldComponent>(Actor);
	Shield->RegisterComponent();
	UDamageComponent* Damage = NewObject<UDamageComponent>(Actor);
	Damage->RegisterComponent();
	USaveGameComponent* Saver = NewObject<USaveGameComponent>(Actor);
	Saver->RegisterComponent();

	Shield->SetCurrentShield(42.0f);
	Damage->CurrentHullHealth = 77.0f;

	const FName Slot(TEXT("ShipStateSlot"));
	TestTrue(TEXT("Save with ship state succeeds"), Saver->SaveGame(Slot));

	Shield->SetCurrentShield(1.0f);
	Damage->CurrentHullHealth = 1.0f;

	TestTrue(TEXT("Load restores ship state"), Saver->LoadGame(Slot));
	TestTrue(TEXT("Shield restored"), FMath::IsNearlyEqual(Shield->GetCurrentShield(), 42.0f));
	TestTrue(TEXT("Hull restored"), FMath::IsNearlyEqual(Damage->CurrentHullHealth, 77.0f));

	UGameplayStatics::DeleteGameInSlot(TEXT("ShipStateSlot"), 0);
	Actor->Destroy();
	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
