// Copyright 2026 Chimera Project. All Rights Reserved.
// Generated by GameCodeGenerator (core/game_code_generator.py::generate_footstep_event_acceptance_tests).
#include "CoreMinimal.h"
#include "../ChimeraMovementComponent.h"
#include "../Sound/SandSoundComponent.h"

/**
 * FFootstepEvent Acceptance Tests
 * Verifies the canonical body-event (seed FFootstepEvent, CHIMERA_VISION.py:737-747)
 * as hard facts, world-independently (NewObject, no PIE), matching the Weather/
 * Memorial test style:
 *   1. Struct defaults are the seed's own (Sand surface, zero vectors, bLanding
 *      false) — a sanity floor for every other test.
 *   2. GetSurfaceFootstepTraits reproduces docs/matter/matter_library.json's
 *      pair_exceptions numbers EXACTLY for sand/metal/rock — regression-proofs the
 *      citation itself, not just its existence.
 *   3. OnFootstep.Broadcast reaches a bound USandSoundComponent listener —
 *      mechanically proves the delegate + AddUniqueDynamic binding works, not just
 *      that the types compile.
 *   4. ONE broadcast reaches MULTIPLE independent listeners — the seed's "ONE
 *      canonical broadcaster per fact so consumers can never desync"
 *      (CHIMERA_VISION.py:734-736), proven rather than asserted.
 */

void TestFootstepEvent_StructDefaults()
{
    FFootstepEvent Event;
    check(Event.SourceActor == nullptr);
    check(Event.SurfaceMaterial == ESurfaceMaterialType::Sand);
    check(Event.Location.IsZero());
    check(FMath::IsNearlyEqual(Event.Yaw, 0.0f));
    check(Event.bLeftFoot == false);
    check(FMath::IsNearlyEqual(Event.SpeedMagnitude, 0.0f));
    check(FMath::IsNearlyEqual(Event.AudioVolume, 0.0f));
    check(Event.TriggerTime == 0.0);
    check(Event.bLanding == false);

    UE_LOG(LogTemp, Display, TEXT("[FOOTSTEP EVENT TEST] StructDefaults: PASS"));
}

void TestFootstepEvent_SurfaceTraitsMatchMatterLibrary()
{
    float Traction = 0.0f;
    bool bMakesPrint = false;
    float DustKick = 0.0f;

    // docs/matter/matter_library.json pair_exceptions["boot|sand"]
    UChimeraMovementComponent::GetSurfaceFootstepTraits(ESurfaceMaterialType::Sand, Traction, bMakesPrint, DustKick);
    check(FMath::IsNearlyEqual(Traction, 0.75f));
    check(bMakesPrint == true);
    check(FMath::IsNearlyEqual(DustKick, 1.00f));

    // pair_exceptions["boot|metal"]
    UChimeraMovementComponent::GetSurfaceFootstepTraits(ESurfaceMaterialType::Metal, Traction, bMakesPrint, DustKick);
    check(FMath::IsNearlyEqual(Traction, 0.90f));
    check(bMakesPrint == true);
    check(FMath::IsNearlyEqual(DustKick, 0.05f));

    // pair_exceptions["boot|rock"] — the seed's only "no print" surface
    UChimeraMovementComponent::GetSurfaceFootstepTraits(ESurfaceMaterialType::Rock, Traction, bMakesPrint, DustKick);
    check(FMath::IsNearlyEqual(Traction, 1.00f));
    check(bMakesPrint == false);
    check(FMath::IsNearlyEqual(DustKick, 0.15f));

    UE_LOG(LogTemp, Display, TEXT("[FOOTSTEP EVENT TEST] SurfaceTraitsMatchMatterLibrary: PASS"));
}

void TestFootstepEvent_DelegateBroadcastReachesListener()
{
    UChimeraMovementComponent* Movement = NewObject<UChimeraMovementComponent>();
    check(Movement != nullptr);

    USandSoundComponent* Sound = NewObject<USandSoundComponent>();
    check(Sound != nullptr);
    check(Sound->GetCanonicalFootstepEventCount() == 0);

    Movement->OnFootstep.AddUniqueDynamic(Sound, &USandSoundComponent::HandleFootstepEvent);

    FFootstepEvent Event;
    Event.SurfaceMaterial = ESurfaceMaterialType::Metal;
    Event.AudioVolume = 0.62f;
    Event.bLeftFoot = true;
    Movement->OnFootstep.Broadcast(Event);

    check(Sound->GetCanonicalFootstepEventCount() == 1);

    UE_LOG(LogTemp, Display, TEXT("[FOOTSTEP EVENT TEST] DelegateBroadcastReachesListener: PASS"));
}

void TestFootstepEvent_DelegateUnifiesMultipleConsumers()
{
    UChimeraMovementComponent* Movement = NewObject<UChimeraMovementComponent>();
    USandSoundComponent* ConsumerA = NewObject<USandSoundComponent>();
    USandSoundComponent* ConsumerB = NewObject<USandSoundComponent>();

    Movement->OnFootstep.AddUniqueDynamic(ConsumerA, &USandSoundComponent::HandleFootstepEvent);
    Movement->OnFootstep.AddUniqueDynamic(ConsumerB, &USandSoundComponent::HandleFootstepEvent);

    FFootstepEvent Event;
    Movement->OnFootstep.Broadcast(Event);

    // ONE canonical broadcast reached BOTH independent listeners — the seed's
    // "ONE canonical broadcaster per fact so audio/VFX/UI/camera can never desync"
    // (CHIMERA_VISION.py:734-736), proven mechanically rather than asserted.
    check(ConsumerA->GetCanonicalFootstepEventCount() == 1);
    check(ConsumerB->GetCanonicalFootstepEventCount() == 1);

    UE_LOG(LogTemp, Display, TEXT("[FOOTSTEP EVENT TEST] DelegateUnifiesMultipleConsumers: PASS"));
}

// Helper function to run all footstep event tests
void RunFootstepEventSystemTests()
{
    UE_LOG(LogTemp, Warning, TEXT("\n====== FOOTSTEP EVENT ACCEPTANCE TESTS ======\n"));

    TestFootstepEvent_StructDefaults();
    TestFootstepEvent_SurfaceTraitsMatchMatterLibrary();
    TestFootstepEvent_DelegateBroadcastReachesListener();
    TestFootstepEvent_DelegateUnifiesMultipleConsumers();

    UE_LOG(LogTemp, Warning, TEXT("\n====== ALL FOOTSTEP EVENT TESTS PASSED ======\n"));
}
