// Generated by GameCodeGenerator - Player Character Acceptance Test Suite Header
// Framework: AAA-Expanded Result Grader (Phase 1: Spec Fidelity & Test Coverage)

#pragma once

#include "CoreMinimal.h"
#include "Modules/ModuleInterface.h"

/**
 * Player Character Acceptance Test Suite - Loop 0 (The Player)
 *
 * Verifies 5 acceptance criteria against DSL-declared parameters:
 * 1. Mesh & Visual Asset Loading (SkeletalMesh, materials, visor)
 * 2. Physics & Movement Parameters (speed 600 UU/s, animation blend time)
 * 3. Audio-Visual Synchronization (footstep latency < 100ms)
 * 4. Save/Load Data Integrity (state persistence)
 * 5. Animation Gesture Library (look_around, check_visor, adjust_suit)
 *
 * Results feed AAA-Expanded Result Grader:
 *   - tests.passed = criteria that pass
 *   - tests.criteria_total = 5
 *   - spec_fidelity = verified_parameters / declared_parameters
 *
 * Phase 1 Goal: Loop 0 spec fidelity 56% → 77%+ (target 85%+)
 */

class FPlayerCharacterAcceptanceTests
{
public:
	/** Test 1: Verify SkeletalMesh asset loaded and materials applied */
	static bool Test_PlayerCharacterMeshLoaded(class UWorld* World);

	/** Test 2: Verify movement speed (600 UU/s) and animation blending (0.3s) */
	static bool Test_PlayerCharacterMovementSpecs(class UWorld* World, float DeltaTime = 0.016f);

	/** Test 3: Verify audio-visual sync (footstep latency < 100ms) - deferred to sleepwalker */
	static bool Test_PlayerCharacterFootstepSync(class UWorld* World);

	/** Test 4: Verify state persistence through save/load cycle */
	static bool Test_PlayerCharacterStatePersistence(class UWorld* World);

	/** Test 5: Verify gesture animation playback (look_around, check_visor, adjust_suit) */
	static bool Test_PlayerCharacterGesturePlayback(class UWorld* World);

	/** Run all 5 acceptance criteria and return pass count */
	static int32 RunAllAcceptanceCriteria(class UWorld* World);
};

/** Module for test framework integration */
class FPlayerCharacterAcceptanceTestsModule : public IModuleInterface
{
public:
	virtual void StartupModule() override {}
	virtual void ShutdownModule() override {}

	/** Execute all acceptance tests */
	void RunTests();
};
