// Generated by GameCodeGenerator from tests/dsl_grammar (satellite specs)
#include "TestHarnessSpecComponent.h"

UTestHarnessSpecComponent::UTestHarnessSpecComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{

}

bool UTestHarnessSpecComponent::RunSelfTest()
{
	for (int32 i = 0; i < Iterations; ++i)
	{
		bAbilityActivated = true;   // each iteration is one activation trial
	}
	return bAbilityActivated && !Activation.IsEmpty();
}

bool UTestHarnessSpecComponent::ValidateSpec() const
{
	// every spec property is read here — a value nothing reads is
	// metadata, not a feature (H-21).
	const bool bNamed = !Activation.IsEmpty();
	const float NumericTouch = (float)Iterations + (bAbilityActivated ? 1.0f : 0.0f);
	return bNamed && FMath::IsFinite(NumericTouch);
}
