// Copyright 2026 Chimera Project. All Rights Reserved.
// Generated by GameCodeGenerator (core/game_code_generator.py::generate_weather_subsystem_files).
#include "CoreMinimal.h"
#include "../Environment/WeatherComponent.h"

/**
 * Weather System Acceptance Tests
 * Verifies the meteorology authority (seed UWeatherSubsystem) as hard facts,
 * world-independently (NewObject, no PIE), matching the WindSystem test style:
 *   1. Initializes with the TRAINED WIND bands (docs/objectives/weather.trained.json (score=0.955)) in their
 *      required order (calm<=breeze<=gust<=storm — a definitional invariant the
 *      trainer itself re-clamps on every mutation, core/trainables/weather.py)
 *      and a calm start. Checked by ORDER, not literal pins, so this test
 *      survives the next retrain instead of going stale against it.
 *   2. Seeded RNG is deterministic — same seed replays the same storm calendar.
 *   3. Night bands match ASun::IsNight (day-fraction < 0.20 or > 0.80).
 *   4. The storm STATE MACHINE runs: ForceStorm raises it, the clock passes it,
 *      the passed-count and StormsPassed telemetry increment (the world-wide
 *      footprint erasure itself is proven in PIE — see the beat follow-up).
 *   5. Between storms wind eases toward the day band and the velocity vector
 *      tracks the scalar speed.
 */

void TestWeather_Initialization()
{
	UWeatherComponent* Weather = NewObject<UWeatherComponent>();
	check(Weather != nullptr);
	Weather->ResetWeather();

	// Ordering invariant (core/trainables/weather.py::mutate re-clamps this on
	// EVERY mutation — "a gust slower than the ambient breeze is not a gust").
	check(Weather->CalmWindSpeed > 0.0f);
	check(Weather->BreezeWindSpeed >= Weather->CalmWindSpeed);
	check(Weather->GustWindSpeed >= Weather->BreezeWindSpeed);
	check(Weather->StormWindSpeed >= Weather->GustWindSpeed);
	check(Weather->GustPeriodMinSeconds > 0.0f);
	check(Weather->GustPeriodMaxSeconds >= Weather->GustPeriodMinSeconds);
	check(Weather->StormDurationMinMinutes > 0.0f);
	check(Weather->StormDurationMaxMinutes >= Weather->StormDurationMinMinutes);
	check(Weather->StormPeriodMinDays > 0.0f);
	check(Weather->StormPeriodMaxDays >= Weather->StormPeriodMinDays);
	check(FMath::IsNearlyEqual(Weather->DayLengthHours, 27.0f)); // sim constant, not trained
	check(FMath::IsNearlyEqual(Weather->WindSpeed, Weather->CalmWindSpeed));
	check(!Weather->IsStormActive());
	check(Weather->StormsPassed == 0);
	check(Weather->DayNumber == 0);

	UE_LOG(LogTemp, Display,
		TEXT("[WEATHER TEST] Initialization: PASS (calm=%.3f breeze=%.3f gust=%.3f storm=%.3f)"),
		Weather->CalmWindSpeed, Weather->BreezeWindSpeed, Weather->GustWindSpeed, Weather->StormWindSpeed);
}

void TestWeather_Determinism()
{
	UWeatherComponent* A = NewObject<UWeatherComponent>();
	UWeatherComponent* B = NewObject<UWeatherComponent>();
	UWeatherComponent* C = NewObject<UWeatherComponent>();
	A->WeatherSeed = 1337;
	B->WeatherSeed = 1337;
	C->WeatherSeed = 4242;
	A->ResetWeather();
	B->ResetWeather();
	C->ResetWeather();

	// Same seed -> identical RNG-derived initial wind heading; different seed diverges.
	check(FMath::IsNearlyEqual(A->WindDirectionRadians, B->WindDirectionRadians, 1e-4f));
	check(!FMath::IsNearlyEqual(A->WindDirectionRadians, C->WindDirectionRadians, 1e-3f));

	UE_LOG(LogTemp, Display, TEXT("[WEATHER TEST] Determinism: PASS"));
}

void TestWeather_NightBands()
{
	UWeatherComponent* Weather = NewObject<UWeatherComponent>();
	Weather->ResetWeather();

	Weather->TimeOfDayHours = 1.0f;   // t=0.037 < 0.20 -> night
	check(Weather->IsNight());
	Weather->TimeOfDayHours = 13.5f;  // t=0.50 -> day
	check(!Weather->IsNight());
	Weather->TimeOfDayHours = 24.0f;  // t=0.889 > 0.80 -> night
	check(Weather->IsNight());

	UE_LOG(LogTemp, Display, TEXT("[WEATHER TEST] NightBands: PASS"));
}

void TestWeather_StormCycle()
{
	UWeatherComponent* Weather = NewObject<UWeatherComponent>();
	Weather->ResetWeather();
	check(!Weather->IsStormActive());

	// Raise a storm on demand; a second request is refused while one runs.
	check(Weather->ForceStorm() == true);
	check(Weather->IsStormActive());
	check(Weather->ForceStorm() == false);

	// Fast-forward the clock until the storm passes (bounded so a logic bug
	// can't hang the suite). At 100 game-hours per tick even the trained
	// storm_duration_min_hi (well under a game-day) ends within a couple ticks.
	Weather->HoursPerRealSecond = 100.0f;
	int32 Guard = 0;
	while (Weather->IsStormActive() && Guard < 100)
	{
		Weather->AdvanceWeather(1.0f);
		++Guard;
	}

	check(!Weather->IsStormActive());
	check(Weather->StormsPassed == 1);
	check(FMath::IsNearlyEqual(Weather->StormIntensity, 0.0f));
	check(Weather->LastStormFootprintsErased == 0); // no world/prints in this harness

	UE_LOG(LogTemp, Display, TEXT("[WEATHER TEST] StormCycle: PASS (passed in %d tick(s))"), Guard);
}

void TestWeather_WindBandResponse()
{
	UWeatherComponent* Weather = NewObject<UWeatherComponent>();
	Weather->ResetWeather();
	Weather->TimeOfDayHours = 8.0f; // daytime -> breeze band target

	// Ease over ~2 s of small steps; no storm can trigger (next storm is at least
	// StormPeriodMinDays out — always far beyond a couple of seconds of sim time).
	for (int32 i = 0; i < 20; ++i)
	{
		Weather->AdvanceWeather(0.1f);
	}

	check(!Weather->IsStormActive());
	check(Weather->WindSpeed > Weather->CalmWindSpeed);          // rose off calm toward breeze
	check(Weather->WindSpeed <= Weather->GustWindSpeed * 1.2f);  // stayed in the ambient range

	const FVector Velocity = Weather->GetWindVelocity();
	check(FMath::IsNearlyEqual(Velocity.Size(), Weather->WindSpeed, 0.01f));

	UE_LOG(LogTemp, Display, TEXT("[WEATHER TEST] WindBandResponse: PASS (speed=%.2f)"), Weather->WindSpeed);
}

// Helper function to run all weather system tests
void RunWeatherSystemTests()
{
	UE_LOG(LogTemp, Warning, TEXT("\n====== WEATHER SYSTEM ACCEPTANCE TESTS ======\n"));

	// tb-0186: exception-free by design, not by omission. try/catch here broke
	// the standalone GAME target (C4530 -- built without /EHsc, unlike the
	// editor target); it was also never load-bearing, since check() failures
	// inside the Test*() calls below are UE fatal-asserts, not thrown
	// std::exception, so the old catch (const std::exception&) could never
	// fire. Same coverage and order as before, matching
	// RunFootstepEventSystemTests' already exception-free convention.
	TestWeather_Initialization();
	TestWeather_Determinism();
	TestWeather_NightBands();
	TestWeather_StormCycle();
	TestWeather_WindBandResponse();

	UE_LOG(LogTemp, Warning, TEXT("\n====== ALL WEATHER SYSTEM TESTS PASSED ======\n"));
}
