// Generated by GameCodeGenerator
#include "CoreMinimal.h"
#include "../Environment/WindSystemComponent.h"
#include "../Materials/DustAccumulationParticleComponent.h"

/**
 * Wind System Acceptance Tests
 * Verifies that:
 * 1. Wind system initializes with correct direction and speed
 * 2. Particles drift with wind (wind_response parameter respected)
 * 3. Wind drift is observable and measurable
 * 4. Particle trajectory deviates from gravity-only baseline
 */

void TestWindSystem_Initialization()
{
	// Test: WindSystemComponent initializes with default parameters
	UWindSystemComponent* WindSystem = NewObject<UWindSystemComponent>();

	check(WindSystem != nullptr);
	check(WindSystem->bWindEnabled == true);
	check(FMath::IsNearlyEqual(WindSystem->BaseWindSpeed, 500.0f));
	check(FMath::IsNearlyEqual(WindSystem->BaseWindDirection.X, 1.0f, 0.01f));
	check(FMath::IsNearlyEqual(WindSystem->WindVariance, 0.3f));
	check(FMath::IsNearlyEqual(WindSystem->WindCycleTime, 10.0f));

	UE_LOG(LogTemp, Display, TEXT("[WIND TEST] Initialization: PASS"));
}

void TestWindSystem_VelocityQuery()
{
	// Test: GetCurrentWindVelocity returns expected magnitude and direction
	UWindSystemComponent* WindSystem = NewObject<UWindSystemComponent>();
	WindSystem->SetWindConfiguration(FVector(1.0f, 0.0f, 0.0f), 500.0f, 0.0f, 0.0f);

	FVector Velocity = WindSystem->GetCurrentWindVelocity();
	float Speed = WindSystem->GetCurrentWindSpeed();

	check(FMath::IsNearlyEqual(Speed, 500.0f));
	check(FMath::IsNearlyEqual(Velocity.X, 500.0f, 1.0f));
	check(FMath::IsNearlyEqual(Velocity.Y, 0.0f, 1.0f));
	check(FMath::IsNearlyEqual(Velocity.Z, 0.0f, 1.0f));

	UE_LOG(LogTemp, Display, TEXT("[WIND TEST] VelocityQuery: PASS"));
}

void TestWindSystem_ResponseParameter()
{
	// Test: wind_response (0.0-1.0) correctly modulates particle drift
	UWindSystemComponent* WindSystem = NewObject<UWindSystemComponent>();
	WindSystem->SetWindConfiguration(FVector(1.0f, 0.0f, 0.0f), 100.0f, 0.0f, 0.0f);

	// Test wind_response = 1.0 (full response)
	FVector FullResponseVel = WindSystem->ApplyWindForce(FVector(0.0f, 0.0f, -100.0f), 1.0f, 1.0f);
	check(FullResponseVel.X > 0.0f);

	// Test wind_response = 0.5 (half response)
	FVector HalfResponseVel = WindSystem->ApplyWindForce(FVector(0.0f, 0.0f, -100.0f), 0.5f, 1.0f);
	check(HalfResponseVel.X < FullResponseVel.X);

	// Test wind_response = 0.0 (no response)
	FVector NoResponseVel = WindSystem->ApplyWindForce(FVector(0.0f, 0.0f, -100.0f), 0.0f, 1.0f);
	check(FMath::IsNearlyEqual(NoResponseVel.Z, -100.0f));

	UE_LOG(LogTemp, Display, TEXT("[WIND TEST] ResponseParameter: PASS"));
}

void TestWindSystem_DriftDirection()
{
	// Test: particles drift in wind direction (not random)
	UWindSystemComponent* WindSystem = NewObject<UWindSystemComponent>();
	WindSystem->SetWindConfiguration(FVector(1.0f, 0.0f, 0.0f), 200.0f, 0.0f, 0.0f);

	// Calculate wind drift over 5 seconds
	FVector Drift = WindSystem->CalculateWindDrift(5.0f);

	check(Drift.X > 0.0f);
	check(FMath::Abs(Drift.X) > FMath::Abs(Drift.Y));
	check(FMath::Abs(Drift.Z) < 1.0f);

	UE_LOG(LogTemp, Display, TEXT("[WIND TEST] DriftDirection: PASS (drift: %.1f, %.1f, %.1f)"),
		Drift.X, Drift.Y, Drift.Z);
}

void TestWindSystem_Variation()
{
	// Test: sinusoidal wind variation (gust patterns)
	UWindSystemComponent* WindSystem = NewObject<UWindSystemComponent>();
	WindSystem->SetWindConfiguration(FVector(1.0f, 0.0f, 0.0f), 100.0f, 0.3f, 10.0f);

	float BaseSpeed = 100.0f;
	float MaxExpectedSpeed = BaseSpeed * (1.0f + 0.3f);
	float MinExpectedSpeed = BaseSpeed * (1.0f - 0.3f);

	bool SpeedVaried = false;
	for (int i = 0; i < 100; ++i)
	{
		WindSystem->TickComponent(0.1f, LEVELTICK_All, nullptr);
		float CurrentSpeed = WindSystem->GetCurrentWindSpeed();

		if (!FMath::IsNearlyEqual(CurrentSpeed, BaseSpeed, 0.1f))
		{
			SpeedVaried = true;
		}

		check(CurrentSpeed >= MinExpectedSpeed && CurrentSpeed <= MaxExpectedSpeed);
	}

	check(SpeedVaried);
	UE_LOG(LogTemp, Display, TEXT("[WIND TEST] Variation: PASS (speed varied over cycle)"));
}

// Helper function to run all wind system tests
void RunWindSystemTests()
{
	UE_LOG(LogTemp, Warning, TEXT("\n====== WIND SYSTEM ACCEPTANCE TESTS ======\n"));

	TestWindSystem_Initialization();
	TestWindSystem_VelocityQuery();
	TestWindSystem_ResponseParameter();
	TestWindSystem_DriftDirection();
	TestWindSystem_Variation();

	UE_LOG(LogTemp, Warning, TEXT("\n====== ALL WIND SYSTEM TESTS PASSED ======\n"));
}
