// Generated by GameCodeGenerator from deep_space_trader.chimera
#pragma once
#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "EnvironmentSpecComponent.generated.h"

UCLASS(meta = (BlueprintType, Category = "Environment"))
class CHIMERA_API UEnvironmentSpecComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UEnvironmentSpecComponent(const FObjectInitializer& ObjectInitializer);

	// spec: wind_system_enabled / wind_base_speed / wind_base_direction
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind")
	bool bWindSystemEnabled = true;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind")
	float WindBaseSpeed = 500.0f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind")
	FVector WindBaseDirection = FVector(1.0f, 0.0f, 0.0f);
	// spec: dust accumulation_enabled
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
	bool bAccumulationEnabled = true;
	// spec: surface reads — ground_texture_types / vegetation_density / skybox_type / color_palette / elements
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Surface")
	TArray<FString> GroundTextureTypes;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Surface")
	float VegetationDensity = 0.0f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sky")
	FString SkyboxType = TEXT("deep_space");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sky")
	FString ColorPalette = TEXT("regolith_amber");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Surface")
	TArray<FString> Elements;
	// spec: gravity_g (per body) / world bounds min_location..max_location / camera_perspective
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Physics")
	float GravityG = 1.5f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Bounds")
	FVector MinLocation = FVector(-100000.0f, -100000.0f, -1000.0f);
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Bounds")
	FVector MaxLocation = FVector(100000.0f, 100000.0f, 50000.0f);
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Camera")
	FString CameraPerspective = TEXT("third_person");

	UFUNCTION(BlueprintCallable, Category = "Wind")
	FVector GetWindVelocity(float TimeSeconds) const;
	UFUNCTION(BlueprintCallable, Category = "Physics")
	float GetGravityZ() const;
	UFUNCTION(BlueprintCallable, Category = "Bounds")
	bool IsInsideWorldBounds(const FVector& Location) const;
	UFUNCTION(BlueprintCallable, Category = "Environment")
	bool ValidateSpec() const;
};
