// Copyright 2026 Chimera Project. All Rights Reserved.
// Generated by GameCodeGenerator (core/game_code_generator.py::generate_weather_subsystem_files).

#include "WeatherComponent.h"
#include "WindSystemComponent.h"
#include "FootprintComponent.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"
#include "Materials/MaterialParameterCollection.h"
#include "Kismet/KismetMaterialLibrary.h"
#include "GameplayEffect.h"

UWeatherComponent::UWeatherComponent()
{
    PrimaryComponentTick.bCanEverTick = true;

    // Wind bands (uu/s) — TRAINED: docs/objectives/weather.trained.json (score=0.955)
    CalmWindSpeed = 1.305413f;
    BreezeWindSpeed = 8.756837f;
    GustWindSpeed = 12.792488f;
    StormWindSpeed = 25.805518f;

    // Cadence — TRAINED: docs/objectives/weather.trained.json (score=0.955)
    GustPeriodMinSeconds = 2.982624f;
    GustPeriodMaxSeconds = 10.139041f;
    StormDurationMinMinutes = 7.629537f;
    StormDurationMaxMinutes = 175.447486f;
    StormPeriodMinDays = 8.451431f;
    StormPeriodMaxDays = 21.003801f;

    // Clock (sim constant, not trained).
    DayLengthHours = 27.0f;          // seed DAY_LENGTH_HOURS
    HoursPerRealSecond = 0.1f;       // a full day every ~4.5 real minutes
    WeatherSeed = 1337;

    // State.
    WindSpeed = CalmWindSpeed;
    WindDirectionRadians = 0.0f;
    bStormActive = false;
    StormIntensity = 0.0f;
    DustAgeHours = 0.0f;
    DayNumber = 0;
    TimeOfDayHours = 8.0f;           // seed seeds time_h = 8
    bPlayerIndoors = false;

    // MPC / GAS bridges — unassigned by default (harmless no-op; assign a
    // Material Parameter Collection / GameplayEffect Blueprint asset on the
    // Blueprint subclass or level default to activate).
    WeatherMPC = nullptr;
    DustClogEffectClass = nullptr;

    // Telemetry.
    StormsPassed = 0;
    LastStormFootprintsErased = 0;
    TotalFootprintsErased = 0;

    // Internal.
    NextGustSeconds = GustPeriodMaxSeconds;
    StormEndsInHours = 0.0f;
    StormTotalHours = 0.0f;
    NextStormDay = StormPeriodMinDays;
    CachedWind = nullptr;
}

void UWeatherComponent::ResetWeather()
{
    Rng.Initialize(WeatherSeed);
    WindSpeed = CalmWindSpeed;
    WindDirectionRadians = Rng.FRandRange(0.0f, 2.0f * PI);
    NextGustSeconds = Rng.FRandRange(GustPeriodMinSeconds, GustPeriodMaxSeconds);
    NextStormDay = Rng.FRandRange(StormPeriodMinDays, StormPeriodMaxDays);
    DustAgeHours = 0.0f;
    DayNumber = 0;
    TimeOfDayHours = 8.0f;
    bStormActive = false;
    StormIntensity = 0.0f;
    StormEndsInHours = 0.0f;
}

void UWeatherComponent::BeginPlay()
{
    Super::BeginPlay();

    ResetWeather();

    if (AActor* Owner = GetOwner())
    {
        CachedWind = Owner->FindComponentByClass<UWindSystemComponent>();
    }

    UE_LOG(LogTemp, Log,
        TEXT("[WEATHER] initialized (seed=%d) — next storm on day %.2f, %s driving sibling wind"),
        WeatherSeed, NextStormDay, CachedWind ? TEXT("is") : TEXT("no"));
}

void UWeatherComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
    Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
    AdvanceWeather(DeltaTime);
}

void UWeatherComponent::AdvanceWeather(float DeltaSeconds)
{
    if (DeltaSeconds > 0.0f)
    {
        TickWeather(DeltaSeconds);
    }
}

void UWeatherComponent::TickWeather(float DeltaSeconds)
{
    // Two timescales, exactly as the seed models them: gusts are short-term and
    // decrement in REAL seconds; the clock, dust, and storm duration are long-term
    // and advance in GAME hours (dt * HoursPerRealSecond).
    const float GameHours = DeltaSeconds * HoursPerRealSecond;

    // Advance the clock and roll the day.
    TimeOfDayHours += GameHours;
    while (TimeOfDayHours >= DayLengthHours)
    {
        TimeOfDayHours -= DayLengthHours;
        ++DayNumber;
    }
    const float FractionalDay = static_cast<float>(DayNumber) + TimeOfDayHours / DayLengthHours;

    if (bStormActive)
    {
        // Howling wind, re-jittered each tick (seed: storm * uniform(0.85,1.15)).
        WindSpeed = StormWindSpeed * Rng.FRandRange(0.85f, 1.15f);
        StormEndsInHours -= GameHours;

        // The scour: dust age falls fast mid-storm.
        DustAgeHours = FMath::Max(0.0f, DustAgeHours - 5.0f * GameHours);

        // Intensity ramps up over the first 15% and down over the last 15% so
        // materials/Niagara can fade the storm-wall in and out.
        const float Edge = FMath::Max(StormTotalHours * 0.15f, KINDA_SMALL_NUMBER);
        const float Elapsed = StormTotalHours - StormEndsInHours;
        StormIntensity = FMath::Clamp(FMath::Min3(Elapsed / Edge, StormEndsInHours / Edge, 1.0f), 0.0f, 1.0f);

        if (StormEndsInHours <= 0.0f)
        {
            EndStorm();
        }
    }
    else
    {
        StormIntensity = 0.0f;

        // Base band: calm at night, breeze by day — with brief gusts.
        float Base = IsNight() ? CalmWindSpeed : BreezeWindSpeed;
        NextGustSeconds -= DeltaSeconds;
        if (NextGustSeconds <= 0.0f)
        {
            NextGustSeconds = Rng.FRandRange(GustPeriodMinSeconds, GustPeriodMaxSeconds);
            Base = GustWindSpeed;
        }

        // Ease toward the target band; let direction wander.
        WindSpeed = FMath::Lerp(WindSpeed, Base, FMath::Clamp(0.4f * DeltaSeconds, 0.0f, 1.0f));
        WindDirectionRadians += Rng.FRandRange(-0.1f, 0.1f) * DeltaSeconds;

        // Between storms the land ages and dust settles.
        DustAgeHours += GameHours;

        if (FractionalDay >= NextStormDay)
        {
            BeginStorm();
        }
    }

    PushWindToSibling();
    PushWeatherToMPC();
    UpdateDustClogEffect();
}

void UWeatherComponent::BeginStorm()
{
    bStormActive = true;
    StormTotalHours = Rng.FRandRange(StormDurationMinMinutes, StormDurationMaxMinutes) / 60.0f;
    StormEndsInHours = StormTotalHours;
    StormIntensity = 0.0f;
    NextStormDay += Rng.FRandRange(StormPeriodMinDays, StormPeriodMaxDays);

    UE_LOG(LogTemp, Log,
        TEXT("[DEMOBEAT][WEATHER] storm RISING on day %d (%.0f min) — next after day %.2f"),
        DayNumber, StormTotalHours * 60.0f, NextStormDay);
    // Witness marker (H-21: a verb needs behavior; beats assert on this exact tag).
    UE_LOG(LogTemp, Log, TEXT("[Weather] StormRising"));

    OnStormStateChanged.Broadcast(EWeatherStormPhase::Rising, 0);
}

void UWeatherComponent::EndStorm()
{
    bStormActive = false;
    StormIntensity = 0.0f;

    // The memento mori: the storm scours every impermanent (sand) print in the
    // world. Durable surfaces (metal grating, dug pits) survive — this is why
    // footprints don't accumulate forever (Design Law 4).
    const int32 Erased = UFootprintComponent::EraseAllImpermanent(GetWorld());
    LastStormFootprintsErased = Erased;
    TotalFootprintsErased += Erased;
    ++StormsPassed;

    UE_LOG(LogTemp, Log,
        TEXT("[DEMOBEAT][WEATHER] storm PASSED on day %d — erased %d sand footprint(s) (%d total)"),
        DayNumber, Erased, TotalFootprintsErased);
    // Witness marker (H-21: a verb needs behavior; beats assert on this exact tag).
    UE_LOG(LogTemp, Log, TEXT("[Weather] StormPassed prints_erased=%d"), Erased);

    OnStormStateChanged.Broadcast(EWeatherStormPhase::Passed, Erased);
}

void UWeatherComponent::PushWindToSibling()
{
    // Resolve lazily — the wind component may attach after us (H-34 attach order).
    if (!CachedWind)
    {
        if (AActor* Owner = GetOwner())
        {
            CachedWind = Owner->FindComponentByClass<UWindSystemComponent>();
            if (!CachedWind && bStormActive)
            {
                UE_LOG(LogTemp, Warning,
                    TEXT("[WEATHER] Storm active but UWindSystemComponent not found on %s — wind not applied"),
                    *Owner->GetName());
            }
        }
    }
    if (CachedWind)
    {
        const FVector Dir(FMath::Cos(WindDirectionRadians), FMath::Sin(WindDirectionRadians), 0.0f);
        CachedWind->SetWindConfiguration(Dir, WindSpeed);
    }
}

void UWeatherComponent::PushWeatherToMPC()
{
    // Real MPC bridge (tb-0151, 2026-07-18): mirrors CHIMERA_VISION.py:3691-3693's
    // game.mpc.SetScalarParameterValue(...) calls exactly, under the same three
    // parameter names, iff a Material Parameter Collection asset is assigned.
    // Unassigned = no-op; materials/telemetry keep reading the scalars above.
    UWorld* World = GetWorld();
    if (!WeatherMPC || !World)
    {
        return;
    }

    UKismetMaterialLibrary::SetScalarParameterValue(World, WeatherMPC, TEXT("WindSpeed"), WindSpeed);
    UKismetMaterialLibrary::SetScalarParameterValue(World, WeatherMPC, TEXT("StormIntensity"), bStormActive ? 1.0f : 0.0f);
    UKismetMaterialLibrary::SetScalarParameterValue(World, WeatherMPC, TEXT("DustAgeHours"), DustAgeHours);
}

void UWeatherComponent::UpdateDustClogEffect()
{
    // Real GAS bridge (tb-0151, 2026-07-18): mirrors CHIMERA_VISION.py:3694-3698
    // exactly — the dust-clog effect is applied to the OWNER's ability system
    // component iff bStormActive && !bPlayerIndoors (ShouldClogSuit()), and removed
    // the instant that flips false. Unassigned DustClogEffectClass or an owner with
    // no ASC is a harmless no-op (the SuitLifeSupportComponent float-drain stand-in
    // keeps working either way).
    if (!DustClogEffectClass)
    {
        return;
    }
    AActor* Owner = GetOwner();
    if (!Owner)
    {
        return;
    }
    UAbilitySystemComponent* ASC = Owner->FindComponentByClass<UAbilitySystemComponent>();
    if (!ASC)
    {
        return;
    }

    const bool bShouldClog = ShouldClogSuit();
    const bool bHasActiveEffect = ActiveDustClogEffectHandle.IsValid();

    if (bShouldClog && !bHasActiveEffect)
    {
        const FGameplayEffectContextHandle Context = ASC->MakeEffectContext();
        const FGameplayEffectSpecHandle Spec = ASC->MakeOutgoingSpec(DustClogEffectClass, 1.0f, Context);
        if (Spec.IsValid())
        {
            ActiveDustClogEffectHandle = ASC->ApplyGameplayEffectSpecToSelf(*Spec.Data.Get());
        }
    }
    else if (!bShouldClog && bHasActiveEffect)
    {
        ASC->RemoveActiveGameplayEffect(ActiveDustClogEffectHandle);
        ActiveDustClogEffectHandle = FActiveGameplayEffectHandle();
    }
}

FVector UWeatherComponent::GetWindVelocity() const
{
    return FVector(FMath::Cos(WindDirectionRadians), FMath::Sin(WindDirectionRadians), 0.0f) * WindSpeed;
}

bool UWeatherComponent::IsNight() const
{
    const float T = TimeOfDayHours / DayLengthHours;
    return T < 0.20f || T > 0.80f;
}

bool UWeatherComponent::ForceStorm()
{
    if (bStormActive)
    {
        return false;
    }
    BeginStorm();
    return true;
}
