// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "Containers/CircularQueue.h"
#include "WindSystemComponent.generated.h"

/**
 * Wind System Component
 * Manages global wind direction and speed for particle interaction.
 * Supports constant wind and time-varying patterns.
 *
 * DSL Parameter: wind_response (0.0-1.0, where 1.0 = full wind interaction)
 */
UCLASS(meta = (BlueprintSpawnableComponent, Category = "Environment|Wind"))
class CHIMERA_API UWindSystemComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UWindSystemComponent();

	virtual void BeginPlay() override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	// === Wind Configuration ===
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind|Configuration")
	bool bWindEnabled;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind|Configuration")
	float BaseWindSpeed;  // UU/s

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind|Configuration")
	FVector BaseWindDirection;  // Normalized direction vector

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind|Configuration")
	float WindVariance;  // Amplitude of time-varying oscillation (0-1)

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind|Configuration")
	float WindCycleTime;  // Period of wind variation in seconds (0 = no variation)

	// === Current State ===
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Wind|State")
	FVector CurrentWindVelocity;  // Current wind velocity vector (direction * speed)

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Wind|State")
	float CurrentWindSpeed;  // Current speed magnitude

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Wind|State")
	FVector CurrentWindDirection;  // Current direction (normalized)

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Wind|State")
	float VariationPhase;  // Current phase in wind cycle (0-1)

	// === Public Methods ===

	/** Get current wind velocity (direction * speed) */
	UFUNCTION(BlueprintCallable, Category = "Wind|Query")
	FVector GetCurrentWindVelocity() const;

	/** Get current wind speed magnitude */
	UFUNCTION(BlueprintCallable, Category = "Wind|Query")
	float GetCurrentWindSpeed() const;

	/** Get current wind direction (normalized) */
	UFUNCTION(BlueprintCallable, Category = "Wind|Query")
	FVector GetCurrentWindDirection() const;

	/** Set wind configuration */
	UFUNCTION(BlueprintCallable, Category = "Wind|Control")
	void SetWindConfiguration(FVector Direction, float Speed, float Variance = 0.0f, float CycleTime = 0.0f);

	/** Apply wind force to a velocity (accounts for wind_response parameter) */
	UFUNCTION(BlueprintCallable, Category = "Wind|Physics")
	FVector ApplyWindForce(FVector CurrentVelocity, float WindResponse, float DeltaTime) const;

	/** Get wind drift displacement over time (for trajectory prediction) */
	UFUNCTION(BlueprintCallable, Category = "Wind|Physics")
	FVector CalculateWindDrift(float TimeSeconds) const;

	// === Measurement / Telemetry ===

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Wind|Telemetry")
	float TotalWindDriftDistance;  // Cumulative drift distance

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Wind|Telemetry")
	float MaxInstantaneousWindSpeed;  // Peak wind speed observed

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Wind|Telemetry")
	int32 UpdateCount;  // Number of physics updates

	/** Get total wind drift magnitude from start */
	UFUNCTION(BlueprintCallable, Category = "Wind|Telemetry")
	float GetTotalWindDrift() const;

	/** Reset telemetry counters */
	UFUNCTION(BlueprintCallable, Category = "Wind|Telemetry")
	void ResetTelemetry();

protected:
	virtual void UpdateWindState(float DeltaTime);
	virtual void UpdateVariation(float DeltaTime);

private:
	// Internal state for telemetry
	float TimeAccumulator;
	FVector LastWindVelocity;
	int32 FrameCount;
};
