// Generated by GameCodeGenerator
#include "WindSystemComponent.h"
#include "Engine/World.h"
#include "Math/Vector.h"

UWindSystemComponent::UWindSystemComponent()
{
	PrimaryComponentTick.bCanEverTick = true;
	PrimaryComponentTick.TickInterval = 0.016f;  // ~60 FPS updates

	// Default wind configuration
	bWindEnabled = true;
	BaseWindSpeed = 500.0f;  // UU/s
	BaseWindDirection = FVector(1.0f, 0.0f, 0.0f);  // Blowing east
	WindVariance = 0.3f;  // 30% oscillation
	WindCycleTime = 10.0f;  // 10 second cycle

	// Initial state
	CurrentWindVelocity = FVector::ZeroVector;
	CurrentWindSpeed = 0.0f;
	CurrentWindDirection = FVector(1.0f, 0.0f, 0.0f);
	VariationPhase = 0.0f;

	// Telemetry
	TotalWindDriftDistance = 0.0f;
	MaxInstantaneousWindSpeed = 0.0f;
	UpdateCount = 0;

	// Internal state
	TimeAccumulator = 0.0f;
	LastWindVelocity = FVector::ZeroVector;
	FrameCount = 0;
}

void UWindSystemComponent::BeginPlay()
{
	Super::BeginPlay();

	// Ensure direction is normalized
	BaseWindDirection = BaseWindDirection.GetSafeNormal();
	CurrentWindDirection = BaseWindDirection;

	// Initialize wind velocity
	CurrentWindVelocity = BaseWindDirection * BaseWindSpeed;

	UE_LOG(LogTemp, Display, TEXT("[WindSystemComponent] Initialized: Speed=%.1f UU/s, Direction=(%.2f, %.2f, %.2f), Variance=%.1f, Cycle=%.1fs"),
		BaseWindSpeed, BaseWindDirection.X, BaseWindDirection.Y, BaseWindDirection.Z, WindVariance, WindCycleTime);
}

void UWindSystemComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	if (!bWindEnabled)
	{
		CurrentWindVelocity = FVector::ZeroVector;
		CurrentWindSpeed = 0.0f;
		return;
	}

	// Update wind state (including variation)
	UpdateWindState(DeltaTime);

	// Track telemetry
	TotalWindDriftDistance += CurrentWindVelocity.Length() * DeltaTime;
	MaxInstantaneousWindSpeed = FMath::Max(MaxInstantaneousWindSpeed, CurrentWindSpeed);
	UpdateCount++;
}

void UWindSystemComponent::UpdateWindState(float DeltaTime)
{
	// Apply time-varying variation if cycle time is set
	if (WindCycleTime > 0.0f)
	{
		UpdateVariation(DeltaTime);
	}

	// Calculate current wind velocity
	CurrentWindSpeed = BaseWindSpeed;
	CurrentWindDirection = BaseWindDirection.GetSafeNormal();
	CurrentWindVelocity = CurrentWindDirection * CurrentWindSpeed;
}

void UWindSystemComponent::UpdateVariation(float DeltaTime)
{
	TimeAccumulator += DeltaTime;

	// Phase oscillates from 0 to 1 and back based on cycle time
	VariationPhase = FMath::Fmod(TimeAccumulator, WindCycleTime) / WindCycleTime;

	// Apply sinusoidal variation to wind speed (amplitude = WindVariance * BaseWindSpeed)
	float SpeedVariation = FMath::Sin(VariationPhase * TWO_PI);
	CurrentWindSpeed = BaseWindSpeed * (1.0f + WindVariance * SpeedVariation);

	// Also vary direction slightly (gust direction changes)
	float DirectionVariation = FMath::Cos(VariationPhase * TWO_PI) * WindVariance * 0.5f;
	FVector VariedDirection = BaseWindDirection.RotateAngleAxis(DirectionVariation * 45.0f, FVector::UpVector);
	CurrentWindDirection = VariedDirection.GetSafeNormal();

	CurrentWindVelocity = CurrentWindDirection * CurrentWindSpeed;
}

FVector UWindSystemComponent::GetCurrentWindVelocity() const
{
	return CurrentWindVelocity;
}

float UWindSystemComponent::GetCurrentWindSpeed() const
{
	return CurrentWindSpeed;
}

FVector UWindSystemComponent::GetCurrentWindDirection() const
{
	return CurrentWindDirection;
}

void UWindSystemComponent::SetWindConfiguration(FVector Direction, float Speed, float Variance, float CycleTime)
{
	BaseWindDirection = Direction.GetSafeNormal();
	BaseWindSpeed = Speed;
	WindVariance = FMath::Clamp(Variance, 0.0f, 1.0f);
	WindCycleTime = CycleTime;

	CurrentWindDirection = BaseWindDirection;
	CurrentWindSpeed = BaseWindSpeed;
	CurrentWindVelocity = CurrentWindDirection * CurrentWindSpeed;

	UE_LOG(LogTemp, Warning, TEXT("[WindSystemComponent] Config updated: Speed=%.1f, Direction=(%.2f, %.2f, %.2f), Variance=%.1f, Cycle=%.1fs"),
		Speed, Direction.X, Direction.Y, Direction.Z, Variance, CycleTime);
}

FVector UWindSystemComponent::ApplyWindForce(FVector CurrentVelocity, float WindResponse, float DeltaTime) const
{
	if (!bWindEnabled || WindResponse <= 0.0f)
	{
		return CurrentVelocity;
	}

	// Clamp wind response to 0-1 range
	float ClampedResponse = FMath::Clamp(WindResponse, 0.0f, 1.0f);

	// Apply wind acceleration: new_velocity = current_velocity + (wind_velocity * response * delta_time)
	FVector WindAcceleration = CurrentWindVelocity * ClampedResponse;
	FVector NewVelocity = CurrentVelocity + (WindAcceleration * DeltaTime);

	return NewVelocity;
}

FVector UWindSystemComponent::CalculateWindDrift(float TimeSeconds) const
{
	// Simple linear drift calculation: wind_velocity * time
	// (ignores variation, assumes constant wind for prediction)
	return CurrentWindVelocity * TimeSeconds;
}

float UWindSystemComponent::GetTotalWindDrift() const
{
	return TotalWindDriftDistance;
}

void UWindSystemComponent::ResetTelemetry()
{
	TotalWindDriftDistance = 0.0f;
	MaxInstantaneousWindSpeed = 0.0f;
	UpdateCount = 0;
	TimeAccumulator = 0.0f;
	FrameCount = 0;

	UE_LOG(LogTemp, Warning, TEXT("[WindSystemComponent] Telemetry reset"));
}
