// Generated by GameCodeGenerator — Generation Subsystem (Design Law 2 & 4)
#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "GenerationSubsystem.generated.h"

class USacrificeLogComponent;
class UStarMemorialComponent;
class ACostlessLifeEndingDiagnostic;

/**
 * Generation Subsystem — closes the generation loop on death.
 * 
 * On death: write the star from the sacrifice log (StarMemorialComponent::AddLife),
 * invoke CostlessLifeEndingDiagnostic (dim star + empty mirror for a costless life),
 * show a wordless will screen, respawn the heir at the habitat with halved credits.
 * 
 * Makes Laws 2 and 4 legible and finishes the loop.
 */
UCLASS()
class CHIMERA_API UGenerationSubsystem : public UGameInstanceSubsystem
{
	GENERATED_BODY()

public:
	virtual void Initialize(FSubsystemCollectionBase& Collection) override;
	virtual bool ShouldCreateSubsystem(UObject* Outer) const override { return true; }
	virtual void Deinitialize() override;

	/** Handle player death — close the generation loop */
	UFUNCTION(BlueprintCallable, Category="Generation")
	void OnPlayerDeath(AActor* DiedPawn, USacrificeLogComponent* SacrificeLog, UStarMemorialComponent* StarMemorial);

protected:
	/** Write the star from the sacrifice log into the memorial */
	void WriteStarFromSacrificeLog(USacrificeLogComponent* SacrificeLog, UStarMemorialComponent* StarMemorial);

	/** Invoke the costless life ending diagnostic */
	void InvokeCostlessLifeEndingDiagnostic(ACostlessLifeEndingDiagnostic* Diagnostic, USacrificeLogComponent* SacrificeLog);

	/** Show wordless will screen (placeholder for future implementation) */
	void ShowWordlessWillScreen();

	/** Respawn the heir at the habitat with halved credits */
	void RespawnHeirAtHabitatWithHalvedCredits(APlayerController* PlayerController);

	UPROPERTY()
	TObjectPtr<ACostlessLifeEndingDiagnostic> CostlessLifeDiagnosticActor;
};
