// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "ChimeraMovementComponent.h"

/**
 * Data payload for a footstep event. Carries surface material,
 * location, and timing for audio-visual sync telemetry.
 */
struct FFootstepEvent
{
	ESurfaceMaterialType SurfaceMaterial = ESurfaceMaterialType::Sand;
	FVector Location = FVector::ZeroVector;
	float SpeedMagnitude = 0.0f;
	float AudioVolume = 0.0f;
	double TriggerTime = 0.0;
};

