// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "ChimeraMovementComponent.h"

/**
 * Data payload for a footstep event. Carries surface material,
 * location, and timing for audio-visual sync telemetry.
 */
USTRUCT(BlueprintType)
struct FFootstepEvent
{
	GENERATED_BODY()

	/** Surface material type where the footstep occurred */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Footstep")
	ESurfaceMaterialType SurfaceMaterial = ESurfaceMaterialType::Sand;

	/** World location of the footstep (ground level) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Footstep")
	FVector Location = FVector::ZeroVector;

	/** Character speed at time of footstep (cm/s) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Footstep")
	float SpeedMagnitude = 0.0f;

	/** Audio volume played for this footstep (0.0-1.0) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Footstep")
	float AudioVolume = 0.0f;

	/** Time offset (seconds) when this footstep was triggered */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Footstep")
	double TriggerTime = 0.0;

};

