// Copyright 2026 Chimera Project. All Rights Reserved.
// Generated by GameCodeGenerator (core/game_code_generator.py::generate_surface_material_type_files).
//
// Extracted from ChimeraMovementComponent.h (tb-0150, 2026-07-18) so FFootstepEvent.h
// can reference ESurfaceMaterialType without depending back on the movement header.
// See generate_surface_material_type_files's own docstring in
// core/game_code_generator.py for the full circular-#include reasoning.
#pragma once

#include "CoreMinimal.h"
#include "SurfaceMaterialType.generated.h"

UENUM(BlueprintType)
enum class ESurfaceMaterialType : uint8
{
    Sand UMETA(DisplayName = "Sand"),
    Metal UMETA(DisplayName = "Metal"),
    Rock UMETA(DisplayName = "Rock"),
    Ground UMETA(DisplayName = "Ground/Dirt"),
    Water UMETA(DisplayName = "Water"),
    Custom UMETA(DisplayName = "Custom/Unknown")
};
