// Generated by GameCodeGenerator
#include "DockingComponent.h"
#include "GameFramework/Actor.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"

UDockingComponent::UDockingComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer), DockingRange(5000.0f), bIsDocked(false), CurrentStation(nullptr)
{
	PrimaryComponentTick.bCanEverTick = true;
}

void UDockingComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	if (bIsDocked) return;

	// Scan for station actors within DockingRange using GetAllActorsOfClass
	UWorld* World = GetWorld();
	if (!World) return;

	DockableStations.Empty();
}

void UDockingComponent::Undock()
{
	bIsDocked = false;
	CurrentStation = nullptr;
}

void UDockingComponent::RefuelShip()
{
	if (!bIsDocked || !CurrentStation) return;
	// TODO: Check if station has refuel service, calculate cost and refill fuel
}

void UDockingComponent::RepairShip()
{
	if (!bIsDocked || !CurrentStation) return;
	// TODO: Check if station has repair service, calculate cost and restore hull/subsystems
}

bool UDockingComponent::IsDocked() const
{
	return bIsDocked;
}

AActor* UDockingComponent::GetCurrentStation() const
{
	return CurrentStation;
}

TArray<FString> UDockingComponent::GetAvailableServices()
{
	TArray<FString> Services;
	Services.Add("refuel");
	Services.Add("repair");
	Services.Add("cargo");
	Services.Add("habitation");
	return Services;
}
