// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "QuantumTravelComponent.generated.h"

UENUM(BlueprintType)
enum class EQuantumDriveStatus : uint8
{
	Idle UMETA(DisplayName = "Idle"),
	Spooling UMETA(DisplayName = "Spooling"),
	InTransit UMETA(DisplayName = "In Transit"),
	Cooldown UMETA(DisplayName = "Cooldown")
};

UCLASS( ClassNoGenerateOptions, meta = (BlueprintType, Category = "QuantumTravel") )
class CHIMERA_API UQuantumTravelComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UQuantumTravelComponent(const FObjectInitializer& ObjectInitializer);

	UPROPERTY(EditDefaultsOnly, Category = "QuantumTravel", meta = (ClampMin = "0"))
	float SpoolTime;

	UPROPERTY(EditDefaultsOnly, Category = "QuantumTravel", meta = (ClampMin = "0"))
	float TravelTime;

	UPROPERTY(EditDefaultsOnly, Category = "QuantumTravel", meta = (ClampMin = "0"))
	float FuelCost;

	UPROPERTY(EditDefaultsOnly, Category = "QuantumTravel", meta = (ClampMin = "0"))
	float MaxRange;

	UPROPERTY(VisibleAnywhere, Category = "QuantumTravel")
	bool bIsSpooling;

	UPROPERTY(VisibleAnywhere, Category = "QuantumTravel")
	bool bInTransit;

	UPROPERTY(EditDefaultsOnly, Category = "QuantumTravel", meta = (ClampMin = "0", ClampMax = "1"))
	float InterdictionChance;

	UPROPERTY(VisibleAnywhere, Category = "QuantumTravel")
	FVector TargetLocation;

	UPROPERTY(VisibleAnywhere, Category = "QuantumTravel")
	EQuantumDriveStatus QuantumDriveStatus;

public:
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	UFUNCTION(BlueprintCallable, Category = "QuantumTravel")
	bool BeginQuantumTravel(FVector TargetLocation);

	UFUNCTION(BlueprintCallable, Category = "QuantumTravel")
	void CancelQuantumTravel();

	UFUNCTION(BlueprintPure, Category = "QuantumTravel")
	bool IsSpooling() const;

	UFUNCTION(BlueprintPure, Category = "QuantumTravel")
	bool IsInTransit() const;

	UFUNCTION(BlueprintPure, Category = "QuantumTravel")
	float GetSpoolProgress() const;

	UFUNCTION(BlueprintPure, Category = "QuantumTravel")
	EQuantumDriveStatus GetQuantumDriveStatus() const { return QuantumDriveStatus; }

	UFUNCTION(BlueprintPure, Category = "QuantumTravel")
	FString GetQuantumDriveStatusString() const;
};
