// Generated by GameCodeGenerator
#include "QuantumTravelComponent.h"
#include "GameFramework/Actor.h"
#include "../Flight/FlightComponent.h"
#include "../Combat/DamageComponent.h"
#include "../Combat/SystemDamageComponent.h"

UQuantumTravelComponent::UQuantumTravelComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer), SpoolTime(5.0f), TravelTime(30.0f), FuelCost(2000.0f), MaxRange(8000000000.0f), bIsSpooling(false), bInTransit(false), InterdictionChance(0.1f)
{
	PrimaryComponentTick.bCanEverTick = true;
}

void UQuantumTravelComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	if (!bIsSpooling && !bInTransit) return;

}

bool UQuantumTravelComponent::BeginQuantumTravel(FVector TargetLocation)
{
	// 1. Check UFlightComponent fuel >= FuelCost
	// 2. Check distance <= MaxRange
	// 3. Check SystemDamageComponent: if Quantum_Engine or QuantumDrive subsystem health <= 0, return false
	// 4. If QuantumDrive health < 50%: SpoolTime *= 2.0
	// 5. Deduct fuel via UFlightComponent
	// 6. Set bIsSpooling = true, start spool timer
	return true;
}

void UQuantumTravelComponent::CancelQuantumTravel()
{
	if (!bIsSpooling) return;
	// Only during spool phase: Refund 50% fuel, Reset timers
	bIsSpooling = false;
}

bool UQuantumTravelComponent::IsSpooling() const
{
	return bIsSpooling;
}

bool UQuantumTravelComponent::IsInTransit() const
{
	return bInTransit;
}

float UQuantumTravelComponent::GetSpoolProgress() const
{
	if (SpoolTime <= 0.0f) return 1.0f;
	// TODO: Calculate spool progress from 0 to 1 based on elapsed time
	return 0.0f;
}
