"""MAT2-D-MASSREG report generator (card-kit make_report pattern).

THE LAW: report.md is GENERATED from the committed receipts; no observed
value is hand-transcribed. Every number is an f-string/format substitution
from a receipt or the register. A reviewer can delete report.md, re-run
this script, and get byte-identical output.

Run AFTER all generator modes, at the candidate head:
    python -B make_report.py
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent


def sha256_file(path):
    return hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()


def load(name):
    return json.loads((HERE / name).read_text(encoding='utf-8'))


def main():
    reg = load('mass_register.json')
    enum = load('enumeration_receipt.json')
    imp = load('implied_bw_receipt.json')
    zdel = load('zero_mass_delta_receipt.json')
    det = load('determinism_receipt.json')
    fals = load('falsifier_receipt.json')
    regres = load('regression_receipt.json')
    totals = reg['totals']
    decision = imp['decision']
    klass = reg['specimen_classification']['scene_class']

    # executed/skipped accounting for the named-check suite (the count is
    # derived from the suite module itself, matching the batch-gate rerun)
    suite = (HERE / 'test_massreg_checks.py').read_text(encoding='utf-8')
    n_tests = suite.count('def test_')

    lines = []
    w = lines.append
    w('# MAT2-D-MASSREG report - the mass register (register, not repair)')
    w('')
    w('Attempt {attempt}, agent wk-massreg-d01, criteria sha256 {crit}. '
      'Isolated attempt checkout of E:/PythonChimera on branch-1; base '
      '{base}; preregistration frozen at commit c5d44831 BEFORE the '
      'implementation existed and before any measurement. This report is '
      'GENERATED by make_report.py from the receipts at freeze time - no '
      'observed value is hand-transcribed. CPU-only card: no GPU queue '
      'submission, no training, no runtime.'.format(
          attempt=reg['attempt_id'], crit=reg['criteria_sha256'],
          base=zdel['base_sha']))
    w('')
    w('## done_when clause map (all clauses executed on the exact candidate '
      'revision)')
    w('')
    w('| clause | execution | result |')
    w('|---|---|---|')
    w('| The mass register exists as a declared, evidence-anchored record | '
      'mass_register.json (schema {schema}), {n} entries + {oos} '
      'declared-out-of-scope rows, every entry anchored | '
      'entry_count={n}, anchors={a} |'.format(
          schema=reg['schema'], n=enum['entry_count'],
          oos=enum['declared_out_of_scope_count'],
          a=len(enum['anchor_manifest'])))
    w('| Every mass contributor classified against the two lawful systems | '
      'system field per entry: scene={scene_n}, '
      'biological-reference={bio_n}; closed vocabularies enforced | '
      'check T2 green |'.format(
          scene_n=sum(1 for e in reg['entries']
                      if e['system'] == 'scene'),
          bio_n=sum(1 for e in reg['entries']
                    if e['system'] == 'biological-reference')))
    w('| Register totals reproduce the pinned audits bit-exact | '
      'scene {s1} (bit-exact={b1}); scene carve {s2} (bit-exact={b2}); '
      'Buffy all_transported {s3} (bit-exact={b3}); TUA {s4} '
      '(bit-exact={b4}); B03 counted {s5} (bit-exact={b5}); root share '
      '{s6} | T4/T5/T6 green |'.format(
          s1=repr(totals['scene_body_total_kg']['value']),
          b1=totals['scene_body_total_kg']['reproduced_bit_exact'],
          s2=repr(totals['scene_carve_sum_kg']['value']),
          b2=totals['scene_carve_sum_kg']['reproduced_bit_exact'],
          s3=repr(totals['buffy_all_transported_kg']['value']),
          b3=totals['buffy_all_transported_kg']['reproduced_bit_exact'],
          s4=repr(totals['buffy_transport_under_assumption_kg']['value']),
          b4=totals['buffy_transport_under_assumption_kg']
          ['reproduced_bit_exact'],
          s5=repr(totals['b03_counted_set_kg']['value']),
          b5=totals['b03_counted_set_kg']['reproduced_bit_exact'],
          s6=repr(totals['buffy_root_reference_share']['value'])))
    w('| Any simulation mass value changed by this card fails | '
      'zero_mass_delta_receipt: Z1 all changed paths under the card '
      'prefix={z1} ({np} paths, {no} outside); Z2 producer blobs unchanged '
      'at both extractions={z2}; Z3 totals bit-exact={z3}; Z4 register '
      'values bit-copied={z4} | zero_mass_delta={zm} |'.format(
          z1=zdel['Z1_all_changed_paths_under_card_prefix'],
          np=len(zdel['changed_paths']),
          no=len(zdel['changed_paths_outside_prefix']),
          z2=all(v['equal_at_both_extractions'] and v['matches_pin']
                 for v in zdel['Z2_producer_blobs_unchanged'].values()),
          z3=all(zdel['Z3_totals_bit_exact'].values()),
          z4=all(zdel['Z4_register_values_bit_copied'].values()),
          zm=zdel['zero_mass_delta']))
    w('| A register entry without an evidence anchor fails the write-time '
      'gate | all {a} store anchors verified against MANIFEST.json at '
      'build time and in check P_input_pins | PASS |'.format(
          a=len(enum['anchor_manifest'])))
    reconciled_flags = [s['reconciled_into_one']
                        for s in reg['systems'].values()]
    w('| Declaring the two systems reconciled into one fails | '
      'two_systems_declared_distinct={d}, systems reconciled_into_one '
      'flags={flags} | T8 green |'.format(
          d=reg['law']['two_systems_declared_distinct'],
          flags=reconciled_flags))
    w('')
    w('## The register')
    w('')
    w('- Families (frozen counts, all reproduced): ' + ', '.join(
        '%s=%d' % (k, v) for k, v in
        sorted(enum['family_counts'].items())) + '; total entries '
      '{n}; declared out-of-scope rows {o} (demonstrator fixtures, '
      'REPIN_STUDY sections 1.5-1.8).'.format(
          n=enum['entry_count'],
          o=enum['declared_out_of_scope_count']))
    w('- Additional pinned totals: excluded osim free-limb claims {exc} '
      '(recomputed {exr}, within float floor={exf}); acceptance '
      'denominator {den} kg (D-W04 masses[0], unvalidated-density); '
      'Turnquist band low {lo} / midpoint {mi} / high {hi} kg; builder '
      'ordered-body sum {bo} (bit-exact={bob}, within float floor={bof} - '
      'the declared PREREG 7.2c disclosure).'.format(
          exc=repr(totals['osim_excluded_free_limb_kg']['value']),
          exr=repr(totals['osim_excluded_free_limb_kg']['recomputed']),
          exf=totals['osim_excluded_free_limb_kg']['within_float_floor'],
          den=repr(totals['acceptance_denominator_kg']['value']),
          lo=repr(totals['reference_band_kg']['low']),
          mi=repr(totals['reference_band_kg']['midpoint']),
          hi=repr(totals['reference_band_kg']['high']),
          bo=repr(totals['builder_order_sum_kg']['value']),
          bob=totals['builder_order_sum_kg']['bit_exact'],
          bof=totals['builder_order_sum_kg']['within_float_floor']))
    w('- Double-count scan: assembly counted mass {cm} kg, ledgers '
      'disjoint={ld}; subsumption hazard carried verbatim-class (B06 '
      'CHK-7).'.format(
          cm=repr(reg['double_count_scan']['assembly_counted_mass_kg']),
          ld=reg['double_count_scan']['ledgers_disjoint']))
    w('- Gap ledger carried: {gaps}.'.format(
        gaps=', '.join(g['gap_id'] for g in reg['gaps'])))
    w('')
    w('## The implied-BW measurement (the Lieutenant addendum) - '
      'escalation branch FIRED as measured')
    w('')
    w('- Method: implied BW kg = (mass_g - b_g) / (m_g/kg), M2-8 Segment '
      'mass m/b rows, atlas section 5 discipline; every number below is an '
      'UNCERTAINTY-UNCALIBRATED screen (atlas A5; M2-8 prints no '
      'dispersion).')
    for e in imp['evaluations']:
        if e.get('refusal'):
            w('- {id}: REFUSED ({ref}) - {note}'.format(
                id=e['id'], ref=e['refusal'], note=e['note']))
        else:
            w('- {id}: scene mass {mg} g -> implied BW {bw} kg{note}'.format(
                id=e['id'], mg=repr(e['scene_mass_g']),
                bw=repr(e['implied_bw_kg']),
                note='' if not e.get('caveat') else
                ' (' + e['caveat'] + ')'))
    w('- Calibration: C1 M2-6 means imply {c1} (matches the atlas: {c1m}); '
      'C2 sealed osim claims imply {c2} (matches the atlas: {c2m}); scene '
      'struts sit INSIDE-1SD of the M2-6 bands (z upper_arm {z1}, forearm '
      '{z2}).'.format(
          c1=imp['calibration']['C1_m26_means_implied_bw_kg'],
          c1m=imp['calibration']['C1_matches_atlas'],
          c2=imp['calibration']['C2_osim_claims_implied_bw_kg'],
          c2m=imp['calibration']['C2_matches_atlas'],
          z1=repr(imp['calibration']['C3_scene_strut_z']['upper_arm']),
          z2=repr(imp['calibration']['C3_scene_strut_z']['forearm'])))
    w('- DECISION (frozen rule applied to the split-free primary E4 only): '
      'E4 = {e4} kg lands INSIDE the female-band window {win}; specimen '
      'class = {klass}; branch = {branch}.'.format(
          e4=repr(decision['e4_primary_implied_bw_kg']),
          win=decision['windows']['female_band_kg'],
          klass=klass, branch=decision['branch']))
    w('- Reconciliation claim: {rc}'.format(
        rc=decision['reconciliation_claim']))
    w('- Escalation: {esc}'.format(esc=decision['escalation']))
    w('- NOTHING was repaired: the sealed scene stands at {s1} kg '
      '(carve {s2}); the register records the inconsistency and flags it '
      'to the walk-tier scene card. This is the REFUSED-step outcome the '
      'addendum named for this branch - a refused reconciliation claim, '
      'not a card failure.'.format(
          s1=repr(totals['scene_body_total_kg']['value']),
          s2=repr(totals['scene_carve_sum_kg']['value'])))
    w('')
    w('## Determinism (X2, byte-identity law)')
    w('')
    w('Two fresh runs produced BYTE-IDENTICAL mass_register.json (the '
      'declared determinism unit): sha256 {r1} both runs, '
      'X2_register_byte_identical={xi}, zero shared-key receipt '
      'differences, augmentation keys {ak}. X2_pass={p}.'.format(
          r1=det['register_sha_run1'], xi=det['X2_register_byte_identical'],
          ak=det['augmentation_keys'], p=det['X2_pass']))
    w('')
    w('## Falsifier proof (arms run with the clean control FIRST in the '
      'same executable; tampered copies in the attempt scratch, never '
      'committed)')
    w('')
    for name, arm in sorted(fals['arms'].items()):
        w('- {name}: tamper {t} -> observed {obs}; expected {exp}; bit={b}; '
          'clean control green={g} (guard {g_})'.format(
              name=name, t=arm['tamper'], obs=arm['observed_codes'],
              exp=arm['expected_codes'], b=arm['bit'],
              g=arm['clean_control']['green'],
              g_=arm['clean_control']['guard']))
    w('- F_all_green = {fg}.'.format(fg=fals['F_all_green']))
    w('')
    w('## Regression (the sealed upstream audit re-run UNMODIFIED)')
    w('')
    w('- b07 mass_audit.py at this revision: exit {ec}; its sealed receipt '
      'sha256 unchanged before/after and equal to the pin '
      '({sh}...): {unchanged}; P_regression_suite_green={p}.'.format(
          ec=regres['exit_code'],
          sh=regres['receipt_sha_before'][:16],
          unchanged=regres['sealed_receipt_sha_unchanged'],
          p=regres['P_regression_suite_green']))
    w('')
    w('## Named checks (re-run by batch_gates G12 at the candidate head)')
    w('')
    w('- Suite test_massreg_checks.py: {n} checks; executed {n}, skipped 0 '
      '(no skipTest anywhere in the suite; no KNOWN_SKIPS '
      'needed).'.format(n=n_tests))
    w('- The suite asserts: register schema/identity (T1), entry fields + '
      'closed vocabularies + anchors (T2), specimen-class backing (T3), '
      'Buffy totals bit-exact (T4), scene totals bit-exact + the honest '
      'builder-order disclosure (T5), B03 counted bit-exact (T6), '
      'zero-mass-delta green (T7), register-not-repair (T8), implied-BW '
      'receipt + calibration + decision (T9), bit-copy law (T10), four FA '
      'arms, and the P probes (pins+store anchors, vacuous guard, '
      'determinism, regression, report-number lint).')
    w('')
    w('## Amendments and implementation disclosures (full disclosure)')
    w('')
    w('- Amendments to PREREGISTRATION.md: NONE (single prereg commit '
      'c5d44831; no A1+ commits exist).')
    w('- Implementation refinements INSIDE the frozen design, disclosed: '
      '(a) the zero-delta proof is isolated as its own generator mode so '
      'its base..head diff covers every other receipt (content as frozen, '
      'PREREG section 8); (b) the prereg b03 family "7 matter rows + 1 '
      'density row" is namespace-split in FAMILY_COUNTS as b03.counted=5, '
      'b03.zero_shell=2, b03.density=1 (same rows); (c) the '
      'scene-family recomputation check uses the prereg-declared float '
      'floor discipline (PREREG 7.2c) because the builder-order sum is '
      'honestly not bit-equal to the carve literal; (d) the '
      'scene-side acceptance-denominator row carries the system-level '
      'specimen class per PREREG 7.3 ("every scene-side row").')
    w('')
    w('## Honest limitations')
    w('')
    w('- The register registers; it does not admit. No R-MASS-04-style '
      'lead decision is recorded or implied; the Buffy quantities stay '
      'uncounted; the two systems stay distinct ledgers.')
    w('- The implied-BW numbers are uncertainty-uncalibrated screens '
      '(atlas A5), recorded as the addendum classification evidence, not '
      'as biology; the E1/E2 per-segment evaluations inherit the '
      'hind-borrowed split (GAP-3) and are recorded as split-dependent.')
    w('- This card produces no visual evidence by design (records/offline; '
      'predeclared nonvisual rationale in PREREG section 9); numerical '
      'and independent review remain required.')
    w('- The zero-delta receipt records head_sha at proof time; its own '
      'artifact commit is excluded from its diff by construction and the '
      'report commit follows it (disclosed single-commit delta).')
    w('')
    w('## File identities (sha256, computed at report freeze time; '
      'report.md excluded - it is this file)')
    w('')
    for name in sorted(p.name for p in HERE.iterdir()
                       if p.is_file() and p.name != 'report.md'
                       and not p.name.endswith('.pyc')):
        w('- {n} {h}'.format(n=name, h=sha256_file(HERE / name)))
    (HERE / 'report.md').write_bytes(
        ('\n'.join(lines) + '\n').encode('utf-8'))
    print('report.md written,', len(lines), 'lines')
    return 0


if __name__ == '__main__':
    sys.exit(main())
