// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "PCGData.h"
#include "Metadata/PCGMetadata.h"
#include "UPCG_Graph_Planet_Surface_Generation.generated.h"

UCLASS( meta = (BlueprintType, Category = "PCG") )
class CHIMERA_API UPCG_Graph_Planet_Surface_Generation : public UActorComponent
{
	GENERATED_BODY()

public:
	UPCG_Graph_Planet_Surface_Generation(const FObjectInitializer& ObjectInitializer);

	UPROPERTY(EditDefaultsOnly, Category = "PCG|DataCollection")
	TArray<FPCGTaggedData> TaggedData;

	UPROPERTY(EditDefaultsOnly, Category = "PCG|Metadata")
	UPCGMetadata* Metadata;

public:
	UFUNCTION(BlueprintCallable, Category = "PCG")
	void InitializeDataCollection(FName CollectionName);

	UFUNCTION(BlueprintPure, Category = "PCG")
	bool GetCancelExecutionOnEmpty() const;

	UFUNCTION(BlueprintPure, Category = "PCG")
	bool GetCancelExecution() const;
};
