// Generated by GameCodeGenerator
#include "UPCG_Graph_Planet_Surface_Generation.h"
#include "PCGData.h"
UPCG_Graph_Planet_Surface_Generation::UPCG_Graph_Planet_Surface_Generation(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}

void UPCG_Graph_Planet_Surface_Generation::InitializeDataCollection(FName CollectionName)
{
	// Initialize FPCGDataCollection with TaggedData items
}

bool UPCG_Graph_Planet_Surface_Generation::GetCancelExecutionOnEmpty() const
{
	return false;
}

bool UPCG_Graph_Planet_Surface_Generation::GetCancelExecution() const
{
	return false;
}
