// Generated by GameCodeGenerator - Lunar Surface Impact Audio
#include "SandSoundComponent.h"
#include "Components/AudioComponent.h"

USandSoundComponent::USandSoundComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
	, ImpactSound(nullptr)
	, VolumeMultiplier(0.4f)
	, PitchMultiplier(1.0f)
	, LowPassFrequency(800.0f)
	, AudioComponent(nullptr)
	, bIsVacuum(true)
	, FootstepSyncEventCount(0)
	, MaxFootstepSyncLatencyMs(0.0f)
	, AverageFootstepSyncLatencyMs(0.0f)
	, LastFootstepVolume(0.0f)
	, TotalFootstepSyncLatencyMs(0.0f)
{
	PrimaryComponentTick.bCanEverTick = false;
}

void USandSoundComponent::BeginPlay()
{
	Super::BeginPlay();

	if (AActor* Owner = GetOwner())
	{
		AudioComponent = Owner->FindComponentByClass<UAudioComponent>();
		if (!AudioComponent)
		{
			AudioComponent = NewObject<UAudioComponent>(Owner, TEXT("SandAudioComponent"));
			AudioComponent->RegisterComponent();
		}

		// Continuous wind layer (auto-start if a wind loop asset is provided and not in vacuum)
		if (WindLoopSound && !bIsVacuum)
		{
			WindAudioComponent = NewObject<UAudioComponent>(Owner, TEXT("SandWindComponent"));
			if (WindAudioComponent)
			{
				WindAudioComponent->RegisterComponent();
				WindAudioComponent->SetLowPassFilterEnabled(true);
				WindAudioComponent->SetSound(WindLoopSound);
				WindAudioComponent->SetVolumeMultiplier(WindMinVolume);
				WindAudioComponent->SetLowPassFilterFrequency(WindLowPassMin);
				WindAudioComponent->Play();
				bWindActive = true;
			}
		}
	}
}

void USandSoundComponent::PlayImpactSound(FVector Location)
{
	if (!ImpactSound || bIsVacuum)
	{
		return;
	}

	if (AudioComponent)
	{
		AudioComponent->SetSound(ImpactSound);
		AudioComponent->SetVolumeMultiplier(VolumeMultiplier);
		AudioComponent->SetPitchMultiplier(PitchMultiplier);
		AudioComponent->SetLowPassFilterEnabled(true);
		AudioComponent->SetLowPassFilterFrequency(LowPassFrequency);
		AudioComponent->SetWorldLocation(Location);
		AudioComponent->Play();
	}
}

void USandSoundComponent::SetVacuumMode(bool bInIsVacuum)
{
	bIsVacuum = bInIsVacuum;
	if (bIsVacuum)
	{
		StopWind();
	}
	else if (WindLoopSound)
	{
		StartWind();
	}
}

// ------------------------------------------------------------------
// Wind Layer - continuous speed-driven wind synthesis
// ------------------------------------------------------------------
void USandSoundComponent::StartWind()
{
	if (!WindLoopSound || bIsVacuum || bWindActive)
	{
		return;
	}

	if (AActor* Owner = GetOwner())
	{
		if (!WindAudioComponent)
		{
			WindAudioComponent = NewObject<UAudioComponent>(Owner, TEXT("SandWindComponent"));
			WindAudioComponent->RegisterComponent();
		}
		WindAudioComponent->SetLowPassFilterEnabled(true);
		WindAudioComponent->SetSound(WindLoopSound);
		WindAudioComponent->SetVolumeMultiplier(WindMinVolume);
		WindAudioComponent->SetLowPassFilterFrequency(WindLowPassMin);
		WindAudioComponent->Play();
		bWindActive = true;
	}
}

void USandSoundComponent::StopWind()
{
	if (WindAudioComponent && bWindActive)
	{
		WindAudioComponent->Stop();
	}
	bWindActive = false;
}

void USandSoundComponent::SetWindIntensity(float WindSpeed)
{
	if (!WindAudioComponent || !bWindActive)
	{
		return;
	}

	const float Fraction = FMath::Clamp(WindSpeed / FMath::Max(WindSpeedForMaxVolume, 1.0f), 0.0f, 1.0f);
	const float Volume = FMath::Lerp(WindMinVolume, WindMaxVolume, Fraction);
	const float LowPass = FMath::Lerp(WindLowPassMin, WindLowPassMax, Fraction);
	const float Pitch = 0.8f + (Fraction * 0.6f); // 0.8x -> 1.4x
	WindAudioComponent->SetVolumeMultiplier(Volume);
	WindAudioComponent->SetLowPassFilterFrequency(LowPass);
	WindAudioComponent->SetPitchMultiplier(Pitch);
}

void USandSoundComponent::RecordFootstepSyncEvent(float LatencyMs, float Volume, float SpeedCmS)
{
	// Increment event count
	++FootstepSyncEventCount;

	// Update maximum latency
	MaxFootstepSyncLatencyMs = FMath::Max(MaxFootstepSyncLatencyMs, LatencyMs);

	// Update running total and recalculate average
	TotalFootstepSyncLatencyMs += LatencyMs;
	AverageFootstepSyncLatencyMs = TotalFootstepSyncLatencyMs / static_cast<float>(FootstepSyncEventCount);

	// Store last volume
	LastFootstepVolume = Volume;

	// Speed-bucketed volume tracking: SpeedCmS < 0 means unknown — counted
	// above, excluded here so it can't poison the comparison.
	if (SpeedCmS >= 0.0f)
	{
		if (SpeedCmS >= SpeedBucketThresholdCmS)
		{
			FastBucketVolumeSum += Volume;
			++FastBucketCount;
		}
		else
		{
			SlowBucketVolumeSum += Volume;
			++SlowBucketCount;
		}
	}
}

bool USandSoundComponent::GetVolumeScalesWithSpeed() const
{
	if (SlowBucketCount == 0 || FastBucketCount == 0)
	{
		return false; // one-sided evidence proves nothing either way
	}
	const float SlowAvg = SlowBucketVolumeSum / static_cast<float>(SlowBucketCount);
	const float FastAvg = FastBucketVolumeSum / static_cast<float>(FastBucketCount);
	return FastAvg > SlowAvg;
}

void USandSoundComponent::ClearFootstepSyncTelemetry()
{
	FootstepSyncEventCount = 0;
	MaxFootstepSyncLatencyMs = 0.0f;
	AverageFootstepSyncLatencyMs = 0.0f;
	LastFootstepVolume = 0.0f;
	TotalFootstepSyncLatencyMs = 0.0f;
	SlowBucketVolumeSum = 0.0f;
	SlowBucketCount = 0;
	FastBucketVolumeSum = 0.0f;
	FastBucketCount = 0;
}
