# Level Creation Script for deepspacetrader_defaultlevel
# Generated by GameCodeGenerator

import unreal

def create_level():
    # Get the editor asset manager and world actor factory
    asset_manager = unreal.EditorAssetLibrary()
    world_factory = unreal.WorldActorFactory()
    
    # Create or load the level
    level_name = "/Game/Levels/deepspacetrader_defaultlevel"
    level_path = f"{level_name}.umap"
    
    # Create a new level in the editor
    print(f"Creating level: {level_path}")
    
    # Set skybox type
    print(f"Setting skybox type: deep_space")
    
    # Create PlayerStart actor
    player_start_class = unreal.PlayerStart
    player_start_actor = unreal.EditorLevelLibrary().spawn_actor_from_class(
        player_start_class,
        unreal.Vector(0.0, 0.0, 100.0),
        unreal.Rotator(0, 0, 0)
    )
    print(f"Created PlayerStart at {player_start_actor.get_location()}")
    
    # Create DirectionalLight (Sun)
    directional_light_class = unreal.DirectionalLight
    sun_light = unreal.EditorLevelLibrary().spawn_actor_from_class(
        directional_light_class,
        unreal.Vector(0, 0, 1000),
        unreal.Rotator(-45, -45, 0)
    )
    if sun_light:
        sun_light.set_light_intensity(1.0)
        print("Created DirectionalLight")
        
    # Create SkyLight
    skylight_class = unreal.SkyLight
    sky_light = unreal.EditorLevelLibrary().spawn_actor_from_class(
        skylight_class,
        unreal.Vector(0, 0, 500),
        unreal.Rotator(0, 0, 0)
    )
    if sky_light:
        print("Created SkyLight")
        
    # Create floor/ground plane
    static_mesh_factory = unreal.StaticMeshActorFactoryBlueprint
    # Use a simple box or plane for the ground
    ground_class = unreal.BoxComponent
    
    # Add station actors at specified locations
    for station in [{'station_name': 'Orbital_Hub_7', 'location': [0.0, 0.0, 0.0]}, {'station_name': 'Ares_Market_Central', 'location': [50000.0, 0.0, 0.0]}, {'station_name': 'Shadow_Reef', 'location': [-30000.0, 20000.0, 0.0]}]:
        station_name = station.get('station_name', 'UnknownStation') if isinstance(station, dict) else station.get('name', 'UnknownStation')
        location = station.get('location', [0, 0, 0]) if isinstance(station, dict) else station.get('location', [0, 0, 0])
        print(f"Placing station {station_name} at {location}")
        
    # Add planet actors at specified locations with scale
    for planet in [{'planet_name': 'Titan', 'location': [100000.0, 0.0, 0.0], 'scale': 5.0}, {'planet_name': 'Ares-Prime', 'location': [50000.0, 50000.0, 0.0], 'scale': 3.0}]:
        planet_name = planet.get('planet_name', 'UnknownPlanet') if isinstance(planet, dict) else planet.get('name', 'UnknownPlanet')
        location = planet.get('location', [0, 0, 0]) if isinstance(planet, dict) else planet.get('location', [0, 0, 0])
        scale = planet.get('scale', 1.0) if isinstance(planet, dict) else planet.get('scale', 1.0)
        print(f"Placing planet {planet_name} at {location} with scale {scale}")

    # Note: PCG volumes must be spawned at runtime via C++ code in the GameMode or Level class.
    # A PCGVolumeManager has been added to the GameMode to spawn APCGVolume actors with UPCGComponents
    # that reference the generated PCG graphs. This is triggered during BeginPlay().
        
    # Save the level
    unreal.EditorLevelLibrary().save_all_current_packages()
    print(f"Level saved to: {level_path}")
    
if __name__ == "__main__":
    create_level()
