// Generated by GameCodeGenerator
#include "PirateAIController.h"
#include "GameFramework/Actor.h"
#include "Kismet/KismetMathLibrary.h"

APirateAIController::APirateAIController(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer), FactionName(TEXT("Void_Syndicate")), HostilityToPlayer(1.0f), DetectionRange(50000.0f), EngagementRange(20000.0f), CurrentState(EAIPirateState::Patrolling) {
}

void APirateAIController::BeginPlay() {
	Super::BeginPlay();
}

void APirateAIController::TickController(float DeltaTime) {
	Super::TickController(DeltaTime);
	
	// State machine logic:
	if (CurrentState == EAIPirateState::Patrolling) {
		if (ScanForPlayer() && HostilityToPlayer > 0.5f) {
			CurrentState = EAIPirateState::Investigating;
		}
	} else if (CurrentState == EAIPirateState::Investigating) {
		// Move toward last known position
		if (ScanForPlayer() && HostilityToPlayer > 0.7f) {
			CurrentState = EAIPirateState::Engaging;
		}
	} else if (CurrentState == EAIPirateState::Engaging) {
		// Maintain combat range, fire weapons
		float Threat = EvaluateThreat();
		if (Threat < 0.3f) {
			CurrentState = EAIPirateState::Retreating;
		}
	} else if (CurrentState == EAIPirateState::Retreating) {
		// Full thrust away, attempt quantum jump
		if (HostilityToPlayer <= 0.5f) {
			CurrentState = EAIPirateState::Patrolling;
		}
	}
}

bool APirateAIController::ScanForPlayer() {
	return false;
}

float APirateAIController::EvaluateThreat() {
	return 0.5f;