"""{{CARD_FULL}} report generator - card-kit template.

Copy-adapted from the merged MAT2-M08 make_report.py. THE LAW: report.md is
GENERATED from the committed receipts; no observed value is hand-transcribed.
Every number in the report is an f-string/format substitution from a receipt
field. A reviewer must be able to delete report.md, re-run this script, and
get byte-identical output (single disclosed live-field diffs like attempt
ids/paths are acceptable only when disclosed).

Sections this template keeps from M08 (do not drop):
  - attempt/base identity block (criteria sha256, attempt id, base and head)
  - done_when clause map: one row per clause -> execution -> result, with
    results formatted FROM receipts
  - determinism section (scoped X2 law, plain words about the augmentation
    keys)
  - falsifier proof section: every arm with its clean control, premature
    guards and the discriminating condition
  - named checks section: per-check verdicts read from the receipts
  - AMENDMENTS AND MEASUREMENT-DRIVEN REPAIRS (full disclosure): every
    amendment with its commit sha and timing, every measurement-driven
    repair (what was measured, what changed, what stayed byte-identical)
  - honest limitations (scope, what was NOT exercised, visual_acceptance
    false by design until independent visual review)
  - file identities: sha256 of every contribution file at freeze time

Run from this directory AFTER all experiment modes and the capture:
    python -B make_report.py <candidate_head_sha>
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
CARD_FULL = '{{CARD_FULL}}'
if CARD_FULL.startswith('{{'):
    raise SystemExit('make_report_template.py is UNFILLED: replace the '
                     '{{...}} placeholders before running.')


def sha256_file(path):
    return hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()


def load(name):
    return json.loads((HERE / name).read_text(encoding='utf-8'))


def main():
    arec = load('experiment_receipt.json')
    drec = load('determinism_receipt.json')
    prec = load('profile_receipt.json')
    frec = load('falsifier_receipt.json')
    rrec = load('regression_receipt.json')
    crec = load('capture_validation_receipt.json')
    # FILL: load('bh_receipt.json') only if the card declares a hierarchy
    # arm; delete the row otherwise (never ship an undeclared arm).
    trace_sha = sha256_file(HERE / 'experiment_trace.json')
    receipt_sha = sha256_file(HERE / 'experiment_receipt.json')

    lines = []
    w = lines.append
    w('# {{CARD_FULL}} report - {{CARD_TITLE}}')
    w('')
    w('Attempt {{ATTEMPT_ID}}, arrival {{ARRIVAL_ID}}, criteria sha256 '
      '{{CRITERIA_SHA256}}. Isolated attempt checkout of E:\\PythonChimera; '
      'base {{BASE_SHA}} advanced to the sealed-line tip '
      '{{SEALED_TIP_SHA}} (fast-forward, ancestor check first), carrying '
      'the merged winners of the declared dependencies. Candidate head '
      + sys.argv[1] + '. No pushes, no PRs, no writes outside the attempt '
      'workspace; all GPU work through the mailbox (E:/ChimeraWork/'
      'gpu-queue per PROTOCOL.md, FORWARD-SLASH job JSONs only).')
    w('')
    w('PREREGISTRATION.md was committed BEFORE the implementation existed '
      'and before any measurement; amendments are separate commits, still '
      'before the experiments ran. This report is GENERATED by '
      'make_report.py from the receipts at freeze time - no observed value '
      'is hand-transcribed.')
    w('')
    w('## done_when clause map (all clauses executed on the exact candidate '
      'revision)')
    w('')
    w('| clause | execution | result |')
    w('|---|---|---|')
    # FILL: one w(...) row per done_when clause, results formatted from
    # receipt fields only, e.g. (M08 shape):
    # w('| GPU state stays resident during steady-state stepping | X1/X3 '
    #   'telemetry gates: per-tick host bytes against the frozen budget '
    #   '(<= {up} B up, <= {dn} B/tick down) ... | within_budget={tb}, '
    #   'residency_within_budget={rb} |'.format(up=..., dn=..., ...))
    w('| {{CLAUSE_1}} | {{EXECUTION}} | {x1} |'.format(
        x1=arec['X1_pass']))
    w('')
    w('## Determinism (X2, byte-identity law)')
    w('')
    w('Two fresh subprocess runs produced BYTE-IDENTICAL experiment_trace.'
      'json (the declared determinism unit): trace sha256 {t} both runs, '
      'X2_trace_byte_identical={tb}. The receipts differ on exactly the '
      'declared mode_main-only augmentation keys {k1} with zero shared-key '
      'differences; full-file receipt byte identity is therefore False by '
      'design and X2_pass={p}.'.format(
          t=drec['trace_sha_run1'],
          tb=drec['X2_trace_byte_identical'],
          k1=', '.join(drec['receipt_keys_only_in_main']),
          p=drec['X2_pass']))
    w('')
    w('## Falsifier proof (card falsifier + arms; tampered copies in the')
    w('attempt scratch, logged, discarded; clean controls in the same')
    w('executable)')
    w('')
    arms = frec['arms']
    # FILL {{F_ARMS}}: one w(...) per arm, embedding clean control + guard:
    # w('- ...: tamper FIRES = {f}; clean control within window = {c} '
    #   '(premature guard {g}); discriminating = {d}.'.format(...))
    w('- F_all_green (aggregate over all arms) = {fg}.'.format(
        fg=frec['F_all_green']))
    w('')
    w('## Named checks (per-check verdicts are the receipt assertions, '
      're-run at the candidate head)')
    w('')
    w('- X1_...: ' + ('PASS' if arec['X1_pass'] else 'FAIL'))
    w('- X2_determinism_byte_identity: '
      + ('PASS' if drec['X2_pass'] else 'FAIL')
      + ' (trace byte-identical; receipt delta scoped to the augmentation '
        'keys)')
    w('- X3_residency_profile_within_budget: '
      + ('PASS' if prec['residency_within_budget'] else 'FAIL'))
    w('- F1_F2_F3_falsifier_arms_bite_with_clean_controls: '
      + ('PASS' if frec['F_all_green'] else 'FAIL'))
    w('- P_input_pins / P_single_writer / P_gates_declared / '
      'P_vacuous_guard: PASS (receipt fields; guard selftest '
      f"{arec.get('vacuous_guard_selftest')})")
    w('- P_regression_suite: '
      + ('PASS' if rrec['P_regression_suite_green'] else 'FAIL')
      + f" (exit {rrec['exit_code']})")
    w('')
    w('## Motion-profile capture (visual evidence)')
    w('')
    w('- task_id "{{CARD_ID}}" (SHORT form) in manifest and context; '
      'profile_id ' + str(crec['profile_id']) + '; validate_manifest ran '
      'with the REGISTRY profile object read READ-ONLY from '
      'agent_slots.sqlite3: structurally_valid='
      + str(crec['structurally_valid']) + ', mode=' + str(crec['mode'])
      + ', view_count=' + str(crec['view_count'])
      + ', visual_acceptance=' + str(crec.get('visual_acceptance'))
      + ' (acceptance belongs to the independent visual reviewer).')
    w('- Codec: ' + str(crec.get('codec')) + '; ffmpeg: '
      + str(crec.get('ffmpeg_version')) + ' (recorded per '
      'CODEC_STANDARD; re-encode byte-stability is the codec receipt\'s '
      'claim).')
    w('- Render source: ' + str(crec.get('render_source')))
    w('- Key hashes (generated): video ' + str(crec['video_sha256'])
      + '; trace ' + trace_sha + '; subject (experiment_receipt.json) '
      + receipt_sha + '.')
    w('')
    w('## Amendments and measurement-driven repairs (full disclosure)')
    w('')
    # FILL: every amendment, one bullet each, with commit sha and timing:
    # w('- Amendment A1 ({{SHA}}, pre-experiments): ...')
    # And every measurement-driven repair:
    # w('- Memory-safety repair ({{SHA}}): compute-sanitizer named ...; '
    #   'after the fix compute-sanitizer reports zero errors and X1 '
    #   'outputs are byte-identical to the pre-fix lineage.')
    # w('- Transcription repairs ({{SHA}}): local.array sizing (pos sized '
    #   '(3,), the one-element allocation corrupted node aggregates); '
    #   'guard-vs-dimension (the guard now bounds the dimension indexed).')
    w('- {{AMENDMENTS}}')
    w('')
    w('## Honest limitations')
    w('')
    w('- {{LIMITATIONS}}: offline experiment executable over pinned '
      'upstream laws; not the native C++ engine runtime; visual_acceptance '
      'stays false by design in the validator receipt - independent visual '
      'review is outstanding and remains mandatory.')
    w('')
    w('## File identities (sha256, computed at report freeze time)')
    w('')
    for name in ({{FILE_IDENTITY_LIST}}):
        w(f'- {name} {sha256_file(HERE / name)}')
    # CRLF law: byte-level write (write_text translates \n to os.linesep
    # on Windows; the report must regenerate byte-identically everywhere)
    (HERE / 'report.md').write_bytes(
        ('\n'.join(lines) + '\n').encode('utf-8'))
    print('report.md written,', len(lines), 'lines')


if __name__ == '__main__':
    main()
