"""R2 corpus builder — mutations authored independently of W1's corpus.

Reads ONLY from tools/ (read-only). Writes ONLY into R2_review_tools/work/w1/.
Mutations:
  r2_m1_ulp_inertia : 1-ULP edit (math.nextafter) of inertia_tensor_about_com.value[0][0]
  r2_m2_swap_prov   : swap input_hashes.manifest_sha256 <-> partition_sha256
  r2_m3_ulp_mass    : 1-ULP edit (math.nextafter) of mass_properties.mass.value
Tampered-pair support: writes mutated groups (1-ULP mass) for the producer-agreement
check; the delivered report is then REGENERATED by W1's pinned_runner itself.
"""
import json
import math
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path("E:/ChimeraWork/mvc-20260924")
TOOLS = REPO / "tools"
R2 = REPO / "material_volume_campaign/impl/R2_review_tools"
W1 = REPO / "material_volume_campaign/impl/W1_source_verify"
OUT = R2 / "work/w1"
OUT.mkdir(parents=True, exist_ok=True)

SRC = {
    "manifest": "material_volume_body_export_manifest_example.json",
    "partition": "material_volume_body_export_partition_example.json",
    "groups": "material_volume_body_export_groups_example.json",
    "report": "material_volume_body_export_example_report.json",
}
for name, fname in SRC.items():
    shutil.copyfile(TOOLS / fname, OUT / f"genuine_{name}.json")

report = json.loads((OUT / "genuine_report.json").read_text(encoding="utf-8"))

def dump(obj, path):
    Path(path).write_text(json.dumps(obj, indent=2) + "\n", encoding="utf-8",
                          newline="\n")

# R2-M1: 1-ULP inertia edit on body_groups[1]
m1 = json.loads(json.dumps(report))
v = m1["body_groups"][1]["mass_properties"]["inertia_tensor_about_com"]["value"]
orig = v[0][0]
v[0][0] = math.nextafter(orig, math.inf)
assert v[0][0] != orig
dump(m1, OUT / "r2_m1_ulp_inertia.json")
print("M1 inertia[0][0]:", orig, "->", v[0][0])

# R2-M2: swapped provenance hash fields
m2 = json.loads(json.dumps(report))
h = m2["input_hashes"]
h["manifest_sha256"], h["partition_sha256"] = h["partition_sha256"], h["manifest_sha256"]
dump(m2, OUT / "r2_m2_swap_prov.json")
print("M2 swapped manifest/partition sha256 fields")

# R2-M3: subtle mass change (1 ULP)
m3 = json.loads(json.dumps(report))
mass = m3["body_groups"][1]["mass_properties"]["mass"]["value"]
m3["body_groups"][1]["mass_properties"]["mass"]["value"] = math.nextafter(mass, math.inf)
dump(m3, OUT / "r2_m3_ulp_mass.json")
print("M3 mass:", mass, "->", m3["body_groups"][1]["mass_properties"]["mass"]["value"])

# Tampered-pair input: 1-ULP mass edit in the GROUPS source itself
groups = json.loads((OUT / "genuine_groups.json").read_text(encoding="utf-8"))
tg = json.loads(json.dumps(groups))
def mutate_groups(node):
    hits = 0
    if isinstance(node, dict):
        for key, val in list(node.items()):
            if key == "mass_kg" and isinstance(val, (int, float)):
                node[key] = math.nextafter(float(val), math.inf)
                hits += 1
            else:
                hits += mutate_groups(val)
    elif isinstance(node, list):
        for item in node:
            hits += mutate_groups(item)
    return hits
hits = mutate_groups(tg)
print("M-TP groups mass_kg fields mutated:", hits)
dump(tg, OUT / "r2_tp_groups.json")
print("corpus written to", OUT)
