"""
C++ Generation Engine for the Chimera Procedural Game Generator.
Handles generation of .h and .cpp files to Source/Chimera/.
"""

import os
from config import *


def ensure_directories():
    """Ensure all required directories exist."""
    dirs_to_create = [
        GameConfiguration.source_dir(),
        os.path.join(GameConfiguration.chimera_root(), "Source", "Chimera", "Generated"),
        os.path.join(GameConfiguration.content_dir(), "ProceduralGenerated"),
        os.path.join(GameConfiguration.content_dir(), "GeneratedLevels")
    ]

    for dir_path in dirs_to_create:
        os.makedirs(dir_path, exist_ok=True)


def generate_cpp_header_file(class_name, base_class, includes=None):
    """Generate a C++ header file."""
    if includes is None:
        includes = ["CoreMinimal.h"]

    header_content = f"// Generated by ProceduralGameGenerator\n"
    header_content += f"#pragma once\n\n"
    header_content += f'#include "CoreMinimal.h"\n'

    for inc in includes:
        if inc != "CoreMinimal.h":
            header_content += f'#include "{inc}"\n'

    header_content += f"\nclass CHIMERA_API U{class_name} : public {base_class}\n"
    header_content += "{\n"
    header_content += f"\tGENERATED_BODY()\n\n"
    header_content += "public:\n"
    header_content += f"\tU{class_name}(const FObjectInitializer& ObjectInitializer);\n\n"
    header_content += "protected:\n"
    header_content += "\t// Override functions here\n\n"
    header_content += "private:\n"
    header_content += "};\n"

    file_path = os.path.join(GameConfiguration.source_dir(), f"{class_name}.h")
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(header_content)

    return file_path


def generate_cpp_source_file(class_name, includes=None):
    """Generate a C++ source file."""
    if includes is None:
        includes = [f"{class_name}.h"]

    source_content = f"// Generated by ProceduralGameGenerator\n"
    source_content += f'#include "{class_name}.h"\n'

    for inc in includes:
        if inc != f"{class_name}.h":
            source_content += f'#include "{inc}"\n'

    source_content += f"\nU{class_name}::U{class_name}(const FObjectInitializer& ObjectInitializer)\n"
    source_content += "\t: Super(ObjectInitializer)\n"
    source_content += "{\n"
    source_content += "\t// Constructor code here\n"
    source_content += "}\n"

    file_path = os.path.join(GameConfiguration.source_dir(), f"{class_name}.cpp")
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(source_content)

    return file_path


def generate_procedural_generator_component():
    """Generate the main procedural generator C++ component."""
    # Generate header
    header_path = generate_cpp_header_file(
        class_name="ProceduralGeneratorComponent",
        base_class="UActorComponent",
        includes=["CoreMinimal.h", "GameFramework/Actor.h"]
    )

    # Generate source
    source_path = generate_cpp_source_file(
        class_name="ProceduralGeneratorComponent",
        includes=["ProceduralGeneratorComponent.h"]
    )

    return header_path, source_path


def generate_vehicle_spawner_component():
    """Generate the vehicle spawner C++ component for procedural placement."""
    # Generate header
    header_path = generate_cpp_header_file(
        class_name="VehicleSpawnerComponent",
        base_class="UActorComponent",
        includes=["CoreMinimal.h", "GameFramework/Actor.h", "Engine/World.h"]
    )

    # Generate source
    source_path = generate_cpp_source_file(
        class_name="VehicleSpawnerComponent",
        includes=["VehicleSpawnerComponent.h"]
    )

    return header_path, source_path


def generate_flight_control_component():
    """Generate the flight control C++ component for 6DOF spaceship-style movement."""
    class_name = "FlightControlComponent"

    # Generate header with full implementation
    header_content = ""
    header_content += "// Generated by ProceduralGameGenerator\n"
    header_content += "#pragma once\n\n"
    header_content += '#include "CoreMinimal.h"\n'
    header_content += '#include "Components/ActorComponent.h"\n'
    header_content += f'#include "{class_name}.generated.h"\n\n'
    header_content += "UCLASS( ClassNoGenerateOptions, meta = (BlueprintType, Category = \"Flight\") )\n"
    header_content += f"class CHIMERA_API U{class_name} : public UActorComponent\n"
    header_content += "{\n"
    header_content += "\tGENERATED_BODY()\n\n"
    header_content += "public:\n"
    header_content += f"\tU{class_name}(const FObjectInitializer& ObjectInitializer);\n\n"
    header_content += "protected:\n"
    header_content += "\t// Flight mode toggle flag\n"
    header_content += "\tUPROPERTY(EditAnywhere, Category = \"Flight\")\n"
    header_content += "\tbool bFlightModeEnabled = false;\n\n"
    header_content += "\t// Maximum thrust force multiplier (applied per Tick)\n"
    header_content += "\tUPROPERTY(EditAnywhere, Category = \"Flight\", meta = (ClampMin = \"0.0\"))\n"
    header_content += "\tfloat ThrustPower = 150.0f;\n\n"
    header_content += "\t// Maximum rotation speed in degrees per second for pitch/yaw/roll\n"
    header_content += "\tUPROPERTY(EditAnywhere, Category = \"Flight\", meta = (ClampMin = \"0.0\"))\n"
    header_content += "\tfloat RotationSpeed = 90.0f;\n\n"
    header_content += "\t// Angular velocity damping when not actively rotating (prevents drift)\n"
    header_content += "\tUPROPERTY(EditAnywhere, Category = \"Flight\")\n"
    header_content += "\tfloat AngularDampingWhenIdle = 5.0f;\n\n"
    header_content += "\t// Velocity damping factor per Tick (simulates minimal drag in space)\n"
    header_content += "\tUPROPERTY(EditAnywhere, Category = \"Flight\", meta = (ClampMin = \"0.0\", ClampMax = \"1.0\"))\n"
    header_content += "\tfloat VelocityDamping = 0.98f;\n\n"
    header_content += "public:\n"
    header_content += f"\tUFUNCTION(BlueprintCallable, Category = \"Flight\")\n"
    header_content += "\tvoid ToggleFlightMode();\n\n"
    header_content += f"\tUFUNCTION(BlueprintCallable, Category = \"Flight\")\n"
    header_content += "\tbool IsFlightModeEnabled() const { return bFlightModeEnabled; }\n\n"
    header_content += f"\tUFUNCTION(BlueprintCallable, Category = \"Flight|Input\")\n"
    header_content += "\tvoid ApplyThrust(float ThrustValue);\n\n"
    header_content += f"\tUFUNCTION(BlueprintCallable, Category = \"Flight|Input\")\n"
    header_content += "\tvoid ApplyStrafeX(float StrafeValue);\n\n"
    header_content += f"\tUFUNCTION(BlueprintCallable, Category = \"Flight|Input\")\n"
    header_content += "\tvoid ApplyStrafeY(float StrafeValue);\n\n"
    header_content += f"\tUFUNCTION(BlueprintCallable, Category = \"Flight|Input\")\n"
    header_content += "\tvoid ApplyStrafeZ(float StrafeValue);\n\n"
    header_content += f"\tUFUNCTION(BlueprintCallable, Category = \"Flight|Input\")\n"
    header_content += "\tvoid ApplyPitch(float PitchValue);\n\n"
    header_content += f"\tUFUNCTION(BlueprintCallable, Category = \"Flight|Input\")\n"
    header_content += "\tvoid ApplyYaw(float YawValue);\n\n"
    header_content += f"\tUFUNCTION(BlueprintCallable, Category = \"Flight|Input\")\n"
    header_content += "\tvoid ApplyRoll(float RollValue);\n\n"
    header_content += "protected:\n"
    header_content += f"\tvirtual void TickComponent(float DeltaTime, enum ETickType TickType, FActorComponentTickFunction* ThisTickFunction) override;\n\n"
    header_content += "private:\n"
    header_content += "\t// Accumulated rotation input (degrees per second)\n"
    header_content += "\tfloat CurrentPitchInput = 0.0f;\n\n"
    header_content += "\tfloat CurrentYawInput = 0.0f;\n\n"
    header_content += "\tfloat CurrentRollInput = 0.0f;\n\n"
    header_content += "\t// Accumulated thrust input (normalized -1 to 1)\n"
    header_content += "\tfloat CurrentThrustInput = 0.0f;\n\n"
    header_content += "\tfloat CurrentStrafeXInput = 0.0f;\n\n"
    header_content += "\tfloat CurrentStrafeYInput = 0.0f;\n\n"
    header_content += "\tfloat CurrentStrafeZInput = 0.0f;\n\n"
    header_content += "};\n"

    # Generate source with full implementation
    source_content = ""
    source_content += "// Generated by ProceduralGameGenerator\n"
    source_content += f'#include "{class_name}.h"\n'
    source_content += '#include "Components/SceneComponent.h"\n'
    source_content += '#include "GameFramework/Actor.h"\n'
    source_content += '#include "Math/UnrealMathFunctions.h"\n\n'
    source_content += f"U{class_name}::U{class_name}(const FObjectInitializer& ObjectInitializer)\n"
    source_content += "\t: Super(ObjectInitializer)\n"
    source_content += "{\n"
    source_content += "\tPrimaryComponentTick.bCanEverTick = true;\n"
    source_content += "}\n\n"
    source_content += f"void U{class_name}::ToggleFlightMode()\n"
    source_content += "{\n"
    source_content += "\tbFlightModeEnabled = !bFlightModeEnabled;\n"
    source_content += "\tif (bFlightModeEnabled && GetOwner())\n"
    source_content += "\t{\n"
    source_content += "\t\tif (USceneComponent* RootComp = GetOwner()->GetRootComponent())\n"
    source_content += "\t\t{\n"
    source_content += "\t\t\tRootComp->SetSimulatePhysics(true);\n"
    source_content += "\t\t\tGetOwner()->SetEnableGravity(false);\n"
    source_content += "\t\t}\n"
    source_content += "\t}\n"
    source_content += "}\n\n"
    source_content += f"void U{class_name}::ApplyThrust(float ThrustValue) {{ CurrentThrustInput = FMath::Clamp(ThrustValue, -1.0f, 1.0f); }}\n\n"
    source_content += f"void U{class_name}::ApplyStrafeX(float StrafeValue) {{ CurrentStrafeXInput = FMath::Clamp(StrafeValue, -1.0f, 1.0f); }}\n\n"
    source_content += f"void U{class_name}::ApplyStrafeY(float StrafeValue) {{ CurrentStrafeYInput = FMath::Clamp(StrafeValue, -1.0f, 1.0f); }}\n\n"
    source_content += f"void U{class_name}::ApplyStrafeZ(float StrafeValue) {{ CurrentStrafeZInput = FMath::Clamp(StrafeValue, -1.0f, 1.0f); }}\n\n"
    source_content += f"void U{class_name}::ApplyPitch(float PitchValue) {{ CurrentPitchInput = FMath::Clamp(PitchValue, -1.0f, 1.0f); }}\n\n"
    source_content += f"void U{class_name}::ApplyYaw(float YawValue) {{ CurrentYawInput = FMath::Clamp(YawValue, -1.0f, 1.0f); }}\n\n"
    source_content += f"void U{class_name}::ApplyRoll(float RollValue) {{ CurrentRollInput = FMath::Clamp(RollValue, -1.0f, 1.0f); }}\n\n"
    source_content += f"void U{class_name}::TickComponent(float DeltaTime, enum ETickType TickType, FActorComponentTickFunction* ThisTickFunction)\n"
    source_content += "{\n"
    source_content += "\tSuper::TickComponent(DeltaTime, TickType, ThisTickFunction);\n"
    source_content += "\tif (!bFlightModeEnabled || !GetOwner()) return;\n"
    source_content += "\tUActor* Owner = GetOwner();\n"
    source_content += "\tif (UPrimitiveComponent* PrimComp = Owner->GetRootPrimitiveComponent())\n"
    source_content += "\t{\n"
    source_content += "\t\tFVector CurrentLinVel = PrimComp->GetLinearVelocity();\n"
    source_content += "\t\tCurrentLinVel *= VelocityDamping;\n"
    source_content += "\t\tFVector ThrustDir = Owner->GetActorForwardVector() * CurrentThrustInput * ThrustPower * DeltaTime;\n"
    source_content += "\t\tCurrentLinVel += ThrustDir;\n"
    source_content += "\t\tCurrentLinVel += Owner->GetActorRightVector() * CurrentStrafeXInput * ThrustPower * DeltaTime;\n"
    source_content += "\t\tCurrentLinVel += Owner->GetActorUpVector() * CurrentStrafeZInput * ThrustPower * DeltaTime;\n"
    source_content += "\t\tPrimComp->SetLinearVelocity(CurrentLinVel, false);\n"
    source_content += "\t\tFVector CurrentAngVel = PrimComp->GetAngularVelocity();\n"
    source_content += "\t\tfloat AngVelScale = RotationSpeed * 100.0f;\n"
    source_content += "\t\tCurrentAngVel.X = CurrentPitchInput * AngVelScale;\n"
    source_content += "\t\tCurrentAngVel.Y = CurrentYawInput * AngVelScale;\n"
    source_content += "\t\tCurrentAngVel.Z = CurrentRollInput * AngVelScale;\n"
    source_content += "\t\tif (FMath::Abs(CurrentPitchInput) < 0.01f && FMath::Abs(CurrentYawInput) < 0.01f && FMath::Abs(CurrentRollInput) < 0.01f)\n"
    source_content += "\t\t{\n"
    source_content += "\t\t\tCurrentAngVel *= (1.0f - AngularDampingWhenIdle * DeltaTime);\n"
    source_content += "\t\t}\n"
    source_content += "\t\tPrimComp->SetAngularVelocity(CurrentAngVel, false);\n"
    source_content += "\t}\n"
    source_content += "\tCurrentThrustInput = 0.0f;\n"
    source_content += "\tCurrentStrafeXInput = 0.0f;\n"
    source_content += "\tCurrentStrafeYInput = 0.0f;\n"
    source_content += "\tCurrentStrafeZInput = 0.0f;\n"
    source_content += "\tCurrentPitchInput = 0.0f;\n"
    source_content += "\tCurrentYawInput = 0.0f;\n"
    source_content += "\tCurrentRollInput = 0.0f;\n"
    source_content += "}\n"

    header_path = os.path.join(GameConfiguration.source_dir(), f"{class_name}.h")
    with open(header_path, 'w', encoding='utf-8') as f:
        f.write(header_content)

    source_path = os.path.join(GameConfiguration.source_dir(), f"{class_name}.cpp")
    with open(source_path, 'w', encoding='utf-8') as f:
        f.write(source_content)

    return header_path, source_path


def generate_level_generator_component():
    """Generate the level generator C++ component for procedural levels."""
    # Generate header
    header_path = generate_cpp_header_file(
        class_name="LevelGeneratorComponent",
        base_class="UActorComponent",
        includes=["CoreMinimal.h", "GameFramework/Actor.h", "Engine/World.h"]
    )

    # Generate source
    source_path = generate_cpp_source_file(
        class_name="LevelGeneratorComponent",
        includes=["LevelGeneratorComponent.h"]
    )

    return header_path, source_path


def generate_all_cpp_components():
    """Generate all C++ components for the procedural generation system."""
    print("Generating C++ generator components...")
    
    # Generate main procedural generator component
    pg_header, pg_source = generate_procedural_generator_component()
    print(f"Generated: ProceduralGeneratorComponent ({pg_header}, {pg_source})")
    
    # Generate vehicle spawner component
    vs_header, vs_source = generate_vehicle_spawner_component()
    print(f"Generated: VehicleSpawnerComponent ({vs_header}, {vs_source})")
    
    # Generate level generator component
    lg_header, lg_source = generate_level_generator_component()
    print(f"Generated: LevelGeneratorComponent ({lg_header}, {lg_source})")
    
    # Generate flight control component (6DOF spaceship movement)
    fc_header, fc_source = generate_flight_control_component()
    print(f"Generated: FlightControlComponent ({fc_header}, {fc_source})")
