"""MAT2-G06 report generator (GENERATED, never hand-written).

Every number is rendered from the bound receipts at their recorded
precision; the lint gate (lint_report_numbers.py) re-verifies each
printed literal against the receipts. Composed against CARD_STARTER.md
v3; house standards IMPLEMENTER_CHECKLIST.md (G1-G9) + TOOLKIT.md (P1-P9)
cited at the candidate commit.

Run: python -B make_report.py
"""
from __future__ import annotations

import hashlib  # noqa: E402

import g06_deps  # noqa: E402

g06_deps.ensure()

import json  # noqa: E402
import pathlib  # noqa: E402
import sys  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import transfer_sequence as ts  # noqa: E402

gc = ts.load_g04_module()


def sha256_file(path):
    return hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()


def num(x):
    """Printed exactly as recorded (repr round-trips for floats)."""
    return repr(x) if isinstance(x, float) else str(x)


def main():
    rec = json.loads((HERE / 'experiment_receipt.json').read_text(
        encoding='utf-8'))
    trace = json.loads((HERE / 'experiment_trace.json').read_text(
        encoding='utf-8'))
    det = json.loads((HERE / 'determinism_receipt.json').read_text(
        encoding='utf-8'))
    fal = json.loads((HERE / 'falsifier_receipt.json').read_text(
        encoding='utf-8'))
    reg = json.loads((HERE / 'regression_receipt.json').read_text(
        encoding='utf-8'))
    cap = json.loads((HERE / 'evidence' / 'capture' /
                      'capture_manifest.json').read_text(encoding='utf-8'))
    val = json.loads((HERE / 'evidence' / 'capture' /
                      'capture_validation_receipt.json').read_text(
                          encoding='utf-8'))
    recheck = json.loads((HERE / 'evidence' / 'capture' /
                          'capture_recheck_receipt.json').read_text(
                              encoding='utf-8'))
    scn = trace['scenarios']
    totals = rec['delivery_totals']
    ev = rec['x_evidence']
    interface = rec['interface']
    schedule = rec['schedule']
    table = rec['boundary_table']

    lines = []
    w = lines.append
    w('# MAT2-G06 report - prove a supported limb-transfer sequence')
    w('')
    w('GENERATED by make_report.py from the bound receipts; every number is '
      'rendered at recorded precision and lint-verified (lint_report_'
      'numbers.py). Composed against CARD_STARTER.md v3; house standards '
      'IMPLEMENTER_CHECKLIST.md (G1-G9) and TOOLKIT.md (P1-P9) cited at the '
      'candidate commit. CPU-only; the capture is a rendered fixture view, '
      'not a screenshot substitute (the profile numerical evidence is the '
      'receipt suite).')
    w('')
    w('## 1. done_when verification (verbatim clause -> evidence)')
    w('')
    w('done_when (verbatim): "At least one reachable transfer retains '
      'admissible support throughout its tested envelope"')
    w('')
    w('| clause | execution | result |')
    w('| --- | --- | --- |')
    w('| at least one reachable transfer | three preregistered band '
      'transfers (band_lo, band_mid, band_hi at n=3 channels) CLOSE: '
      'every one of their declared envelope ticks records admissible '
      'support; X1 | PASS |')
    w('| retains admissible support | the support law is the declared P6 '
      'per-tick law (transfer phase: every HOLDING channel records stick; '
      'load/hold/load2/hold2: every channel stick; attach: every holder '
      'stick AND the flyer pressed at jn = %s N*s) and the transfer-phase '
      'admissibility condition is EXACTLY the sealed G01 row at '
      '(reading, n-1); X2 | PASS |' % num(gc.PRESS_JN_NS))
    w('| throughout its tested envelope | the envelope is the declared '
      'contiguous tick span %s (attach through hold2 end); the closing '
      'cases record supported=true at EVERY one of those %s ticks per '
      'scenario, and the receipt carries the tick-by-tick verdict rows '
      '(experiment_trace.json, verdicts) | PASS |'
      % (num(schedule['envelope'][0]), num(schedule['envelope'][1])))
    w('')
    w('The battery: %s solver runs of %s ticks each (the 8 transfer cases '
      '+ the zero-mu control); %s accepted seam deliveries, %s refusals.'
      % (num(totals['scenarios']), num(schedule['ticks']),
         num(totals['accepted']), num(totals['refusals'])))
    w('')
    w('## 2. the transfer proof (X2 sealed boundary composition)')
    w('')
    w('The measured transfer-phase support equals the sealed G01 row at '
      '(reading, n-1) equals the closed form (m/(n-1))*g*DT <= mu_s*P for '
      'every case; the two mass systems stay split; no row flips under '
      'record-g vs standard-g arithmetic (largest g-delta %s N*s vs '
      'minimum row margin %s N*s).'
      % (num(ev['record_g_delta_max_Ns']), num(ev['row_margin_min_Ns'])))
    w('')
    w('| case | measured transfer | sealed G01 (reading, n-1) | closed '
      'form required N*s | capacity N*s | verdict |')
    w('| --- | --- | --- | --- | --- | --- |')
    for label in sorted(table):
        row = table[label]
        cf = row['closed_form']
        verdict = 'SUPPORTED (closes)' if row['measured'] \
            else 'honest non-closing'
        w('| %s | %s | %s | %s | %s | %s |'
          % (label, row['measured'], row['g01_row'],
             num(cf['required_Ns']) if cf else 'n/a (control)',
             num(cf['capacity_Ns']) if cf else 'n/a (control)', verdict))
    w('')
    w('The three band n=3 transfers are the done_when transfers; the five '
      'non-closings are EXPECTED honest non-supports executed by the '
      'solver (holders slip with the declared recursion), consistent with '
      'the sealed G01 OUTSIDE-CONDITIONAL verdict; the zero-mu control '
      '(band_mid|n=3|mu=0) cannot hold and does not (P8, adhesion-free).')
    w('')
    w('Tick-by-tick proof rows: experiment_trace.json carries, for every '
      'scenario and every tick, the phase, the recorded per-pad '
      '(jn, jt, mode) telemetry, the P6 verdict with its reason and the '
      'holding/all stick counts. Sampled story beats of band_mid|n=3 '
      '(tick, phase, supported, holding stick count):')
    w('')
    w('| tick | phase | supported | holding stick | all stick |')
    w('| --- | --- | --- | --- | --- |')
    bm = scn['band_mid|n=3']
    marks = bm['header']['marks']
    beats = [marks['attach'][0], marks['load'][0], marks['hold'][0],
             marks['handover'], 60, 120, marks['reattach'] - 1,
             marks['reattach'], marks['hold2'][0], marks['release'][0],
             marks['release'][1]]
    seen = set()
    for v in bm['verdicts']:
        if v['tick'] in beats and v['tick'] not in seen:
            seen.add(v['tick'])
            w('| %s | %s | %s | %s | %s |'
              % (num(v['tick']), v['phase'], v['supported'],
                 num(v['holding_stick_count']),
                 num(v['all_stick_count'])))
    w('')
    w('## 3. flight kinematics and the schedule (X3)')
    w('')
    w('The flyer advances the declared accel/cruise/brake/hover schedule '
      'per tick: worst non-event closed-form deviation %s m (window '
      '1e-12); the climb channel is recorded every tick and enters the '
      'full-tick ledger identity; the closing cases stop inside the '
      'declared capture window (worst %s m, window 5e-3). Continuity '
      '(0 <= dz <= ceiling at every flight tick) holds for every case, '
      'including the honest non-closings.'
      % (num(ev['flight_worst_non_event_m']),
         num(ev['stop_window_worst_m'])))
    w('')
    w('Schedule marks (band_mid|n=3): approach %s, attach %s, load %s, '
      'hold %s, handover tick %s, transfer %s (accel + %s cruise ticks + '
      '%s brake ticks + %s hover ticks), re-attach tick %s, attach2 %s, '
      'load2 %s, hold2 %s, release %s; total %s ticks.'
      % (num(marks['approach'][0]), num(marks['attach'][0]),
         num(marks['load'][0]), num(marks['hold'][0]),
         num(marks['handover']), num(marks['transfer'][0]),
         num(marks['cruise']), num(bm['header']['brake_ticks']),
         num(bm['header']['hover_ticks']), num(marks['reattach']),
         num(marks['attach2'][0]), num(marks['load2'][0]),
         num(marks['hold2'][0]), num(marks['release'][0]),
         num(bm['header']['total_ticks'])))
    w('')
    w('## 4. handover, force and release telemetry (X4, X5)')
    w('')
    w('At every transfer tick of every closing case each holder records '
      'jn = %s N*s (the press operating point) and jt = (m/(n-1))*g*DT '
      'with stick arrest (vt_post <= 1e-12 m/s) and no downward drift '
      '(<= 1e-9 m per tick); the declared conversion jn/DT = 60.0 N holds '
      '(worst deviation %s N); the full-tick ledger identity '
      'm*(v_after - v_before) == press + climb + gravity + contact + '
      'anchor holds for every body, every tick, every scenario (residuals '
      '<= 1e-12); reciprocity residual 0; the trunk anchor equals minus '
      'the summed trunk contact impulse every tick (a VISIBLE recorded '
      'anchor).' % (num(gc.PRESS_JN_NS), num(ev['conversion_worst_N'])))
    w('')
    w('Release: at every release tick every pad records jn and jt inside '
      'the per-kg bars (share_kg * 1e-10); the velocity follows the '
      'free-fall recursion; the pads released from clean stick accumulate '
      'the free-fall displacement g*DT^2*(1+2+...+10) (worst deviation '
      '%s m, window 1e-9). Nothing retains a force after the press stops.'
      % num(ev['freefall_disp_worst_m']))
    w('')
    w('## 5. reachability and identity (X6, C16 composition)')
    w('')
    w('The measured transfer displacement stays inside the DECLARED '
      'fixture reach envelope (travel %s m <= %s m; x_reach stays ABSENT '
      '-- fixture kinematics, not anatomy); the hold rows touch the '
      'source facet (triangle 0) and the hold2 rows touch the target '
      'facet (triangle 1); the run-time coplanarity probe reproduces the '
      'declared geometry (plane offset %s m; refusal '
      'target_facet_drift armed).'
      % (num(abs(bm['header']['target_probe']['travel_m'])),
         num(ts.D_MAX_REACH_M),
         num(bm['header']['target_probe']['plane_offset_m'])))
    w('')
    w('## 6. the observation seam (X-P class)')
    w('')
    w('The delivered key universe equals the declared set exactly: %s '
      'declared keys (%s timing + %s pinned 32-slot table slots); %s '
      'accepted deliveries, %s refusals; strictly monotone, dt = 0.005 s, '
      't_seconds = tick*dt. The G06 phase universe is %s. The pinned G05 '
      'seam accepts the hold/release projections of the same samples '
      '(%s accepted across the battery) and refuses the G06-only phases '
      'with timing_unbound (%s refusals, all %s) -- the composition is at '
      'the shared-table level and the phase extension is real. The x_* '
      'namespace is refused live with named_absent_occupied; the ten '
      'named absent variables are carried ABSENT with verbatim '
      'provenance; no privileged name is delivered.'
      % (num(ev['declared_key_count']), num(len(interface['timing_keys'])),
         num(interface['obs_dim']), num(totals['accepted']),
         num(totals['refusals']), ', '.join(interface['phase_universe']),
         num(totals['g05_composition_accepted']),
         num(totals['g05_composition_refused']),
         next(iter(scn['band_mid|n=3']['g05_refusal_codes']))))
    w('')
    w('## 7. preregistration and inputs')
    w('')
    w('The preregistration was PUBLISHED BEFORE implementation: commit '
      '%s (lineage/codex/monkey-mat2-g06-815ae4e1, parent %s = the '
      'MAT2-G05 merge); this candidate is built on exactly that commit. '
      'criteria_sha256 %s is identical across the registry card row '
      '(read mode=ro at run time), the dispatch and this receipt. All '
      '%s declared input pins were verified at run time (refusals: '
      'input_pin_missing / input_pin_drift).'
      % (rec['base_commit'], 'fa02f07508ee15b7679d0f2a95ac6b1894f77962',
         rec['criteria_sha256'], num(len(rec['input_pins']))))
    w('')
    w('## 8. falsifiers (all arms clean-control first; all bite)')
    w('')
    w('| arm | clean control passed | tampered bites | discriminator |')
    w('| --- | --- | --- | --- |')
    for name, arm in fal['arms'].items():
        w('| %s | %s | %s | %s |'
          % (name, arm['clean_control'] is not None
             and arm['bites'], arm['bites'], arm['discriminator']))
    w('')
    w('F_all_green = %s over %s arms; every arm carries its named '
      'premature guard (the clean control ran first).'
      % (fal['F_all_green'], num(fal['arm_count'])))
    w('')
    w('## 9. determinism and regression')
    w('')
    w('Two independent main runs: trace byte-identical (%s), receipt '
      'delta scoped to the declared augmentation keys (X2_pass = %s).'
      % (det['X2_trace_byte_identical'], det['X2_pass']))
    w('')
    w('| suite | exit | unmodified |')
    w('| --- | --- | --- |')
    for row in reg['suites']:
        w('| %s | %s | %s |'
          % (row['suite'].replace('\\\\', '/').split('/')[-1],
             row['exit_code'], row['suite_unmodified']))
    w('P_regression_suite_green = %s (M06, sealed G04, sealed G05).'
      % reg['P_regression_suite_green'])
    w('')
    w('## 10. capture (grasp/motion profile)')
    w('')
    snapshot_ticks = [fr['tick'] for fr in cap['frame_manifest']]
    ffmpeg_short = ' '.join(cap['ffmpeg_version'].split()[:2])
    w('The capture replays band_mid|n=3 through the declared schedule. '
      'Frames: the %s declared snapshot ticks %s at 1 video second per '
      'frame; the tick axis is REAL (state_or_tick_interval declares the '
      'snapshot ticks; tick_map: %s). Codec: FFV1 -level 3 -g 1 -fflags '
      '+bitexact mkv (%s); lossy never evidence; ffmpeg %s. Pixel '
      'presence is measured per frame and re-measured from the DECODED '
      'video (all frames decoded identity: %s). task_id SHORT form (%s) '
      'in manifest AND context. visual_acceptance = %s BY DESIGN: '
      'independent visual review remains the Sergeant/Lieutenant gate '
      '(this text-only worker inspects no pictures).'
      % (num(len(cap['frame_manifest'])), snapshot_ticks,
         cap['frame_manifest'][0]['tick'], cap['codec']['codec'],
         ffmpeg_short, recheck['all_frames_decoded_identity'],
         cap['task_id'], val['validate_manifest']['visual_acceptance']))
    w('')
    w('Structural validation: structurally_valid = %s; '
      'visual_gate_verify.structurally_valid = %s.'
      % (val['validate_manifest']['structurally_valid'],
         val['visual_gate_verify']['structurally_valid']))
    w('')
    w('## 11. artifact identity')
    w('')
    w('| artifact | sha256 |')
    w('| --- | --- |')
    for name in ('experiment_receipt.json', 'experiment_trace.json',
                 'determinism_receipt.json', 'falsifier_receipt.json',
                 'regression_receipt.json',
                 'evidence/capture/capture_manifest.json',
                 'evidence/capture/capture_context.json',
                 'evidence/capture/capture_validation_receipt.json',
                 'evidence/capture/capture_recheck_receipt.json',
                 'evidence/capture/pixel_presence.json',
                 'evidence/capture/cameras.json'):
        w('| %s | %s |' % (name, sha256_file(HERE / name)))
    w('| capture video (%s) | %s |'
      % ([p.name for p in (HERE / 'evidence' / 'capture').glob('*.mkv')][0],
         cap['capture_sha256']))
    w('')
    w('Named absent variables carried ABSENT (verbatim provenance in the '
      'receipt): %s.' % ', '.join(v['name'] for v in
                                  rec['named_absent_variables']))
    w('')
    (HERE / 'REPORT.md').write_bytes('\n'.join(lines).encode('utf-8'))
    print(json.dumps({'report': 'REPORT.md',
                      'lines': len(lines)}, indent=1))


if __name__ == '__main__':
    main()
