// Generated by GameCodeGenerator
#include "ATool_Shovel.h"

ATool_Shovel::ATool_Shovel()
{
	PrimaryActorTick.bCanEverTick = false;

	MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComponent"));
	RootComponent = MeshComponent;

	ToolCategory = FName(TEXT("Shovel"));
	Durability = 100.0f;
	DigRadius = 50.0f;
	DigDepth = 10.0f;

	static ConstructorHelpers::FObjectFinder<UStaticMesh> MeshFinder(TEXT("/Game/Tools/Geometry/SM_Shovel.SM_Shovel"));
	if (MeshFinder.Succeeded())
	{
		MeshComponent->SetStaticMesh(MeshFinder.Object);
	}

	static ConstructorHelpers::FObjectFinder<UMaterialInterface> MaterialFinder(TEXT("/Game/Tools/Materials/MAT_ShovelHandle.MAT_ShovelHandle"));
	if (MaterialFinder.Succeeded())
	{
		MeshComponent->SetMaterial(0, MaterialFinder.Object);
	}
}

void ATool_Shovel::BeginPlay()
{
	Super::BeginPlay();
}