// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "ATool_Weapon.generated.h"

UCLASS()
class CHIMERA_API ATool_Weapon : public AActor
{
	GENERATED_BODY()

public:
	ATool_Weapon();

	UPROPERTY(VisibleAnywhere, Category = "Tool", meta = (AllowPrivateAccess = "true"))
	UStaticMeshComponent* MeshComponent;

	UPROPERTY(EditDefaultsOnly, Category = "Tool")
	FName ToolCategory;

	UPROPERTY(EditDefaultsOnly, Category = "Tool", meta = (ClampMin = "0"))
	float Durability;

	UPROPERTY(EditDefaultsOnly, Category = "Weapon")
	float BaseDamage;

	UPROPERTY(EditDefaultsOnly, Category = "Weapon")
	float FireRate;

	UPROPERTY(EditDefaultsOnly, Category = "Weapon")
	float Range;

protected:
	virtual void BeginPlay() override;
};