// Generated by GameCodeGenerator
#include "ATool_Scanner.h"
#include "ToolScannerComponent.h"
#include "EngineUtils.h" // TActorIterator

ATool_Scanner::ATool_Scanner()
{
	PrimaryActorTick.bCanEverTick = true;

	BodyMeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("BodyMeshComponent"));
	RootComponent = BodyMeshComponent;

	LensMeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("LensMeshComponent"));
	LensMeshComponent->SetupAttachment(RootComponent);
	LensMeshComponent->SetRelativeLocation(FVector(14.0f, 0.0f, 0.0f));

	// H-34: the scanner's behaviour component, attached at construction (was a
	// component class with zero spawners — the Verb_Shovel battery's red atom).
	ScannerComponent = CreateDefaultSubobject<UToolScannerComponent>(TEXT("ScannerComponent"));

	ToolCategory = FName(TEXT("Scanner"));
	Durability = 100.0f;
	ScanRadius = 500.0f;
	ScanTime = 2.0f;

	static ConstructorHelpers::FObjectFinder<UStaticMesh> BodyMeshFinder(TEXT("/Game/Tools/Geometry/SM_ScannerBody.SM_ScannerBody"));
	if (BodyMeshFinder.Succeeded())
	{
		BodyMeshComponent->SetStaticMesh(BodyMeshFinder.Object);
	}

	static ConstructorHelpers::FObjectFinder<UStaticMesh> LensMeshFinder(TEXT("/Game/Tools/Geometry/SM_ScannerLens.SM_ScannerLens"));
	if (LensMeshFinder.Succeeded())
	{
		LensMeshComponent->SetStaticMesh(LensMeshFinder.Object);
	}

	static ConstructorHelpers::FObjectFinder<UMaterialInterface> BodyMaterialFinder(TEXT("/Game/Tools/Materials/MAT_ScannerBody.MAT_ScannerBody"));
	if (BodyMaterialFinder.Succeeded())
	{
		BodyMeshComponent->SetMaterial(0, BodyMaterialFinder.Object);
	}

	static ConstructorHelpers::FObjectFinder<UMaterialInterface> LensMaterialFinder(TEXT("/Game/Tools/Materials/MAT_ScannerLens.MAT_ScannerLens"));
	if (LensMaterialFinder.Succeeded())
	{
		LensMeshComponent->SetMaterial(0, LensMaterialFinder.Object);
	}
}

void ATool_Scanner::BeginPlay()
{
	Super::BeginPlay();
}

bool ATool_Scanner::Scan()
{
	if (!GetWorld() || Durability <= 0.0f || ScanRadius <= 0.0f)
	{
		return false;
	}

	// Perform range query to find all actors within scan radius
	const FVector ScanLocation = GetActorLocation();
	int32 ActorCount = 0;
	FString DetectedActors;

	for (TActorIterator<AActor> ActorItr(GetWorld()); ActorItr; ++ActorItr)
	{
		AActor* TestActor = *ActorItr;
		if (!TestActor || TestActor == this || TestActor == GetOwner())
		{
			continue;
		}

		float Distance = FVector::Dist(ScanLocation, TestActor->GetActorLocation());
		if (Distance <= ScanRadius)
		{
			ActorCount++;
			if (ActorCount <= 5)  // Log first 5 detections
			{
				DetectedActors += FString::Printf(TEXT("%s (%.1f uu) | "), *TestActor->GetName(), Distance);
			}
		}
	}

	// Reduce durability
	Durability = FMath::Max(0.0f, Durability - 1.0f);

	UE_LOG(LogTemp, Log, TEXT("ATool_Scanner::Scan -> detected %d actors within %.1f uu radius (durability %.1f). Samples: %s"),
		ActorCount, ScanRadius, Durability, *DetectedActors);

	return true;
}