// Generated by GameCodeGenerator
#pragma warning(disable: 5038)
#pragma warning(disable: 4996)
#include "ATool_Weapon.h"
#include "Engine/World.h"
#include "CollisionQueryParams.h"

ATool_Weapon::ATool_Weapon()
{
	PrimaryActorTick.bCanEverTick = true;

	MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComponent"));
	RootComponent = MeshComponent;

	ToolCategory = FName(TEXT("Weapon"));
	Durability = 100.0f;
	BaseDamage = 25.0f;
	FireRate = 0.5f;
	Range = 1000.0f;

	static ConstructorHelpers::FObjectFinder<UStaticMesh> MeshFinder(TEXT("/Game/Tools/Geometry/SM_Weapon.SM_Weapon"));
	if (MeshFinder.Succeeded())
	{
		MeshComponent->SetStaticMesh(MeshFinder.Object);
	}

	static ConstructorHelpers::FObjectFinder<UMaterialInterface> MaterialFinder(TEXT("/Game/Tools/Materials/MAT_WeaponBody.MAT_WeaponBody"));
	if (MaterialFinder.Succeeded())
	{
		MeshComponent->SetMaterial(0, MaterialFinder.Object);
	}
}

void ATool_Weapon::BeginPlay()
{
	Super::BeginPlay();
}

bool ATool_Weapon::Fire()
{
	if (!GetWorld() || Durability <= 0.0f || Range <= 0.0f)
	{
		return false;
	}

	// Fire in the direction the weapon is facing
	const FVector FireStart = GetActorLocation();
	const FVector FireDirection = GetActorForwardVector();
	const FVector FireEnd = FireStart + FireDirection * Range;

	FHitResult Hit;
	FCollisionQueryParams Params(SCENE_QUERY_STAT(WeaponFire), true, this);

	// Query for pawns/characters in the fire direction
	bool bHit = GetWorld()->LineTraceSingleByChannel(Hit, FireStart, FireEnd, ECC_Pawn, Params);

	// Reduce durability
	Durability = FMath::Max(0.0f, Durability - 1.0f);

	if (bHit && Hit.GetActor())
	{
		// Log hit
		UE_LOG(LogTemp, Log, TEXT("ATool_Weapon::Fire -> hit %s at distance %.1f uu (damage %.1f, durability %.1f)"),
			*Hit.GetActor()->GetName(), Hit.Distance, BaseDamage, Durability);
		return true;
	}
	else
	{
		UE_LOG(LogTemp, Log, TEXT("ATool_Weapon::Fire -> no target in range %.1f uu (durability %.1f)"),
			Range, Durability);
		return false;
	}
}