// Generated by GameCodeGenerator
#pragma warning(disable: 5038)
#pragma warning(disable: 4996)
#include "ATool_Shovel.h"
#include "Components/DecalComponent.h"
#include "Materials/Material.h"
#include "Engine/World.h"
#include "CollisionQueryParams.h"
#include "GameFramework/PlayerController.h"
#include "SandSoundComponent.h"
#include "DustAccumulationParticleComponent.h"

ATool_Shovel::ATool_Shovel()
{
	PrimaryActorTick.bCanEverTick = false;

	MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComponent"));
	RootComponent = MeshComponent;

	ToolCategory = FName(TEXT("Shovel"));
	Durability = 100.0f;
	DigRadius = 50.0f;
	DigDepth = 10.0f;

	static ConstructorHelpers::FObjectFinder<UStaticMesh> MeshFinder(TEXT("/Game/Tools/Geometry/SM_Shovel.SM_Shovel"));
	if (MeshFinder.Succeeded())
	{
		MeshComponent->SetStaticMesh(MeshFinder.Object);
	}

	static ConstructorHelpers::FObjectFinder<UMaterialInterface> MaterialFinder(TEXT("/Game/Tools/Materials/MAT_ShovelHandle.MAT_ShovelHandle"));
	if (MaterialFinder.Succeeded())
	{
		MeshComponent->SetMaterial(0, MaterialFinder.Object);
	}
}

void ATool_Shovel::BeginPlay()
{
	Super::BeginPlay();
}

bool ATool_Shovel::Dig()
{
	if (!GetWorld() || Durability <= 0.0f)
	{
		return false;
	}

	const FVector Start = GetActorLocation() + FVector(0.0f, 0.0f, 50.0f);
	const FVector End = Start + FVector(0.0f, 0.0f, -(DigDepth + 100.0f));
	FHitResult Hit;
	FCollisionQueryParams Params(SCENE_QUERY_STAT(ShovelDig), true, this);

	if (!GetWorld()->LineTraceSingleByChannel(Hit, Start, End, ECC_Visibility, Params) || !Hit.bBlockingHit)
	{
		return false;
	}

	AActor* SearchRoot = GetOwner() ? GetOwner() : this;
	if (!SearchRoot->FindComponentByClass<UDustAccumulationParticleComponent>())
	{
		if (APlayerController* PC = GetWorld()->GetFirstPlayerController())
		{
			if (AActor* Pawn = PC->GetPawn())
			{
				SearchRoot = Pawn;
			}
		}
	}

	if (UDustAccumulationParticleComponent* Dust = SearchRoot->FindComponentByClass<UDustAccumulationParticleComponent>())
	{
		const int32 ParticleCount = FMath::Clamp(FMath::RoundToInt(DigRadius / 5.0f), 4, 64);
		Dust->EmitDustAtLocation(Hit.ImpactPoint, ParticleCount);
	}

	if (USandSoundComponent* Sand = SearchRoot->FindComponentByClass<USandSoundComponent>())
	{
		Sand->PlayImpactSound(Hit.ImpactPoint);
	}

	if (UMaterial* DefaultDecal = UMaterial::GetDefaultMaterial(EMaterialDomain::MD_DeferredDecal))
	{
		if (UDecalComponent* Decal = NewObject<UDecalComponent>(this))
		{
			Decal->SetWorldLocationAndRotation(Hit.ImpactPoint, Hit.ImpactNormal.Rotation());
			Decal->DecalSize = FVector(DigRadius, DigRadius, DigRadius * 0.5f);
			Decal->SetMaterial(0, DefaultDecal);
			Decal->RegisterComponent();
		}
	}

	Durability = FMath::Max(0.0f, Durability - 1.0f);

	UE_LOG(LogTemp, Log, TEXT("ATool_Shovel::Dig -> impact %s (durability %.1f)"),
		*Hit.ImpactPoint.ToString(), Durability);
	return true;
}
