// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "ATool_Scanner.generated.h"

UCLASS()
class CHIMERA_API ATool_Scanner : public AActor
{
	GENERATED_BODY()

public:
	ATool_Scanner();

	UPROPERTY(VisibleAnywhere, Category = "Tool", meta = (AllowPrivateAccess = "true"))
	UStaticMeshComponent* BodyMeshComponent;

	UPROPERTY(VisibleAnywhere, Category = "Tool", meta = (AllowPrivateAccess = "true"))
	UStaticMeshComponent* LensMeshComponent;

	UPROPERTY(EditDefaultsOnly, Category = "Tool")
	FName ToolCategory;

	UPROPERTY(EditDefaultsOnly, Category = "Tool", meta = (ClampMin = "0"))
	float Durability;

	UPROPERTY(EditDefaultsOnly, Category = "Tool")
	float ScanRadius;

	UPROPERTY(EditDefaultsOnly, Category = "Tool")
	float ScanTime;

	UFUNCTION(BlueprintCallable, Category = "Tool")
	bool Scan();

protected:
	virtual void BeginPlay() override;
};