// Generated by GameCodeGenerator
#include "ATool_Scanner.h"

ATool_Scanner::ATool_Scanner()
{
	PrimaryActorTick.bCanEverTick = true;

	BodyMeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("BodyMeshComponent"));
	RootComponent = BodyMeshComponent;

	LensMeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("LensMeshComponent"));
	LensMeshComponent->SetupAttachment(RootComponent);
	LensMeshComponent->SetRelativeLocation(FVector(14.0f, 0.0f, 0.0f));

	ToolCategory = FName(TEXT("Scanner"));
	Durability = 100.0f;
	ScanRadius = 500.0f;
	ScanTime = 2.0f;

	static ConstructorHelpers::FObjectFinder<UStaticMesh> BodyMeshFinder(TEXT("/Game/Tools/Geometry/SM_ScannerBody.SM_ScannerBody"));
	if (BodyMeshFinder.Succeeded())
	{
		BodyMeshComponent->SetStaticMesh(BodyMeshFinder.Object);
	}

	static ConstructorHelpers::FObjectFinder<UStaticMesh> LensMeshFinder(TEXT("/Game/Tools/Geometry/SM_ScannerLens.SM_ScannerLens"));
	if (LensMeshFinder.Succeeded())
	{
		LensMeshComponent->SetStaticMesh(LensMeshFinder.Object);
	}

	static ConstructorHelpers::FObjectFinder<UMaterialInterface> BodyMaterialFinder(TEXT("/Game/Tools/Materials/MAT_ScannerBody.MAT_ScannerBody"));
	if (BodyMaterialFinder.Succeeded())
	{
		BodyMeshComponent->SetMaterial(0, BodyMaterialFinder.Object);
	}

	static ConstructorHelpers::FObjectFinder<UMaterialInterface> LensMaterialFinder(TEXT("/Game/Tools/Materials/MAT_ScannerLens.MAT_ScannerLens"));
	if (LensMaterialFinder.Succeeded())
	{
		LensMeshComponent->SetMaterial(0, LensMaterialFinder.Object);
	}
}

void ATool_Scanner::BeginPlay()
{
	Super::BeginPlay();
}