// Generated by GameCodeGenerator
#pragma warning(disable: 5038)
#pragma warning(disable: 4996)
#include "ToolScannerComponent.h"
#include "GameFramework/Actor.h"
#include "Kismet/GameplayStatics.h"
#include "EngineUtils.h" // TActorIterator

UToolScannerComponent::UToolScannerComponent()
{
	PrimaryComponentTick.bCanEverTick = true;
	ScanRange = 500.0f;
	ScanInterval = 1.0f;
	LastScanTime = 0.0f;
}

void UToolScannerComponent::BeginPlay()
{
	Super::BeginPlay();
}

void UToolScannerComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	LastScanTime += DeltaTime;
	if (LastScanTime >= ScanInterval)
	{
		LastScanTime = 0.0f;

		// Perform auto-scan: query actors in range and log findings
		if (AActor* Owner = GetOwner())
		{
			const FVector ScanLocation = Owner->GetActorLocation();
			int32 DetectionCount = 0;

			if (UWorld* World = GetWorld())
			{
				for (TActorIterator<AActor> ActorItr(World); ActorItr; ++ActorItr)
				{
					AActor* TestActor = *ActorItr;
					if (!TestActor || TestActor == Owner)
					{
						continue;
					}

					float Distance = FVector::Dist(ScanLocation, TestActor->GetActorLocation());
					if (Distance <= ScanRange)
					{
						DetectionCount++;
					}
				}

				UE_LOG(LogTemp, Log, TEXT("ToolScannerComponent::AutoScan -> detected %d actors within range %.1f uu (interval %.1f s)"),
					DetectionCount, ScanRange, ScanInterval);
			}
		}
	}
}

void UToolScannerComponent::ScanActor(AActor* TargetActor)
{
	if (!TargetActor) return;

	UE_LOG(LogTemp, Display, TEXT("ToolScanner: Scanning actor %s"), *TargetActor->GetName());
	// Scan implementation: gather data, update UI, trigger interactions
}

float UToolScannerComponent::GetScanDistance() const
{
	return ScanRange;
}
