// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "ToolScannerComponent.generated.h"

UCLASS( ClassGroup=(Custom), meta=(BlueprintType, Category = "Tools") )
class CHIMERA_API UToolScannerComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UToolScannerComponent();

protected:
	virtual void BeginPlay() override;

public:
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	UFUNCTION(BlueprintCallable, Category = "Tools|Scanner")
	void ScanActor(AActor* TargetActor);

	UFUNCTION(BlueprintCallable, Category = "Tools|Scanner")
	float GetScanDistance() const;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Tools|Scanner")
	float ScanRange;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Tools|Scanner")
	float ScanInterval;

private:
	float LastScanTime;
};
