// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "QuantumTravelComponent.generated.h"

UCLASS( meta = (BlueprintType, Category = "QuantumTravel") )
class CHIMERA_API UQuantumTravelComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UQuantumTravelComponent(const FObjectInitializer& ObjectInitializer);
};
