// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "DockingComponent.generated.h"

UCLASS( meta = (BlueprintType, Category = "Docking") )
class CHIMERA_API UDockingComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UDockingComponent(const FObjectInitializer& ObjectInitializer);
};
