// Generated by GameCodeGenerator from tests/dsl_grammar (satellite specs)
// source spec: quantum_travel.chimera
#pragma once
#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "QuantumTravelSpecComponent.generated.h"

UCLASS(meta = (BlueprintType, Category = "SpecBindings"))
class CHIMERA_API UQuantumTravelSpecComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UQuantumTravelSpecComponent(const FObjectInitializer& ObjectInitializer);

	// spec: origin_anchor
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	FString OriginAnchor = TEXT("aegis_station_prime");
	// spec: destination_anchor
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	FString DestinationAnchor = TEXT("crocus_outpost");
	// spec: anchor_strength
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float AnchorStrength = 100.0f;
	// spec: distance_light_years
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float DistanceLightYears = 12.5f;
	// spec: duration_variation_minutes
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float DurationVariationMinutes = 15.0f;
	// spec: energy_cost_megajoules
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float EnergyCostMegajoules = 5000.0f;
	// spec: location_coordinates
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	FVector LocationCoordinates = FVector(0.0f, 0.0f, 0.0f);
	// spec: max_concurrent_jumps
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	int32 MaxConcurrentJumps = 50;
	// spec: nimbus_condition_threshold
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float NimbusConditionThreshold = 0.8f;
	// spec: phenomenon
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	FString Phenomenon = TEXT("quantum_nimbus_storm");
	// spec: recharge_rate_per_second
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float RechargeRatePerSecond = 2.0f;
	// spec: requires_favorable_nimbus_conditions
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	bool bRequiresFavorableNimbusConditions = false;
	// spec: affects_jump_safety
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	bool bAffectsJumpSafety = true;
	// spec: safety_reduction_percentage
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float SafetyReductionPercentage = 40.0f;
	// spec: affected_radius_light_years
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	float AffectedRadiusLightYears = 5.0f;
	// spec: supports_ship_classes
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Spec")
	TArray<FString> SupportsShipClasses;

	UFUNCTION(BlueprintCallable, Category = "Spec")
	float JumpEnergyFor(float DistanceLy) const;
	UFUNCTION(BlueprintCallable, Category = "Spec")
	bool CanJump(int32 ActiveJumps, float NimbusQuality01) const;
	UFUNCTION(BlueprintCallable, Category = "Spec")
	float EffectiveSafety(float BaseSafety01) const;
	UFUNCTION(BlueprintCallable, Category = "Spec")
	float RechargeSecondsFor(float Megajoules) const;

	UFUNCTION(BlueprintCallable, Category = "Spec")
	bool ValidateSpec() const;
};
