// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "NiagaraComponent.h"
#include "DustAccumulationMaterial.h"
#include "DustAccumulationParticleComponent.generated.h"

class UWindSystemComponent;

/**
 * Dust Accumulation Particle System Component
 * Manages procedural dust particle emission on footsteps and ground accumulation via DustAccumulationMaterial.
 *
 * Wires particle vertex normals to GetDustIntensity() for settling effect.
 * Integrates with WindSystemComponent for wind-driven particle drift.
 * Measures settling time and accumulation layer thickness over time.
 */
UCLASS(meta = (BlueprintSpawnableComponent, Category = "Materials|Dust"))
class CHIMERA_API UDustAccumulationParticleComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UDustAccumulationParticleComponent();

	virtual void BeginPlay() override;
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	// === Particle System Configuration ===
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Particles")
	TObjectPtr<UNiagaraSystem> DustParticleSystem;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Particles")
	float ParticleEmissionRate;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Particles")
	float ParticleLifetime;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Particles")
	float ParticleGravityScale;

	// === Wind Interaction ===
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Wind")
	float WindResponse;  // 0.0 = no wind, 1.0 = full wind effect (DSL parameter)

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Wind")
	bool bUseGlobalWindSystem;  // If true, tries to find WindSystemComponent in world

	// === Accumulation Configuration ===
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Accumulation")
	float AccumulationThreshold;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Accumulation")
	float SettlingSpeedScale;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Accumulation")
	float MaxAccumulationHeight;

	// === Footstep Trigger ===
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Footsteps")
	bool bEmitOnFootstep;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Footsteps")
	float FootstepEmitRadius;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust|Footsteps")
	float FootstepParticleCount;

	// === Measurement / Telemetry ===
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Dust|Telemetry")
	float CurrentAccumulationLayer;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Dust|Telemetry")
	float AccumulationStartTime;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Dust|Telemetry")
	float SettlingTime;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Dust|Telemetry")
	bool bIsSettled;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Dust|Telemetry")
	float TotalWindDriftDistance;  // Cumulative drift from wind

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Dust|Telemetry")
	FVector AverageWindDriftVector;  // Average drift direction and magnitude

	// === Public Methods ===

	/** Emit dust particles at a given location (e.g., from footstep) */
	UFUNCTION(BlueprintCallable, Category = "Dust|Particles")
	void EmitDustAtLocation(FVector Location, int32 ParticleCount);

	/** Apply dust accumulation material to ground surface */
	UFUNCTION(BlueprintCallable, Category = "Dust|Accumulation")
	void ApplyAccumulationMaterialToGround(UMaterialInterface* GroundMaterial);

	/** Get current dust intensity at a vertex normal */
	UFUNCTION(BlueprintCallable, Category = "Dust|Accumulation")
	float GetDustIntensityAtNormal(FVector VertexNormal);

	/** Start dust accumulation measurement session */
	UFUNCTION(BlueprintCallable, Category = "Dust|Telemetry")
	void StartAccumulationMeasurement();

	/** Get measured settling time in seconds */
	UFUNCTION(BlueprintCallable, Category = "Dust|Telemetry")
	float GetMeasuredSettlingTime() const;

	/** Get accumulation layer thickness (0-1 normalized) */
	UFUNCTION(BlueprintCallable, Category = "Dust|Telemetry")
	float GetAccumulationLayerThickness() const;

	/** Verify dust is visible on ground after walking/settling */
	UFUNCTION(BlueprintCallable, Category = "Dust|Telemetry")
	bool IsAccumulationObservable() const;

	/** Get wind drift distance during particle settling */
	UFUNCTION(BlueprintCallable, Category = "Dust|Wind")
	float GetWindDriftDistance() const;

	/** Get average wind drift direction during settling */
	UFUNCTION(BlueprintCallable, Category = "Dust|Wind")
	FVector GetAverageWindDrift() const;

protected:
	virtual void OnFootstepTriggered(FVector FootstepLocation);

private:
	// Internal dust accumulation material instance
	UPROPERTY()
	TObjectPtr<UDustAccumulationMaterial> DustMaterial;

	// Reference to global wind system (if available)
	UPROPERTY()
	TObjectPtr<UWindSystemComponent> CachedWindSystem;

	// Track active particles and their settling progress
	struct FDustParticleData
	{
		FVector Location;
		FVector Velocity;
		FVector VertexNormal;
		FVector WindDriftAccumulator;  // Cumulative wind drift on this particle
		float Age;
		float AccumulationFactor;
		bool bSettled;
	};

	TArray<FDustParticleData> ActiveParticles;

	// Accumulation tracking
	float TotalAccumulation;
	float PeakAccumulation;
	float AccumulationStartFrame;
	float LastEmissionTime;
	FVector TotalWindDrift;  // Cumulative wind drift vector for all particles

	// Internal update logic
	void UpdateParticleSettling(float DeltaTime);
	void UpdateAccumulationLayer();
	float CalculateSettlingProgression(float Age) const;

	// Wind system integration
	void InitializeWindSystem();
	void ApplyWindToParticles(float DeltaTime);
	UWindSystemComponent* FindOrCreateWindSystem();
};
