// Generated by GameCodeGenerator
#include "AShip_Trader_Vessel_Alpha.h"
AShip_Trader_Vessel_Alpha::AShip_Trader_Vessel_Alpha(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer), FuelCapacityLiters(10000), CargoCapacityKg(50000), ShieldCapacity(1000.0), ShieldRegenRate(50.0), HullHealth(5000.0)
{
	PrimaryActorTick.bCanEverTick = true;

	ShipRoot = CreateDefaultSubobject<USceneComponent>(TEXT("ShipRoot"));
	ShipCategory = TEXT("Freighter");  // seed default; DSL ship class overrides
	RootComponent = ShipRoot;

	ShipMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ShipMesh"));
	ShipMesh->SetupAttachment(RootComponent);

	CameraComponent = CreateDefaultSubobject<UCameraComponent>(TEXT("CameraComponent"));
	CameraComponent->SetupAttachment(RootComponent);
	CameraComponent->SetRelativeLocation(FVector(0.0f, 0.0f, 200.0f));
	CameraComponent->SetRelativeRotation(FRotator(-15.0f, 0.0f, 0.0f));

	// Create all components in constructor to prevent UE5 initialization crash
	FlightComponent = CreateDefaultSubobject<UFlightComponent>(TEXT("FlightComponent"));
	WeaponComponent = CreateDefaultSubobject<UWeaponComponent>(TEXT("WeaponComponent"));
	ShieldComponent = CreateDefaultSubobject<UShieldComponent>(TEXT("ShieldComponent"));
	DamageComponent = CreateDefaultSubobject<UDamageComponent>(TEXT("DamageComponent"));
	SystemDamageComponent = CreateDefaultSubobject<USystemDamageComponent>(TEXT("SystemDamageComponent"));
	CombatTargetComponent = CreateDefaultSubobject<UCombatTargetComponent>(TEXT("CombatTargetComponent"));
	DockingComponent = CreateDefaultSubobject<UDockingComponent>(TEXT("DockingComponent"));
	MissionComponent = CreateDefaultSubobject<UMissionComponent>(TEXT("MissionComponent"));
	FactionComponent = CreateDefaultSubobject<UFactionComponent>(TEXT("FactionComponent"));
	SaveGameComponent = CreateDefaultSubobject<USaveGameComponent>(TEXT("SaveGameComponent"));
}

void AShip_Trader_Vessel_Alpha::BeginPlay()
{
	Super::BeginPlay();

	// Initialize flight component with ship-specific parameters
	if (FlightComponent)
	{
		FlightComponent->InitializeFromShip(FuelCapacityLiters, 0.5f, 2000.0f, 30.0f);
	}

	// Initialize combat components with ship-specific values
	if (ShieldComponent)
	{
		ShieldComponent->InitializeFromShip(ShieldCapacity, ShieldRegenRate);
	}

	if (DamageComponent)
	{
		DamageComponent->InitializeFromShip(HullHealth);
	}

	// Initialize SystemDamageComponent with subsystem names
	if (SystemDamageComponent)
	{
		TArray<FName> SubsystemNames;
		SubsystemNames.Add("Engines");
		SubsystemNames.Add("Weapons");
		SubsystemNames.Add("LifeSupport");
		SystemDamageComponent->InitializeFromShip(SubsystemNames);
	}
}

