// Generated by GameCodeGenerator from tests/dsl_grammar (satellite specs)
#include "ShipClassSpecComponent.h"

UShipClassSpecComponent::UShipClassSpecComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{

}

float UShipClassSpecComponent::SecondsToTravelKm(float Km) const
{
	return Km / FMath::Max(MaxSpeedKmPerSec, 0.01f);
}

bool UShipClassSpecComponent::CargoFits(float VolumeCubicMeters) const
{
	return VolumeCubicMeters <= CargoVolumeCubicMeters;
}

bool UShipClassSpecComponent::IsCombatCapable() const
{
	return bHasWeaponSystems && ManeuverabilityRating > 0.0f;
}

bool UShipClassSpecComponent::ValidateSpec() const
{
	// every spec property is read here — a value nothing reads is
	// metadata, not a feature (H-21).
	const bool bNamed = !ShieldClass.IsEmpty();
	const float NumericTouch = (float)CargoVolumeCubicMeters + (float)MaxSpeedKmPerSec + (float)ManeuverabilityRating + (bHasQuantumDrive ? 1.0f : 0.0f) + (bHasWeaponSystems ? 1.0f : 0.0f);
	return bNamed && FMath::IsFinite(NumericTouch);
}
