// Generated by GameCodeGenerator
// Half-buried leviathan shell, 18m long, at the Yard's edge
#include "AErisaidActor.h"
#include "GameFramework/Pawn.h"
#include "Components/CapsuleComponent.h"
#include "Kismet/KismetMathLibrary.h"

AAErisaidActor::AAErisaidActor()
{
	PrimaryActorTick.bCanEverTick = true;

	// Create shell root component
	ShellRoot = CreateDefaultSubobject<USceneComponent>(TEXT("ShellRoot"));
	RootComponent = ShellRoot;

	// Create interaction sphere (larger than visual shell for detection)
	InteractionSphere = CreateDefaultSubobject<USphereComponent>(TEXT("InteractionSphere"));
	InteractionSphere->SetupAttachment(ShellRoot);
	InteractionSphere->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
	InteractionSphere->SetCollisionProfileName("Trigger");
	InteractionSphere->SetSphereRadius(1500.0f);  // ~15m detection radius

	// Create spore cloud particle system (hidden until Captive Burst)
	SporeCloud = CreateDefaultSubobject<UParticleSystemComponent>(TEXT("SporeCloud"));
	SporeCloud->SetupAttachment(ShellRoot);
	SporeCloud->bAutoActivate = false;  // Activated on Captive Burst

	// Create interior volume for contraction detection
	InteriorVolume = CreateDefaultSubobject<UBoxComponent>(TEXT("InteriorVolume"));
	InteriorVolume->SetupAttachment(ShellRoot);
	InteriorVolume->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
	InteriorVolume->SetBoxExtent(FVector(500.0f, 500.0f, 300.0f));  // ~5m radius

	// Initialize default state
	CurrentState = EShellState::Inert_Buried;
	RespirationPhase = ERespirationPhase::Expansion;
	bBeaconInserted = false;
}

void AAErisaidActor::BeginPlay()
{
	Super::BeginPlay();

	// Register overlap events on interaction sphere
	if (InteractionSphere)
	{
		InteractionSphere->OnComponentBeginOverlap.AddDynamic(this, &AAErisaidActor::OnInteractionSphereOverlap);
		InteractionSphere->OnComponentEndOverlap.AddDynamic(this, &AAErisaidActor::OnInteractionSphereUnoverlap);
	}

	// Log shell activation
	UE_LOG(LogTemp, Log, TEXT("AErisaidActor activated at %s"), *GetActorLocation().ToString());
}

void AAErisaidActor::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	// Update respiration cycle timer
	RespirationTimer += DeltaSeconds;

	if (RespirationPhase == ERespirationPhase::Contraction)
	{
		// Contraction is active - periodically spawn shell mites
		// and collapse interior volume
	}
	else if (RespirationPhase == ERespirationPhase::Expansion)
	{
		// Expansion phase - interior is stable
	}
}

bool AAErisaidActor::HasCranialResonanceBeacon(AActor* Player) const
{
	if (!Player) return false;

	// Check if player has the Cranial Resonance Beacon item
	// This would query the player's inventory or equipped items
	// For now, return false - requires beacon to interact
	return false;  // TODO: implement inventory check
}

void AAErisaidActor::InsertBeacon()
{
	if (bBeaconInserted) return;  // Already inserted

	bBeaconInserted = true;
	CurrentState = EShellState::Beacon_Unlocked;

	// Play insertion animation/sound
	UE_LOG(LogTemp, Log, TEXT("Cranial Resonance Beacon inserted into jaw hinge"));

	// Notify listeners
	OnShellStateChanged(CurrentState);
}

void AAErisaidActor::TriggerInertialRepulsion(AActor* Player)
{
	if (!Player) return;

	CurrentState = EShellState::Repulsion_Active;

	// Calculate pushback direction (away from shell center)
	FVector Direction = GetActorLocation() - Player->GetActorLocation();
	if (Direction.IsNearlyZero())
	{
		Direction = FVector(1.0f, 0.0f, 0.0f);  // Default push direction
	}
	Direction.Normalize();

	// Apply impulse to player (push them back)
	UCapsuleComponent* Capsule = Cast<UCapsuleComponent>(Player->FindComponentByClass(UCapsuleComponent::StaticClass()));
	if (Capsule)
	{
		FVector Impulse = Direction * InertialRepulsionForce;
		Capsule->AddImpulse(Impulse, NAME_None, true);
	}

	// Log repulsion event
	UE_LOG(LogTemp, Warning, TEXT("Inertial Repulsion triggered - pushed player %.1fm away"), InertialRepulsionPushbackMeters);

	// Reset state after repulsion completes
	GetWorldTimerManager().SetTimer(RepulsionResetTimer, this, &AAErisaidActor::OnRepulsionComplete, 2.0f);
}

void AAErisaidActor::OnRepulsionComplete()
{
	if (CurrentState == EShellState::Repulsion_Active)
	{
		CurrentState = EShellState::Inert_Buried;
	}
}

void AAErisaidActor::OnSonicEmitterDetected(AActor* Emitter)
{
	if (!Emitter) return;

	CurrentState = EShellState::Sonic_Vibrating;

	// Vibrate and shift buried position by 304.8cm (10 feet)
	FVector Shift = FVector(0.0f, 0.0f, -SonicShiftDistanceCm);  // Shift downward/unearth
	AddActorLocalOffset(Shift, false);

	// Unearth subterranean passage (trigger level geometry change)
	UE_LOG(LogTemp, Log, TEXT("Sonic vibration unearthed subterranean passage"));

	// Notify listeners
	OnShellStateChanged(CurrentState);

	// Reset after vibration completes
	GetWorldTimerManager().SetTimer(SonicResetTimer, this, &AAErisaidActor::OnSonicComplete, 5.0f);
}

void AAErisaidActor::OnSonicComplete()
{
	if (CurrentState == EShellState::Sonic_Vibrating)
	{
		CurrentState = bBeaconInserted ? EShellState::Beacon_Unlocked : EShellState::Inert_Buried;
	}
}

void AAErisaidActor::TriggerCaptiveBurst()
{
	CurrentState = EShellState::Captive_Burst_Fired;

	// Release toxic spores in cloud
	if (SporeCloud)
	{
		SporeCloud->Activate();
	}

	// Apply Asphyxiation status effect to all players in radius
	FVector Center = GetActorLocation();
	float RadiusSq = SporeCloudRadiusMeters * SporeCloudRadiusMeters * 100.0f;  // Convert m to cm, square
	for (FConstPlayerControllerIterator It = GetWorld()->GetPlayerControllerIterator(); It; ++It)
	{
		APlayerController* PC = *It;
		if (PC && PC->IsLocalPlayerController())
		{
			APawn* Pawn = PC->GetPawn();
			if (Pawn)
			{
				FVector PlayerLoc = Pawn->GetActorLocation();
				float DistSq = (PlayerLoc - Center).SizeSquared();
				if (DistSq <= RadiusSq)
				{
					// Apply Asphyxiation status effect
					UE_LOG(LogTemp, Warning, TEXT("Captive Burst: Asphyxiation applied to player at %s"), *PlayerLoc.ToString());
				}
			}
		}
	}

	// Convert to turret mode - fire at nearby players
	CurrentState = EShellState::Turret_Mode;
	UE_LOG(LogTemp, Warning, TEXT("AErisaidActor entered Turret Mode!"));

	// Notify listeners
	OnShellStateChanged(CurrentState);
}

void AAErisaidActor::StartContractionPhase()
{
	RespirationPhase = ERespirationPhase::Contraction;

	// Collapse nearby walls and ceilings (reduce interior volume)
	UE_LOG(LogTemp, Log, TEXT("Respiration Cycle: Contraction Phase started"));

	// Spawn shell mites during contraction
	SpawnShellMites(3);  // Spawn 3 mites per contraction

	// Notify listeners
	OnRespirationPhaseChanged(ERespirationPhase::Contraction);

	// Auto-reset to expansion after cycle period
	GetWorldTimerManager().SetTimer(ContractionResetTimer, this, &AAErisaidActor::OnContractionComplete, RespirationCyclePeriodSec);
}

void AAErisaidActor::OnContractionComplete()
{
	if (RespirationPhase == ERespirationPhase::Contraction)
	{
		RespirationPhase = ERespirationPhase::Expansion;
		OnRespirationPhaseChanged(ERespirationPhase::Expansion);
	}
}

void AAErisaidActor::SpawnShellMites(int32 Count)
{
	for (int32 i = 0; i < Count; i++)
	{
		// Spawn shell mite at random position within contraction radius
		FVector Offset = FVector::ZeroVector;
		Offset.X = FMath::RandRange(-ContractionRadiusMeters * 100.0f, ContractionRadiusMeters * 100.0f);
		Offset.Y = FMath::RandRange(-ContractionRadiusMeters * 100.0f, ContractionRadiusMeters * 100.0f);
		Offset.Z = FMath::RandRange(-200.0f, 200.0f);

		FShellMiteData Mite;
		Mite.SpawnLocation = GetActorLocation() + Offset;
		ActiveShellMites.Add(Mite);
	}

	UE_LOG(LogTemp, Log, TEXT("Spawned %d shell mites during contraction"), Count);
}

void AAErisaidActor::OnInteractionSphereOverlap(UPrimitiveComponent* OverlappedComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	if (!OtherActor || !Cast<APawn>(OtherActor)) return;  // Only respond to pawns

	// Check if player has Cranial Resonance Beacon
	if (!HasCranialResonanceBeacon(OtherActor))
	{
		// No beacon - trigger Inertial Repulsion
		TriggerInertialRepulsion(OtherActor);
	}
	else if (CurrentState == EShellState::Beacon_Unlocked)
	{
		// Beacon inserted - allow interior access
		CurrentState = EShellState::Interior_Open;
		OnShellStateChanged(CurrentState);
	}
}

void AAErisaidActor::OnInteractionSphereUnoverlap(UPrimitiveComponent* OverlappedComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	// Player left interaction sphere - no state change needed
}
