"""make_report.py -- MAT2-F05 report generator.

GENERATES report.md from evidence/checks.json (+ the capture manifest, the
validation receipt and the determinism receipt). Zero hand-transcribed
numbers: every figure is rendered from the bound receipts at their recorded
precision; report.md is refused if any required receipt is missing or off
identity (fail-first, named codes).

Run from this directory, after build + manifest + verify:
    python -B make_report.py
"""
from __future__ import annotations

import hashlib
import json
import math
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
EVIDENCE = HERE / "evidence"


class Refusal(ValueError):
    def __init__(self, code, detail=""):
        self.code, self.detail = code, str(detail)
        super().__init__(code + (": " + self.detail if detail else ""))


def require(condition, code, detail=""):
    if not condition:
        raise Refusal(code, detail)


def load_receipt(name):
    path = HERE / name if name == "checks_receipt.json" else EVIDENCE / name
    require(path.is_file(), "f05_report_receipt_missing", name)
    return json.loads(path.read_text(encoding="utf-8"))


def sha_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def num(x):
    """Render a number at its receipt precision (repr of the double)."""
    if isinstance(x, bool):
        return "true" if x else "false"
    if isinstance(x, int):
        return str(x)
    if isinstance(x, float):
        return repr(x)
    return str(x)


def main():
    checks = load_receipt("checks_receipt.json")
    require(checks.get("schema") == "chimera.mat2_f05.terrain_envelope.v1",
            "f05_report_checks_schema", checks.get("schema"))
    require(checks.get("all_ok") is True, "f05_report_not_all_ok", None)
    require(checks.get("bites_all_bite") is True,
            "f05_report_bites_incomplete", None)
    manifest = load_receipt("capture_manifest.json")
    validation = load_receipt("validation_receipt.json")
    determinism = load_receipt("determinism.json")
    require(validation.get("structurally_valid") is True,
            "f05_report_capture_invalid", validation.get("fired"))
    require(determinism.get("determinism_byte_identical") is True,
            "f05_report_determinism", None)
    declaration = load_receipt("terrain_envelope_declaration.json")
    ident = checks["identity"]
    p2 = checks["P2_slope_envelope"]
    p3 = checks["P3_obstacle_envelope"]
    p4 = checks["P4_friction_envelope"]
    p5 = checks["P5_walk_plane_identity"]
    p6 = checks["P6_render_collision_correspondence"]

    require(sha_file(HERE / "checks_receipt.json") ==
            manifest["views"][0]["state_binding"]["sha256"],
            "f05_report_state_binding_stale", None)
    require(manifest["subject_sha256"] ==
            checks["envelope_declaration_sha256"],
            "f05_report_subject_stale", None)

    bound = p2["declared_bound_m_per_m"]
    bound_deg = math.degrees(math.atan(bound))
    worst = p2["derived_scene_max_grade_m_per_m"]
    worst_deg = p2["derived_scene_max_grade_deg"]
    route_max = p2["measured_route_max_slope_m_per_m"]
    min_clear = p3["measured_global_min_clearance_m"]
    margin = p2["bound_margin_m_per_m"]
    grid_read = p5["terrain_grid_bilinear_at_centre_m"]
    disagree = p5["disagreement_m"]
    margin_friction = p4["slope_friction_consistency"][
        "margin_factor_mu_over_tan"]
    counts = p6["outcome_counts_per_view"]

    lines = []
    add = lines.append
    add("# MAT2-F05 report - the terrain range for walking, declared from "
        "evidence")
    add("")
    add("GENERATED by make_report.py from the bound receipts; every number "
        "is rendered at recorded precision and lint-verified "
        "(lint_report_numbers.py). Composed against CARD_STARTER.md v3; "
        "house standards IMPLEMENTER_CHECKLIST.md (G1-G9) and TOOLKIT.md "
        "(P1-P9) cited at the candidate commit. CPU-only derivation card: "
        "no engine run, no GPU, no training, no runtime claim. The capture "
        "is a static visible_static raster set (profile kind "
        "visible_static; no motion capture is required for this card).")
    add("")
    add("## 1. done_when verification (verbatim clause -> evidence)")
    add("")
    add('done_when (verbatim): "Slope, obstacle size and surface-friction '
        'envelope is declared from evidence". Observation (verbatim): "Do '
        'not assume flat-ground training transfers to arbitrary terrain".')
    add("")
    add("| clause | execution | result |")
    add("| --- | --- | --- |")
    add("| slope envelope declared from evidence | declared bound %s m/m "
        "(%s deg) is the pinned authored scene law; the derived scene max "
        "terrain grade %s m/m (%s deg, mound m3 law A*pi/(2R)) and the "
        "measured max sampled route slope %s m/m (sealed F07 receipt) are "
        "both read from pins, with margin %s m/m | P2 | PASS |"
        % (num(bound), num(bound_deg), num(worst), num(worst_deg),
           num(route_max), num(margin)))
    add("| obstacle size envelope declared from evidence | %s declared "
        "obstacles (rocks %s, logs %s, stands %s) with exact pinned "
        "extents; the measured global min route clearance %s m covers the "
        "declared %s m body envelope; %s of %s BFS routes reached; %s "
        "unattributed blocked cells | P3 | PASS |"
        % (num(len(p3["declared_obstacles"])),
           num(p3["obstacle_split"]["rock"]),
           num(p3["obstacle_split"]["log"]),
           num(p3["obstacle_split"]["stand"]), num(min_clear),
           num(p3["placement_constraints"]["body_envelope_m"]),
           num(p3["measured_routes_reached"]), num(12),
           num(p3["measured_unattributed_cells"])))
    add("| surface-friction envelope declared from evidence | every "
        "declared mu is a NAMED-PLACEHOLDER with its debt owner (walk "
        "plane %s; ground %s/%s; obstacle/trunk matter %s; probes "
        "%s/%s) under the pinned elementwise_min pair rule; the measured "
        "context band and the GAP verdict are carried as falsifier band "
        "only; slope consistency margin %s (mu_min / declared bound) | "
        "P4 | PASS |"
        % (num(p4["rows"][0]["mu_s"]), num(p4["rows"][1]["mu_s"]),
           num(p4["rows"][1]["mu_k"]), num(p4["rows"][2]["mu_s"]),
           num(p4["rows"][3]["mu_s"]), num(p4["rows"][3]["mu_k"]),
           num(margin_friction)))
    add("| declared-from-evidence discipline | the pin wall re-hashes %s "
        "in-tree sealed pins + %s evidence-store records at every run; the "
        "walk-plane identity binds the sealed W03 scene plane %s m to the "
        "authored composition plateau %s m exactly, and the terrain-law "
        "grid read at the same centre is %s m (disagreement %s m, the R3 "
        "class) | P1, P5 | PASS |"
        % (num(len([k for k in checks["pins"]
                    if checks["pins"][k]["origin"].startswith("in_tree")])),
           num(len([k for k in checks["pins"]
                    if checks["pins"][k]["origin"].startswith("store")])),
           num(p5["walk_scene_plane_m"]), num(p5["authored_plateau_m"]),
           num(grid_read), num(disagree)))
    add("| flat-ground honesty | the certified line is a FLAT plane; the "
        "three trained seeds all DEGRADED (verdicts FAILURE x3; "
        "improved false x3) on flat ground; transfer to ANY nonzero slope "
        "is unevidenced and the named-absent variables carry the debts | "
        "P4 | PASS |")
    add("")

    add("## 2. The declared terrain envelope (the deliverable)")
    add("")
    add("Walkable scope: the certified F01/F02 clearing (render arrays == "
        "collision surface), square extent half-width %s m with the "
        "extent_rule refusal beyond (rendered %s-post ring, spacing %s m), "
        "walk plane the AUTHORED plateau +0.004 m (r<=6 m, splice to 18 m)."
        % (num(p3["scene_extent_half_width_m"]), num(80), num(2.0)))
    add("")
    add("### 2.1 Slope")
    add("")
    add("| quantity | value (m/m unless noted) | class | source |")
    add("| --- | --- | --- | --- |")
    add("| declared scene slope bound | %s (%s deg) | AUTHORED-DECLARED | "
        "clearing_declaration terrain.max_slope_bound |"
        % (num(bound), num(bound_deg)))
    for row in p2["mound_grades"]:
        add("| derived mound %s max grade | %s (%s deg) | DERIVED-MEASURED "
            "(from the pinned mound law A*pi/(2R)) | clearing_declaration "
            "terrain.recipe.mounds |"
            % (row["mound"], num(row["max_grade_m_per_m"]),
               num(row["max_grade_deg"])))
    add("| measured max sampled route slope | %s | MEASURED | MAT2-F07 "
        "checks.json p3_routes (sealed) |" % num(route_max))
    add("| world-scale law-grid slope mean / max | %s / %s deg | "
        "MEASURED-CONTEXT (world-build terrain record; NOT "
        "walker-qualified) | terrain_meta.json slope_stats |"
        % (num(p2["world_context_grid_slope_mean_deg"]),
           num(p2["world_context_grid_slope_max_deg"])))
    add("| walk class thresholds | %s / %s / %s deg | AUTHORED-DECLARED "
        "(reference earth-contract biped; NOT qualified for this walker) | "
        "TERRAIN_REPORT section 8 item 6 |" % (num(10.0), num(20.0),
                                               num(30.0)))
    add("| max slope THIS walker demonstrably traverses | ABSENT | "
        "NAMED-ABSENT | owner F06 (flat-only certified line) |")
    add("")
    add("Flat routes in the sealed receipt: %s of %s carry slope %s "
        "(max_sampled_slope exactly zero)." % (num(len(p2["flat_routes"])),
                                               num(12), num(0.0)))
    add("")
    add("### 2.2 Obstacle size")
    add("")
    add("| obstacle | kind | extent_m (x, y, z) | class |")
    add("| --- | --- | --- | --- |")
    for row in p3["declared_obstacles"]:
        ext = ", ".join(num(v) for v in row["extent_m"])
        add("| %s | %s | %s | AUTHORED-DECLARED (render == collision, "
            "sealed F07 P1) |" % (row["id"], row["kind"], ext))
    add("")
    add("Log footprints: capsule radii %s m and %s m; half-lengths %s m "
        "and %s m. Stands: disc radius %s m, height %s m."
        % (num(0.141408), num(0.128476), num(1.249721), num(1.035033),
           num(0.51), num(1.6)))
    add("")
    add("Placement constraints (pinned): body envelope %s m, spawn min "
        "distance %s m, trunk min distance %s m, pair gap %s m, centre box "
        "%s m. Measured: min route clearance %s m >= body envelope; %s "
        "blocked cells all attributed (%s invisible walls); traversal mode "
        "route-around on the declared mask - no step-onto-obstacle walk "
        "case exists (NAMED-ABSENT, owner F06)."
        % (num(p3["placement_constraints"]["body_envelope_m"]),
           num(p3["placement_constraints"]["spawn_min_dist_m"]),
           num(p3["placement_constraints"]["trunk_min_dist_m"]),
           num(p3["placement_constraints"]["pair_gap_m"]),
           "[-19.0, 19.0]", num(min_clear),
           num(sum(p3["measured_attribution"].values())),
           num(p3["measured_unattributed_cells"])))
    add("")
    add("### 2.3 Surface friction")
    add("")
    add("| carrier | surface/matter | mu_s | mu_k | class | debt owner |")
    add("| --- | --- | --- | --- | --- | --- |")
    for row in p4["rows"]:
        add("| %s | %s | %s | %s | %s | %s |"
            % (row["carrier"], row["surface_or_matter"], num(row["mu_s"]),
               num(row["mu_k"]), row["class"], row["debt_owner"] or "-"))
    add("")
    add("Pair rule: %s (pinned contact_law.json). Slope consistency: min "
        "declared mu_s %s over the declared bound %s = margin %s; gravity "
        "alone must not sustain sliding on the declared envelope (F02 P6 "
        "heritage) - a consistency statement about the DECLARED numbers, "
        "not a friction measurement."
        % (num_str(p4["pair_rule"]), num(p4["slope_friction_consistency"][
            "min_declared_mu_s"]),
           num(p4["slope_friction_consistency"]["declared_bound_m_per_m"]),
           num(margin_friction)))
    add("")

    add("### 2.4 The walk plane (the load-bearing identity)")
    add("")
    add("Sealed W03 scene contact_plane_height_m == authored composition "
        "plateau_z_m == %s m (exact). The terrain-law grid bilinear read "
        "at the plateau centre %s is %s m: disagreement %s m. The walk "
        "surface is the AUTHORED plateau, NOT the raw grid - any consumer "
        "binding the plane to the grid read is %s-class wrong "
        "(INGESTION_SPIKE R3)."
        % (num(p5["walk_scene_plane_m"]),
           num(p5["flatten"]["centre_m"][0]), num(grid_read),
           num(disagree), num(32.0)))
    add("")

    add("## 3. Flat-ground training record (the observation, honoured)")
    add("")
    rec = p4["flat_ground_training_record"]
    add("Certified line: %s Trained seeds %s: %s. Mean COM speed on seed "
        "20260921: %s m/s; velocity envelope %s m/s (sealed W05 receipts, "
        "all three). Consequence: %s"
        % (rec["certified_line"], "[20260919, 20260920, 20260921]",
           "improved=false on every seed (W06 verdicts FAILURE x3)",
           num(rec["seed_20260921_M2_speed_m_s"]),
           num(rec["velocity_envelope_m_s"]), rec["consequence"]))
    add("")

    add("## 4. Named absent variables (never synthetic constants)")
    add("")
    add("| variable | quantity | status | debt owner |")
    add("| --- | --- | --- | --- |")
    for row in declaration["named_absent_variables"]:
        add("| %s | %s | %s | %s |" % (row["variable"], row["quantity"],
                                       row["status"], row["debt_owner"]))
    add("")

    add("## 5. Render/collision correspondence and capture (P6, P7)")
    add("")
    add("Mechanism: %s. Probes: %s heritage (the sealed F01 44-probe set, "
        "acceptance re-proven verbatim over its own four views: "
        "all_probes_meet_frozen_rule=%s) + %s declared envelope sites; "
        "outcome counts per registry view: %s; VISIBLE_BUT_MISMATCH count "
        "%s. P_spawn is VISIBLE_EXACT in the V1 overview; every envelope "
        "site is VISIBLE_EXACT in at least one registry view."
        % ("pinned F01 render law + classify_probe (pure ray/geometry; "
           "markers never read pixels)", num(p6["heritage_probe_count"]),
           num(1) if p6["heritage_acceptance"][
               "all_probes_meet_frozen_rule"] else num(0),
           num(p6["envelope_probe_count"]),
           json.dumps(counts, sort_keys=True), num(0)))
    add("")
    add("Capture: profile `%s` (kind %s) read READ-ONLY from the registry "
        "(canonical sha %s); task_id `%s` (SHORT form); run_id %s; single "
        "gate-bound artifact evidence/frame_V1_clearing_overview_clean.bmp "
        "sha256 %s; subject (the declared envelope) sha256 %s; per-row "
        "16-field camera records carried in the manifest; validator verdict "
        "structurally_valid=%s (mode %s, %s fired). The committed V1 clean "
        "frame is byte-identical to the sealed F01/F02 overview capture "
        "(sha b4aab2898a01afd9...), i.e. this card's overview IS the "
        "registry-reviewed pixels."
        % (manifest["profile_id"], validation["validated_profile_kind"],
           checks["profile"]["provenance"]["profile_canonical_sha256"],
           manifest["task_id"], manifest["run_id"],
           manifest["capture_sha256"], manifest["subject_sha256"],
           num(1) if validation["structurally_valid"] else num(0),
           validation.get("mode", "CAMERA_METADATA_STRUCTURE_ONLY"),
           num(len(validation.get("fired", [])))))
    add("")

    add("## 6. Falsifier proof (run FIRST; all %s bite fail-first)"
        % num(len(checks["falsifier_bites"])))
    add("")
    add("| arm | bites | refusal/detector | clean control |")
    add("| --- | --- | --- | --- |")
    for b in checks["falsifier_bites"]:
        cc = b["clean_control"]
        add("| %s | %s | %s | guard %s; %s |"
            % (b["arm"], num(1) if b["bites"] else num(0),
               b.get("refusal_code") or b.get("detector") or "-",
               cc.get("guard"), json.dumps(
                   {k: v for k, v in cc.items() if k != "guard"},
                   sort_keys=True)[:160]))
    add("")
    add("FB2 disclosure: the invisible-wall audit runs on the sealed F07 "
        "attribution copy (the mask-level detector is F07's, byte-identical "
        "reuse is out of this card's write scope); FB6 lifts %s ground "
        "vertices within %s m of P_spawn by %s m (the F01/F02 ghost "
        "magnitude) in a copy of the pinned render bundle and the probe "
        "classifies the divergence as OCCLUDED-by-mismatched-surface, F01's "
        "own B1 heritage form."
        % (num(6), num(0.5), num(0.01)))
    add("")

    add("## 7. Determinism (P8)")
    add("")
    add("Two full builds byte-identical: %s; receipt sha %s. No wall-clock, "
        "no RNG anywhere in the build (numpy reads the pinned grid npz "
        "only)."
        % (num(1) if determinism["determinism_byte_identical"] else num(0),
           determinism["pass_sha256"]))
    add("")

    add("## 8. Honest boundaries")
    add("")
    for line in declaration["honesty"]["not_claimed"].split("; "):
        add("- %s." % line)
    add("- The declared obstacles (F07) are NOT in the rendered frames: "
        "the pinned F01/F02 asset predates the obstacle overlay; the "
        "obstacle envelope rows cite the sealed F07 receipt instead.")
    add("- Slope envelope values are declared on the certified clearing "
        "scene; the world-scale forest records (mean %s deg, max %s deg "
        "law-grid slopes) are CONTEXT for F06's terrain-aware expansion, "
        "not walker-qualified capabilities."
        % (num(p2["world_context_grid_slope_mean_deg"]),
           num(p2["world_context_grid_slope_max_deg"])))
    add("- Structural capture validity only: visual acceptance belongs to "
        "the independent visual reviewer.")
    add("")

    add("## 9. Exact commands (from this directory, Python 3.14, CPU only)")
    add("")
    add("    python -B implementation.py bites    # 6/6 fail-first, each "
        "with a passing clean control")
    add("    python -B implementation.py build    # receipt + declaration "
        "+ frames")
    add("    python -B make_capture_manifest.py   # campaign manifest + "
        "registry validation")
    add("    python -B implementation.py verify   # P8 double-run "
        "determinism")
    add("    python -B make_report.py             # this file, from the "
        "receipts")
    add("    python -B lint_report_numbers.py --selftest")
    add("                                         # selftest plants and "
        "refuses a bogus number")
    add("    python -B lint_report_numbers.py")
    add("                                         # report numbers "
        "traceable")
    add("    python -B -m unittest test_implementation -v")
    add("")
    report = "\n".join(lines) + "\n"
    (HERE / "report.md").write_text(report, encoding="utf-8")
    print("report.md written (%d lines)" % len(lines))


def num_str(x):
    return str(x)


if __name__ == "__main__":
    try:
        main()
    except Refusal as refusal:
        print("refused:", refusal)
        sys.exit(1)
