// Generated by GameCodeGenerator - tb-0198 THE MATERIALIZATION BUBBLE
// Trained-data provenance: TRAINED (docs/objectives/granular.trained.json, the 40-deg regolith rule)
// World provenance: TRAINED CHAIN (bigbang.systems.json system 0 -> planet.trained.json: ocean @ 0.83 AU, 293 K, ocean_cov 0.030)
#pragma once
#include "CoreMinimal.h"
#include "Subsystems/WorldSubsystem.h"
#include "MaterializationSubsystem.generated.h"

class UInstancedStaticMeshComponent;

UCLASS()
class CHIMERA_API UMaterializationSubsystem : public UTickableWorldSubsystem
{
	GENERATED_BODY()
public:
	virtual void Initialize(FSubsystemCollectionBase& Collection) override;
	virtual void Tick(float DeltaTime) override;
	virtual TStatId GetStatId() const override;
	virtual bool DoesSupportWorldType(const EWorldType::Type WorldType) const override;

	// One patch = kPatchCells x kPatchCells columns of kCellW cm; the bubble
	// keeps the 3x3 around the pawn formed and coalesces beyond radius 2.
	static uint32 CellSeed(const FIntPoint& Cell);

private:
	UPROPERTY()
	TMap<FIntPoint, TObjectPtr<AActor>> FormedPatches;

	void EnsureBubble(const FVector& PawnLocation);
	AActor* FormPatch(const FIntPoint& Cell);
};
