// Generated by GameCodeGenerator
#pragma once
#include "CoreMinimal.h"
#include "GameFramework/Pawn.h"
#include "Components/SceneComponent.h"
#include "ADotCharacter.generated.h"

UCLASS()
class CHIMERA_API ADotCharacter : public APawn
{
	GENERATED_BODY()

public:
	ADotCharacter(const FObjectInitializer& ObjectInitializer);

	// Mass crowd entity representation
	UPROPERTY(VisibleAnywhere, Category = "Crowd")
	USceneComponent* CrowdRoot;

	UPROPERTY(EditDefaultsOnly, Category = "Crowd", meta = (ClampMin = "0"))
	int32 MassCount;

	// High-fidelity actor representation
	UPROPERTY(VisibleAnywhere, Category = "Representation")
	USceneComponent* RepresentationRoot;

};
