"""
rope_network.py — Lane R standing-skeleton tension network.

This module is owned by the rope/tension lane. It defines the MINIMAL rope
set that makes the standing human skeleton's configuration the unique stable
equilibrium, expressed in a BODY-PLAN FRAME that is independent of
LightEngine/skeleton_scaling.py (Lane S). Integration with the assembly lane
comes later.

Body-plan frame
---------------
- origin: midpoint between ankle joint centers on the ground (z = 0).
- +x: anterior.
- +y: left lateral.
- +z: superior.
- H = 1.0 is normalized standing height.
- whole-body COM: (0.020, 0.000, 0.550).

Every rope record cites three settled laws:
  1. unique-stability  — theLeg v3 full-arc gate makes the loaded-side rope
     the pose selector and the unloaded-side rope a crumpling boundary.
  2. no-prop            — theTendon v4 / theLeg v3: rope is tension-only;
     slack_direction names the motion that lets it fold instead of prop.
  3. anchor-on-bone-end — socket v1 law: joints capture by wrapping the bone's
     END, so every anchor sits on an epiphysis / process / metaphysis.

The module uses only the Python standard library.
"""

from __future__ import annotations

import math
from typing import Any


# ---------------------------------------------------------------------------
# Body-plan frame (Lane R; independent of Lane S scaling)
# ---------------------------------------------------------------------------

H = 1.0
COM_X = 0.020 * H
COM_Y = 0.000 * H
COM_Z = 0.550 * H

# Joint centers in the body-plan frame.  y is the lateral half-distance;
# left/right copies are generated by sign-flipping y.
JOINT_CENTERS: dict[str, tuple[float, float, float]] = {
    "ankle": (0.000, 0.060, 0.040),
    "knee": (0.030, 0.070, 0.260),
    "hip": (0.040, 0.090, 0.530),
    "shoulder": (0.020, 0.160, 0.820),
    "foot_arch_keystone": (0.020, 0.040, 0.025),
}

# Vertebral body centers (x, z).  y = 0 for the midline spine.
VERTEBRAL_CENTERS: dict[str, tuple[float, float]] = {
    # sacral base (fictive S1 body for the lumbosacral junction)
    "S1": (-0.030, 0.580),
    # lumbar
    "L5": (0.015, 0.600),
    "L4": (0.020, 0.635),
    "L3": (0.025, 0.670),
    "L2": (0.025, 0.705),
    "L1": (0.020, 0.740),
    # thoracic
    "T12": (0.010, 0.770),
    "T11": (0.005, 0.780),
    "T10": (0.000, 0.790),
    "T9": (-0.005, 0.800),
    "T8": (-0.010, 0.810),
    "T7": (-0.012, 0.822),
    "T6": (-0.014, 0.834),
    "T5": (-0.016, 0.846),
    "T4": (-0.017, 0.858),
    "T3": (-0.018, 0.870),
    "T2": (-0.019, 0.881),
    "T1": (-0.020, 0.890),
    # cervical
    "C7": (-0.020, 0.898),
    "C6": (-0.018, 0.910),
    "C5": (-0.016, 0.920),
    "C4": (-0.014, 0.930),
    "C3": (-0.018, 0.936),
    "C2": (-0.022, 0.944),
    "C1": (-0.020, 0.940),
}

# Spinous process offset posterior to the vertebral body center, in H.
SPINOUS_OFFSET_X = -0.035 * H
SPINOUS_OFFSET_Z = 0.000 * H

# Sacrum / pelvis arch reference points.
SACRUM_POSTERIOR = (-0.040, 0.000, 0.580)
SACRUM_PROMONTORY = (-0.020, 0.000, 0.580)
ILIUM_POSTERIOR = (-0.020, 0.110, 0.540)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _mirror_y(point: tuple[float, float, float]) -> tuple[float, float, float]:
    """Return the right-side copy of a left-side point."""
    x, y, z = point
    return (x, -y, z)


def _sub(a: tuple[float, float, float], b: tuple[float, float, float]) -> tuple[float, float, float]:
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _norm(v: tuple[float, float, float]) -> float:
    return math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])


def _unit(v: tuple[float, float, float]) -> tuple[float, float, float]:
    n = _norm(v)
    if n < 1e-12:
        return (0.0, 0.0, 0.0)
    return (v[0] / n, v[1] / n, v[2] / n)


def _rope(
    name: str,
    anchor_a: str,
    anchor_b: str,
    point_a: tuple[float, float, float],
    point_b: tuple[float, float, float],
    kills_mode: str,
    slack_direction: str,
    antagonist_of: str | None,
) -> dict[str, Any]:
    """Build a rope record with a derived unit line-of-pull."""
    vec = _sub(point_b, point_a)
    unit = _unit(vec)
    return {
        "name": name,
        "anchor_a": anchor_a,
        "anchor_b": anchor_b,
        "anchor_a_point": point_a,
        "anchor_b_point": point_b,
        "line_of_pull_unit_vector": unit,
        "kills_mode": kills_mode,
        "slack_direction": slack_direction,
        "antagonist_of": antagonist_of,
        "law_citations": ["unique-stability", "no-prop", "anchor-on-bone-end"],
    }


def _pair(
    base_name: str,
    anchor_a: str,
    anchor_b: str,
    point_a_left: tuple[float, float, float],
    point_b_left: tuple[float, float, float],
    kills_mode: str,
    slack_direction: str,
    antagonist_of: str | None,
) -> list[dict[str, Any]]:
    """Generate left/right symmetric rope records."""
    return [
        _rope(
            f"{base_name}_L",
            anchor_a,
            anchor_b,
            point_a_left,
            point_b_left,
            kills_mode,
            slack_direction,
            antagonist_of + "_L" if antagonist_of else None,
        ),
        _rope(
            f"{base_name}_R",
            anchor_a,
            anchor_b,
            _mirror_y(point_a_left),
            _mirror_y(point_b_left),
            kills_mode,
            slack_direction,
            antagonist_of + "_R" if antagonist_of else None,
        ),
    ]


# ---------------------------------------------------------------------------
# Rope network construction
# ---------------------------------------------------------------------------

def build_rope_network() -> list[dict[str, Any]]:
    """Return the standing-skeleton rope network as a list of records."""
    ropes: list[dict[str, Any]] = []

    # --- ankle pair ---------------------------------------------------------
    # Posterior rope = Achilles / triceps surae analog.
    # anchor_a on posterior distal femur/proximal tibia region;
    # anchor_b on posterior calcaneus.
    ankle_post_a = (-0.015, 0.060, 0.080)
    ankle_post_b = (-0.020, 0.060, 0.015)
    ropes.extend(
        _pair(
            "ankle_posterior",
            "femur",
            "calcaneus",
            ankle_post_a,
            ankle_post_b,
            kills_mode="forward-tip / dorsiflexion collapse",
            slack_direction="ankle plantarflexion",
            antagonist_of="ankle_anterior",
        )
    )
    # Anterior rope = tibialis anterior analog.
    ankle_ant_a = (0.020, 0.050, 0.080)
    ankle_ant_b = (0.035, 0.050, 0.010)
    ropes.extend(
        _pair(
            "ankle_anterior",
            "tibia",
            "tarsal_base",
            ankle_ant_a,
            ankle_ant_b,
            kills_mode="backward-tip / plantarflexion collapse",
            slack_direction="ankle dorsiflexion",
            antagonist_of="ankle_posterior",
        )
    )

    # --- knee pair ----------------------------------------------------------
    # Posterior rope = PCL / posterior capsule / hamstring analog.
    knee_post_a = (0.015, 0.070, 0.270)
    knee_post_b = (0.010, 0.070, 0.250)
    ropes.extend(
        _pair(
            "knee_posterior",
            "femur",
            "tibia",
            knee_post_a,
            knee_post_b,
            kills_mode="knee hyperextension / backward-collapse",
            slack_direction="knee flexion",
            antagonist_of="knee_anterior",
        )
    )
    # Anterior rope = quadriceps / patellar tendon analog.
    knee_ant_a = (0.045, 0.070, 0.270)
    knee_ant_b = (0.050, 0.070, 0.250)
    ropes.extend(
        _pair(
            "knee_anterior",
            "femur",
            "tibia",
            knee_ant_a,
            knee_ant_b,
            kills_mode="knee flexion / forward-collapse",
            slack_direction="knee extension",
            antagonist_of="knee_posterior",
        )
    )

    # --- hip pair -----------------------------------------------------------
    # Anterior rope = iliofemoral ligament / anterior capsule analog.
    hip_ant_a = (0.060, 0.090, 0.540)
    hip_ant_b = (0.050, 0.090, 0.520)
    ropes.extend(
        _pair(
            "hip_anterior",
            "pelvis",
            "femur",
            hip_ant_a,
            hip_ant_b,
            kills_mode="hip hyperextension / backward-collapse",
            slack_direction="hip flexion",
            antagonist_of="hip_posterior",
        )
    )
    # Posterior rope = ischiofemoral ligament / hamstring analog.
    hip_post_a = (0.010, 0.090, 0.520)
    hip_post_b = (0.020, 0.090, 0.500)
    ropes.extend(
        _pair(
            "hip_posterior",
            "pelvis",
            "femur",
            hip_post_a,
            hip_post_b,
            kills_mode="hip flexion / forward-collapse",
            slack_direction="hip extension",
            antagonist_of="hip_anterior",
        )
    )

    # --- lumbar spine -------------------------------------------------------
    lumbar_levels = ["L5", "L4", "L3", "L2", "L1"]
    for i in range(len(lumbar_levels) - 1):
        lower_name = lumbar_levels[i]
        upper_name = lumbar_levels[i + 1]
        lower_xz = VERTEBRAL_CENTERS[lower_name]
        upper_xz = VERTEBRAL_CENTERS[upper_name]
        lower_pt = (
            lower_xz[0] + SPINOUS_OFFSET_X,
            0.0,
            lower_xz[1] + SPINOUS_OFFSET_Z,
        )
        upper_pt = (
            upper_xz[0] + SPINOUS_OFFSET_X,
            0.0,
            upper_xz[1] + SPINOUS_OFFSET_Z,
        )
        ropes.append(
            _rope(
                f"lumbar_posterior_{i + 1}",
                lower_name,
                upper_name,
                lower_pt,
                upper_pt,
                kills_mode="lumbar flexion / forward-bending collapse",
                slack_direction="lumbar extension",
                antagonist_of=None,
            )
        )

    # Lumbosacral transition (L5-S1).
    l5_s1_lower = (
        VERTEBRAL_CENTERS["S1"][0] + SPINOUS_OFFSET_X,
        0.0,
        VERTEBRAL_CENTERS["S1"][1] + SPINOUS_OFFSET_Z,
    )
    l5_s1_upper = (
        VERTEBRAL_CENTERS["L5"][0] + SPINOUS_OFFSET_X,
        0.0,
        VERTEBRAL_CENTERS["L5"][1] + SPINOUS_OFFSET_Z,
    )
    ropes.append(
        _rope(
            "lumbar_posterior_5",
            "S1",
            "L5",
            l5_s1_lower,
            l5_s1_upper,
            kills_mode="lumbosacral flexion / forward-bending collapse",
            slack_direction="lumbosacral extension",
            antagonist_of=None,
        )
    )

    # --- thoracic spine -----------------------------------------------------
    thoracic_levels = [
        "T12", "T11", "T10", "T9", "T8", "T7",
        "T6", "T5", "T4", "T3", "T2", "T1",
    ]
    for i in range(len(thoracic_levels) - 1):
        lower_name = thoracic_levels[i]
        upper_name = thoracic_levels[i + 1]
        lower_xz = VERTEBRAL_CENTERS[lower_name]
        upper_xz = VERTEBRAL_CENTERS[upper_name]
        lower_pt = (
            lower_xz[0] + SPINOUS_OFFSET_X,
            0.0,
            lower_xz[1] + SPINOUS_OFFSET_Z,
        )
        upper_pt = (
            upper_xz[0] + SPINOUS_OFFSET_X,
            0.0,
            upper_xz[1] + SPINOUS_OFFSET_Z,
        )
        ropes.append(
            _rope(
                f"thoracic_posterior_{i + 1}",
                lower_name,
                upper_name,
                lower_pt,
                upper_pt,
                kills_mode="thoracic flexion / forward-bending collapse",
                slack_direction="thoracic extension",
                antagonist_of=None,
            )
        )

    # Thoracolumbar transition (T12-L1).
    t12_l1_lower = (
        VERTEBRAL_CENTERS["T12"][0] + SPINOUS_OFFSET_X,
        0.0,
        VERTEBRAL_CENTERS["T12"][1] + SPINOUS_OFFSET_Z,
    )
    t12_l1_upper = (
        VERTEBRAL_CENTERS["L1"][0] + SPINOUS_OFFSET_X,
        0.0,
        VERTEBRAL_CENTERS["L1"][1] + SPINOUS_OFFSET_Z,
    )
    ropes.append(
        _rope(
            "thoracic_posterior_12",
            "T12",
            "L1",
            t12_l1_lower,
            t12_l1_upper,
            kills_mode="thoracolumbar flexion / forward-bending collapse",
            slack_direction="thoracolumbar extension",
            antagonist_of=None,
        )
    )

    # --- cervical spine -----------------------------------------------------
    cervical_levels = ["C7", "C6", "C5", "C4", "C3", "C2", "C1"]
    for i in range(len(cervical_levels) - 1):
        lower_name = cervical_levels[i]
        upper_name = cervical_levels[i + 1]
        lower_xz = VERTEBRAL_CENTERS[lower_name]
        upper_xz = VERTEBRAL_CENTERS[upper_name]
        lower_pt = (
            lower_xz[0] + SPINOUS_OFFSET_X,
            0.0,
            lower_xz[1] + SPINOUS_OFFSET_Z,
        )
        upper_pt = (
            upper_xz[0] + SPINOUS_OFFSET_X,
            0.0,
            upper_xz[1] + SPINOUS_OFFSET_Z,
        )
        ropes.append(
            _rope(
                f"cervical_posterior_{i + 1}",
                lower_name,
                upper_name,
                lower_pt,
                upper_pt,
                kills_mode="cervical flexion / forward nod",
                slack_direction="cervical extension",
                antagonist_of=None,
            )
        )

    # Cervicothoracic transition (C7-T1).
    c7_t1_lower = (
        VERTEBRAL_CENTERS["T1"][0] + SPINOUS_OFFSET_X,
        0.0,
        VERTEBRAL_CENTERS["T1"][1] + SPINOUS_OFFSET_Z,
    )
    c7_t1_upper = (
        VERTEBRAL_CENTERS["C7"][0] + SPINOUS_OFFSET_X,
        0.0,
        VERTEBRAL_CENTERS["C7"][1] + SPINOUS_OFFSET_Z,
    )
    ropes.append(
        _rope(
            "cervical_posterior_7",
            "T1",
            "C7",
            c7_t1_lower,
            c7_t1_upper,
            kills_mode="cervicothoracic flexion / forward nod",
            slack_direction="cervicothoracic extension",
            antagonist_of=None,
        )
    )

    # --- occipito-atlantal / skull ------------------------------------------
    skull_anchor = (-0.055, 0.000, 0.960)
    c2_anchor = (
        VERTEBRAL_CENTERS["C2"][0] + SPINOUS_OFFSET_X,
        0.0,
        VERTEBRAL_CENTERS["C2"][1] + SPINOUS_OFFSET_Z,
    )
    ropes.append(
        _rope(
            "skull_posterior",
            "C2",
            "skull",
            c2_anchor,
            skull_anchor,
            kills_mode="skull forward nod / atlanto-occipital flexion collapse",
            slack_direction="skull extension",
            antagonist_of=None,
        )
    )

    # --- shoulder pair ------------------------------------------------------
    shoulder_a = (0.025, 0.160, 0.860)
    shoulder_b = (0.030, 0.160, 0.800)
    ropes.extend(
        _pair(
            "shoulder_superior",
            "scapula",
            "humerus",
            shoulder_a,
            shoulder_b,
            kills_mode="inferior subluxation of humeral head",
            slack_direction="humeral abduction / elevation",
            antagonist_of=None,
        )
    )

    # --- foot arch pair -----------------------------------------------------
    foot_a = (-0.020, 0.040, 0.005)
    foot_b = (0.070, 0.050, 0.005)
    ropes.extend(
        _pair(
            "foot_arch_plantar",
            "calcaneus",
            "metatarsal_base",
            foot_a,
            foot_b,
            kills_mode="longitudinal arch flattening",
            slack_direction="arch rising / supination",
            antagonist_of=None,
        )
    )

    # --- pelvis arch --------------------------------------------------------
    pelvis_a_left = ILIUM_POSTERIOR
    pelvis_b_left = SACRUM_POSTERIOR
    ropes.extend(
        _pair(
            "pelvis_arch_posterior",
            "ilium",
            "sacrum",
            pelvis_a_left,
            pelvis_b_left,
            kills_mode="sacral nutation / pelvic arch opening",
            slack_direction="sacral counternutation",
            antagonist_of=None,
        )
    )

    return ropes


# ---------------------------------------------------------------------------
# Module-level export
# ---------------------------------------------------------------------------

ROPE_NETWORK = build_rope_network()


def get_rope_network() -> list[dict[str, Any]]:
    """Return the rope network; safe to call multiple times."""
    return list(ROPE_NETWORK)


def rope_count() -> int:
    """Return total number of ropes."""
    return len(ROPE_NETWORK)


if __name__ == "__main__":
    net = get_rope_network()
    print(f"total rope count: {len(net)}")
    for r in net:
        print(
            f"{r['name']:28s}  {r['anchor_a']:10s}->{r['anchor_b']:10s}  "
            f"kills={r['kills_mode']:42s}  slack={r['slack_direction']}"
        )
