// Generated by GameCodeGenerator
#pragma once
#include "CoreMinimal.h"
#include "AIController.h"
#include "BehaviorTree/BlackboardComponent.h"
#include "PirateAIController.generated.h"

UENUM(BlueprintType)
enum class EAIPirateState : uint8 {
	Patrolling UMETA(DisplayName = "Patrolling"),
	Investigating UMETA(DisplayName = "Investigating"),
	Pursuing UMETA(DisplayName = "Pursuing"),
	Engaging UMETA(DisplayName = "Engaging"),
	Retreating UMETA(DisplayName = "Retreating")
};

UCLASS()
class CHIMERA_API APirateAIController : public AAIController {
GENERATED_BODY()
public:
	APirateAIController(const FObjectInitializer& ObjectInitializer);

	UPROPERTY(EditDefaultsOnly, Category = "Pirate AI")
	FName FactionName;

	UPROPERTY(EditDefaultsOnly, Category = "Pirate AI", meta = (ClampMin = "0.0", ClampMax = "1.0"))
	float HostilityToPlayer;

	UPROPERTY(EditDefaultsOnly, Category = "Pirate AI", meta = (ClampMin = "0.0"))
	float DetectionRange;

	UPROPERTY(EditDefaultsOnly, Category = "Pirate AI", meta = (ClampMin = "0.0"))
	float EngagementRange;

	UPROPERTY(VisibleAnywhere, Category = "Pirate AI State")
	EAIPirateState CurrentState;

protected:
	virtual void BeginPlay() override;
	virtual void Tick(float DeltaSeconds) override;

private:
	bool ScanForPlayer();
	float EvaluateThreat();
};