"""
AERODYNAMICS & FLIGHT DYNAMICS SIMULATION
==========================================
This module implements aerodynamics and flight dynamics simulations for airplane 
flight dynamics, thrust vector & CoG (Center of Gravity) flight dynamics, and 
environmental forces (gravity/wind/drag) in the Python/physics pipeline. It maps to 
the Aerodynamic/Atmospheric Port and Gravitational Anchor connection shapes.

CORE CONCEPTS:
- Thrust Vector & CoG Flight Dynamics: Balancing Center of Gravity vs. Center of Thrust 
  to stabilize torque and achieve stable flight trajectories.
- Environmental Forces: Gravity, wind, and drag forces acting on an aircraft in flight.
- Aerodynamic/Atmospheric Port: Physics interface for lift, drag, thrust, and airflow 
  patterns (Bernoulli's principle).

FLIGHT DYNAMICS METRICS:
- lift_coefficient: dimensionless coefficient representing lift generated by wings
- drag_coefficient: dimensionless coefficient representing aerodynamic resistance
- thrust_vector_x_y_z: 3D vector representing thrust direction and magnitude
- center_of_gravity: 3D coordinates of the aircraft's center of gravity
- center_of_thrust: 3D coordinates of the thrust vector origin
"""

import math
import random
from typing import Dict, Any, List, Tuple

class AerodynamicsFlightDynamics:
    """Simulates aerodynamics and flight dynamics for aircraft."""
    
    def __init__(self, seed_value: int = 42):
        self.seed_value = seed_value
        random.seed(self.seed_value)
        
    def calculate_thrust_vector_cog_dynamics(self, thrust_magnitude: float, 
                                            cog_x: float, cog_y: float, cog_z: float,
                                            ct_x: float, ct_y: float, ct_z: float) -> Dict[str, Any]:
        """
        Calculate Thrust Vector & Center of Gravity (CoG) flight dynamics.
        
        Args:
            thrust_magnitude: total thrust force in Newtons
            cog_x, cog_y, cog_z: coordinates of center of gravity
            ct_x, ct_y, ct_z: coordinates of center of thrust
            
        Returns:
            Dictionary containing thrust vector and torque stabilization metrics
        """
        # Thrust vector direction (from CT to COG or vice versa depending on engine placement)
        # For simplicity, thrust vector is along the positive Z axis with X/Y offsets based on CT-COG delta
        delta_x = ct_x - cog_x
        delta_y = ct_y - cog_y
        delta_z = ct_z - cog_z
        
        # Normalize thrust vector
        magnitude = math.sqrt(delta_x**2 + delta_y**2 + delta_z**2) or 1.0
        thrust_vector_x = (delta_x / magnitude) * thrust_magnitude
        thrust_vector_y = (delta_y / magnitude) * thrust_magnitude
        thrust_vector_z = (delta_z / magnitude) * thrust_magnitude
        
        # Torque stabilization: difference between CoG and CT creates torque
        # Torque = r x F (cross product of position vector and force vector)
        torque_x = cog_y * thrust_vector_z - cog_z * thrust_vector_y
        torque_y = cog_z * thrust_vector_x - cog_x * thrust_vector_z
        torque_z = cog_x * thrust_vector_y - cog_y * thrust_vector_x
        
        # Balance CoG/CoT Torque Stabilization metric
        total_torque_magnitude = math.sqrt(torque_x**2 + torque_y**2 + torque_z**2)
        is_stable = total_torque_magnitude < 50.0  # Threshold for stable flight
        
        return {
            "thrust_magnitude_n": thrust_magnitude,
            "cog_coordinates": {"x": cog_x, "y": cog_y, "z": cog_z},
            "ct_coordinates": {"x": ct_x, "y": ct_y, "z": ct_z},
            "thrust_vector_xyz": {"x": thrust_vector_x, "y": thrust_vector_y, "z": thrust_vector_z},
            "torque_xyz": {"x": torque_x, "y": torque_y, "z": torque_z},
            "total_torque_magnitude": total_torque_magnitude,
            "is_flight_stable": is_stable
        }

    def calculate_environmental_forces(self, aircraft_mass: float, velocity: float, 
                                      altitude: float, wind_speed: float, wind_direction: str) -> Dict[str, float]:
        """
        Calculate environmental forces: gravity, wind, and drag.
        
        Args:
            aircraft_mass: mass of aircraft in kg
            velocity: aircraft speed in m/s
            altitude: current altitude in meters
            wind_speed: wind speed in m/s
            wind_direction: 'headwind', 'tailwind', 'crosswind_left', 'crosswind_right'
            
        Returns:
            Dictionary containing gravity, wind, and drag force metrics
        """
        # Gravity force (F = m * g)
        gravitational_acceleration = 9.81 - (0.00003 * altitude)  # Slight reduction with altitude
        gravity_force_n = aircraft_mass * gravitational_acceleration
        
        # Drag force (F = 0.5 * rho * v^2 * A * Cd)
        # Air density decreases with altitude
        air_density_at_sea_level = 1.225
        air_density = air_density_at_sea_level * math.exp(-altitude / 8500.0)
        
        drag_coefficient = 0.02 + (random.uniform(0.0, 0.01))  # Modern aircraft Cd approx
        frontal_area = 20.0  # m^2 approximation
        
        drag_force_n = 0.5 * air_density * (velocity ** 2) * frontal_area * drag_coefficient
        
        # Wind force calculation based on direction
        wind_force_factor = {
            "headwind": -1.0,   # Opposes flight
            "tailwind": 1.0,    # Assists flight
            "crosswind_left": 0.3,  # Lateral force left
            "crosswind_right": -0.3 # Lateral force right
        }
        
        wind_force_n = wind_speed * aircraft_mass * wind_force_factor.get(wind_direction.lower(), 0.0)
        
        return {
            "aircraft_mass_kg": aircraft_mass,
            "gravity_force_newtons": gravity_force_n,
            "gravitational_acceleration_mps2": gravitational_acceleration,
            "velocity_mps": velocity,
            "air_density_kgm3": air_density,
            "drag_coefficient": drag_coefficient,
            "frontal_area_m2": frontal_area,
            "drag_force_newtons": drag_force_n,
            "wind_speed_mps": wind_speed,
            "wind_direction": wind_direction,
            "wind_force_newtons": wind_force_n
        }


class AerodynamicAtmosphericPort:
    """Represents the Aerodynamic/Atmospheric Port connection shape for flight dynamics."""
    
    def __init__(self):
        self.port_type = "Aerodynamic/Atmospheric Port"
        self.physics_principles = [
            "Lift",
            "Drag",
            "Thrust",
            "Airflow patterns (Bernoulli's principle)"
        ]
        
    def get_connection_metadata(self) -> Dict[str, Any]:
        """Return metadata for the Aerodynamic/Atmospheric Port connection shape."""
        return {
            "port_name": self.port_type,
            "physics_principles": self.physics_principles,
            "compatible_modules": [
                "Aerodynamics_Flight_Dynamics",
                "Thrust_Vector_CoG_Flight_Dynamics",
                "Environmental_Forces_Gravity_Wind_Drag"
            ]
        }


class GravitationalAnchor:
    """Represents the Gravitational Anchor connection shape for celestial gravity fields."""
    
    def __init__(self):
        self.port_type = "Gravitational Anchor"
        self.physics_principles = [
            "Newtonian gravity",
            "Mass attraction",
            "Keplerian mechanics"
        ]
        
    def get_connection_metadata(self) -> Dict[str, Any]:
        """Return metadata for the Gravitational Anchor connection shape."""
        return {
            "port_name": self.port_type,
            "physics_principles": self.physics_principles,
            "compatible_modules": [
                "Orbital_Mechanics_Celestial_Gravity",
                "Aerodynamics_Flight_Dynamics"
            ]
        }


def execute_aerodynamics_flight_dynamics_simulation(simulation_type: str, 
                                                   seed_value: int = 42) -> Dict[str, Any]:
    """
    Convenience function to execute aerodynamics and flight dynamics simulation.
    
    Args:
        simulation_type: 'thrust_vector_cog' or 'environmental_forces'
        seed_value: procedural seed for unique simulation generation
        
    Returns:
        simulated_flight_state: aerodynamics and flight dynamics results
    """
    simulator = AerodynamicsFlightDynamics(seed_value=seed_value)
    
    if simulation_type == "thrust_vector_cog":
        # Default parameters for thrust vector & CoG calculation
        results = simulator.calculate_thrust_vector_cog_dynamics(
            thrust_magnitude=50000.0,  # 50 kN thrust
            cog_x=0.0, cog_y=0.0, cog_z=0.0,  # CoG at origin
            ct_x=0.5, ct_y=0.0, ct_z=-2.0     # CT slightly offset
        )
    elif simulation_type == "environmental_forces":
        # Default parameters for environmental forces calculation
        results = simulator.calculate_environmental_forces(
            aircraft_mass=75000.0,  # Large commercial aircraft
            velocity=250.0,         # 250 m/s approx Mach 0.73
            altitude=10000.0,       # 10 km altitude
            wind_speed=30.0,        # 30 m/s wind
            wind_direction="headwind"
        )
    else:
        raise ValueError(f"Unknown simulation type: {simulation_type}")
        
    return {
        "simulation_status": "verified",
        "simulation_type": simulation_type,
        "aerodynamic_port_applied": True if simulation_type == "environmental_forces" else False,
        "gravitational_anchor_applied": True if simulation_type == "thrust_vector_cog" else False,
        "connection_shapes": ["Aerodynamic/Atmospheric Port", "Gravitational Anchor"],
        "metrics": results
    }
