"""MAT2-G01 report generator (house standard: GENERATED, zero hand-written numbers).

Reads feasibility_receipt.json, feasibility_receipt_rerun2.json and
falsifier_receipt.json, runs the named-check suite for the skip accounting,
and emits REPORT.md. Every number in the report is rendered from the receipts
at their printed precision; lint_report_numbers.py proves traceability.
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent


def load(name):
    return json.loads((HERE / name).read_text(encoding="utf-8"))


def fmt(x) -> str:
    if isinstance(x, bool):
        return "true" if x else "false"
    if isinstance(x, float):
        return repr(x)
    return str(x)


def suite_counts() -> tuple[int, int]:
    out = subprocess.run(
        [sys.executable, "-B", "-m", "unittest", "test_g01_checks", "-v"],
        cwd=str(HERE), capture_output=True, text=True)
    text = out.stderr + out.stdout
    m = re.search(r"Ran (\d+) tests?", text)
    if not m:
        raise SystemExit(f"Refusal suite_counts_missing: {text[-400:]}")
    executed = int(m.group(1))
    skipped = len(re.findall(r"skipped", text))
    if out.returncode != 0:
        raise SystemExit(f"Refusal suite_not_green: {text[-800:]}")
    return executed, skipped


def main() -> int:
    r = load("feasibility_receipt.json")
    r2 = load("feasibility_receipt_rerun2.json")
    f = load("falsifier_receipt.json")
    d = r["derivation"]
    q = r["declared_quantities"]

    # two-pass bootstrap: provisional write (no counts numbers) -> suite ->
    # accounting receipt -> final write; the provisional and final differ ONLY
    # in the counts line.
    write_report(r, r2, f, None, None)
    executed, skipped = suite_counts()
    accounting = {
        "schema": "chimera.g01.checks_accounting.v1",
        "card": "MAT2-G01",
        "attempt_id": r["attempt_id"],
        "criteria_sha256": r["criteria_sha256"],
        "command": "python -B -m unittest test_g01_checks -v",
        "executed": executed,
        "skipped": skipped,
        "known_skips": "none (zero skips by design; no KNOWN_SKIPS entries)",
    }
    (HERE / "checks_accounting.json").write_bytes(
        (json.dumps(accounting, sort_keys=True, separators=(",", ":"),
                    ensure_ascii=False, allow_nan=False) + "\n").encode("utf-8"))
    write_report(r, r2, f, executed, skipped)
    return 0


def write_report(r, r2, f, executed, skipped) -> None:
    d = r["derivation"]
    q = r["declared_quantities"]
    cap = d["capacity"]
    geo = d["geometry"]
    w = d["body_readings"]
    wrap = d["wrap_comparison"]
    by_clause = {v["clause"]: v for v in d["verdicts"]}

    cap = d["capacity"]
    geo = d["geometry"]
    w = d["body_readings"]
    wrap = d["wrap_comparison"]
    by_clause = {v["clause"]: v for v in d["verdicts"]}

    def num_row_case(reading):
        cells = []
        for n in (1, 2, 3):
            row = next(x for x in d["case_table"]
                       if x["reading"] == reading and x["n_channels"] == n)
            cells.append(
                f"| {reading} | {n} | {fmt(row['W_N'])} | {fmt(row['support_N'])} | "
                f"{'WITHIN' if row['friction_feasible'] else 'OUTSIDE'} | "
                f"{fmt(row['required_press_per_channel_N'])} | "
                f"{'yes' if row['press_at_operating_point'] else 'no'} |")
        return "\r\n".join(cells)

    lines = []
    A = lines.append
    A("# MAT2-G01 report - derive support and grip feasibility (records/offline)")
    A("")
    A("GENERATED by make_report.py from the receipts; every number is rendered from")
    A("feasibility_receipt.json / falsifier_receipt.json at printed precision and")
    A("lint-proven traceable. Composed against CARD_STARTER v3; house standards")
    A("IMPLEMENTER_CHECKLIST.md (G1-G9) + TOOLKIT.md (P1-P9) cited at the candidate")
    A("commit. CPU-only; records/offline profile; no capture, no camera, no runtime")
    A("(the profile's nonvisual reason: a screenshot is not a substitute).")
    A("")
    A("| identity | value |")
    A("|---|---|")
    A(f"| card | {r['card']} (task_id short form {r['task_id_short']}) |")
    A(f"| attempt | {r['attempt_id']} (agent {r['agent_id']}, branch-2, slot 2) |")
    A(f"| criteria_sha256 | {r['criteria_sha256']} |")
    A(f"| base | {r['base_commit']} (origin/astra/gait-capture; the MAT2-W04 merge PR #295) |")
    A(f"| preregistration | commit {r['preregistration_commit']}, sha256 "
      f"{r['preregistration_sha256']} |")
    A(f"| ontology scope_sha256 | {r['scope_sha256']} |")
    A("")
    A("## 1. done_when verification (verbatim clause -> evidence)")
    A("")
    A('done_when (verbatim): "Required force/moment support lies within reachable')
    A('contacts and actuator bounds for the declared trunk". Card observation')
    A('(verbatim): "Static support is necessary, not proof of climbing".')
    A("")
    A("| clause | verdict | load-bearing numbers | evidence |")
    A("|---|---|---|---|")
    for v in d["verdicts"]:
        if v["clause"].startswith("C19 case"):
            continue
        nums = "; ".join(f"{k}={fmt(x)}" for k, x in v.get("numbers", {}).items()) or "-"
        vars_ = ", ".join(v.get("named_variables", [])) or "-"
        A(f"| {v['clause']} | {v['verdict']} | {nums} | named variables: {vars_}; "
          f"pins: {', '.join(v['citations'])} |")
    A(f"| OVERALL | {d['overall']['verdict']} | see section 3 | derivation.overall.verdict |")
    A("")
    A("## 2. Declared quantities (every number's source)")
    A("")
    A("| quantity | value | source pin |")
    A("|---|---|---|")
    A(f"| mu_s (UNEVIDENCED-PLACEHOLDER, G04 debt) | {fmt(cap['mu_s'])} | f03_checks S1 |")
    A(f"| jn (press impulse) | {fmt(cap['jn_Ns'])} N*s | f03_checks S1 |")
    A(f"| dt (M06 tick) | {fmt(cap['dt_s'])} s | grasp_benchmark |")
    A(f"| demonstrated press operating point jn/dt | {fmt(cap['press_operating_point_N'])} N | "
      "derived from f03_checks S1 |")
    A(f"| grip capacity | {fmt(cap['capacity_kg'])} kg | f03_checks S1 (bit-reproduced: "
      f"{str(cap['capacity_formula_bit_reproduced']).lower()}) |")
    A(f"| capacity at record-g {fmt(q['g_record'])} | {fmt(cap['capacity_N_record_g'])} N | derived |")
    A(f"| capacity at standard g {fmt(q['g_std'])} | {fmt(cap['capacity_N_std_g'])} N | derived; "
      f"benchmark conversion match: {str(cap['benchmark_conversion_match']).lower()} |")
    A(f"| declared trunk radius (from sealed analytic volume) | {fmt(geo['declared_radius_m'])} m | "
      "f03_checks P2 volume + f03_trunk_mesh height |")
    A(f"| declared trunk diameter | {fmt(geo['declared_diameter_m'])} m | derived |")
    A(f"| trunk height | {fmt(geo['height_m'])} m | f03_trunk_mesh bounds |")
    A(f"| trunk mass | {fmt(q['trunk_mass_kg'])} kg (band {fmt(q['trunk_mass_band_kg'][0])} - "
      f"{fmt(q['trunk_mass_band_kg'][1])}) | f03_checks P3 |")
    A(f"| scene body reading | {fmt(w['scene']['mass_kg'])} kg -> W {fmt(w['scene']['W_N'])} N | "
      "d_massreg_register totals.scene_carve_sum_kg |")
    A(f"| band reading low/mid/high | {fmt(w['band_lo']['mass_kg'])} / "
      f"{fmt(w['band_mid']['mass_kg'])} / {fmt(w['band_hi']['mass_kg'])} kg -> W "
      f"{fmt(w['band_lo']['W_N'])} / {fmt(w['band_mid']['W_N'])} / {fmt(w['band_hi']['W_N'])} N | "
      "d_massreg_register totals.reference_band_kg |")
    A(f"| recorded fingertip span | {fmt(wrap['recorded_fingertip_span_m'])} m | "
      "a09_grasp_package endpoints (supported, hand frame) |")
    A(f"| W03 corroboration found | {str(q['w03_corroboration_found']).lower()} "
      f"(mass literal {q['w03_mass_corroboration_kg_literal']}, weight literal "
      f"{q['w03_weight_corroboration_N_literal']}) | w03_report |")
    A("")
    A("## 3. The C19 case analysis (equal-share case model; x_share ABSENT)")
    A("")
    A("| reading | n | W [N] | support n*c0 [N] | friction verdict | required press per "
      "channel [N] | press <= operating point |")
    A("|---|---|---|---|---|---|---|")
    for reading in ("scene", "band_lo", "band_mid", "band_hi"):
        A(num_row_case(reading))
    A("")
    A(f"Reading split (the two mass systems stay DISTINCT per the sealed register; no "
      f"reconciliation: {q['massreg_reconciliation_verbatim']}):")
    A("")
    A(f"- scene system: n=1 OUTSIDE, n=2 OUTSIDE (support {fmt(2 * cap['capacity_N_std_g'])} N "
      f"< W {fmt(w['scene']['W_N'])} N), n=3 WITHIN "
      f"({fmt(3 * cap['capacity_N_std_g'])} N >= {fmt(w['scene']['W_N'])} N).")
    A(f"- biological-reference band: n=1 OUTSIDE; n=2 WITHIN (support "
      f"{fmt(2 * cap['capacity_N_std_g'])} N >= band-high W {fmt(w['band_hi']['W_N'])} N); "
      "n=3 WITHIN.")
    A("")
    A("## 4. Named variables - the absent interface quantities (never synthetic constants)")
    A("")
    A("| variable | quantity | status | absence provenance (verbatim source) |")
    A("|---|---|---|---|")
    for name, var in d["named_variables"].items():
        prov = str(var["provenance_verbatim"]).replace("|", "/")
        if len(prov) > 220:
            prov = prov[:217] + "..."
        A(f"| {name} | {var['quantity']} | {var['status']} | {prov} |")
    A("")
    A("Named-variable law: no synthetic constant occupies an absent slot; declared never")
    A("qualifies, synthetic never transfers (the lambda_min law).")
    A("")
    A("## 5. Reach and wrap (what IS derivable in-record)")
    A("")
    A(f"- Recorded fingertip span (5 supported fingertips, hand frame): "
      f"{fmt(wrap['recorded_fingertip_span_m'])} m; pair {wrap['span_pair'][0]} - "
      f"{wrap['span_pair'][1]}.")
    A(f"- Declared trunk diameter: {fmt(wrap['declared_trunk_diameter_m'])} m; margin "
      f"{fmt(wrap['margin_m'])} m.")
    A(f"- Recorded-configuration wrap verdict: "
      f"{by_clause['recorded-configuration wrap of the declared trunk']['verdict']} "
      "(scope: " + wrap["scope"] + ").")
    A(f"- Trunk-relative reachability: UNDECIDABLE-IN-RECORDS; frame law verbatim: "
      f'"{q["frame_law_verbatim"]}"')
    A(f"- A07 carried state: outside sites {q['a07_counts']['envelope_measured_outside']} "
      f"(insertions {q['a07_counts']['outside_insertions']} + waypoints "
      f"{q['a07_counts']['outside_waypoints']}); pending assembly mappings "
      f"{q['a07_counts']['pending_assembly_mapping']}.")
    A("")
    A("## 6. C20 vertical transfer (potential-energy line only)")
    A("")
    A("| reading | per meter [J] | at S1 facet height [J] | full trunk [J] |")
    A("|---|---|---|---|")
    for name in ("scene", "band_lo", "band_mid", "band_hi"):
        pe = d["pe_line"][name]
        A(f"| {name} | {fmt(pe['per_meter_J'])} | {fmt(pe['at_facet_height_J'])} | "
          f"{fmt(pe['full_trunk_J'])} |")
    A("")
    A("Dynamic transfer is UNDECIDABLE-IN-RECORDS: the support sequence, adopted-assembly")
    A("inertia, transfer trajectory and losses are absent (x_sequence, x_inertia,")
    A("x_trajectory, x_losses). Static support is necessary, not proof of climbing.")
    A("")
    A("## 7. Moment disclosures (templates; x_com and x_trunk_strength ABSENT)")
    A("")
    A(f"- Demonstrated cases carry zero external moment: "
      f'"{d["moment_disclosures"]["demonstrated_case_external_moment"]}".')
    A("- Root-moment template at the pinned S1 facet height "
      f"{fmt(d['moment_disclosures']['s1_facet_height_m'])} m: "
      + "; ".join(f"{k} {fmt(v)} N*m" for k, v in
                  d["moment_disclosures"]["root_moment_template_N_m"].items()) + ".")
    A("- Hold-moment template probes recorded at x_com = 0 and x_com = span/2 in the "
      "receipt (arithmetic disclosures, never feasibility claims).")
    A(f"- Trunk-side reaction state: the declared trunk admits any reaction BY DECLARATION "
      f"ONLY (rigid-and-rooted, RED-1); no measured trunk strength exists in any pinned "
      f"source (C17 study verdict found: {str(q['c17_no_measured_pin_verbatim']).lower()}).")
    A("")
    A("## 8. Falsifier proof (clean control FIRST, then the bite)")
    A("")
    A("| arm | guard (clean) | mutation | caught | observed |")
    A("|---|---|---|---|---|")
    for a in f["arms"]:
        A(f"| {a['arm']} | {a['guard']}: "
          f"{'PASS' if a['clean_control']['green'] else 'FAIL'} | {a['mutation']} | "
          f"{'CAUGHT' if a['caught'] else 'MISSED'} | {'; '.join(a['observed'][:3])} |")
    A("")
    A("## 9. Determinism and named-check accounting")
    A("")
    A(f"- X2 determinism: feasibility_receipt.json and feasibility_receipt_rerun2.json are "
      f"byte-identical (sha256 "
      f"{hashlib.sha256((HERE / 'feasibility_receipt.json').read_bytes()).hexdigest()}).")
    A(f"- Named checks: {executed if executed is not None else 'pending'} executed, "
      f"{skipped if skipped is not None else 'pending'} skipped (test_g01_checks.py; "
      "no KNOWN_SKIPS entries).")
    A(f"- Input pins verified at run time: {len(r['input_pins'])} "
      "(sha256 re-verified against PREREGISTRATION.md section 5; refusals: "
      "input_pin_missing, input_pin_drift).")
    A(f"- Ports honesty context carried: {q['ports_qualified']}/{q['ports_total']} ports "
      "qualified (honest refusal record); 24/24 waypoint refusals re-executed record "
      f"(verbatim counts found: {str(q['port_counts_verbatim_found']).lower()}, "
      f"24/24 re-execution line found: "
      f"{str(q['waypoint_refusal_24_of_24_found']).lower()}).")
    A("")
    A("## 10. Honest limitations")
    A("")
    A("- The verdict is a RECORD-SPACE derivation: no runtime scene co-instantiates the")
    A("  trunk with any creature body (the adopted assembly has no runtime scene module),")
    A("  and none is created here.")
    A("- mu_s = 0.6 is the declared placeholder (acquisition_prerequisite G04); every")
    A("  capacity number inherits it linearly.")
    A("- The equal-share case analysis is a model of the balance, not a measured load")
    A("  partition (x_share ABSENT).")
    A("- The scene and biological-reference body readings stay DISTINCT ledgers; verdicts")
    A("  are recorded per reading, never averaged.")
    A("- The 39 sealed osim Fmax rows are declared carriers with force_runtime_ready")
    A("  false (A08-U1); they bound nothing and are used as bounds nowhere in this")
    A("  derivation. The scene drive caps (fore shoulder / fore elbow) carry the TC-3")
    A("  never-transfer law and are likewise not consumed as bounds.")
    A("- GAP-1 (muscle placeholders), GAP-5 (palm friction), GAP-6 (C17 inputs lawfully")
    A("  absent), GAP-9 (missing duty-factor channel) are inherited, not repaired.")
    A("")
    A("## 11. Refused steps recorded (none silent)")
    A("")
    A("- The dispatch's paraphrase of upstream F03 (\"forearm package ... fictional-")
    A("  Chimanoid falsifier history\") does not match the sealed store; per the card's")
    A("  own instruction the wave brief and the store govern: F03 is the one-rigid-")
    A("  climbable-trunk package (PR #248). Recorded in PREREGISTRATION.md section 3;")
    A("  no upstream record was modified.")
    A("- Reconciliation of the two mass systems: refused upstream by the sealed register")
    A(f"  ({q['massreg_reconciliation_verbatim']}); this derivation splits verdicts per")
    A("  reading instead.")
    A("- No transform was composed between the hand frame and any trunk/world frame")
    A("  (A09 frame law); reachability of trunk contacts is carried as x_reach.")
    A("")
    A("## 12. File identities (sha256 at report freeze time)")
    A("")
    A("| file | sha256 |")
    A("|---|---|")
    for p in sorted(HERE.iterdir()):
        if p.is_file() and p.name != "REPORT.md":
            A(f"| {p.name} | {hashlib.sha256(p.read_bytes()).hexdigest()} |")
    A("")

    report = "\r\n".join(lines) + "\r\n"
    (HERE / "REPORT.md").write_bytes(report.encode("utf-8"))
    print(f"wrote REPORT.md sha256 {hashlib.sha256(report.encode('utf-8')).hexdigest()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
