// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "MissionData.generated.h"

USTRUCT()
struct FMissionObjective
{
	GENERATED_BODY()

	UPROPERTY() FString Type;
	UPROPERTY() FName Commodity;
	UPROPERTY() int32 Quantity;
	UPROPERTY() FName Station;
	UPROPERTY() int32 Count;
	UPROPERTY() bool bComplete;
};

USTRUCT()
struct FMissionData
{
	GENERATED_BODY()

	UPROPERTY() FName MissionID;
	UPROPERTY() FString Type;
	UPROPERTY() FString Description;
	UPROPERTY() TArray<FMissionObjective> Objectives;
	UPROPERTY() int32 CurrentObjectiveIndex;
	UPROPERTY() float RewardCredits;
	UPROPERTY() FName FactionID;
	UPROPERTY() float StandingChange;
	UPROPERTY() FString Status;
};

