// Generated by GameCodeGenerator
#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "MissionData.h"
#include "MissionComponent.generated.h"

UCLASS( meta = (BlueprintType, Category = "Missions") )
class CHIMERA_API UMissionComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UMissionComponent(const FObjectInitializer& ObjectInitializer);

	UPROPERTY() TArray<FMissionData> ActiveMissions;
	UPROPERTY() TArray<FName> CompletedMissions;
	UPROPERTY() TArray<FName> FailedMissions;
	UPROPERTY() TArray<FMissionData> AvailableMissions;

public:
	UFUNCTION(BlueprintCallable, Category = "Mission")
	void AcceptMission(FName MissionID);

	UFUNCTION(BlueprintCallable, Category = "Mission")
	void UpdateObjective(FString ObjectiveType, FString Parameter);

	UFUNCTION(BlueprintImplementableEvent, Category = "Mission|Events")
	void CompleteMission(FName MissionID);

	UFUNCTION(BlueprintImplementableEvent, Category = "Mission|Events")
	void FailMission(FName MissionID, const FString& Reason);

public:
	void CheckMissionBoard(FName StationID, TArray<FMissionData>& OutMissions);

	void GetActiveMissions(TArray<FMissionData>& OutMissions) const;
};
