// Generated by GameCodeGenerator
#include "MissionComponent.h"
#include "../Factions/FactionComponent.h"

UMissionComponent::UMissionComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}

void UMissionComponent::AcceptMission(FName MissionID)
{
	// Find mission in AvailableMissions, move to ActiveMissions, set Status = "Active"
}

void UMissionComponent::UpdateObjective(FString ObjectiveType, FString Parameter)
{
	// Find current active objective in current mission
	// Check if parameter matches (commodity, station, quantity)
	// If match: mark objective complete, increment CurrentObjectiveIndex
	// If all objectives complete: CompleteMission()
}

void UMissionComponent::CheckMissionBoard(FName StationID, TArray<FMissionData>& OutMissions)
{
	OutMissions.Empty();
	// Return missions available at this station
}

void UMissionComponent::GetActiveMissions(TArray<FMissionData>& OutMissions) const
{
	OutMissions = ActiveMissions;
}
