// Generated by GameCodeGenerator
#pragma warning(disable: 5038)
#pragma warning(disable: 4996)
#include "ShelterHabitatComponent.h"
#include "Engine/World.h"
#include "GameFramework/Actor.h"
#include "GameFramework/Pawn.h"
#include "GameFramework/Character.h"
#include "Components/SphereComponent.h"
#include "../Suit/SuitLifeSupportComponent.h"
#include "Kismet/GameplayStatics.h"

UShelterHabitatComponent::UShelterHabitatComponent()
{
	PrimaryComponentTick.bCanEverTick = true;
	ShelterRadius = 300.0f;
	bShelterActive = false;
	bGeometryInitialized = false;
	bMaterialsApplied = false;
	bLightingSetup = false;
	ShelterTrigger = nullptr;
	bLastFramePlayerInside = false;
}

void UShelterHabitatComponent::BeginPlay()
{
	Super::BeginPlay();
	InitializeHabitatGeometry();
	ApplyHabitatMaterials();
	SetupHabitatLighting();
	SetupShelterTrigger();
	bShelterActive = true;
	bLastFramePlayerInside = false;

	// Force-enable tick. Blueprint SCS components may not auto-enable.
	SetComponentTickEnabled(true);
}

void UShelterHabitatComponent::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	// Clear the bInShelter flag on any pawns that were inside when the shelter is destroyed
	if (ShelterTrigger)
	{
		TArray<AActor*> OverlappingActors;
		ShelterTrigger->GetOverlappingActors(OverlappingActors, APawn::StaticClass());

		for (AActor* Actor : OverlappingActors)
		{
			if (APawn* Pawn = Cast<APawn>(Actor))
			{
				if (USuitLifeSupportComponent* Suit = Pawn->FindComponentByClass<USuitLifeSupportComponent>())
				{
					Suit->bInShelter = false;
					Suit->bAtOxygenGarden = false;
					Suit->bAtBatteryBank = false;
				}
			}
		}
	}
	Super::EndPlay(EndPlayReason);
}

void UShelterHabitatComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	// Proximity check: every tick, measure distance from this shelter's owner
	// to the player pawn. If within ShelterRadius, set refill flags.
	// Uses direct distance calculation — reliable regardless of collision config.
	if (bShelterActive && GetOwner())
	{
		UWorld* World = GetWorld();
		if (World)
		{
			APlayerController* PC = UGameplayStatics::GetPlayerController(World, 0);
			APawn* PlayerPawn = PC ? PC->GetPawn() : nullptr;

			if (PlayerPawn)
			{
				const float DistSq = FVector::DistSquared(GetOwner()->GetActorLocation(), PlayerPawn->GetActorLocation());
				const bool bPlayerInside = (DistSq <= ShelterRadius * ShelterRadius);

				if (bPlayerInside != bLastFramePlayerInside)
				{
					bLastFramePlayerInside = bPlayerInside;

					if (USuitLifeSupportComponent* Suit = PlayerPawn->FindComponentByClass<USuitLifeSupportComponent>())
					{
						if (bPlayerInside)
						{
							Suit->bInShelter = true;
							Suit->bAtOxygenGarden = true;
							Suit->bAtBatteryBank = true;
							UE_LOG(LogTemp, Display, TEXT("[Materialize] Shelter proximity: Player ENTERED shelter (dist=%.1f, radius=%.1f)"),
								FMath::Sqrt(DistSq), ShelterRadius);
						}
						else
						{
							Suit->bInShelter = false;
							Suit->bAtOxygenGarden = false;
							Suit->bAtBatteryBank = false;
							UE_LOG(LogTemp, Display, TEXT("[Materialize] Shelter proximity: Player LEFT shelter"));
						}
					}
				}
			}
		}
	}
}

void UShelterHabitatComponent::InitializeHabitatGeometry()
{
	if (!bGeometryInitialized)
	{
		bGeometryInitialized = true;
		UE_LOG(LogTemp, Display, TEXT("ShelterHabitat: Geometry initialized"));
	}
}

void UShelterHabitatComponent::ApplyHabitatMaterials()
{
	if (!bMaterialsApplied)
	{
		bMaterialsApplied = true;
		UE_LOG(LogTemp, Display, TEXT("ShelterHabitat: Materials applied"));
	}
}

void UShelterHabitatComponent::SetupHabitatLighting()
{
	if (!bLightingSetup)
	{
		bLightingSetup = true;
		UE_LOG(LogTemp, Display, TEXT("ShelterHabitat: Lighting setup complete"));
	}
}

void UShelterHabitatComponent::SetupShelterTrigger()
{
	if (!ShelterTrigger)
	{
		AActor* Owner = GetOwner();
		if (!Owner)
		{
			UE_LOG(LogTemp, Warning, TEXT("ShelterHabitatComponent: No owner set, cannot create trigger"));
			return;
		}

		ShelterTrigger = NewObject<USphereComponent>(Owner);
		if (ShelterTrigger)
		{
			ShelterTrigger->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
			ShelterTrigger->SetCollisionObjectType(ECC_WorldStatic);
			ShelterTrigger->SetCollisionResponseToAllChannels(ECR_Ignore);
			ShelterTrigger->SetCollisionResponseToChannel(ECC_Pawn, ECR_Overlap);
			ShelterTrigger->SetSphereRadius(ShelterRadius);
			ShelterTrigger->SetGenerateOverlapEvents(true);

			ShelterTrigger->OnComponentBeginOverlap.AddDynamic(this, &UShelterHabitatComponent::OnShelterBeginOverlap);
			ShelterTrigger->OnComponentEndOverlap.AddDynamic(this, &UShelterHabitatComponent::OnShelterEndOverlap);

			ShelterTrigger->RegisterComponent();
			ShelterTrigger->AttachToComponent(Owner->GetRootComponent(), FAttachmentTransformRules::SnapToTargetNotIncludingScale);

			UE_LOG(LogTemp, Display, TEXT("ShelterHabitat: Trigger created with radius %.1f"), ShelterRadius);
		}
	}
}

void UShelterHabitatComponent::OnShelterBeginOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
	UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	if (!bShelterActive || !OtherActor)
	{
		return;
	}

	if (APawn* Pawn = Cast<APawn>(OtherActor))
	{
		if (USuitLifeSupportComponent* Suit = Pawn->FindComponentByClass<USuitLifeSupportComponent>())
		{
			Suit->bInShelter = true;
			Suit->bAtOxygenGarden = true;
			Suit->bAtBatteryBank = true;
			UE_LOG(LogTemp, Display, TEXT("ShelterHabitat: %s entered shelter (O2/battery refill active)"), *GetNameSafe(Pawn));
		}
	}
}

void UShelterHabitatComponent::OnShelterEndOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor,
	UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	if (!OtherActor)
	{
		return;
	}

	if (APawn* Pawn = Cast<APawn>(OtherActor))
	{
		if (USuitLifeSupportComponent* Suit = Pawn->FindComponentByClass<USuitLifeSupportComponent>())
		{
			Suit->bInShelter = false;
			Suit->bAtOxygenGarden = false;
			Suit->bAtBatteryBank = false;
			UE_LOG(LogTemp, Display, TEXT("ShelterHabitat: %s left shelter (O2/battery refill ended)"), *GetNameSafe(Pawn));
		}
	}
}
