// Generated by GameCodeGenerator
#include "ShelterHabitatComponent.h"
#include "Engine/World.h"
#include "GameFramework/Actor.h"

UShelterHabitatComponent::UShelterHabitatComponent()
{
	PrimaryComponentTick.bCanEverTick = true;
	MaxOccupants = 10;
	LifeSupportCapacity = 500.0f;
	bGeometryInitialized = false;
	bMaterialsApplied = false;
	bLightingSetup = false;
}

void UShelterHabitatComponent::BeginPlay()
{
	Super::BeginPlay();
	InitializeHabitatGeometry();
	ApplyHabitatMaterials();
	SetupHabitatLighting();
}

void UShelterHabitatComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
	// Life support and habitat maintenance logic
}

void UShelterHabitatComponent::InitializeHabitatGeometry()
{
	if (!bGeometryInitialized)
	{
		bGeometryInitialized = true;
		UE_LOG(LogTemp, Display, TEXT("ShelterHabitat: Geometry initialized"));
	}
}

void UShelterHabitatComponent::ApplyHabitatMaterials()
{
	if (!bMaterialsApplied)
	{
		bMaterialsApplied = true;
		UE_LOG(LogTemp, Display, TEXT("ShelterHabitat: Materials applied"));
	}
}

void UShelterHabitatComponent::SetupHabitatLighting()
{
	if (!bLightingSetup)
	{
		bLightingSetup = true;
		UE_LOG(LogTemp, Display, TEXT("ShelterHabitat: Lighting setup complete"));
	}
}
