"""MAT2-G08 report generator (house pattern: the report is GENERATED from
the bound receipts; zero hand-transcribed numbers; every float is rendered
at its recorded precision and lint-verified by lint_report_numbers.py).

Run: python -B make_report.py
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

CARD_ID = 'G08'
CARD_FULL = 'MAT2-G08'


def load(name):
    return json.loads((HERE / name).read_text(encoding='utf-8'))


def f(x):
    """Render a float at its recorded precision (repr), integers as ints."""
    if isinstance(x, bool):
        return 'True' if x else 'False'
    if isinstance(x, int):
        return str(x)
    return repr(x)


def sha(path):
    return hashlib.sha256((HERE / path).read_bytes()).hexdigest()


def main():
    r = load('experiment_receipt.json')
    det = load('determinism_receipt.json')
    fal = load('falsifier_receipt.json')
    reg = load('regression_receipt.json')
    chk = load('checks_receipt.json')
    led = r['A4_evidence']
    budget = r['A9_evidence']
    refmath = r['A7_evidence']
    seam = r['A8_evidence']
    cont = r['A5_evidence']

    lines = []
    w = lines.append
    w('# MAT2-G08 report - qualify climbing dynamics and numerical budget')
    w('')
    w('GENERATED by make_report.py from the bound receipts; every number is '
      'rendered at recorded precision and lint-verified '
      '(lint_report_numbers.py). Composed against CARD_STARTER.md v3; house '
      'standards IMPLEMENTER_CHECKLIST.md (G1-G9) and TOOLKIT.md (P1-P9) '
      'cited at the candidate commit. CPU-only; the capture is a rendered '
      'fixture view, not a screenshot substitute (the profile numerical '
      'evidence is the receipt suite).')
    w('')
    w('## 1. done_when verification (verbatim clause -> evidence) and the '
      'assembly verdict table')
    w('')
    w('done_when (verbatim): "Accepted mechanics pass CPU/GPU and runtime '
      'identity gates relevant to climbing"')
    w('')
    w('| gate | verdict | evidence |')
    w('| --- | --- | --- |')
    a_rows = [
        ('A1 line_identity (the assembled line reproduces the certified '
         'G06/G07 rows byte-exactly; structural facts exact)', 'A1',
         '%s of %s identity blocks green' % (
             sum(1 for b in r['A1_evidence']['t'] + r['A1_evidence']['r']
                 if b['identity_ok']),
             len(r['A1_evidence']['t']) + len(r['A1_evidence']['r']))),
        ('A2 transfer_envelope (the sealed G06 envelope re-passes assembled;'
         ' verdicts == certified boundary table)', 'A2', 'A1_evidence.t'),
        ('A3 release_and_fall (the sealed G07 release account re-passes '
         'assembled; collision events bind)', 'A3', 'A1_evidence.r'),
        ('A4 unsupported_ledger (the union support ledger; every '
         'unsupported tick carries a declared response class)',
         'A4', 'A4_evidence'),
        ('A5 continuity (the sealed flight-window advance law over every '
         'assembled transfer run)', 'A5', 'A5_evidence'),
        ('A6 event_localization (handover %s, reattach %s, T release %s, '
         'R flip %s; the certified CCD events)' % (
             f(r['A6_evidence']['t_handover_ticks'][0]),
             f(r['A6_evidence']['t_reattach_ticks'][0]),
             f(r['A6_evidence']['t_release_start_ticks'][0]),
             f(r['A6_evidence']['r_release_flip_ticks'][0])),
         'A6', 'A6_evidence'),
        ('A7 reference_math (record-g vs standard-g no-flip; the jn/DT '
         'conversion at the established operating points)', 'A7',
         'A7_evidence'),
        ('A8 seam_union (the union census equals the certified census '
         'exactly)', 'A8', 'A8_evidence'),
        ('A9 numerical_budget (every operation inside its frozen window)',
         'A9', 'A9_evidence'),
        ('A10 determinism (two fresh full runs byte-identical)', 'A10',
         'determinism_receipt.json'),
    ]
    for text, key, ev in a_rows:
        flag = r['%s_%s' % (key, {'A1': 'line_identity',
                                  'A2': 'transfer_envelope',
                                  'A3': 'release_and_fall',
                                  'A4': 'unsupported_ledger',
                                  'A5': 'continuity',
                                  'A6': 'event_localization',
                                  'A7': 'reference_math',
                                  'A8': 'seam_union',
                                  'A9': 'numerical_budget'}.get(key, ''))] \
            if key != 'A10' else det['trace_byte_identical']
        w('| %s | %s | %s |' % (text, 'PASS' if flag else 'FAIL', ev))
    w('| P-class (seam law; named-variable law; prereg identity; matter '
      'identity; input pins) | %s | receipt p_class + matter_identity + '
      'input_pins |' % ('PASS' if r['criteria_registry_match'] and
                        r['vacuous_guard_selftest'] and
                        not r['p_class']['x_namespace_delivered'] else
                        'FAIL'))
    w('| named checks (test_g08_checks) | %s | checks_receipt.json '
      '(suite exit %s) |' % ('PASS' if chk['named_checks_green'] else 'FAIL',
                             f(chk['suite_exit'])))
    w('| falsifiers FB1-FB5 (clean control first) | %s | '
      'falsifier_receipt.json |' % ('PASS' if fal['F_all_green'] else
                                    'FAIL'))
    w('| regression (M06, G04, G05, G06, G07, G01 suites unmodified) | %s '
      '| regression_receipt.json |' % (
          'PASS' if reg['P_regression_suite_green'] else 'FAIL'))
    w('')
    w('Verdict: the accepted climbing mechanics (G04 grip, G05 observation, '
      'G06 supported transfer, G07 release/fall, G01 boundary, F05 matter '
      'declarations) PASS the assembled CPU identity gates; the GPU '
      'device-leg parity for the climb contact path is UNRESOLVED and is '
      'not claimed (section 7).')
    w('')
    w('## 2. The composed battery and the line identity')
    w('')
    w('- battery: %s T-segment scenarios x %s ticks + %s R-segment '
      'scenarios x %s ticks = %s assembled ticks in ONE deterministic '
      'process.' % (f(len(r['battery']['t_scenarios'])),
                     f(r['battery']['t_ticks_each']),
                     f(len(r['battery']['r_scenarios'])),
                     f(r['battery']['r_ticks_each']),
                     f(r['battery']['total_ticks'])))
    t_blocks = r['A1_evidence']['t']
    r_blocks = r['A1_evidence']['r']
    w('- line identity: %s/%s T row hashes and %s/%s R row hashes equal '
      'the certified pinned traces byte-for-byte; the transfer verdicts '
      'equal the certified boundary table; the band_mid|n=3 schedule marks '
      'equal the certified schedule.' % (
          f(sum(1 for b in t_blocks if b['row_hash_ok'])), f(len(t_blocks)),
          f(sum(1 for b in r_blocks if b['row_hash_ok'])),
          f(len(r_blocks))))
    w('- the walking certification is NOT inherited (card observation): '
      'the assembled line carries its own tick-level support ledger.')
    w('')
    w('## 3. The union support ledger (the W09-disclosure handling)')
    w('')
    w('| quantity | value |')
    w('| --- | --- |')
    for k in ('total_ticks', 'supported', 'unsupported'):
        w('| %s | %s |' % (k, f(led[k])))
    w('| declared_release | %s |' % f(led['response_classes'][
        'declared_release']))
    w('| declared_establishing | %s |' % f(led['response_classes'][
        'declared_establishing']))
    w('| declared_solver_slip | %s |' % f(led['response_classes'][
        'declared_solver_slip']))
    w('| declared_flight_hover | %s |' % f(led['response_classes'][
        'declared_flight_hover']))
    w('')
    w('Every unsupported tick carries exactly one declared response class; '
      'the class registry (amendment a1) is declared_release, '
      'declared_solver_slip, declared_flight_hover, declared_establishing; '
      'zero ticks are unexplained.')
    w('')
    w('## 4. The numerical budget (C09 deliverable; frozen windows, '
      'MEASURED values)')
    w('')
    w('| operation | frozen window | measured worst | margin | within |')
    w('| --- | --- | --- | --- | --- |')
    for op in budget['operations']:
        w('| %s | %s | %s | %s | %s |' % (
            op['operation'], f(op['window']), f(op['measured_worst']),
            f(op['margin']), 'True' if op['within_window'] else 'False'))
    tm = budget['tightest_margin_operation']
    w('')
    w('Tightest margin: %s (margin %s of window %s, measured %s). No '
      'window was widened.' % (tm['operation'], f(tm['margin']),
                               f(tm['window']), f(tm['measured_worst'])))
    w('')
    w('Reference math: any_flip %s; conversion worst %s N (window %s N); '
      'worst no-flip margin %s N*s.' % (
          f(refmath['any_flip']), f(refmath['conversion_worst_N']),
          f(refmath['conversion_window_N']), f(refmath['worst_margin_Ns'])))
    w('Continuity (T flight windows): worst %s m (window %s m).' % (
        f(cont['worst_m']), f(cont['window'])))
    w('')
    w('## 5. Seam union (A8)')
    w('')
    w('| census | measured | certified |')
    w('| --- | --- | --- |')
    for k, mv in seam['measured_vs_certified'].items():
        w('| %s | %s | %s |' % (k, f(mv['measured']), f(mv['certified'])))
    w('')
    w('G05-composition refusal codes on the T segment: %s (the pinned G05 '
      'seam refuses the G06-only phases with timing_unbound -- the '
      'composition is real, exactly as certified).' % json.dumps(
          seam['g05_refusal_codes_t'], sort_keys=True))
    w('')
    w('## 6. Falsifiers (clean control FIRST; named premature guards)')
    w('')
    w('| arm | clean control | tampered bites | discriminator |')
    w('| --- | --- | --- | --- |')
    for arm in fal['arms']:
        w('| %s | %s | %s | %s |' % (
            arm['arm'], json.dumps(arm['clean'], sort_keys=True),
            json.dumps({k: v for k, v in arm['tampered'].items()
                        if k != 'bites'}, sort_keys=True),
            arm['discriminator']))
    w('')
    w('F_all_green = %s over %s arms.' % (f(fal['F_all_green']),
                                          f(len(fal['arms']))))
    w('')
    w('## 7. CPU/GPU and runtime identity inventory (honest scoping)')
    w('')
    inv = r['inventory']
    w('- CPU identity gates CERTIFIED HERE: ' + '; '.join(
        inv['cpu_identity_gates_certified_here']) + '.')
    g = inv['gpu_device_leg_climb_contact_parity']
    w('- GPU device-leg parity for the climb contact path: %s -- %s' % (
        g['status'], g['reason']))
    e = inv['engine_device_leg_anchors']
    w('- Engine device-leg anchors (W03 freefall/stand/C1/C2): %s -- %s' % (
        e['status'], e['reason']))
    w('- C05 joint kinematics: %s -- %s' % (inv['c05_joint_kinematics']
                                            ['status'],
                                            inv['c05_joint_kinematics']
                                            ['reason']))
    w('- C06 creature articulated chain: %s -- %s' % (
        inv['c06_articulated_chain']['status'],
        inv['c06_articulated_chain']['reason']))
    w('')
    w('## 8. Determinism, regression, accounting')
    w('')
    w('- X2: trace byte-identical across two fresh runs (%s); trace sha '
      '%s; receipt delta scoped to the declared augmentation keys %s.' % (
          f(det['trace_byte_identical']), det['trace_sha_main'][:12],
          json.dumps(det['receipt_delta_keys'])))
    w('- Regression: %s upstream suites re-ran UNMODIFIED on this revision '
      '(exit 0 each): %s.' % (f(len(reg['suites'])),
                              '; '.join(s['suite'] for s in reg['suites'])))
    w('- F05 non-execution disclosure: %s (%s)' % (
        f(reg['f05_note']['executed']), reg['f05_note']['reason']))
    w('- Named checks: the test_g08_checks suite ran in-process (see '
      'checks_receipt.json, suite exit %s); the 12-gate batch re-runs it '
      'on the host.' % f(chk['suite_exit']))
    w('- Matter identity (P1): trunk %s %s/%s; pads %s/%s; F05 rows '
      '%s/%s and %s/%s under the elementwise-min pair rule.' % (
          r['matter_identity']['trunk_matter'],
          f(r['matter_identity']['trunk_mu_s']),
          f(r['matter_identity']['trunk_mu_k']),
          f(r['matter_identity']['pad_mu_s']),
          f(r['matter_identity']['pad_mu_k']),
          f(r['matter_identity']['f05_trunk_row'][0]),
          f(r['matter_identity']['f05_trunk_row'][1]),
          f(r['matter_identity']['f05_probe_row'][0]),
          f(r['matter_identity']['f05_probe_row'][1])))
    w('')
    w('## 9. Capture identity (grasp/motion profile)')
    w('')
    try:
        capman = load('evidence/capture/capture_manifest.json')
        capctx = load('evidence/capture/capture_context.json')
        val = load('evidence/capture/capture_validation_receipt.json')
        rechk = load('evidence/capture/capture_recheck_receipt.json')
        cams = load('evidence/capture/cameras.json')
        oracle_max = max(o['delta_px'] for o in cams['oracle'])
        w('- FFV1 `-level 3 -g 1 -fflags +bitexact` mkv (rgb24), '
          'capture_sha256 %s; ffmpeg: %s.' % (
              capman['capture_sha256'], capman['ffmpeg_version']))
        w('- Frames: %s declared story beats on the composed axis %s at 1 '
          'video second per frame; state hash identical across each '
          'diagnostic/clean pair.' % (
              f(len(capman['frame_manifest'])),
              json.dumps(capman['tick_interval'])))
        w('- Reprojection oracle max delta %s px; decode identity '
          're-proven per frame (%s frames, all_identity %s).' % (
              f(oracle_max), f(len(rechk['frames'])),
              f(rechk['all_frames_decoded_identity'])))
        w('- validate_manifest: structurally_valid %s; visual_acceptance '
          '%s BY DESIGN (independent visual review remains the Sergeant '
          'gate); visual_gate.verify structurally_valid %s.' % (
              f(val['validate_manifest']['structurally_valid']),
              f(val['validate_manifest']['visual_acceptance']),
              f(val['visual_gate_verify']['structurally_valid'])))
        w('- This text-only worker inspected no pictures: pixel claims are '
          'MEASURED (per-frame exact-color counts, re-measured from the '
          'decoded video at identity) and image review is owned by the '
          'Sergeant/Lieutenant.')
    except FileNotFoundError:
        w('- (capture receipts not present at report time)')
    w('')
    w('## 10. Named absent variables (never synthetic constants)')
    w('')
    w('| variable | quantity | status |')
    w('| --- | --- | --- |')
    for n in r['named_absent_variables']:
        w('| %s | %s | ABSENT |' % (n['name'], n['quantity']))
    w('')
    w('Named-variable law: the ten variables are inherited VERBATIM from '
      'the pinned G04 module; no synthetic constant occupies an absent '
      'slot; the sealed G05 seam refuses any sample whose keys enter the '
      'x_* namespace.')
    w('')
    w('## 11. Preregistration and inputs')
    w('')
    w('- preregistration chain (committed BEFORE any experiment): %s.' %
      ' -> '.join(r['prereg_commits']))
    w('- package base: %s.' % r['base_commit'])
    w('- criteria_sha256 %s identical across the registry card row (read '
      'mode=ro at run time), the dispatch and this receipt.' %
      r['criteria_sha256'])
    w('- input pins verified at run time: %s host pins (refusals: '
      'input_pin_missing / input_pin_drift); the repo pin table resolved '
      'from the base tree.' % f(len(r['input_pins']['host'])))
    w('- dev-run disclosures: DEV_RUN_REFUSALS.md (candidate-scoped; no '
      'refusal codes beyond the prereg section 13 registry fired).')
    w('')
    w('## 12. Artifact identity')
    w('')
    w('| artifact | sha256 |')
    w('| --- | --- |')
    for name in ('experiment_receipt.json', 'experiment_trace.json',
                 'determinism_receipt.json', 'falsifier_receipt.json',
                 'regression_receipt.json', 'checks_receipt.json'):
        w('| %s | %s |' % (name, sha(name)))
    w('')
    w('## 13. Honest limitations')
    w('')
    w('- The card QUALIFIES the assembled fixture mechanics; the '
      'creature-side grasp (reach, aperture, actuator bounds, tendons, '
      'joints) is NOT claimed: x_press, x_share, x_aperture, x_reach, '
      'x_com, x_inertia, x_trajectory, x_sequence, x_losses, '
      'x_trunk_strength stay ABSENT with verbatim provenance (G01/G04 '
      'inheritance). No creature body exists in this fixture and none is '
      'faked.')
    w('- NO impact landing is modeled or claimed: no floor body exists in '
      'this fixture; falls descend alongside the trunk inside the declared '
      'windows (the G07 honest limitation, inherited).')
    w('- mu_s = 0.6 / mu_k = 0.4 remain the NAMED placeholders of the '
      'sealed upstream; the measured-volar acquisition stays G04 recorded '
      'debt and is not re-opened here.')
    w('- The GPU device-leg parity for the climb contact path is '
      'UNRESOLVED (section 7) and is not claimed by this card.')
    w('- Amendment a1 (pre-experiment, committed): the declared response '
      'class registry gained declared_establishing; the composition '
      'binding window (1e-9) was declared; the A4 ledger clarification. '
      'Nothing frozen changed verdict laws, windows, battery or '
      'falsifiers.')
    w('')
    (HERE / 'REPORT.md').write_text('\n'.join(lines) + '\n',
                                    encoding='utf-8')
    print('REPORT.md written: %s lines' % f(len(lines)))


if __name__ == '__main__':
    main()
