// Generated by GameCodeGenerator
#include "Projectile.h"
#include "Components/SphereComponent.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "NiagaraFunctionLibrary.h"
#include "NiagaraSystem.h"

AProjectile::AProjectile(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer),
	Damage(50.0f), Speed(100000.0f), Range(300000.0f), TrackingStrength(0.0f), DistanceTraveled(0.0f) {
	CollisionSphere = CreateDefaultSubobject<USphereComponent>(TEXT("CollisionSphere"));

	RootComponent = CollisionSphere;
	CollisionSphere->InitSphereRadius(50.0f);

#if WITH_EDITORONLY_DATA
	CollisionSphere->SetHiddenInGame(true, true);
#endif
}

void AProjectile::BeginPlay() {
	Super::BeginPlay();
	if (CollisionSphere) {
		CollisionSphere->OnComponentHit.AddDynamic(this, &AProjectile::OnHit);
	}
	// Enable movement component
	GetWorld()->GetTimerManager().SetTimerForNextTick([this]() {
		UProjectileMovementComponent* MoveComp = FindComponentByClass<UProjectileMovementComponent>();
		if (MoveComp) {
			MoveComp->Activate(true);
		}
	});
}

void AProjectile::Tick(float DeltaSeconds) {
	Super::Tick(DeltaSeconds);

	DistanceTraveled += Speed * DeltaSeconds;
	if (DistanceTraveled > Range) {
		Destroy();
		return;
	}

	// Tracking logic: if tracking > 0 and target valid, interpolate velocity toward target
	if (TrackingStrength > 0.0f && TargetReference.IsValid()) {
		AActor* Target = TargetReference.Get();
		if (Target) {
			FVector TargetLocation = Target->GetActorLocation();
			FVector CurrentLocation = GetActorLocation();
			FVector DesiredDirection = (TargetLocation - CurrentLocation).GetSafeNormal();
			// Interpolate velocity toward target based on TrackingStrength
		}
	}
}

void AProjectile::OnHit(UPrimitiveComponent* HitComp, AActor* OtherActor, UPrimitiveComponent* OtherComp, FVector NormalImpulse, const FHitResult& Hit) {
	if (OtherActor && OtherActor != this->GetOwner()) {
		// Find UDamageComponent on OtherActor and call ApplyDamage
		// TODO: Replace with actual Niagara system
		// UNiagaraSystem* ImpactVFX = LoadObject<UNiagaraSystem>(nullptr, TEXT("/Game/VFX/NS_ProjectileImpact"));
		// UNiagaraFunctionLibrary::SpawnSystemAtLocation(GetWorld(), ImpactVFX, Hit.ImpactPoint);
	}
	Destroy();
}