// Generated by GameCodeGenerator from deep_space_trader.chimera
#include "ShipAttributeSpecComponent.h"

UShipAttributeSpecComponent::UShipAttributeSpecComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	DefaultAbilities = { TEXT("GA_Thrust"), TEXT("GA_QuantumJump"), TEXT("GA_FireWeapon") };
	StatusEffects = { TEXT("GE_HullBreach"), TEXT("GE_EngineOverheat") };
	HitReactions = { TEXT("shield_flare"), TEXT("hull_spark"), TEXT("system_damage") };
	DamageFormulas = { TEXT("kinetic: raw - shield_absorb"), TEXT("energy: raw * (1 - resist)") };
}

float UShipAttributeSpecComponent::ComputeFuelUseLiters(float DistanceKm) const
{
	return FMath::Max(0.0f, DistanceKm) * ConsumptionRatePerKm;
}

float UShipAttributeSpecComponent::ClampSpeedKmh(float RequestedKmh) const
{
	return FMath::Clamp(RequestedKmh, 0.0f, MaxSpeedKmh);
}

float UShipAttributeSpecComponent::TurnDegreesIn(float Seconds) const
{
	return TurnRateDegPerSec * FMath::Max(0.0f, Seconds);
}

bool UShipAttributeSpecComponent::ValidateSpec() const
{
	const bool bGas = !AbilitySystemComponent.IsEmpty() && !AttributeSet.IsEmpty()
		&& DefaultAbilities.Num() > 0 && StatusEffects.Num() >= 0
		&& HitReactions.Num() > 0 && DamageFormulas.Num() > 0;
	const bool bStats = !FuelStat.IsEmpty() && !CargoWeightStat.IsEmpty();
	return bGas && bStats && MaxSpeedKmh > 0.0f;
}
