// Generated by GameCodeGenerator
#include "SystemDamageComponent.h"

USystemDamageComponent::USystemDamageComponent(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer), SubsystemDamageThreshold(0.1f) {
}

void USystemDamageComponent::BeginPlay() {
	Super::BeginPlay();
}

void USystemDamageComponent::InitializeFromShip(const TArray<FName>& SystemNames) {
	// Default subsystems
	SubsystemHealth.Add(TEXT("Engines"), 100.0f);
	SubsystemMaxHealth.Add(TEXT("Engines"), 100.0f);
	SubsystemHealth.Add(TEXT("Weapons"), 100.0f);
	SubsystemMaxHealth.Add(TEXT("Weapons"), 100.0f);
	SubsystemHealth.Add(TEXT("LifeSupport"), 100.0f);
	SubsystemMaxHealth.Add(TEXT("LifeSupport"), 100.0f);

	// Additional subsystems from DSL
	for (const FName& SysName : SystemNames) {
		if (!SubsystemHealth.Contains(SysName)) {
			SubsystemHealth.Add(SysName, 100.0f);
			SubsystemMaxHealth.Add(SysName, 100.0f);
		}
	}
}

void USystemDamageComponent::ApplySystemDamage(float IncomingHullDamage) {
	float SubsystemDamage = IncomingHullDamage * SubsystemDamageThreshold;

	// Select random subsystem weighted by health and apply damage
	for (TPair<FName, float>& Pair : SubsystemHealth) {
		if (Pair.Value > 0.0f) {
			float DamageToApply = FMath::Min(SubsystemDamage, Pair.Value);
			Pair.Value -= DamageToApply;
			SubsystemDamage -= DamageToApply;

			// Apply penalties based on subsystem type:
			if (Pair.Key == TEXT("Engines") || Pair.Key == TEXT("Fuel_Tank")) {
				float HealthPercent = Pair.Value / SubsystemMaxHealth[TEXT("Engines")];
				if (HealthPercent < 0.25f) {
					// Engines/Fuel_Tank < 25%: reduce thrust to 30%
				} else if (HealthPercent < 0.5f) {
					// Engines/Fuel_Tank < 50%: reduce max speed by 40%
				}
			} else if (Pair.Key == TEXT("Quantum_Engine") || Pair.Key == TEXT("QuantumDrive")) {
				float HealthPercent = Pair.Value / SubsystemMaxHealth[TEXT("Quantum_Engine")];
				if (HealthPercent <= 0.0f) {
					// Quantum_Engine/QuantumDrive <= 0: cannot quantum jump
				} else if (HealthPercent < 0.5f) {
					// Quantum_Engine/QuantumDrive < 50%: double spool time
				}
			} else if (Pair.Key == TEXT("Weapons")) {
				float HealthPercent = Pair.Value / SubsystemMaxHealth[TEXT("Weapons")];
				if (HealthPercent <= 0.0f) {
					// Weapons <= 0: cannot fire
				} else if (HealthPercent < 0.5f) {
					// Weapons < 50%: double fire rate (slower)
				}
			}
		}
	}
}

void USystemDamageComponent::RepairSubsystem(FName SystemName, float Amount) {
	if (SubsystemHealth.Contains(SystemName)) {
		float NewHealth = FMath::Min(SubsystemHealth[SystemName] + Amount, SubsystemMaxHealth[SystemName]);
		SubsystemHealth[SystemName] = NewHealth;
	}
}

float USystemDamageComponent::GetSubsystemHealth(FName SystemName) const {
	if (SubsystemHealth.Contains(SystemName)) {
		return SubsystemHealth[SystemName];
	}
	return 0.0f;
}

USystemDamageComponent::ESubsystemStatus USystemDamageComponent::GetSubsystemStatus(FName SystemName) const {
	float Health = GetSubsystemHealth(SystemName);
	float MaxHealth = 100.0f;
	if (SubsystemMaxHealth.Contains(SystemName)) {
		MaxHealth = SubsystemMaxHealth[SystemName];
	}
	float Percent = MaxHealth > 0.0f ? Health / MaxHealth : 1.0f;

	if (Percent <= 0.0f) return ESubsystemStatus::Destroyed;
	if (Percent < 0.25f) return ESubsystemStatus::Critical;
	if (Percent < 0.5f) return ESubsystemStatus::Damaged;
	return ESubsystemStatus::Operational;