# PREREGISTRATION (DRAFT) — SUPPORTED LANDING: the release arm's ground transition on a declared floor fixture

Status: DRAFT authored by `wk-landing` for the Lieutenant. Per the publication
law this file is committed ALONE FIRST (separate-first; the M03/P04 law; the
K01 precedent commit `cdfaa8cc1535dbe723097aa1277385aeb2aa79d3`; the K02
precedent commit `19d0cff806969ac2ae4bf485576006c8c4091ade`) BY THE
LIEUTENANT; the committed bytes are the freeze and every emitted receipt must
embed `preregistration_sha256` of exactly those bytes and refuse any mismatch.
No implementation file, harness run, measurement or capture frame of this card
exists at draft time. Write scope of the draft: the NEW lane dir
`E:/ChimeraWork/monkey-coordination/landing/` (NO_WORKTREES law honored; no
worktree, no clone; all CPU verification through
`python -B E:/PythonChimera/tools/monkey_campaign/task_package.py seal|run`).

- Card MAT2-SUPPORTED-LANDING, agent-author `wk-landing`, lane
  `E:/ChimeraWork/monkey-coordination/landing/`. CARD IDENTITY (honest
  mapping, Lieutenant-owned): this is the Lieutenant-dispatched
  release-to-ground chain stop — the Captain's named demonstration line
  "PHYSICAL GRASP -> SUPPORTED HOLD -> RELEASE -> SUPPORTED LANDING, each
  transition evidenced" (Lieutenant event 2026-10-02T03:03:48, Captain order
  #7) — advancing the `release` member of K01's frozen first skill family
  ("attach, ascend, hold, descend, release") through its named missing
  transition: the K02 merge message records "THE SUPPORTED LANDING REMAINS
  THE NAMED MISSING TRANSITION" (PR #316 at `7c1f395a`). The ordinal mapping
  (which K-tier number this card carries) is the Lieutenant's concern and is
  fenced out of this draft (section 1). The card does NOT close the registry
  rows "K02 | Build reproducible climbing reset scenarios" or "K04 | Evaluate
  climb, hold and descend separately" (verbatim below) — reset-scenario
  authoring and descent METERING stay fenced OUT (section 1).
- Registry rows consumed (verbatim, `MONKEY_COMPLETION_MAP.md` sha256
  `0e3984578b0cae38ab435daaa77cc10559cceeadbaf9885c3f31b979a362ecae`,
  re-hashed 2026-10-02 this lane): K01 row — "K01 | Freeze the climbing skill
  specification | G08, U05 | C10, C21 | Observations, actions, reward,
  termination, success metrics, seeds, envelope and falsifiers approved before
  training | First skill family: attach, ascend, hold, descend, release";
  G07 row (the upstream measurement this card extends) — "G07 | Measure
  unsupported release and falls | G04 | C13, C20 | Loss/release of support
  removes its forces and yields accounted motion and energy | Preserve
  failures; no reset or leftover constraint concealing loss of support";
  criterion C13 row — "C13 | Falls, energy and recovery | Potential/kinetic
  energy, actuator work, contacts and dissipation | Account delta stored
  energy against work, losses and external support under the declared model |
  Lawful falls and explicit post-failure behavior | Release/impact traces; no
  residual support, teleport or hidden reset"; criterion C20 row — used only
  as the static/dynamic separation reference inherited from the G07 observer.
  Context rows NOT consumed and NOT closed: W09 ("Implement explicit
  out-of-envelope behavior ... Unsupported states and falls have a declared
  controller response"), K07, X03, X05.
- Build line: K02 is MERGED (PR #316 at `7c1f395a89687b17c6f2cf430eec994ed545a084`,
  the new astra tip — DECLARED context per the Lieutenant's 2026-10-02 chain
  stop; verified PRESENT in this checkout's local object database at draft
  time: `git cat-file -t 7c1f395a` = commit). The merged tip is the
  implementation base ONLY after the publisher refreshes a named ref and the
  implementation package verifies it by hash; a cached ref is not a claim of
  remote freshness. The K02 SEALED RECEIPTS (runner job
  `e4a9da8c3cab4cec89f9e9789dfd234b`, hash-pinned in section 8) are the
  measurement authority consumed here — they exist on sealed evidence bytes,
  independent of the merge.
- Dispatch map position: ONE CHAIN STOP — the release arm's ground transition
  (the SUPPORTED LANDING) at declared parameters, fixture-class. The grasp,
  ascent/transfer, descent metering, recovery and reset-scenario cards are NOT
  authored here.
- Criteria consumed: C13 (primary: release/impact traces; energy accounting;
  no residual support, teleport or hidden reset), C20 (the observer's
  static/dynamic separation, inherited), C21/C10 via the K01 family framing.
- RESUMPTION NOTE (honest, 2026-10-02): this lane is a post-power-failure
  resumption (Lieutenant event 2026-10-02T12:45:17: the 8 background workers
  died mid-lane; landing RESUMED as `agent_23ce4bba`). The predecessor's
  EVIDENCE.md and any partial draft did NOT survive (the lane held only
  `_scratch/`); the three surviving scratch files were hash-verified before
  any work: `scene_cpu_68aa57bd5d2fba9b0cf713cc2cf2b19ed8f52661.py` sha256
  `ce12faee34dfdcf2a7c256e91b183c62fe33815898c52aa7e90174d8d38e47b4` ==
  `tools/policy_compat/scene_cpu.py` at commit `68aa57bd5d2fba9b0cf713cc2cf2b
  19ed8f52661` ("policy_compat runner + checks 1-3 + injection suite: ALL
  GREEN", 2026-09-22), and `scene_cpu_893f06b7ff9357878e884fc3688f8629cfd85974.py`
  sha256 `7a2cb57812dd05ab99aa5605d35ceba3ee77e1b7c69c9f25fc0aa91e15026ca2` ==
  the same file at commit `893f06b7ff9357878e884fc3688f8629cfd85974`
  ("policy_compat: certificate format + declared CPU walk scene; PRE-DATA
  derivation amendment (re-freeze)", 2026-09-22) — both are W-TIER
  policy-compat SURROGATE reference copies (section 2 finding item F-4);
  `scene_cpu_w04.py` is a 0-byte truncation artifact of the failure (sha256
  `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`),
  PRESERVED as the failure record, never used. This draft was reconstructed
  from the dispatch text and the sealed records; no surviving draft text was
  consumed because none survived.

## 0. The provisional baseline and the lineage basis (applied, never approved)

THE PROVISIONAL BASELINE LAW (binding wording, carried from the K01 frozen
prereg verbatim via the K02 frozen prereg): the 10.037998 kg certified line is
the PROVISIONAL baseline for every K-tier card, PROVIDED its receipt binds the
actual body composition, mass ownership and runtime configuration. A hash
establishes identity; it does not by itself establish correct mass accounting.
Every K-tier document carries this law and the open items of section 0.2.

THE LINEAGE BASIS (recorded verbatim in every K prereg): the Captain's
standing criterion is "select body mass and ownership from authoritative
assembly evidence, never to obtain a passing result" (goal text + correction
order #3). The assembly-identity comparison
(`assembly-identity/ASSEMBLY_IDENTITY.md` sha256
`2ab248bda4db799685a5be9f446bb3e731a47b40b9db1108072cce18bafad035`,
re-hashed 2026-10-02 this lane) shows ONLY the 10.037998 kg line is a body any
sealed receipt hashes. THEREFORE this card assumes the 10.037998 kg certified
line as DYNAMICS through the certified scene reading (`READINGS_KG` scene
entry `10.037998`, the G04 sealed module's own literal), exactly as K02 did —
the landing's per-channel mass share is the G04 `share = reading_kg /
n_channels = 3.3459993333333333` kg declared trial inertia per channel
(K02 B6 wording carried). LINEAGE APPLIED PER THE CAPTAIN'S EVIDENCE
CRITERION; SUBJECT TO HIS ONE-WORD VETO. THE RESERVED DECISION STAYS OPEN in
every document: KEEP-10.038-AS-DYNAMICS | ORDER-BAND-MASS-ASSEMBLY |
ROUTE-TO-WALK-TIER-CARD (ASSEMBLY_IDENTITY section 5). No artifact of this
card closes it. The binding receipts (verified and re-hashed 2026-10-02 this
lane, section 8): `mass_register.json`
`61fb79b1bf2df8c5e1a5b1bff2ab1c4f41700de25bc7f1a114cbc78fe693cc7a`;
`RUNTIME_CONTRACT.md`
`f33c188bcb561b1946b104340cf36cba366709526c095874684529a599df338c`
(`assembly_mass_kg 10.037998000000004`, `weight_N 98.43913308670002`,
std-g = 9.80665, rec-g = 9.81 per the corpus's labeled convention);
`w04_certificate.json`
`07f05bfa982e066ae67413b04e3367c5ad7570830e99fc32edcb86cbe8d87598`;
`adoption_record.json`
`f6952e8afc778f79a0ede05b61d73dd7c3fabd68789703552cd6136e25ef0199`
(mass_law_carried.certified_walking_body_kg 10.037998 UNCHANGED;
qualification_state NOT runtime-qualified; TC-8 ports 0/8).

### 0.2 Open items preserved (unresolved assembly discrepancies; explicit)

OI-1 The TC-7 adoption digest is revision-relative, not a stable body identity
(three byte-revisions, three digests) — carried open. OI-2 Specimen class of
the scene line is `internally-inconsistent-female-band` — carried as-is, NOT
repaired here. OI-3 The two sealed mass systems stay DISTINCT; the band
5.4 / 6.15 / 6.9 kg never enters this card's dynamics as anything but the
G04 `READINGS_KG` entries' existing sealed roles (this card runs the `scene`
reading only, as K02 did). OI-4 Builder-order 14-body sum
`10.037998000000004` vs carve literal `10.037998`: declared float-floor
disclosure — carried, not silently rounded; the executable share derives from
the scene-reading literal. OI-5 The raw W03 `scene.json` bytes were not
re-hashable in the assembly-identity session — carried as unresolved. NONE of
OI-1..OI-5 is closed by this card.

### 0.3 The objective law (verbatim, binding on every outcome reading)

"DEMONSTRATED IMPOSSIBILITY CAN CLOSE AN INVESTIGATION, BUT IT CANNOT COMPLETE
THE PLAYABLE-MONKEY GOAL." Standing rule for every infeasible or non-closing
configuration encountered under this prereg: record the result, then either
identify a physically justified change WITHIN the project's authority (a
declared-synthetic parameter, a geometry choice, an actuator within anatomical
bounds — NEVER a tuned measured value) or escalate the specific decision needed
to the Lieutenant with bounded options. The playable objective stays OPEN
until the positive behavior is demonstrated. APPLIED TO THIS CARD: the
SUPPORTED LANDING measured here is a FIXTURE-CLASS transition of the certified
scene line (declared pads onto a declared floor) — it NEVER completes the
playable release-and-land objective (the grasp itself is open; section 1
fences); a supported fixture landing completes a diagnostic demonstration of
the certified contact line's ground response, nothing more.

## 1. Scope — what this card is (one chain stop: RELEASE -> GROUND CONTACT -> REST)

BEHAVIOR UNDER TEST: the RELEASE-TO-GROUND TRANSITION of the certified
scene|n=3 release arm — the G04 fixture pad set on `trunk_01.lateral`
(F01/F03 asset; the pinned trunk is the only rooted body; three tetrahedral
fixture pads, mass share `3.3459993333333333` kg per channel from the
`scene` reading `10.037998`, pressed at the declared operating point
jn = `0.3` N*s/tick/channel, jn/DT = 60.0 N) — held 20 ticks (the sealed
G07/K02 structure), released EXACTLY (press channel removed, W_press == 0.0 J
every release tick), falling 60 release ticks to FIRST CONTACT with a NEW
DECLARED FLOOR FIXTURE, then held under observation for a declared 60-tick
REST WINDOW. The card measures the four landing evidences: (i) NONPENETRATION
AT CONTACT, (ii) THE SUPPORTING IMPULSE (impact + steady support), (iii)
POST-LANDING REST STABILITY, (iv) THE IMPACT-ENERGY DESTINATION (the energy
account extended THROUGH impact — the exact point where the K02 release
account declared itself stopped-before-impact).

THE DECLARED RELEASE FIXTURE (labeled fixture, NEVER a grasp-chain claim):
the hold/release fixture is the certified G04 contact class exactly as sealed
(K01/K02 measured it): three fixture pads, the trunk rooted, the press
channel a DECLARED fixture operating point (60.0 N, never actuator-qualified;
x_press ABSENT, gap 6, TC-8 ports 0/8), pad friction the NAMED PLACEHOLDERS
mu_s 0.6 / mu_k 0.4. The fixture stands in DECLARED contact where the
recorded anatomical configuration cannot close (K01's grasp refusal: wrap
margin `-0.01733690019744087` m mu-independent; pincer mu_crit
`0.8399663223427114` > 0.6 — docket context ONLY, never re-run here). THE
LABEL: every artifact of this card says FIXTURE. No statement, number or
capture of this card is evidence about grasp closure, the anatomical hand
(the B6 hand-body problem is untouched), or the playable objective. The
release fixture's hold prefix is the G07/K02 20-tick structure RE-MEASURED
for comparability at the same operating point — it re-runs NO new hold
physics.

THE DECLARED FLOOR FIXTURE (NEW scene element, one declared body):
`landing.ground_plane` — a PINNED body (rooted, the trunk's own declared
class), matter id `declared_fixture_ground`, friction mu_s 0.6 / mu_k 0.4
(the NAMED PLACEHOLDERS, labeled — the same placeholder law as every surface
of this scene; pair rule `min()` per the sealed `pair_mu`), thickness
`SOLID_THICKNESS_M = 0.0` (the F03 heritage value the trunk uses; no shell
invented), geometry two triangles forming a horizontal plane (the
area-scaled load report needs real triangle area; the plane's extent is
declared >= 0.5 m x 0.5 m so no pad vertex can pass its boundary in-window),
placed with its upper surface through
`z_floor = min_k(lowest-vertex z of pad k at release) - d(60)` where
`d(60) = g*DT^2*(60*61/2) = 0.4488075` m (record-g g = 9.81, DT = 0.005 s —
the certified `chimera.local_contact.v1` declarations; DERIVED from pinned
constants at run, never hand-copied). The plane is declared at fixture scope:
it is the DECLARED ground of this fixture, exactly as the trunk is the
DECLARED wall — its matter, friction and geometry are declared screening
choices, never measurements, never tuned (the placeholder-mu law, section 4).

IN SCOPE (one arm, 140 ticks total, plus its byte-identical rerun):
1. HOLD PREFIX (20 ticks): the certified n=3 fixture hold at the declared
   operating point — comparability anchor, expected to reproduce the
   K02-sealed hold window values within the sealed windows (P1).
2. RELEASE + FALL (60 release ticks): press removed exactly; free-fall
   identity per the sealed observer; the first 40 release ticks REPRODUCE the
   K02-sealed release account (fall displacement channel 0 vs the G07-report
   sealed reading `0.20110499999871972` m within 1e-9 m; terminal-speed
   class: the identity 40*g*DT re-derived at run, K02-sealed measured class
   `1.9619999999872946` m/s) — the pads pass the G07 window end (where K02
   honestly stopped, still falling) and continue to the floor (P2).
3. IMPACT + REST (the 60-tick rest window following first floor contact):
   nonpenetration (P3), the supporting impulse (P4), rest stability (P5),
   the impact-energy destination through the sealed observer's account
   (P6).

OUT OF SCOPE (fenced, not smuggled in):
- DESCENT METERING: the G06 brake schedule and any controlled-descent law is
  K04-class; this card's release is UNCONTROLLED (the failure-arm class),
  and its landing is the declared fixture's response — never a descent skill.
- RECOVERY: X03-class post-failure recovery experience is out of scope (the
  W09 row's controller response is NOT implemented or assumed here).
- RESTITUTION / BOUNCE MODELING: any nonzero-restitution or impact-model
  REPAIR is a NEW engine-model decision that exists nowhere in the certified
  line; this card neither assumes nor requests it (section 2 finding; section
  9 A2 routes it as a bounded option, untouched).
- THE W-TIER WALKING LINE: untouched — no surrogate edit, no walking-card
  number consumed as landing evidence (section 2 finding item F-4).
- TRANSFER / ASCENT (B5 fence carried), n=4 (the Captain's five unmet
  demonstrations), GRASP CLOSURE (B1/B2 docket), RESET SCENARIOS (registry
  K02 row), TRAINING-SPEC items (K03-entry chain freeze), ANY friction
  measurement (NB-01/02 stands), any new scenario parameter (the 0.41 arm
  does NOT run here — the landing is a contact-line measurement, not a hold
  measurement; running it at the placeholder parameters only is what makes it
  comparable to the sealed release account).
- NO SECOND LANDING CONFIGURATION: one floor height, one release structure,
  one rest window. Multi-height impact envelopes, pose-dependent landing
  (the solver is TRANSLATION-ONLY — section 9 A8) and repeated-impact
  studies are future cards.

## 2. THE IMPACT-MODEL AVAILABILITY FINDING (the dispatch's first question,
##    answered from sealed records, pinned)

THE QUESTION (dispatch, verbatim): "does the certified line have a
ground-impact response at all (the W-tier walking's certified ground-contact
line may carry it) or is the impact model a DECLARED ABSENT needing a modeling
decision routed to the Lt."

THE ANSWER: the certified line HAS a ground-impact response at the solver
level — a DECLARED, MEASURED, SEALED inelastic impact law — and the
"impact model ABSENT" naming in the sealed corpus is SCENARIO-level (no
floor body in any released fixture), NOT model-level. The W-tier walking's
certified ground-contact line does NOT carry the vertical impact response.
THEREFORE no engine modeling decision is required for a landing card; the
only decision this draft routes to the Lieutenant is the bounded fixture
acceptance at commit (section 9 A2). The finding, item by item:

- F-1 THE SOLVER LAW (pinned): the certified contact solver
  `tools/monkey_campaign/contributions/MAT2-M06/local_contact.py`
  (`chimera.local_contact.v1`), sha256
  `1cd662b30343011eb4a0a01e461a1e82b00482d0371857c8e42d6bec8f9a28dc`
  (store copy, git-tree copy at the merged tip `7c1f395a`, and the G07/K02
  `imported_not_forked` upstream pins — three sources, one hash), declares:
  line 36 `RESTITUTION = 0.0        # declared inelastic`; lines 319-320
  `bias = BETA / DT * max(pen - SLOP_M, 0.0)` /
  `jn = max(m_eff * (-(1.0 + RESTITUTION) * vn + bias), 0.0)` — the normal
  impulse cancels the approach velocity with NO elastic return and clears
  penetration above the slop; the M06 frozen prereg (sha256
  `8c81b21cb4c879e1351bf43053dc7509c1e899b0fa5909602aa7154100e041e5`)
  states verbatim: "Restitution e = 0 (declared inelastic; no bounce)".
  Nonpenetration at speed is the declared high-speed treatment:
  conservative-advancement CCD ("per-tick conservative-advancement CCD
  (exact one-step for linear motion; crossing trajectories cannot tunnel)",
  module docstring), with the event-driven commit that "lets a resting patch
  settle onto the surface (gap -> MARGIN) instead of hovering one substep
  short of it" (solver `solve_tick` step 4 comment). Constants: G 9.81,
  DT 0.005, THICKNESS_M 0.002, SLOP_M 1e-5, MARGIN 1e-5, BETA 0.2.
- F-2 THE MEASURED CERTIFICATION (pinned): the sealed M06 receipt
  (`evidence-store/MAT2-M06/numerical/experiment_receipt.json`, sha256
  `2956dd7aaf3682fc18de9b724ddd8a695011ec74c9a12a5a56744b3d738a9397`)
  contains measured impact experiments at this solver:
  `X1_resting`: `impact_tick 8`, `settle_tick 9`, `weight_N 1.1772`,
  `jn_steady_Ns 0.005886` (== weight*DT exactly — receipt field
  `anchor_is_weight_dt: true`), `steady_min_gap_m 1.0000000000000026e-05`
  (== MARGIN: the resting body holds AT the margin, never penetrating),
  `ledger_residual_max 6.938893903907228e-18`, 600 ticks steady-from 500;
  `X2_oblique`: `impact_tick 7`, `jn_impact_Ns 0.030000000000000086`,
  `jt_impact_Ns 0.012000000000000035`, `vt_after 0.3330127018922183`,
  `slip_regime true` (frozen prereg predictions; measured);
  `X4_crossing`: the CCD no-tunnel variants, `impact_tick 1` each, post-impact
  velocities zero within 1e-12 (e = 0). X1 IS a landing-scale precedent:
  impact tick, settle tick, weight-carrying steady support, nonpenetration at
  the margin, ledger closing — at the certified solver, sealed.
- F-3 THE ABSENCE IS SCENARIO-LEVEL (pinned): the G07 sealed report
  (`evidence-store/MAT2-G07/report/REPORT.md`, sha256
  `34a4a095e1f4b3e5c87160a77e399c5c27a38202c1ad3675b0bcbf70d4b956a1`)
  states verbatim: "NO impact landing is modeled or claimed: no floor body
  exists in this fixture; the falling pad descends alongside the trunk inside
  the declared window (C13 impact traces stay downstream work)". The G07
  receipt (`chimera.g07_release_fall.v1`, sha256
  `c539617b098190918187d9a7dcbb0a5e33a85998adaa58f6b781703bbdeb88f8`)
  consumed the solver imported_not_forked (sha256 `1cd662b3...`) — the same
  solver WITH the impact law; what the G07 fixture lacked is the floor body.
  The K02 honest-absent naming ("NO impact/landing model exists; post-contact
  dynamics UNDECIDABLE", k02-impl EVIDENCE section 2, prereg section 8 A3)
  is the same fixture-scope statement (its prereg section 1 leg 4: "no impact
  model exists or is claimed (section 8 A4)" — a claim about what K02's arm
  CLAIMED, inside a fixture with no floor). This draft's reading: the impact
  RESPONSE is a property the certified solver line already declares and
  measures; the LANDING SCENARIO (a floor fixture receiving the released
  certified line) is what does not exist yet — and authoring it is exactly
  this card's declared-fixture work, not an engine-model repair.
- F-4 THE W-TIER WALKING LINE DOES NOT CARRY IT (pinned): the certified
  W-tier walking ground-contact line is the declared CPU surrogate, and it
  has NO vertical ground-impact response: the W09 falsifier receipt
  (`evidence-store/MAT2-W09/numerical/falsifier_receipt.json`, sha256
  `3a61cdbf43f7b11b4b284c7be969c5f0a36208556942f0832f1022fe87b1204c`)
  energy-account model field, verbatim: "no vertical body dynamics, gravity
  or floor body in this declared surrogate (impact traces stay downstream
  work, G07 record)". The W08 report
  (`evidence-store/MAT2-W08/verdict_ref/REPORT.md`, sha256
  `75bb3d697d80fdfad1044a908269c31881ed83e0386518d4fe8a96146caa6193`)
  verifies the surrogate walk with "contact floor min 4 (bar >= 2)", "pad
  gaps all > 0 (P8)" and records `N1_vertical_fall_channel: NAMED_MISSING
  (surrogate scope; trip channels measured: True)` — horizontal-planar
  contact support only. The predecessor's scratch copies of
  `tools/policy_compat/scene_cpu.py` (the W-tier policy-compat surrogate,
  commits `68aa57bd`/`893f06b7`, hash-verified in the resumption note) are
  the same surrogate family. CONSEQUENCE: the dispatch's alternative — that
  the W-tier walking's certified ground-contact line carries the landing —
  is REFUTED by the sealed walking records themselves.
- F-5 ROUTING CONSEQUENCE (the bounded decision, and the only one): because
  F-1/F-2 establish the certified response and F-3/F-4 establish that only a
  declared scene element is missing, this card needs NO modeling decision
  from the Lieutenant to run — it needs the Lieutenant's COMMIT of this
  prereg, whose section 1 declares the floor fixture. The commit IS the
  accept mechanism (the K02 law: "the Lieutenant commits this file ALONE
  FIRST"; the Lt may refine declared fixture values at commit before
  freezing). The alternative branch — ordering a restitution/bounce
  declaration (a nonzero e, or any new impact model) — is a Captain/Lt
  engine-model decision that this card does not make, does not assume and
  does not request; if ordered, it is a NEW prereg (the placeholder/declared
  -value law: no mid-run parameter invention).

## 3. The claim-by-claim table (SEPARATE CLAIMS: landing != descent metering
##    != recovery != restitution modeling; every numeric bound fenced)

LAW (Captain correction #2, binding, carried): the hold, release, fall and
landing are SEPARATE claims; no number below is stretched across claims.
Labels: every threshold is a CONDITIONAL-CALCULATION of the declared models
under assumption set A1-A8 (A1 the declared mass line via the G04 scene
reading and its `share` construction; A2 the declared fixture contact class
n=3; A3 the DECLARED 60.0 N press operating point, TC-8 ports 0/8; A4 the
DECLARED floor fixture class of section 1; A5 friction placeholders
mu_s 0.6 / mu_k 0.4, monkey-bark UNMEASURED (NB-01/02); A6 law forms: the
solver's own jn/jt formulas and the sealed observer's impulse-replay
account — the ONLY accounting forms used; A7 the certified solver
declarations G 9.81 / DT 0.005 / SLOP 1e-5 / MARGIN 1e-5 / BETA 0.2 /
RESTITUTION 0.0 read from the pinned module; A8 translation-only rigid
bodies — no angular dynamics anywhere in this card). No number below is a
measured monkey-bark value; the closed-form fall numbers are derived
DECLARATIONS re-derived at run from pinned constants.

| # | bound (verbatim value, source) | constrains ONLY | does NOT touch |
|---|---|---|---|
| LB1 | the certified impact law: RESTITUTION 0.0, `jn = max(m_eff*(-(1+e)*vn + bias), 0)`, SLOP 1e-5, MARGIN 1e-5, BETA 0.2, CCD no-tunnel (M06 local_contact.py `1cd662b3...`, lines 29-42/319-320; prereg `8c81b21c...` "Restitution e = 0 (declared inelastic; no bounce)") | the landing response of the DECLARED fixture class on the certified solver line | any restitution/bounce modeling (fenced); the walking surrogate line; the trunk fixture's own behavior |
| LB2 | the measured solver precedent (M06 receipt `2956dd7a...`): X1 impact_tick 8 / settle_tick 9 / jn_steady 0.005886 N*s == weight*DT / steady_min_gap 1.0000000000000026e-05 m / ledger_residual 6.938893903907228e-18; X2 impact_tick 7 / jn_impact 0.030000000000000086 / jt_impact 0.012000000000000035 / vt_after 0.3330127018922183 | the CLAIM CLASS the landing measures (impact->settle->steady support at THIS solver), at the sealed probe's scale | the scene-line landing numbers themselves (P2-P6 measure them at scene scale; X1's 0.005886 N*s is a 0.12 kg-class probe, never a scene prediction) |
| LB3 | the scenario absence (G07 report `34a4a095...` verbatim "no floor body exists in this fixture"; G07 receipt `c539617b...`; W09 receipt `3a61cdbf...` "no vertical body dynamics, gravity or floor body in this declared surrogate"; W08 report `75bb3d69...` N1_vertical_fall_channel NAMED_MISSING) | the FINDING (section 2) and the fixture scope: nothing in the certified corpus measured a released-body landing | the W-tier walking line (untouched); any repair claim — this card repairs nothing |
| LB4 | the fall continuation declarations (derived from pinned G/DT): d(N) = g*DT^2*N(N+1)/2; v(N) = N*g*DT; d(40) = 0.20110500000000003 m class vs the SEALED G07/K02 reading `0.20110499999871972` m (window closed_form_m 1e-9); v(40) = 1.9620000000000002 m/s; d(60) = 0.4488075 m; v(60) = 2.943 m/s | the declared floor placement and the free-fall identity windows of THIS arm | impact-speed predictions (the recorded pre-impact velocity at the recorded contact tick is the input, derived at run); K02's own sealed windows (unchanged) |
| LB5 | the mass law: scene reading 10.037998 kg; share 3.3459993333333333 kg/channel (G04 `run_scenario` literal construction); per-tick weight-share impulse share*g*DT = 0.1641212673 N*s (the executable G04-share construction; the mass-register-float construction gives 0.16412126730000007 — both inside the 1e-9 bar, the executable form is the check target); 3-pad total 0.49236380190000006 N*s/tick (== the B6 prop-impulse token exactly) | the per-channel supporting-impulse identities of P4/P5 | the B6 hand-body problem (untouched); the band readings 5.4/6.15/6.9 (not run) |
| LB6 | the closed-form impact-energy scale (DECLARED annotation class, NOT an enforced identity): KE_closed(60) = 0.5*share*v(60)^2 = 14.490266689917 J/pad, 3-pad 43.470800069751 J; the ENFORCED identity is the sealed observer's per-tick account (WIN_ENERGY 1e-12 J non-CCD ticks; the CCD impact tick's stored-energy exchange RECORDED per the observer's declared CCD-tick law) | the annotation-scale framing of P6 | any continuous-time energy identity (the discrete closed form and m*g*d differ at the g*DT^2*N/2 scale — declared here so no check ever enforces the continuous form) |
| LB7 | the K02 sealed release account (job `e4a9da8c...`, k02_experiment_receipt.json `544c744c...`): W_press == 0.0 J exactly every release tick; jn/jt worst 6.478619778652711e-11 N*s; free-fall recursion worst 5.8086521703692995e-12 m/s; gravity work == KE gain within 1.5440804190802737e-10 J; terminal 1.9619999999872946 vs 1.9620000000000002; fall displacement [0.20110499999871972, 0.20110499999895207, 0.2011049999986973] m, channel 0 bit-exact vs G07; 120 post-release micro-contacts, supporting: 0 — the arm STOPS mid-fall | the P1/P2 comparability anchors of THIS card at the SAME structure and parameters | anything beyond 40 release ticks (unmeasured by K02 — exactly what this card extends); any claim that K02's arm landed (it did not; the merge message records it) |
| LB8 | friction: pad placeholders 0.6/0.4, trunk 0.6/0.6, floor DECLARED 0.6/0.4, pair rule min() (M06 `pair_mu`); monkey-bark UNMEASURED (FRICTION_SOURCES `336118e9...`; NB-01/02) | the declared contact parameters of this fixture run | any friction measurement claim; the 0.41 scenario-parameter reading (NOT run here — fenced in section 1) |

## 4. Friction provenance and the mu label (binding on every use)

- mu_s = 0.6 / mu_k = 0.4 are NAMED PLACEHOLDERS (FRICTION_SOURCES verdict
  GAP; REPIN ORDER 2; acquisition gap NB-01/02 STANDS). Monkey-bark friction
  is UNMEASURED — the corpus master verdict is verbatim: "NO measured macaque
  volar skin on bark value exists anywhere in the corpus". The floor
  fixture's mu values are the SAME placeholders DECLARED for the fixture
  class — a screening choice, never a measurement, never tuned.
- THE PLACEHOLDER-MU LAW: no re-pin of mu mid-run. This card's run begins and
  ends at the declared placeholders; the mu=0.41 declared scenario parameter
  (K01/K02's labeled human-analogue transfer value) is NOT used by this card
  at all (section 1 fence); parameter changes are new preregged runs, and no
  measured value is ever tuned to force success (section 0.3).

## 5. Frozen predictions and tolerances (the certified scene|n=3 line)

All outcomes are read from committed per-tick records of the build line
running the declared scene through the SEALED observer
(`release_fall_account.py` `observe_with_account`, sha256
`78b5cc66f7019fa181765eb0366fe6c98525941840f57723d0ae99cb55b2a8c5`,
imported-not-forked, cross-checked bit-identical against `gc.run_scenario`
per the K02 observer-drift law) EXTENDED past the G07 window end onto the
declared floor. Every check-derived constant is DERIVED AT RUN from pinned
bytes/constants (the solver's own module constants; the mass register; the
G04 module's literals); corpus-value-match applies wherever the value exists
in pinned bytes (mismatch = refusal `threshold_pin_mismatch`). Honest
predicted-outcome statement first: UNDER THE CURRENT DECLARATIONS the honest
predicted outcome is CONFIRMING-MIXED — the hold prefix reproduces the sealed
windows (P1), the fall continues the free-fall identity to first floor
contact at release tick 60 (P2, with the declared tick window), the floor
contact is nonpenetrating AT the margin (P3), the supporting impulse follows
the two-term certified law — the one-tick impact impulse canceling the
approach velocity, then the per-tick weight-share steady support
`0.1641212673` N*s/channel (P4), rest is immediate and stable within
the declared windows (P5, the M06 X1 settle class), and the energy account
closes per tick THROUGH the impact with the destination decomposition
recorded (P6). Honest risks carried: (a) the impact tick may land one tick
early/late against the closed form (the CCD margin and the pads' tiny
residual horizontal velocities from the wall micro-contacts are inside the
declared window); (b) a wall facet may still touch a pad ON the impact tick
(the account's CCD-tick law records the exchange; multi-contact impact is
RECORDED, not forced into a single-contact story); (c) if any pad's
micro-contact history leaves residual tangential velocity, the impact tick's
friction class is RECORDED (stick expected — mu_s*jn dwarfs the tangential
demand — and a slip class is a recorded outcome with `w_f_ke` in the
destination ledger, never a failure). A prereg that predicts its own honest
failure modes where the declarations say so is correct discipline, NOT
pessimism.

- P1 HOLD-PREFIX COMPARABILITY `hold_prefix_reproduces_sealed_windows`: the
  20 hold ticks at the declared operating point reproduce the K02-sealed
  window values within the sealed windows — press jn worst deviation class
  `1.012356865004449e-12` N*s (sealed K01/K02 worst), all channels stick,
  zero creep class (the K02 measured `[0.0, 0.0, 0.0]`), the W20 ledger
  against the pinned G07 scene|n=3 values (press `0.8069338128977511` J /
  gravity `0.24150444483195008` J / friction `0.24150444482831965` J) within
  1e-9 J. TOLERANCES: the sealed observer's own windows (WIN_ENERGY 1e-12 J,
  WIN_REPLAY_V 1e-12 m/s, WIN_CONT 1e-9 m, WIN_DRIFT 1e-9 J,
  WIN_RELEASE_SCALE 1e-10 N*s/kg, closed-form/continuity 1e-9) + the K02
  cross-window 1e-9 J gate for the ledger reference. HONEST FAILURE MODE: a
  window breach in the prefix — a records discrepancy (construction-class
  question) routed for review, never silently normalized.
- P2 RELEASE AND FALL TO FIRST CONTACT
  `release_fall_identity_to_declared_floor`: W_press == 0.0 J EXACTLY every
  release tick; jn/jt to the share-scaled bar (`share_kg * 1e-10` N*s
  convention, sealed amendment a2); free-fall recursion
  v_down(k) - v_down(k-1) == g*DT within 1e-9 m/s; the FIRST-40 release-tick
  prefix reproduces the LB7 sealed values within the same declared windows
  (fall displacement channel 0 vs `0.20110499999871972` m within 1e-9 m;
  terminal-speed class at tick 40 vs 40*g*DT within 1e-9 m/s); the fall
  CONTINUES past the G07 window end on the same identity; FIRST FLOOR
  CONTACT predicted at release tick 60, declared acceptance window
  {59, 60, 61} (the CCD advances to the margin inside the tick: remaining
  travel at tick-60 start = g*DT^2*60 = `0.014715000000000002` m vs MARGIN
  1e-5 — the
  contact is deterministic inside tick 60 up to the pads' ~1e-13-class
  release-z spread and float-path noise, hence the honest +-1 window); the
  recorded per-channel impact tick and pre-impact normal velocity are the
  P4 inputs. FALSIFIER: a floor-contact record outside the declared window,
  a free-fall identity breach beyond the declared windows, or any recorded
  floor-contact impulse DURING the declared free-fall window (contact before
  the declared fall is complete). A predicted-recording observed is a
  SUPPORTED PREDICTION (correction #3 wording law).
- P3 NONPENETRATION AT CONTACT
  `floor_contact_nonpenetration_at_margin`: EVERY recorded pad-floor contact
  record in the impact+rest window has `gap_m >= -SLOP_M` (never below
  -1e-5 m: the declared bias-activation bound); the steady-state minimum gap
  sits AT the margin class (the M06 X1 `steady_min_gap_m
  1.0000000000000026e-05` class, window 1e-12 m around MARGIN); no tunneling
  (every floor crossing produces a contact record — the CCD declaration; the
  negative-control tunneling mode of the M06 prereg is dev-suite-only and
  never runs in the sealed battery). FALSIFIER: any contact record with gap
  < -SLOP_M, or any tick where a pad's position crosses the floor plane
  without a recorded floor contact (records + continuity rows are the
  evidence; the observer's anti-teleport law bites on both).
- P4 THE SUPPORTING IMPULSE `supporting_impulse_two_term_law`: (a) IMPACT
  TERM — on each pad's first floor-contact tick, the summed floor jn equals
  the certified inelastic value re-derived at run from the recorded
  pre-impact state: `jn_total == share*|vn_pre|` within 1e-9 N*s (m_eff ==
  share against the pinned floor; RESTITUTION 0.0; bias 0 at a margin
  contact — the solver's own formula, re-derived from the pinned module
  constants, value-compared to the recorded impulses); (b) STEADY TERM —
  every subsequent rest-window tick, per-channel floor jn == share*g*DT ==
  `0.1641212673` N*s (the executable G04-share construction, re-derived at
  run from the pinned module literals; the mass-register-float construction
  gives `0.16412126730000007` — both forms inside the bar) within the
  1e-9 N*s bar (the M06 `anchor_is_weight_dt` law at scene share scale —
  the K02-quoted per-tick weight-share impulse class); (c) SUPPORTING
  CLASSIFICATION — the floor contacts carry the pads' weight (jn > 0 with
  the pad held at rest): this is the Captain's recorded-vs-supporting
  distinction (order #7 check 1) RESOLVED for the landing — the K02 arm's
  120 micro-contacts were recorded-NOT-supporting mid-fall; this card
  records the transition to SUPPORTING with the impulse identities as the
  evidence. FALSIFIER: an impact tick whose summed jn violates the
  re-derived inelastic identity beyond 1e-9 N*s, or any rest tick whose
  support impulse leaves the weight-share bar while the pad remains at rest
  (both would contradict the certified law as applied — records
  discrepancies, never tuned).
- P5 POST-LANDING REST STABILITY `rest_stability_declared_window`: from the
  first tick AFTER each pad's last nonzero floor impulse (the settle tick;
  M06 X1 class settle = impact + 1), through the declared 60-tick rest
  window: post-solve |v| <= 1e-9 m/s every tick every channel; per-tick
  displacement <= 1e-9 m (the K02 zero-creep class); NO upward velocity
  component beyond 1e-9 m/s at any post-impact tick (the e = 0 no-bounce
  declaration — a bounce would be THE P5 falsifier, contradicting
  RESTITUTION 0.0); mode census recorded per tick (still/stick expected;
  a slip tick is a recorded outcome with its friction work in the P6
  ledger); the settle duration RECORDED (expected impact+1; a longer settle
  is a completed measurement, never tuned). FALSIFIER: any |v| breach, any
  upward-motion tick, or any displacement beyond the declared windows inside
  the rest window. WINDOW LAW: the rest window is 60 ticks AFTER the last
  channel's settle tick; with the impact at release tick 60 the total scene
  is <= 20 + 60 + 1 + 60 = 141 ticks (annotations: 0.1 s hold, 0.3 s fall,
  0.3 s rest at 200 Hz — seconds computed FROM tick counts, the K01
  finding-1 class impossible by construction).
- P6 IMPACT-ENERGY DESTINATION `energy_destination_through_impact`: the
  sealed observer's account runs EVERY tick INCLUDING the impact tick: (a)
  on non-CCD ticks the impulse-work identity
  dKE == W_press + W_weld + W_grav + W_contact + W_anchor closes within
  WIN_ENERGY 1e-12 J per body per tick, the friction split closes within
  WIN_LOSS 1e-12 J, and the stored-energy drift identity within WIN_DRIFT
  1e-9 J; (b) on the CCD impact tick the observer's DECLARED CCD-tick law
  applies (the exact forms' residuals RECORDED as the collision's stored-
  energy exchange, the kinematic anti-teleport bound enforced) — the
  destination decomposition is computed at run FROM THE RECORDED RECORDS:
  the normal-approach kinetic energy removed by the e = 0 floor impulse
  (== 0.5*share*vn_pre^2, re-derived; NO elastic return — with RESTITUTION
  0.0 this energy appears in NO stored, returned or rebound form), the
  friction losses (w_friction + loss_solver), the tick's gravity work
  (w_grav), the pinned floor's anchor reaction (== minus the contact
  impulse, the trunk-anchor law); (c) over the whole release phase the
  account stops NOWHERE — the K02 account's declared stop-before-impact is
  EXTENDED THROUGH impact to rest, answering the Captain's order-#7 check 2
  scope question for the landing leg: the release account WITH the landing
  includes the impact and its energy destination, fully labeled. THE
  P6 FALSIFIER: any identity window breach on any non-CCD tick, a
  missing/incomplete impulse replay (refusal `impulse_replay_incomplete`),
  or a destination decomposition that does not close against the recorded
  impulses (arithmetic mismatch = records discrepancy routed, never
  normalized).
- P7 FENCED `fences_not_run`: NO restitution declaration, NO recovery
  implementation, NO descent metering, NO transfer phase, NO n=4, NO grasp
  arm, NO 0.41 arm, NO W-tier surrogate edit runs. Stated here ONLY so the
  fences are never smuggled.

Refusal/prediction wording law (Captain correction #3, applied): a predicted
refusal observed is a SUPPORTED PREDICTION; each falsifier names the
observation that would CONTRADICT its prediction.

## 6. Falsifier disposition summary

- "Landing misread as descent skill or recovery" -> section 1 fences + P7;
  the release is the uncontrolled failure-arm class; no controller exists
  here.
- "Fixture landing misread as the playable objective" -> section 0.3
  objective law; every artifact carries the FIXTURE label.
- "Closed-form/continuous identity smuggling" -> LB6 (the discrete-vs-
  continuous difference is DECLARED); the only enforced identities are the
  sealed observer's per-tick forms.
- "Hidden assist in the fall or landing" -> the anti-assist law's inherited
  form: the arm may only REMOVE the press channel (the K02 release law); the
  floor fixture is a DECLARED scene body present from tick 0 of the scene
  definition (never inserted mid-run); the observer's weld/anchor/teleport
  laws bite; a landing that grants support BEFORE the declared fall completes
  is the P2 falsifier.
- "Impulse record stretched across claims" -> section 3 table; LB2's probe
  scale never stands in for scene predictions; LB7's sealed release values
  are anchors within their windows, never landed-state claims.
- "Annotation drift" -> declared seconds computed from frozen tick counts at
  DT = 0.005 s (200 Hz); tick counts are the frozen executable quantities.
- "Rest read as toppling-stability" -> A8: the solver is translation-only;
  P5 claims TRANSLATIONAL rest only; toppling is unmodeled (section 9).

## 7. Failure preservation, refinement checks, the standing infeasibility rule

- Every dev-run refusal and every failed arm is preserved in
  `DEV_RUN_REFUSALS.md` in the card package (honest negatives, never
  deleted); failure captures use the same declared views as success
  captures.
- REFINEMENT CHECKS: every threshold quoted in any report is re-derived from
  the pinned bytes/constants at run time (section 8 pins); any mismatch is a
  refusal (`threshold_pin_mismatch`), never a silent update. The five
  RETRACTED defective static quotes (tabulated in DERIVATION.md section 7;
  pinned `da344205...`) MUST NOT appear in any K-tier artifact — the
  consistency gate asserts their absence, and they appear nowhere in this
  draft.
- THE STANDING INFEASIBILITY RULE (section 0.3): on an infeasible or
  non-closing configuration: record the result; then EITHER name a
  physically justified change within project authority (a declared fixture
  geometry or parameter — never a tuned measured value) and prereg it, OR
  escalate to the Lieutenant with bounded options. The bounded option menu
  for this card's future: the restitution declaration route (section 9 A2),
  the resolved-friction route (the Captain's docket), the multi-height
  impact-envelope route (a new prereg). The playable objective stays OPEN.

## 8. Input pins (verified byte-exact 2026-10-02 by this lane; drift = refusal
##    `input_pin_mismatch` / `input_pin_missing`)

Certified interfaces (imported at run, hash-asserted, never forked; hashes
verified against BOTH the sealed store copies AND the git-tree copies at the
merged tip `7c1f395a` — three-source identity where both exist):
- `tools/monkey_campaign/contributions/MAT2-M06/local_contact.py`
  sha256 `1cd662b30343011eb4a0a01e461a1e82b00482d0371857c8e42d6bec8f9a28dc`
- `tools/monkey_campaign/contributions/MAT2-G04/grip_contact.py` sha256
  `0d6375484c350039468b31a2f7db2895d3365412aee52ce98de72b4173d69245`
- `tools/monkey_campaign/contributions/MAT2-G05/contact_support_obs.py`
  sha256 `3dae0a3805cec86bba8dbae9a6fc563f43cddc98fcd01a693f725e4f31c46bd3`
- `tools/monkey_campaign/contributions/MAT2-F03/assets/trunk_01_mesh.json`
  sha256 `3b17441764714c5e5e9c7a43c3253b3271a0f508954095e1960a57820cef6ee7`
- `evidence-store/MAT2-G07/source/release_fall_account.py` sha256
  `78b5cc66f7019fa181765eb0366fe6c98525941840f57723d0ae99cb55b2a8c5`

Sealed store pins (the finding + reference authorities):
- `evidence-store/MAT2-M06/numerical/experiment_receipt.json` sha256
  `2956dd7aaf3682fc18de9b724ddd8a695011ec74c9a12a5a56744b3d738a9397`
  (== the git-tree copy at `7c1f395a`; X1/X2/X4 the impact precedents)
- `tools/monkey_campaign/contributions/MAT2-M06/PREREGISTRATION.md` sha256
  `8c81b21cb4c879e1351bf43053dc7509c1e899b0fa5909602aa7154100e041e5`
  (git-tree at `7c1f395a`; "Restitution e = 0 (declared inelastic; no
  bounce)")
- `tools/monkey_campaign/contributions/MAT2-M06/contact_law.json` sha256
  `583962c29f18118a478dedb167f2c3667414b86f5cab4ee54763416f1df7e41b`
  (git-tree at `7c1f395a`)
- `evidence-store/MAT2-G07/numerical/experiment_receipt.json` sha256
  `c539617b098190918187d9a7dcbb0a5e33a85998adaa58f6b781703bbdeb88f8`
  (the hold/release ledger + declared windows authority; schema
  chimera.g07_release_fall.v1; hold_ticks 20; release_ticks 40; g 9.81;
  dt 0.005)
- `evidence-store/MAT2-G07/report/REPORT.md` sha256
  `34a4a095e1f4b3e5c87160a77e399c5c27a38202c1ad3675b0bcbf70d4b956a1`
  (the verbatim "no floor body exists in this fixture" finding)
- `evidence-store/MAT2-W09/numerical/falsifier_receipt.json` sha256
  `3a61cdbf43f7b11b4b284c7be969c5f0a36208556942f0832f1022fe87b1204c`
- `evidence-store/MAT2-W08/verdict_ref/REPORT.md` sha256
  `75bb3d697d80fdfad1044a908269c31881ed83e0386518d4fe8a96146caa6193`
- `evidence-store/MAT2-D-MASSREG/numerical/mass_register.json` sha256
  `61fb79b1bf2df8c5e1a5b1bff2ab1c4f41700de25bc7f1a114cbc78fe693cc7a`
- `evidence-store/MAT2-W04/numerical/w04_certificate.json` sha256
  `07f05bfa982e066ae67413b04e3367c5ad7570830e99fc32edcb86cbe8d87598`
- `evidence-store/MAT2-W04/numerical/w04_freeze_manifest.json` sha256
  `be632ffc85865515285f3d622a09882a3180a43101027914f1ed3408496f5d29`
- `evidence-store/MAT2-B07/unclassified/adoption_record.json` sha256
  `f6952e8afc778f79a0ede05b61d73dd7c3fabd68789703552cd6136e25ef0199`
- `b07-prereqs/RUNTIME_CONTRACT.md` sha256
  `f33c188bcb561b1946b104340cf36cba366709526c095874684529a599df338c`
- `climb-derivation/DERIVATION.md` sha256
  `da34420558f6632b0544ca94bc3e25ece515027628c7bd8cc54b9fdd30b7ebd9`
- `assembly-identity/ASSEMBLY_IDENTITY.md` sha256
  `2ab248bda4db799685a5be9f446bb3e731a47b40b9db1108072cce18bafad035`
- `evidence-store/MAT2-F05/source/FRICTION_SOURCES.md` sha256
  `336118e929bd0b4fb067db5a448dc2e348fed073007787635549a4cf1cf5868b`
- `E:/PythonChimera/tools/monkey_campaign/MONKEY_COMPLETION_MAP.md` sha256
  `0e3984578b0cae38ab435daaa77cc10559cceeadbaf9885c3f31b979a362ecae`

K02 sealed receipts (the measurement authority consumed by this draft):
- FINAL run runner receipt
  `E:/ChimeraWork/task-runner/results/e4a9da8c3cab4cec89f9e9789dfd234b/
  receipt.json` sha256
  `02fbe13f5c2970b04b471c6f71161ebcc4888a1c88f7628c353d610870f8f054`
  (job `e4a9da8c3cab4cec89f9e9789dfd234b`, state PASSED, exit 0,
  cleanup_verified true; base `19d0cff8...`; sealed manifest
  `09affd2f514ef736d9bd631a70285a52da729f0d0b08bb006a93a6c3651c2c64`)
- `.../artifacts/outputs/k02_experiment_receipt.json` sha256
  `544c744cd230c062133f4411186a46e4234d526d70d80b097eda5cdec64297ac`
  (embeds preregistration_sha256
  `40cb161d7386cc0c46ea0a15cd3d001c364e8bbd5ee4dc6f5d91df71a021814b`)
- K01 comparability receipts (verified, from the K02 prereg section 7 pins,
  re-hashed this lane): k01_experiment_receipt.json `ee1b26fc8e3eda1f2a95f75
  806cb1caed44805aa8787698e92f09bad69304dd5`.

Capture-gate pins (the standing two-stage gate of section 10):
- `E:/ChimeraWork/monkey-coordination/capture-gate-template/README.md`
  sha256 `331939f3156ca6158956e53c557cc324a3eeb0aa6a381b5170ec5ea83175ddb6`
- `E:/ChimeraWork/monkey-coordination/capture-gate-template/
  TEMPLATE_MANIFEST.json` sha256
  `1c4d1dcad9af98c73e1aa4ebb46bff6359b9992e390b38c37fae578e779a59a7`

Git line pins:
- K02 frozen prereg commit `19d0cff806969ac2ae4bf485576006c8c4091ade`
  (committed `PREREGISTRATION.md` blob sha256
  `40cb161d7386cc0c46ea0a15cd3d001c364e8bbd5ee4dc6f5d91df71a021814b`,
  verified in the local object database this lane)
- K02 MERGED tip `7c1f395a89687b17c6f2cf430eec994ed545a084` (PR #316, the
  new astra tip; present in the local object database; DECLARED context)

## 9. Honest-absent inventory (declared absences; named conditions per behavior)

- A1 FIXTURE CLASS — every landing claim of this card is fixture-class: the
  pads are declared trial-inertia carriers, the floor is a declared screening
  body; NOTHING here is evidence about the anatomical grasp, the hand bodies
  (B6 untouched), or the playable objective.
- A2 RESTITUTION / IMPACT-MODEL SCOPE — the certified line's impact response
  is the DECLARED INELASTIC law (e = 0); NO nonzero-restitution, bounce or
  impact-repair model exists, is assumed or is requested. If the Captain/Lt
  ever orders one, it is a NEW engine-model declaration and a new prereg —
  the bounded routing of section 2 F-5, recorded here so the absence is
  named, not hidden.
- A3 ANGULAR DYNAMICS — the certified solver is TRANSLATION-ONLY (rigid
  translation kinematics; no angular velocity anywhere in
  `chimera.local_contact.v1`). "Rest stability" (P5) is TRANSLATIONAL rest
  ONLY. Toppling, tumbling and pose-settling are UNMODELED — named-absent,
  never claimed, never inspected away.
- A4 DESCENT METERING — the G06 brake schedule / controlled-descent law is
  K04-class; absent here by fence.
- A5 RECOVERY — the X03-class post-failure experience is absent (W09 row
  untouched).
- A6 FRICTION — monkey-bark UNMEASURED (NB-01/02); all mu values in this
  card are named placeholders or declared fixture values; the 0.41 reading
  is not used.
- A7 MASS-ACCOUNTING OPEN ITEMS — OI-1..OI-5 (section 0.2) stay open in
  every downstream artifact.
- A8 TRAINING-SPEC ITEMS — reward, termination, seeds for TRAINING are NOT
  frozen by this physical leg (K03-entry chain freeze).
- A9 PERSISTENCE OF REST BEYOND THE WINDOW — rest is measured for the
  declared 60-tick window only; longer rest, creep accumulation and
  perturbation response are unmeasured, not unmeasurable.

## 10. Evidence obligations (numerical + visual)

- NUMERICAL: per-tick per-channel rows through the SEALED observer for every
  phase (hold/fall/impact/rest) with jn, jt, mode, gap, toc; the impact-tick
  records with pre/post velocities per pad; the supporting-impulse series
  (P4a/b identities, re-derived at run); the rest-window census (P5); the
  energy-destination decomposition (P6) computed from the recorded impulses;
  the P1-P7 verdicts as named variables with their derived constants; every
  receipt embeds `preregistration_sha256` of the committed prereg bytes and
  refuses mismatch; the two-pass byte-determinism law (trace + receipt
  byte-identical across reruns, the K01/K02 law).
- VISUAL: captures use THE STANDING TWO-STAGE GATE through the card capture
  path (`capture-gate-template/` v1: stage-0 palette blank-check retained +
  stage-1 mask co-location; template law: a run cannot emit a pass without
  the gate having run; template modules never forked or edited). Declared
  views (candidate freeze, Lt may refine at commit): the release/fall frame
  mid-fall; the FIRST-CONTACT frame (the impact tick, from the trace's
  recorded tick); the rest frame at window end — each in clean + diagnostic
  pairs, with the view-spec pinned in card_prereg BEFORE capture (the K01
  spec-version calibration law). The "palette stage-0" minimum is the
  declared fallback floor if the template path is not yet wired for this
  card at capture time — the fallback is DECLARED here in advance, never
  silent, and a stage-0-only pass is labeled `gate_stage0_only` in the
  receipt.
- All CPU verification through the runner: `python -B
  E:/PythonChimera/tools/monkey_campaign/task_package.py seal|run`; sealed
  manifest hash, base SHA, run receipt and exit status recorded in
  `landing/EVIDENCE.md` with sha256 of every load-bearing artifact.

## 11. Resource allowances (frozen draft values; the committed bytes are the freeze)

- Interpreter: `C:/Python314/python.exe -B` (the corpus's convention).
- CPU runner only; four fixed slots; BUSY (exit 75) = wait and retry with
  >= 10 s backoff; no new directories on BUSY.
- Scene cadence DT = 0.005 s (200 Hz; seconds computed FROM tick counts).
  Frozen structure (declared as scaffold; Lt may refine at commit): 20 hold
  ticks; 60 release ticks to first contact; rest window 60 ticks after the
  last settle tick; ONE arm + its byte-identical rerun; <= 141 ticks/pass.
  Declared retained outputs per job <= the runner's 256 MiB admission — the
  whole battery is tick-bounded far below the K01 approach horizon.
- ONE chain stop: this card's package, seal, run and evidence land in
  `landing/` only; no other lane's bytes are edited.

## 12. Resume state

- DRAFT-TIME CONSISTENCY EVIDENCE: the lane's `consistency_check.py`
  (runner-sealed, receipt in `landing/EVIDENCE.md`) proves every quoted
  sealed number appears in the hash-pinned bytes, the solver-law quotes
  match the pinned module lines, the derived arithmetics re-derive from
  pinned constants, the finding quotes (F-3/F-4) appear verbatim in the
  pinned reports/receipts, and the draft's own sha256 is recorded for the
  chain stop.
- Open decisions awaiting the Captain/Lieutenant (bounded; NONE closed or
  assumed here): the reserved lineage decision (section 0); the three grasp
  docket options (context only); the restitution-declaration route (section
  9 A2 — NOT requested); any n=4 declaration; the K-tier ordinal mapping of
  this card (section header note).
- After the committed prereg exists: the implementation lane freezes its
  view spec BEFORE capture, extends the sealed observer onto the declared
  floor fixture (imported-not-forked; the CCD-tick law is the observer's
  own), pins its package to the committed bytes
  (`preregistration_sha256` embedded and refused-mismatch), and runs the
  battery through the runner.

## 13. Corrections ledger (applied verbatim obligations)

1. PROVISIONAL BASELINE — section 0 (binding wording; OI-1..OI-5 preserved;
   lineage applied as criterion, never approval; reserved decision open).
2. SEPARATE CLAIMS — section 3 claim-by-claim table (landing != descent
   metering != recovery != restitution modeling; every bound fenced;
   LB2/LB4/LB7 carry the probe-scale, derived-declaration and sealed-anchor
   scopes explicitly so no sealed number is stretched to a behavior it never
   measured).
3. FALSIFIER WORDING — section 5 prediction/falsifier pairs (each falsifier
   names the contradicting observation; a predicted recording completes the
   measurement, not a failure) + section 0.3.
4. MU LABEL — section 4 (placeholders 0.6/0.4 + the declared floor values;
   no re-pin mid-run; 0.41 not used, fenced).
5. REMAINING CONDITIONS — section 9 named absences per behavior (fixture
   class, restitution scope, angular dynamics, descent metering, recovery,
   friction, mass items, training items, rest-window persistence).
6. OBJECTIVE LINE — section 0.3 verbatim + the standing infeasibility rule
   (justified change within authority or bounded escalation; never a tuned
   measured value).
7. CADENCE ANNOTATION — section 11 declares DT = 0.005 s (200 Hz) and
   derives seconds from tick counts (the K01 finding-1 class impossible by
   construction; tick counts are the frozen executable quantities).
8. THE CAPTAIN'S ORDER-#7 PRECISION CHECKS, CARRIED TO THIS CARD — (1)
   GROUND SUPPORT: P4c resolves recorded-vs-supporting for the landing
   (the K02 arm's `supporting: []` is completed by the supporting-class
   evidence with impulse identities); (2) ENERGY SCOPE: P6 states the
   release account WITH the landing INCLUDES the impact and its destination,
   explicitly extending K02's declared stop-before-impact; (3) ZERO CREEP:
   P5's zero-displacement claim is scoped to the declared precision over the
   declared window, and the translational-only scope (A8) is declared so a
   constraint-zero and a solved-zero are distinguished by the recorded
   per-tick impulse identities (the support impulse is PHYSICALLY SOLVED —
   the same solver law that slips when the cone is exceeded).
