"""L5 real-trace counterfactual (constraint-ledger lane
agent/cl-L5-transitive-20260921).

The non-synthetic leg of F-MISSED-COUPLING: small perturbations on a REAL
trace of the pinned substrate (the L0 evidence boundary, READ-ONLY — no
existing module is edited; the harness is compiled from
tools/constraint_ledger/trace_harness.cpp verbatim and the scene is
regenerated by the registered recipe into the lane's own .tmp/l5/ dir).

PERTURBATION TARGET (declared, per-leg): scene gait_controller
recipe.defaults.start_phase_left — the LEFT hind clock's start phase (the
declared external quantity gait.hind.phase.left's initial). Its declared
interface twin, gait.hind.phase.right = start_phase_right, is untouched.
LADDER (pre-stated): 1, 2, 4 ulps up, then 1e-12, 1e-9 — the first rung
whose trace differs is THE counterfactual; if none changes the trace the
leg reports not_discharged (never a silent pass).

PREDICTED CONE on the real trace (the frozen interface's own rules):
  * row 0 is the RESET row: only the perturbed leg's own declared init may
    move (phase0). Any OTHER row-0 change (the right leg at rest, the left
    pose, a decision bit) is an UNDECLARED constructor coupling —
    F-MISSED-COUPLING FIRES.
  * full horizon: a RIGHT-leg DECISION change (touch1, fires1, tds1, held1,
    clear_tick1, fire_class1, plant_y1, alt_due1, hold_ticks1) is
    adjudicated against the RIGHT leg's OWN INPUT series (gaps 2..3, mode1,
    t1, phase1, heel_y1, mp_y1): witnessed (an input diverged at some row
    <= the first changed row) => the influence arrived through that input
    (declared or opaque-plant); UNWITNESSED => it arrived through an
    undeclared cross-leg carrier (the scheduler: the interface declares
    gait.fire.* opaque) — REPORTED as measured evidence with the first
    witness row; the cone stands because the frozen interface declares the
    scheduler opaque (unknown externals conservatively reach everything).
  * the instrument must stay byte-deterministic (double run) on base AND
    perturbed scenes.
"""
from __future__ import annotations

import json
import math
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WORK = ROOT / '.tmp/l5'
SCENE = WORK / 'scene.json'
SCENE_PERT = WORK / 'scene_pert.json'
TRACE_BASE = WORK / 'trace_base.jsonl'
TRACE_BASE2 = WORK / 'trace_base2.jsonl'
TRACE_PERT = WORK / 'trace_pert.jsonl'
TRACE_PERT2 = WORK / 'trace_pert2.jsonl'
HARNESS = WORK / 'trace_harness.exe'

BUILD_CMD = ['g++', '-O2', '-std=c++17',
             '-I', 'ChimeraEngine/engine', '-I', 'ChimeraEngine/native/viewer3rd',
             'tools/constraint_ledger/trace_harness.cpp',
             '-o', str(HARNESS)]
PERT_KEY = 'start_phase_left'          # the declared per-leg clock init
LADDER = (('ulp', 1), ('ulp', 2), ('ulp', 4), ('delta', 1e-12), ('delta', 1e-9))

LEG_DECISION_COLS = ('fires', 'tds', 'held', 'clear_tick',
                     'fire_class', 'plant_y', 'alt_due', 'hold_ticks')
LEG_INPUT_COLS = ('mode', 't', 'phase', 'heel_y', 'mp_y')
# (touch is a TOP-LEVEL row key: touch[0], touch[1] — captured in row_obs)


def _run(cmd, **kw):
    return subprocess.run(cmd, cwd=ROOT, check=True,
                          capture_output=True, text=True, **kw)


def ensure_scene() -> Path:
    if SCENE.exists():
        return SCENE
    WORK.mkdir(parents=True, exist_ok=True)
    _run(['python', 'tools/science_funnel/gait_scene.py',
          '--output', str(WORK / 'scene-walker')])
    src = WORK / 'scene-walker/scene.json'
    if not src.exists():
        raise RuntimeError(f'scene generation produced no {src}')
    SCENE.write_bytes(src.read_bytes())
    return SCENE


def ensure_harness() -> Path:
    if HARNESS.exists():
        return HARNESS
    WORK.mkdir(parents=True, exist_ok=True)
    _run(BUILD_CMD)
    return HARNESS


def run_trace(scene: Path, out: Path) -> dict:
    _run([str(HARNESS), str(scene), str(out)])
    rows, meta = [], None
    for ln in out.read_text(encoding='utf-8').splitlines():
        obj = json.loads(ln)
        if obj.get('meta'):
            meta = obj
        else:
            rows.append(obj)
    return {'meta': meta, 'rows': rows}


def load_scene() -> dict:
    return json.loads(SCENE.read_text(encoding='utf-8'))


def perturbed_scene(rung: tuple) -> dict:
    scene = load_scene()
    node = scene['gait_controller']['recipe']['defaults']
    v = node[PERT_KEY]
    if rung[0] == 'ulp':
        for _ in range(rung[1]):
            v = math.nextafter(v, math.inf)
    else:
        v = v + rung[1]
    node[PERT_KEY] = v
    return scene


def _leg_cols(leg: dict, prefix: str) -> dict:
    out = {}
    for k in LEG_DECISION_COLS + LEG_INPUT_COLS:
        out[f'{prefix}.{k}'] = leg[k]
    for k in ('plant_y', 'heel_y', 'mp_y'):
        out[f'{prefix}.{k}#bits'] = leg[k + '_bits']
    return out


def row_obs(row: dict) -> dict:
    """Every observable of one trace row, as comparable values (floats are
    exact: %.17g round-trips binary64; *_bits columns pin the floats)."""
    obs = {}
    for i, g in enumerate(row['gaps']):
        obs[f'gaps[{i}]'] = g
    for i, t in enumerate(row['touch']):
        obs[f'touch[{i}]'] = t
    for i, leg in enumerate(row['leg']):
        obs.update(_leg_cols(leg, f'leg{i}'))
    return obs


def diff_rows(rows_a: list, rows_b: list) -> dict:
    """First-divergence structure: per-row observable diffs keyed by column.
    Requires identical row counts (else the refusal face moved — recorded).
    """
    if len(rows_a) != len(rows_b):
        return {'row_count_changed': (len(rows_a), len(rows_b)),
                'diffs': {}, 'first_row': None}
    diffs: dict[str, list] = {}
    for ra, rb in zip(rows_a, rows_b):
        if ra['j'] != rb['j']:
            raise RuntimeError('row index misalignment')
        oa, ob = row_obs(ra), row_obs(rb)
        for k in oa:
            if oa[k] != ob[k]:
                diffs.setdefault(k, []).append(ra['j'])
    first = min((min(v) for v in diffs.values()), default=None)
    return {'row_count_changed': None, 'diffs': diffs, 'first_row': first}


def adjudicate(diff: dict) -> dict:
    """The declared-cone adjudication (see module docstring)."""
    out = {'row0_ok': True, 'row0_violations': [],
           'right_unwitnessed': [], 'right_witnessed': [],
           'left_changed_cols': [], 'right_input_first_divergence': None}
    diffs = diff['diffs']
    # row 0: only the perturbed leg's declared clock init may move
    for col, rows_ in sorted(diffs.items()):
        if 0 in rows_ and col != 'leg0.phase':
            out['row0_ok'] = False
            out['row0_violations'].append(col)
    # right-leg adjudication
    right_inputs_changed_rows = []
    for col in [f'leg1.{k}' for k in LEG_INPUT_COLS] + \
               ['gaps[2]', 'gaps[3]']:
        right_inputs_changed_rows += diffs.get(col, [])
    right_inputs_changed_rows.sort()
    out['right_input_first_divergence'] = (right_inputs_changed_rows[0]
                                           if right_inputs_changed_rows else None)
    right_decision_cols = [f'leg1.{k}' for k in LEG_DECISION_COLS] + ['touch[1]']
    for col in right_decision_cols:
        rows_ = diffs.get(col)
        if not rows_:
            continue
        first = min(rows_)
        if right_inputs_changed_rows and right_inputs_changed_rows[0] <= first:
            out['right_witnessed'].append({'col': col, 'first_row': first})
        else:
            out['right_unwitnessed'].append({'col': col, 'first_row': first})
    out['left_changed_cols'] = sorted(k for k in diffs if k.startswith('leg0')
                                      or k.startswith('gaps[0]')
                                      or k.startswith('gaps[1]'))
    return out


def counterfactual(max_rungs: int = len(LADDER)) -> dict:
    """The full real-trace leg. NEVER silent: the verdict names either a
    discharged counterfactual or not_discharged with the measured reason."""
    ensure_scene()
    ensure_harness()
    base = run_trace(SCENE, TRACE_BASE)
    base2 = run_trace(SCENE, TRACE_BASE2)
    deterministic = (TRACE_BASE.read_bytes() == TRACE_BASE2.read_bytes())
    tried = []
    chosen = None
    for rung in LADDER[:max_rungs]:
        scene = perturbed_scene(rung)
        SCENE_PERT.write_text(json.dumps(scene, sort_keys=True,
                                         separators=(',', ':')),
                              encoding='utf-8', newline='\n')
        pert = run_trace(SCENE_PERT, TRACE_PERT)
        d = diff_rows(base['rows'], pert['rows'])
        changed = bool(d['diffs']) or d['row_count_changed'] is not None
        tried.append({'rung': rung, 'changed': changed,
                      'n_diff_cols': len(d['diffs'])})
        if changed:
            pert2 = run_trace(SCENE_PERT, TRACE_PERT2)
            det_pert = (TRACE_PERT.read_bytes() == TRACE_PERT2.read_bytes())
            chosen = {'rung': rung, 'diff': d, 'adjudication': adjudicate(d),
                      'pert_deterministic': det_pert}
            break
    verdict = {
        'base_rows': len(base['rows']), 'base_refusal_meta': base['meta'],
        'base_deterministic': deterministic,
        'ladder': tried, 'counterfactual': chosen,
        'discharged': chosen is not None,
        'f_missed_coupling_fires': False,
        'notes': [],
    }
    if chosen is not None:
        adj = chosen['adjudication']
        if not base_deterministic_safe(verdict):
            verdict['notes'].append('BASE INSTRUMENT NOT DETERMINISTIC')
        if not adj['row0_ok']:
            verdict['f_missed_coupling_fires'] = True
            verdict['notes'].append(
                'row-0 undeclared coupling: ' + ','.join(adj['row0_violations']))
        if adj['right_unwitnessed']:
            verdict['notes'].append(
                'unwitnessed right-leg decision change (undeclared cross-leg '
                'carrier — the interface declares gait.fire.* opaque; '
                'measured evidence, cone stands): ' +
                json.dumps(adj['right_unwitnessed']))
        if not chosen['pert_deterministic']:
            verdict['f_missed_coupling_fires'] = True
            verdict['notes'].append('perturbed instrument not deterministic')
    else:
        verdict['notes'].append('no ladder rung changed the trace '
                                '(not_discharged; never a silent pass)')
    return verdict


def base_deterministic_safe(verdict: dict) -> bool:
    return verdict['base_deterministic']
