"""Generate report.md for MAT2-M06 from the frozen artifacts.

PROSE DISCIPLINE: every observed value in report.md is generated HERE from
the receipt/trace/falsifier/validation JSON on disk at freeze time - never
hand-transcribed. Re-running this script regenerates the report byte-
identically from the same artifacts (deterministic; no wall-clock).
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ATTEMPT = HERE.parents[4]

G = 9.81
DT = 0.005


def sha(name):
    return hashlib.sha256((HERE / name).read_bytes()).hexdigest()


def main():
    r = json.loads((HERE / 'experiment_receipt.json').read_text('utf-8'))
    e = r['experiments']
    x1, x2, x3, x4 = e['X1_resting'], e['X2_oblique'], e['X3_sliding'], \
        e['X4_crossing']
    p7, s1, ref = e['P7_area_scaling'], e['S1_random_sweep'], \
        e['refusal_probes']
    x0a, x0t, x0b, x0c = (e['X0_independent_shapes'], e['X0_tetra_drop'],
                          e['X0_sternum_clavicle'], e['X0_full_arm'])
    flog = json.loads((ATTEMPT / 'scratch-falsifiers' / 'FALSIFIER_LOG.json')
                      .read_text('utf-8'))
    cap = pathlib.Path(
        'E:/ChimeraWork/monkey-coordination/kanban-attempts/MAT2-M06/'
        '4b3ed2b05f3546b190bd1cc4e9e9075c/capture-evidence-20260928')
    vr = json.loads((cap / 'evidence' / 'validation_receipt.json')
                    .read_text('utf-8'))
    cm = json.loads((cap / 'evidence' / 'capture_manifest.json')
                    .read_text('utf-8'))
    vp = json.loads((cap / 'evidence' / 'video_probe.json').read_text('utf-8'))
    marg = json.loads((cap / 'evidence' / 'margins.json').read_text('utf-8'))
    video_sha = cm['capture_sha256']

    def n(v):
        return repr(v)

    report = f"""# MAT2-M06 report — local triangle contact and finite sliding

Attempt 4b3ed2b05f3546b190bd1cc4e9e9075c, arrival
arrival-bfbc8ae99ec54ab5870f6c05d4435671, criteria sha256
bb695fddee166aeb79edf99c62bf6537bb24d52b3d85866f1834f0526feb9efc. Isolated
attempt checkout of E:\\PythonChimera, canonical startup slot branch-1,
prepared base c525b82c7c3ce0128565424764293a3c85811ab3; the local attempt
branch was fast-forwarded to the sealed line tip f67a622a (= merge of PR #244
review/MAT2-M03's peer reviews; carries the merged MAT2-M01 schema, MAT2-M02
compiler, MAT2-M04 passive laws, MAT2-B03/B04). No pushes, no PRs, no writes
outside the attempt workspace.

Preregistration PREREGISTRATION.md was committed (1aa6794e) BEFORE the
implementation existed and before any measurement; Amendments A1 (5e37a373),
A2 (01ef2331) and A3 (68f06bd9) are separate commits, all before
implementation (dd8b61fe) and before any capture frame existed (capture
binding enrichment acc8bef3, re-verified green before rendering). This
report.md is GENERATED by make_report.py from the receipt/falsifier/validation
JSON at freeze time - no observed value is hand-transcribed.

## done_when clause map (all clauses executed on the exact candidate revision)

| clause | execution | result |
|---|---|---|
| Candidate search feeds actual local surface contact | sweep-and-prune over swept-inflated triangle AABBs; the narrow phase sees ONLY candidate pairs (subset property asserted per contact, refusal `contact_not_in_candidates`); contacts carry surface/material ids from the pinned compiled vocabulary | X0 recall {n(x0a['recall'])} on the independent shapes ({x0a['contacts']} contacts, ids {x0a['surface_ids_used']}); tetra drop {x0t['contacts']} contacts over pinned ids {x0t['surface_ids_used']}; sternum x clavicle {x0b['contacts']} contacts against a complete {x0b['exhaustive_pairs']}-pair exhaustive reference; full arm {x0c['triangles']} triangles -> {x0c['candidate_pair_count']} candidates, {x0c['contacts']} contacts, subset property green |
| friction | Coulomb stick/slip with the declared pair rule (elementwise min); slip at mu_k * Jn, stick below mu_s * Jn | X2 slip regime measured (required stop {n(x2['slip_required_stop_Ns'])} N·s > mu_s cap {n(x2['mu_s_cap_Ns'])} N·s); jt/jn = {n(x2['jt_over_jn'])}; X3 stops exactly (tick {x3['stop_tick']}) and stays stopped |
| declared thin-feature treatment | shell midsurfaces + declared thickness {n(0.002)} m pinned from MAT2-M02 shell_thickness_m; gap = distance - (h_A + h_B)/2 | contact records carry thickness_a/thickness_b per pair; activation margin {n(1e-05)} m with CCD tolerance |
| declared high-speed treatment | per-tick conservative-advancement CCD with committed substeps (exact one-step for head-on linear approach; declared uniform-resample fallback when the Lipschitz advance crawls) | X4: {len(x4['variants'])}/{len(x4['variants'])} crossing variants detected BEFORE mid-surface overlap (min gap at detection > 0); declared no-CCD controls all detect late (after overlap) with a spurious bias velocity kick |
| Native tests cover resting load | X1: block ({n(0.12)} kg) settles onto the pinned plate; steady per-tick impulse {n(x1['jn_steady_Ns'])} N·s, support force {n(x1['support_force_N'])} N = weight {n(x1['weight_N'])} N; per-triangle split {n(x1['per_triangle_forces_N']['0'])} + {n(x1['per_triangle_forces_N']['1'])} N (bitwise-equal pinned areas); anchor = {n(x1['anchor_impulse_Ns_mean'])} N·s = m*g*dt; ledger residual max {n(x1['ledger_residual_max'])} J; steady penetration {n(max(0.0, -x1['steady_min_gap_m']))} m <= 1e-4 | PASS |
| Native tests cover oblique contact | X2: 30 deg incidence at 0.5 m/s, gravity off (A3 free-space rig); contact normal = +z within 1e-9; vn after {n(x2['vn_after'])} (|.| <= 1e-12); vt after {n(x2['vt_after'])} | PASS |
| Native tests cover sliding | X3: v0 0.5 m/s, mu_k 0.4: stop distance {n(x3['distance_m'])} m vs oracle {n(x3['distance_oracle_m'])} m (error {n(x3['distance_error_m'])} m <= v0*dt = 0.0025); W_f = {n(x3['w_f_ke_J'])} J = initial KE 0.015 J (1e-9); force-path slack {n(x3['work_slack_J'])} J <= 1e-3; finite ds max {n(x3['ds_max_m'])} m; no creep after stop | PASS |
| Native tests cover crossing trajectories | X4: two 0.02 kg shells, closing 4 m/s (0.02 m/tick = 10x thickness), 5 lateral-offset variants | all detected pre-overlap; post-impact velocities |v| <= 1e-12 (e = 0, equal masses); momentum residual <= {n(max(v['max_momentum_residual'] for v in x4['variants']))} ; post gaps >= {n(min(v['min_post_gap_m'] for v in x4['variants']))} m | PASS |
| compare against exhaustive contact candidates on small fixtures | S1 seeded randomized sweep: {s1['scene_count']} scenes (seed base {s1['seed_base']}, scene k seed = base+k), 3 bodies x 2-4 triangles, contact-dense landings | {s1['total_contacts']} contacts across the sweep, ZERO missed vs the exhaustive all-pairs reference (recall {n(s1['recall_min'])} on every scene); contact sets identical pruned-vs-exhaustive everywhere |

## Determinism (seeds documented)

- No RNG outside the declared 64-bit LCG (seed_base {s1['seed_base']}, 32
  scenes, scene k seed = seed_base + k); no wall-clock anywhere.
- P-determinism (test P13): run_experiments.py run twice -> experiment_trace.json
  and experiment_receipt.json BYTE-IDENTICAL.
- All scenario physics is seeded-free (authored fixtures only); the LCG
  drives only the randomized sweep's scene layout.

## Falsifier proof (card falsifier + profile arms; tampered copies in the
## attempt scratch, logged, discarded)

- F1 "{flog['F1']['tamper']}": {flog['F1']['missed_contacts']} missed contact(s)
  vs the exhaustive reference -> {flog['F1']['verdict']}; the untampered module
  stays green on the same scenes.
- F2 "{flog['F2']['tamper']}": {flog['F2']['observed']} -> {flog['F2']['verdict']};
  pinned visual/physical identity verified ({flog['F2']['identity_guard']}).
- F3 "{flog['F3']['tamper']}": fires `{flog['F3']['fired']}` -> {flog['F3']['verdict']}.
- F4 "{flog['F4']['tamper']}": {flog['F4']['observed']} -> {flog['F4']['verdict']}.
- Profile arms: unbound media (capture binds the trace sha, below); clipped
  load path (measured camera margins all >= 3% per side, evidence/margins.json:
  whole left {n(marg['whole']['left'])} right {n(marg['whole']['right'])});
  hidden constraint/support (pinned plate rendered and labeled in
  whole/planes/close views); area-independent triangle forces (P7: equal
  areas -> equal forces within {n(p7['equal_abs_diff'])}; twin plate ratio
  {n(p7['twin_ratio'])}); overlay-driven motion (fixed-bookmark cameras;
  geometry moves only per the sha-bound trace; predicates P-a..P-f refuse
  before assembly); unaccounted energy (X3 ledger + F3 ledger +
  reciprocity residual <= 1e-12 per tick).

## Refusal probes (named codes)

unknown_surface_id -> `{ref['unknown_surface_id']}`; bad_friction ->
`{ref['bad_friction']}`; bad_thickness -> `{ref['bad_thickness']}`;
zero/negative area -> `{p7['zero_area_refusal']}`.

## Regressions

P12 re-runs the UNMODIFIED M01, M02 and M04 frozen suites in this checkout on
the exact candidate revision: all green (exit 0; M01 35 named checks; M02
142/142; M04 P1-P12/F1-F3).

## Motion-profile capture (visual evidence, material profile)

Built per the M01/M04 discipline in
E:\\ChimeraWork\\monkey-coordination\\kanban-attempts\\MAT2-M06\\
4b3ed2b05f3546b190bd1cc4e9e9075c\\capture-evidence-20260928\\ (PREDICTIONS.md
+ Amendment A1 frozen before the final render; full record in EVIDENCE.md):

- Real 3D orthographic renders of the X3 sliding scenario displaced ONLY by
  the sha-bound solver trace; 6 manifest views (3 profile view ids x
  diagnostic/clean), {vp['nb_read_frames']} lossless FFV1 frames 1280x720,
  {vp['duration']} s at 1 fps (each row window replays all 75 solver states);
  ffprobe-verified.
- ALL FIVE registry diagnostic layers carried in every diagnostic row
  (triangle/port IDs; pressure and area-scaled force vectors; rest/current
  geometry and material directions; contact/bond state; energy/work and
  simulation tick); clean rows draw only the shells (verified by pixels).
- task_id "M06" (SHORT form) in manifest and context;
  visual_capture.validate_manifest with the registry profile read read-only
  from card MAT2-M06: structurally_valid={vr['structurally_valid']},
  fired={vr['fired']}, capture_kind {vr['capture_kind']}, view_count
  {vr['view_count']}, visual_acceptance={vr['visual_acceptance']} (acceptance
  belongs to the independent visual reviewer).
- Key hashes (generated): video {video_sha}; rendered/display trace
  {cm['views'][0]['state_binding']['sha256']}; subject (contact_law.json)
  {cm['subject_sha256']}.

## Reconciliation notes

- Fills M02's inventoried absence exactly: the compiled material_state
  documents declare an EMPTY `contacts` field and no contact solver existed
  on the sealed line; M06 adds the first local triangle-surface contact law
  as the M06-owned versioned document `chimera.local_contact.v1` (schema
  vocabulary stays closed; nothing inside M01/M02/M04 files was modified).
- Heritage cited from real pins: G3 deterministic Baumgarte contact solve,
  estimator B penetration proxy (docs/THE_MASTER_LIST.md H7 stage 3,
  agent_logs/kimi/contact_ref_01.md, .tmp/contact_ref.py, 0 ULP double-run
  discipline); B2 bonds-are-materials (capacity = strength x area -> the
  area-scaled per-triangle load report); L3 tri_ca registry (stable triangle
  ids in contact records); req.teddy_gpu_matter_kernel law_families.local
  (contact/friction as local adjacency/constraint passes).
- M03 (pressure membrane) is NOT merged (pending on review/MAT2-M03); the
  pressure law is out of M06 scope and was not invented here.

## Honest limitations

- Offline CPU-only contact experiment executable over pinned M02 surfaces and
  authored small fixtures; not the native C++ engine, no GPU residency, no
  live renderer, no runtime integration, no training. "Native tests" at this
  stage means the campaign's own named executable checks actually run here
  (M01/M02/M04 precedent); runtime integration remains with the downstream
  native-runtime cards and is NOT claimed.
- Rigid translation kinematics only: no rotation dynamics (a resting block
  cannot tip), no deformation, no spatially varying friction.
- The complete exhaustive comparison stays on small fixtures (independent
  shapes 8 pairs, sternum x clavicle {n(x0b['exhaustive_pairs'])} pairs, S1's
  32 seeded scenes); the full 5384-triangle arm sweep records candidate
  counts and the internal subset property, not a 14.5M-pair exhaustive
  comparison (Amendment A1; recorded as an applicability note, not a pass).
- The CCD uniform-resample fallback (near-tangential resting pairs) can
  under-detect only within the declared bound |w|*dt/S; head-on approaches
  (the frozen X4 claims) converge in one exact Lipschitz step and never use
  the fallback.
- visual_acceptance is false by design in the validator receipt; independent
  visual acceptance is outstanding.

## File identities (sha256, computed at report freeze time)

- local_contact.py {sha('local_contact.py')}
- author_contact.py {sha('author_contact.py')}
- run_experiments.py {sha('run_experiments.py')}
- test_local_contact.py {sha('test_local_contact.py')}
- experiment_receipt.json {sha('experiment_receipt.json')}
- experiment_trace.json {sha('experiment_trace.json')}
- contact_law.json {sha('contact_law.json')}
"""
    (HERE / 'report.md').write_text(report, encoding='utf-8')
    print('report.md written:', len(report), 'chars')


if __name__ == '__main__':
    main()
