// Generated by GameCodeGenerator
#include "GestureWheel.h"
#include "Components/Overlay.h"
#include "Components/CanvasPanel.h"
#include "GameFramework/PlayerController.h"

UGestureWheel::UGestureWheel(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer),
	SelectedSlotIndex(0), CurrentTarget(nullptr), bIsOpen(false)
{
}

void UGestureWheel::NativeConstruct()
{
	Super::NativeConstruct();

	// Register TAB key handlers via the owning Pawn/Character
	if (APlayerController* PC = GetOwningPlayer())
	{
	    // Wheel is controlled by the pawn's input binding;
	    // this widget simply provides the UI and delegates.
	}
}

void UGestureWheel::NativeDestruct()
{
	Super::NativeDestruct();
}

void UGestureWheel::OpenWheel()
{
	if (bIsOpen) return;
	bIsOpen = true;
	if (WheelOverlay) WheelOverlay->SetVisibility(ESlateVisibility::Visible);
	// Witness marker: sleepwalker log_contains expects key on this exact string.
	UE_LOG(LogTemp, Log, TEXT("[GestureWheel] OpenWheel"));
	OnWheelVisibilityChanged.Broadcast(true);
}

void UGestureWheel::CloseWheel()
{
	if (!bIsOpen) return;
	bIsOpen = false;
	if (WheelOverlay) WheelOverlay->SetVisibility(ESlateVisibility::Collapsed);
	OnWheelVisibilityChanged.Broadcast(false);
}

void UGestureWheel::ToggleWheel()
{
	if (bIsOpen) CloseWheel();
	else OpenWheel();
}

void UGestureWheel::CommitGesture(AActor* Target)
{
	if (Target == nullptr) Target = CurrentTarget;

	FGestureEvent Event;
	Event.From = GetOwningPlayer() ? GetOwningPlayer()->GetPawn() : nullptr;
	Event.To = Target;
	Event.Gesture = static_cast<EChimeraGesture>(SelectedSlotIndex);

	// Witness marker: sleepwalker log_contains expects key on this exact string.
	UE_LOG(LogTemp, Log, TEXT("[GestureWheel] CommitGesture slot=%d"), SelectedSlotIndex);
	OnGestureCommitted.Broadcast(Event);
	CloseWheel();
}

void UGestureWheel::SetTarget(AActor* NewTarget)
{
	CurrentTarget = NewTarget;
}

void UGestureWheel::SelectSlot(int32 SlotIndex)
{
	if (SlotIndex < 0 || SlotIndex > 6) return;
	SelectedSlotIndex = SlotIndex;
}

FReply UGestureWheel::OnTabPressed()
{
	OpenWheel();
	return FReply::Handled();
}

FReply UGestureWheel::OnTabReleased()
{
	CommitGesture(CurrentTarget);
	return FReply::Handled();
}
