"""
Chimera Physics Engine — one rule to bind them all.

Everything emerges from particles + physical forces:
  - Gravity → trees grow upward, water flows down, dust settles
  - Light → leaves orient toward sky, atmosphere scatters blue
  - Wind → canopy asymmetry, sand drift, wave patterns
  - Stress → branches taper, rocks fracture, materials deform
  - Fluid → water flows, smoke rises, atmosphere convects

No separate generators. One physics simulation produces all phenomena.
The training data is 2D renders of this simulation from camera angles.
"""

import numpy as np
import math
from dataclasses import dataclass, field
from typing import Callable


@dataclass
class PhysicalLaw:
    """A force or constraint that applies to all particles."""
    name: str
    apply: Callable  # fn(particles, dt) -> None
    enabled: bool = True


class PhysicsUniverse:
    """
    One engine, one set of physical laws. Everything — trees, water,
    atmosphere, rocks — is particles governed by these laws.

    Laws are added modularly. Training data is generated by rendering
    this universe from different camera positions.
    """

    def __init__(self):
        self.laws: dict[str, PhysicalLaw] = {}
        self.particles = None  # GPU buffer
        self.camera = None
        self.renderer = None

    def add_law(self, name: str, fn: Callable):
        """Register a physical law. Applied every frame to all particles."""
        self.laws[name] = PhysicalLaw(name=name, apply=fn)

    def step(self, dt: float):
        """Apply all enabled laws to the particle system."""
        for law in self.laws.values():
            if law.enabled:
                law.apply(self.particles, dt)

    def render(self, camera) -> np.ndarray:
        """Render the current state as a 2D image (training data)."""
        return self.renderer.render_splats(
            self.particles.positions,
            self.particles.covariances,
            self.particles.colors,
            self.particles.opacities,
            camera, camera.params(800, 600),
        )

    def generate_training_data(self, n_views: int = 100) -> list[np.ndarray]:
        """Generate 2D renders from multiple camera angles."""
        images = []
        for i in range(n_views):
            angle = 2 * math.pi * i / n_views
            elevation = math.sin(i * 0.3) * 0.3
            # Position camera, render, collect
            images.append(self.render(self.camera))
        return images


# ═══════════════════════════════════════════════════════════════════
#  Standard physical laws
# ═══════════════════════════════════════════════════════════════════

def law_gravity(particles, dt):
    """F = mg — applies to everything."""
    particles.accelerations += np.array([0, 0, -9.81]) * dt


def law_wind(particles, dt):
    """Drag force proportional to cross-section and wind velocity."""
    wind = np.array([2.0, 0.0, 0.5])  # prevailing wind
    drag_coeff = 0.1
    # Smaller particles experience more drag relative to mass
    size = particles.sizes
    drag = drag_coeff / (size + 0.01)
    particles.accelerations += wind * drag[:, None] * dt


def law_phototropism(particles, dt):
    """Growth toward light (sky hemisphere). For vegetation particles."""
    light_dir = np.array([0.0, 0.0, 1.0])
    strength = 0.5
    # Only applies to vegetation-type particles (type >= some threshold)
    vegetation = particles.types >= 3
    particles.accelerations[vegetation] += light_dir * strength * dt


def law_beam_stress(particles, dt):
    """Structural integrity: thin supports cannot hold heavy loads."""
    # For each branch-like structure, radius must satisfy:
    #   r_parent³ ≥ Σ(r_child³)  (Murray's law)
    # If violated, either thicken parent or prune child
    pass  # Implemented per-structure in tree generator


def law_fluid_pressure(particles, dt):
    """Particles flow from high density to low density regions."""
    # Compute local density for each particle
    # Apply pressure gradient force
    pass  # SPH-style fluid simulation


def law_light_scattering(particles, dt):
    """Rayleigh scattering: blue light scatters more than red."""
    # Atmosphere particles scatter short wavelengths
    pass


# ═══════════════════════════════════════════════════════════════════
#  Default universe with standard laws
# ═══════════════════════════════════════════════════════════════════

def create_default_universe() -> PhysicsUniverse:
    """Create a universe with the standard physical laws."""
    u = PhysicsUniverse()
    u.add_law("gravity", law_gravity)
    u.add_law("wind", law_wind)
    u.add_law("phototropism", law_phototropism)
    # Future: u.add_law("fluid", law_fluid_pressure)
    # Future: u.add_law("scattering", law_light_scattering)
    return u
