#!/usr/bin/env python3
"""MAT2-F06: the report GENERATOR (zero hand-transcribed numbers).

Every number in report.md is rendered from the bound receipts at their
recorded precision; lint_report_numbers.py verifies the traceability.

Run:  python -B make_report.py
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPORT = HERE / "report.md"


def main() -> int:
    r = json.loads((HERE / "receipts" / "walking_receipt.json")
                   .read_bytes().decode("utf-8"))
    a0 = r["A0_flat_regression"]
    a1 = r["A1_route"]
    a2 = r["A2_crest_stall"]
    a3 = r["A3_step_over"]
    a4 = r["A4_approach"]
    fb = r["falsifiers"]
    p8 = r["P8_stability_bars"]
    p9 = r["P9_arc_identity"]
    dc = r["derived_constants"]
    p2 = r["p2_route_replay"]
    lines = []
    add = lines.append
    add("# MAT2-F06 report - terrain-aware walking, generated from the bound receipts")
    add("")
    add("GENERATED by make_report.py from receipts/walking_receipt.json; every")
    add("number is rendered from the receipts at recorded precision and")
    add("lint-verified (lint_report_numbers.py).  Composed against")
    add("CARD_STARTER.md v6 and the house standards IMPLEMENTER_CHECKLIST.md")
    add("(G1-G9) and TOOLKIT.md (P1-P9) cited at the candidate commit.  CPU")
    add("only; the claim class is offline/trace at the "
        + str(a0["P1"]["physics_hz"]) + " Hz tick ("
        + r["derived_constants"]["tc_gap_id"] + " COST-GAP carried); the")
    add("visual acceptance stays false BY DESIGN (the independent visual")
    add("review is the Sergeant's).")
    add("")
    add("## 1. done_when verification (verbatim clause -> evidence)")
    add("")
    add('done_when (verbatim): "Player walks the declared uneven-ground cases')
    add('with certified runtime/training agreement. Material-first addition:')
    add('Qualify player-controlled walking between trees and on the declared')
    add('uneven-ground envelope in the same build as W10, with actual')
    add('contacts."')
    add("")
    add("| clause | execution | measured |")
    add("| --- | --- | --- |")
    add(f"| certified runtime/training agreement | A0: the extension line is "
        f"bit-identical to the certified line on the flat declared surface; "
        f"the certified line reproduces the sealed W08 measured segment-end "
        f"speed | bit_identical "
        f"{str(a0['P1']['bit_identical']).lower()}; v(5415) "
        f"{a0['P1']['v_at_segment_end_m_s']} == sealed "
        f"{a0['P1']['sealed_w08_measured_m_s']} |")
    add(f"| walks the declared uneven-ground cases | A1 walks the sealed "
        f"D_rock_01 route (the measured route slope class) with the derived "
        f"speed floor held and the clearances held; A2 walks the declared "
        f"direct flank line and STALLS exactly as the frozen negative "
        f"predicted | floor {a1['measured_min_speed_m_s']} >= "
        f"{a1['speed_floor_bound_m_s']}; stall tick {a2['stall_tick']}; "
        f"travel {a2['travel_into_stretch_m']} <= {a2['travel_bound_m']} |")
    add(f"| with actual contacts | every tick of every clean arm carries the "
        f"scene's own contact channels; the P8 stability bars are zero on "
        f"all arms | violations " +
        str(sum(b["count"] for b in p8.values())) + " |")
    add("| between trees / declared furniture | A4 walks the declared "
        "approach to the climbable trunk and stops at the declared standoff "
        f"ring | standoff {a4['axis_distance_at_stop_m']} m; penetration "
        f"{a4['trunk_penetration_count']} |")
    add(f"| the named absent variables resolved by measurement | "
        f"x_max_qualified_slope = {a2['x_max_qualified_slope_traversed']} "
        f"traversed (A1), stalled below the crest; x_step_over_case = "
        f"EXECUTED (A3): the certified envelope's step-over ceiling is "
        f"{a3['d_step_m']} m and every declared obstacle top is above it "
        f"(log_02 {a3['log02_top_m']}, deficit {a3['deficit_m']}, required "
        f"lift {a3['required_lift_command']} > bounds_hi 1.8); "
        f"x_slope_gait_qualification = the authored 10/20/30 deg classes are "
        f"NOT walker-qualified (the derived stall grade is "
        f"{r['derived_constants']['gamma_stall']}; the authored classes "
        f"{a2['authored_walk_classes_deg'][0]}/"
        f"{a2['authored_walk_classes_deg'][1]}/"
        f"{a2['authored_walk_classes_deg'][2]} deg) | recorded |")
    add("")
    add("## 2. The sealed route replay (P2)")
    add("")
    add(f"reachable {p2['reachable_cells']} / blocked {p2['blocked_cell_count']} "
        f"/ unattributed {p2['unattributed_count']}; "
        + "; ".join(n + " exact " + str(v["exact"])
                    for n, v in p2["routes"].items())
        + f"; the declared crest route max sampled slope "
        f"{p2['crest_route']['max_sampled_slope']}")
    add("")
    add("## 3. The arms")
    add("")
    add(f"- A0 flat regression: bit-identical (first divergence "
        f"{a0['P1']['first_divergence_tick']}); wrong command diverges at "
        f"{a0['P10']['first_divergence_tick']} (expected "
        f"{a0['P10']['expected_first_divergence_tick']}), separation "
        f"{a0['P10']['separation_m_s']} m/s.")
    add(f"- A1 uneven-ground route: min speed {a1['measured_min_speed_m_s']} "
        f"(bound {a1['speed_floor_bound_m_s']}); measured max grade "
        f"{a1['measured_max_grade']}; min footprint clearance "
        f"{a1['measured_min_footprint_clearance_m']}; terminal "
        f"({a1['terminal_px_m']}, {a1['terminal_pz_m']}) at tick "
        f"{a1['ticks']}.")
    add(f"- A2 crest attempt (the honest negative): stalled at tick "
        f"{a2['stall_tick']} at ({a2['stall_px_m']}, {a2['stall_pz_m']}); "
        f"grade at stall {a2['grade_at_stall']}; travel into the stretch "
        f"{a2['travel_into_stretch_m']} (bound {a2['travel_bound_m']}).")
    add(f"- A3 step-over (the honest negative): the envelope stop fired at "
        f"tick {a3['stop_tick']} at ({a3['stop_px_m']}, {a3['stop_pz_m']}); "
        f"measured fire step {a3['measured_support_spread_m']} (the "
        f"perpendicular ideal band {a3['spread_fire_band']}; the deviation "
        f"{a3['spread_deviation_from_ideal_band']['deviation_m']} is the "
        f"oblique-crossing disclosure of amendment A1.3); deficit "
        f"{a3['deficit_m']}; required lift {a3['required_lift_command']}.")
    add(f"- A4 approach (the gap-10 bridge): the ring contact at tick "
        f"{a4['stop_tick']}; standoff {a4['axis_distance_at_stop_m']} "
        f"(exact: {str(a4['axis_distance_at_stop_exact']).lower()}); "
        f"heading residual {a4['heading_residual_rad']}; the catch margin "
        f"check: {a4['catch_margin_check']}.")
    add("")
    add("## 4. The falsifier arms (G1: clean controls FIRST)")
    add("")
    add("| arm | clean control green | bit |")
    add("| --- | --- | --- |")
    for name, arm in fb.items():
        add(f"| {name} | {str(arm['clean_control']['green']).lower()} | "
            f"{str(arm['bit']).lower()} |")
    add("")
    add(f"F_all_green: {str(r['F_all_green']).lower()}")
    add("")
    add("## 5. The stability bars and the arc identities")
    add("")
    add("| arm | P8 violations | P9 worst residual (m) |")
    add("| --- | --- | --- |")
    for name in ("A0_cert", "A0_ext", "A1", "A2", "A3", "A4"):
        add(f"| {name} | {p8[name]['count']} | "
            f"{p9[name]['worst_residual_m'] if name in p9 else '-'} |")
    add("")
    add("## 6. Honest limitations (declared, never imputed)")
    add("")
    add("- No training ran and no training objective expanded (the "
        "observation clause); the W06 degraded-training record stands; the "
        "trained bundle stays BLOCKED at the pinned deploy gate.")
    add("- The declared negatives are MEASURED: A2 stalled on the m3 flank; "
        "A3's step-over envelope stopped the walk (the certified lift "
        "command ceiling 1.8 cannot mount any declared obstacle top); a "
        "passing step-over requires a new approved runbook.")
    add("- The surrogate has no vertical body dynamics; the support height "
        "is kinematic; the step-over envelope is a swing-apex envelope.")
    add("- Rocks and stands are contact_stop solids without top profiles; "
        "their ascent is unmodeled.")
    add("- The declared scene has ONE climbable trunk; the route cases walk "
        "between the declared obstacle footprints and the trunk under the "
        "declared clearance rules.")
    add("- The approach terminal declares GEOMETRY only; the attach/facing "
        "precondition is K06's (U05's frozen walk contract unchanged).")
    add("- This text-only worker inspected no pictures: pixel claims stay "
        "MEASURED decode checks; image review is owned by the "
        "Sergeant/Lieutenant.")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("report written:", REPORT)
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
