"""
StandingHuman kinematic skeleton specification (Lane K1).

Builds a 77-link rigid-link tree from the existing scaling and structure lanes:
  - LightEngine/skeleton_scaling.scale_skeleton() provides bone geometry,
    mass fractions, and end-type tags.
  - LightEngine/skeleton_structures._body_instances() provides concrete left/right
    instances with proximal/distal endpoints and joint centers.
  - LightEngine/rope_network.py provides the 43 ligament/rope attachment points.

The tree is rooted at the sacrum (the chosen representative of the sacrum/pelvis
base; the two pelvic halves and the spine branch from it).  Every number is
marked ANATOMY-DATUM or DERIVED-GEOMETRY and cites its source.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np

from LightEngine import skeleton_scaling, skeleton_structures
from LightEngine.rope_network import get_rope_network, VERTEBRAL_CENTERS
from LightEngine.constants import R_WALL


# ---------------------------------------------------------------------------
# Settled measured constants
# ---------------------------------------------------------------------------
# Joint capture band measured by prior cushion/joint experiments.
# Source: LightEngine/skeleton_scaling.D_EQ_LU and LightEngine.constants.R_WALL.
S_WALL_LU = R_WALL  # ANATOMY-DATUM: lower bound of the capture band.
D_EQ_LU = skeleton_scaling.D_EQ_LU  # ANATOMY-DATUM: upper bound / d_eq.

# DoF classes encoded from prior experimental verdicts.
BALL_CUP = "ball-cup"  # 3 rotational DoF
SADDLE = "saddle"      # 2 rotational DoF
HINGE = "hinge"        # 1 rotational DoF
SUTURE = "suture"      # 0 rotational DoF

_DOF_COUNT = {
    BALL_CUP: 3,
    SADDLE: 2,
    HINGE: 1,
    SUTURE: 0,
}


# ---------------------------------------------------------------------------
# Tree topology: child link -> (parent link, joint center key).
# ---------------------------------------------------------------------------
# DERIVED-GEOMETRY: each joint center key is a named point from
# LightEngine/skeleton_structures._joint_dict().  The parent is always the next
# link toward the sacrum, so the tree is setting-first from the standing load
# path.  Left/right pairs are generated by suffix substitution.
# ---------------------------------------------------------------------------

_LEVELS = [f"C{i}" for i in range(1, 8)] + \
          [f"T{i}" for i in range(1, 13)] + \
          [f"L{i}" for i in range(1, 6)]


def _spine_topology() -> dict[str, tuple[str | None, str | None]]:
    """Return parent/joint mapping for the skull-spine-sacrum chain."""
    topo: dict[str, tuple[str | None, str | None]] = {
        "sacrum": (None, None),
    }
    # sacrum -> L5 -> L4 -> ... -> C2 -> C1 -> skull
    topo["vertebra_L5"] = ("sacrum", "S1")
    for i in range(len(_LEVELS) - 1):
        lower = _LEVELS[i + 1]
        upper = _LEVELS[i]
        topo[f"vertebra_{upper}"] = (f"vertebra_{lower}", lower)
    topo["skull"] = ("vertebra_C1", "skull_suture")
    return topo


def _torso_topology() -> dict[str, tuple[str | None, str | None]]:
    """Return parent/joint mapping for ribs, sternum, shoulder girdle, arms."""
    topo: dict[str, tuple[str | None, str | None]] = {}
    for side in ("L", "R"):
        for n in range(1, 13):
            vert = f"T{min(n, 12)}"
            topo[f"rib_{side}_{n}"] = (f"vertebra_{vert}", vert)
        topo[f"scapula_{side}"] = (f"rib_{side}_1", f"rib_sternum_{side}_1")
        topo[f"humerus_{side}"] = (f"scapula_{side}", f"shoulder_{side}")
        topo[f"radius_ulna_{side}"] = (f"humerus_{side}", f"elbow_{side}")
        topo[f"hand_{side}"] = (f"radius_ulna_{side}", f"wrist_{side}")
    topo["sternum"] = ("vertebra_T1", "sternum_top")
    for side in ("L", "R"):
        topo[f"clavicle_{side}"] = ("sternum", "sternum_top")
    return topo


def _leg_topology() -> dict[str, tuple[str | None, str | None]]:
    """Return parent/joint mapping for pelvis and legs."""
    topo: dict[str, tuple[str | None, str | None]] = {}
    for side in ("L", "R"):
        topo[f"pelvis_{side}"] = ("sacrum", f"ilium_posterior_{side}")
        topo[f"femur_{side}"] = (f"pelvis_{side}", f"hip_{side}")
        topo[f"patella_{side}"] = (f"femur_{side}", f"knee_{side}")
        topo[f"tibia_{side}"] = (f"femur_{side}", f"knee_{side}")
        topo[f"fibula_{side}"] = (f"femur_{side}", f"knee_{side}")
        topo[f"tarsals_{side}"] = (f"tibia_{side}", f"ankle_{side}")
        topo[f"metatarsals_{side}"] = (f"tarsals_{side}", f"tarsal_{side}")
        topo[f"forefoot_{side}"] = (f"metatarsals_{side}", f"mtp_{side}")
    return topo


def _topology() -> dict[str, tuple[str | None, str | None]]:
    """Return the complete child -> (parent, joint_key) map."""
    topo: dict[str, tuple[str | None, str | None]] = {}
    topo.update(_spine_topology())
    topo.update(_torso_topology())
    topo.update(_leg_topology())
    return topo


# ---------------------------------------------------------------------------
# Local frame construction
# ---------------------------------------------------------------------------
def _orthonormal_basis(z_axis: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return right-handed orthonormal basis (x, y, z) with z = z_axis.

    DERIVED-GEOMETRY: z is the link's long axis.  y is the world lateral
    direction projected perpendicular to z (with a fallback to world anterior
    when the link is nearly vertical).  x completes the right-handed frame.
    This basis is the first approximation for all limb cross-sections; the
    demo battery will measure its error.
    """
    z = np.asarray(z_axis, dtype=np.float64).reshape(3)
    n = float(np.linalg.norm(z))
    if n < 1e-12:
        z = np.array([0.0, 0.0, 1.0], dtype=np.float64)
    else:
        z = z / n

    # Prefer world +y (left lateral) as the anatomical y reference.
    ref = np.array([0.0, 1.0, 0.0], dtype=np.float64)
    if abs(float(np.dot(z, ref))) > 0.9:
        ref = np.array([1.0, 0.0, 0.0], dtype=np.float64)

    y = ref - np.dot(ref, z) * z
    ny = float(np.linalg.norm(y))
    if ny < 1e-12:
        y = np.array([1.0, 0.0, 0.0], dtype=np.float64) if abs(z[0]) < 0.9 else \
            np.array([0.0, 1.0, 0.0], dtype=np.float64)
    else:
        y = y / ny

    x = np.cross(y, z)
    x = x / float(np.linalg.norm(x))
    return x, y, z


def _world_to_local_matrix(x: np.ndarray, y: np.ndarray, z: np.ndarray) -> np.ndarray:
    """Return the 3x3 rotation matrix R such that v_local = R @ v_world."""
    return np.vstack([x, y, z])


# ---------------------------------------------------------------------------
# Spec builders
# ---------------------------------------------------------------------------
def _normalize_mass(instances: list[dict], mass_kg: float) -> dict[str, float]:
    """Normalize design loads so the 77 links sum to mass_kg.

    DERIVED-GEOMETRY: load_fraction from skeleton_scaling is a design load, not
    a true mass fraction.  Renormalizing makes the center-of-mass calculation
    consistent with the requested total body mass.
    """
    total_load = sum(float(inst["row"]["design_load_kg"]) for inst in instances)
    if total_load <= 0.0:
        return {inst["name"]: mass_kg / len(instances) for inst in instances}
    scale = mass_kg / total_load
    return {inst["name"]: float(inst["row"]["design_load_kg"]) * scale
            for inst in instances}


def _solid_rod_inertia(mass_kg: float, length_m: float,
                       outer_diameter_m: float) -> np.ndarray:
    """Return the diagonal inertia tensor (kg*m^2) of a solid cylinder about COM.

    DERIVED-GEOMETRY: radius r = outer_diameter_m / 2 from the scaling table.
    Solid cylinder formulas: I_z = 0.5*m*r^2 about the long axis,
    I_x = I_y = (m/12)*(3*r^2 + L^2) about perpendicular axes through COM.
    """
    r = 0.5 * outer_diameter_m
    r2 = r * r
    L2 = length_m * length_m
    ix = (mass_kg / 12.0) * (3.0 * r2 + L2)
    iz = 0.5 * mass_kg * r2
    return np.array([ix, ix, iz], dtype=np.float64)


def _build_link_specs(instances: list[dict], mass_kg: float,
                      lam: float) -> dict[str, dict[str, Any]]:
    """Return the per-link spec dictionary."""
    mass_by_name = _normalize_mass(instances, mass_kg)
    links: dict[str, dict[str, Any]] = {}

    for inst in instances:
        name = inst["name"]
        row = inst["row"]
        prox_lu = np.asarray(inst["prox"], dtype=np.float64).reshape(3)
        dist_lu = np.asarray(inst["dist"], dtype=np.float64).reshape(3)
        axis_lu = dist_lu - prox_lu
        length_lu = float(np.linalg.norm(axis_lu))
        prox_m = prox_lu * lam
        dist_m = dist_lu * lam
        length_m = length_lu * lam

        # DERIVED-GEOMETRY: uniform-rod midpoint is the first COM approximation.
        # Its error will be measured by the demo battery.
        com_offset_lu = 0.5 * axis_lu
        com_offset_m = com_offset_lu * lam

        mass = mass_by_name[name]
        inertia_m = _solid_rod_inertia(
            mass, length_m, float(row["outer_diameter_m"])
        )
        # Inertia in lu units: I_lu = I_m / lambda^2 (mass*length^2 scaling).
        inertia_lu = inertia_m / (lam ** 2) if lam > 0.0 else inertia_m

        if length_lu > 1e-12:
            x, y, z = _orthonormal_basis(axis_lu)
        else:
            # Zero-length patella: align with world axes as a neutral fallback.
            x, y, z = _orthonormal_basis(np.array([0.0, 0.0, 1.0]))
        R_world_to_local = _world_to_local_matrix(x, y, z)

        links[name] = {
            "name": name,
            "parent_name": None,
            "joint_name": None,
            "row": row,
            "prox_lu": prox_lu,
            "dist_lu": dist_lu,
            "prox_m": prox_m,
            "dist_m": dist_m,
            "length_lu": length_lu,
            "length_m": length_m,
            "mass_kg": mass,
            # DERIVED-GEOMETRY: uniform-rod midpoint; error to be measured.
            "com_offset_lu": com_offset_lu,
            "com_offset_m": com_offset_m,
            # DERIVED-GEOMETRY: solid-rod inertia from table-derived radius.
            "inertia_diag_lu": inertia_lu,
            "inertia_diag_m": inertia_m,
            "R_world_to_local": R_world_to_local,
            "basis_x": x,
            "basis_y": y,
            "basis_z": z,
            "joint_center_local_lu": None,
            "joint_center_local_m": None,
        }

    return links


def _joint_center_local(joint_world_lu: np.ndarray,
                        prox_world_lu: np.ndarray,
                        R_world_to_local: np.ndarray) -> np.ndarray:
    """Return the joint center expressed in a link's local frame."""
    return R_world_to_local @ (joint_world_lu - prox_world_lu)


def _build_joint_specs(links: dict[str, dict[str, Any]],
                       lam: float) -> dict[str, dict[str, Any]]:
    """Return the per-joint spec dictionary keyed by joint name."""
    topo = _topology()
    joints: dict[str, dict[str, Any]] = {}

    for child_name, (parent_name, joint_key) in topo.items():
        if parent_name is None or joint_key is None:
            continue

        child = links[child_name]
        parent = links[parent_name]

        # Use the child link name as the unique joint name; the joint_key is the
        # anatomical center and is retained for documentation.
        joint_name = child_name
        child["parent_name"] = parent_name
        child["joint_name"] = joint_name
        child["joint_center_key"] = joint_key

        # DERIVED-GEOMETRY: vertebral links attach to their parent by the distal
        # end because the spine chain runs upward from sacrum to skull.  All
        # other links attach by the proximal end.
        if child_name.startswith("vertebra_"):
            j_lu = child["dist_lu"].copy()
        else:
            j_lu = child["prox_lu"].copy()
        j_m = j_lu * lam

        # Joint center in parent local frame (where the child hangs).
        center_parent_lu = _joint_center_local(
            j_lu, parent["prox_lu"], parent["R_world_to_local"]
        )
        center_parent_m = center_parent_lu * lam

        # Joint center in child local frame (where the child attaches to parent).
        center_child_lu = _joint_center_local(
            j_lu, child["prox_lu"], child["R_world_to_local"]
        )
        center_child_m = center_child_lu * lam

        child["joint_center_local_lu"] = center_child_lu
        child["joint_center_local_m"] = center_child_m

        # DoF class is taken from the child's proximal end tag, per doctrine.
        dof_class = str(child["row"]["prox"])
        if dof_class not in _DOF_COUNT:
            raise ValueError(
                f"Link {child_name!r} has illegal prox type {dof_class!r}"
            )

        # Axes are defined in the PARENT local frame (the joint rotation frame).
        px, py, pz = parent["basis_x"], parent["basis_y"], parent["basis_z"]
        if dof_class == HINGE:
            # DERIVED-GEOMETRY: first approximation uses the parent lateral axis
            # (perpendicular to the sagittal plane).  Per-joint refinements will
            # be measured by the demo battery.
            axes = [py.copy()]
        elif dof_class == SADDLE:
            # DERIVED-GEOMETRY: two orthogonal axes in the parent frame.
            axes = [py.copy(), px.copy()]
        else:
            axes = []

        joints[joint_name] = {
            "name": joint_name,
            "parent_link": parent_name,
            "child_link": child_name,
            "center_parent_local_lu": center_parent_lu,
            "center_parent_local_m": center_parent_m,
            "center_child_local_lu": center_child_lu,
            "center_child_local_m": center_child_m,
            "center_lu": j_lu,
            "center_m": j_m,
            "dof_class": dof_class,
            "axes": axes,
            # Joint capture band [S_WALL, d_eq]; d_eq is stored as the tolerance.
            "play_tolerance_lu": D_EQ_LU,
            "play_tolerance_m": D_EQ_LU * lam,
            "s_wall_lu": S_WALL_LU,
            "s_wall_m": S_WALL_LU * lam,
        }

    return joints


# ---------------------------------------------------------------------------
# Ligaments from the rope network
# ---------------------------------------------------------------------------
def _rope_anchor_link(anchor: str, side: str | None) -> str:
    """Map a rope anchor name to a concrete link name.

    DERIVED-GEOMETRY: generic names in rope_network.py are resolved to the
    left/right instance used by this lane's body_instances().
    """
    side_suffix = f"_{side}" if side in ("L", "R") else ""

    if anchor in ("femur", "tibia", "pelvis", "ilium", "scapula", "humerus"):
        return f"{anchor}{side_suffix}" if anchor != "ilium" else f"pelvis{side_suffix}"
    if anchor in ("calcaneus", "tarsal_base"):
        return f"tarsals{side_suffix}"
    if anchor == "metatarsal_base":
        return f"metatarsals{side_suffix}"
    if anchor == "sacrum":
        return "sacrum"
    if anchor == "skull":
        return "skull"
    if anchor == "S1":
        return "sacrum"
    if anchor in VERTEBRAL_CENTERS:
        return f"vertebra_{anchor}"
    raise ValueError(f"Unmapped rope anchor {anchor!r} for side {side!r}")


def _build_ligament_specs(links: dict[str, dict[str, Any]],
                          height_lu: float, lam: float) -> list[dict[str, Any]]:
    """Return ligament records with attachments in link-local frames.

    DERIVED-GEOMETRY: rope anchor points (in H units) are scaled to lu and then
    expressed as (link_name, local_offset) so the dynamics lane can attach
    springs without re-deriving the geometry.  Stiffness and rest-length are
    placeholders for the dynamics lane.
    """
    ligaments: list[dict[str, Any]] = []
    for rope in get_rope_network():
        name = str(rope["name"])
        side: str | None = None
        if name.endswith("_L"):
            side = "L"
        elif name.endswith("_R"):
            side = "R"

        anchor_a = str(rope["anchor_a"])
        anchor_b = str(rope["anchor_b"])
        link_a = _rope_anchor_link(anchor_a, side)
        link_b = _rope_anchor_link(anchor_b, side)

        point_a_lu = np.asarray(rope["anchor_a_point"], dtype=np.float64).reshape(3) * height_lu
        point_b_lu = np.asarray(rope["anchor_b_point"], dtype=np.float64).reshape(3) * height_lu
        point_a_m = point_a_lu * lam
        point_b_m = point_b_lu * lam

        def _attachment(link_name: str, point_lu: np.ndarray, point_m: np.ndarray):
            link = links[link_name]
            offset_lu = link["R_world_to_local"] @ (point_lu - link["prox_lu"])
            offset_m = offset_lu * lam
            return {
                "link": link_name,
                "point_lu": point_lu,
                "point_m": point_m,
                "offset_lu": offset_lu,
                "offset_m": offset_m,
            }

        rest_length_lu = float(np.linalg.norm(point_b_lu - point_a_lu))
        rest_length_m = rest_length_lu * lam

        ligaments.append({
            "name": name,
            "anchor_a": _attachment(link_a, point_a_lu, point_a_m),
            "anchor_b": _attachment(link_b, point_b_lu, point_b_m),
            "rest_length_lu": rest_length_lu,
            "rest_length_m": rest_length_m,
            # Placeholder for the dynamics lane.
            "stiffness": None,
        })

    return ligaments


def _build_contact_specs(height_lu: float, lam: float) -> dict[str, list[dict[str, Any]]]:
    """Return foot support polygon points per side.

    DERIVED-GEOMETRY: points are the scaled joint centers projected to z=0,
    exactly as produced by LightEngine/skeleton_structures._foot_projection_points().
    """
    points = skeleton_structures._foot_projection_points(height_lu)
    contacts: dict[str, list[dict[str, Any]]] = {}
    for side in ("L", "R"):
        contacts[side] = []
        for x, y in points[side]:
            p_lu = np.array([float(x), float(y), 0.0], dtype=np.float64)
            p_m = p_lu * lam
            contacts[side].append({"point_lu": p_lu, "point_m": p_m})
    return contacts


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def build_spec(height_m: float = 1.80, mass_kg: float = 80.0) -> dict[str, Any]:
    """Build and return the 77-link StandingHuman kinematic spec.

    Returns a dictionary with keys:
      - "links": dict[str, dict]     -- per-link rigid-body data.
      - "joints": dict[str, dict]    -- per-joint data (parent, child, DoF, axes).
      - "ligaments": list[dict]      -- 43 rope-derived ligament records.
      - "contacts": dict[str, list]  -- foot support polygon points per side.
      - "lam": float                 -- meters per lu (derived from budget fit).
      - "height_lu": float           -- total standing height in lu.
      - "height_m": float            -- input height in meters.
      - "mass_kg": float             -- input mass in kilograms.
    """
    table, lam, total, breakdown, rc, cand_log = skeleton_scaling.scale_skeleton(
        height_m, mass_kg
    )
    height_lu = height_m / lam

    instances = skeleton_structures._body_instances(table, height_lu)
    instances_by_name = {inst["name"]: inst for inst in instances}

    # Validate that the topology covers exactly the generated instances.
    topo = _topology()
    expected_names = set(instances_by_name.keys())
    topo_names = set(topo.keys())
    missing = expected_names - topo_names
    extra = topo_names - expected_names
    if missing:
        raise RuntimeError(f"Topology missing links: {sorted(missing)}")
    if extra:
        raise RuntimeError(f"Topology has extra links: {sorted(extra)}")

    links = _build_link_specs(instances, mass_kg, lam)
    joints = _build_joint_specs(links, lam)
    ligaments = _build_ligament_specs(links, height_lu, lam)
    contacts = _build_contact_specs(height_lu, lam)

    # Ensure every non-root link has a joint record.
    for name, link in links.items():
        if link["parent_name"] is None:
            continue
        jname = link["joint_name"]
        if jname not in joints:
            raise RuntimeError(f"Link {name!r} references missing joint {jname!r}")

    return {
        "links": links,
        "joints": joints,
        "ligaments": ligaments,
        "contacts": contacts,
        "lam": lam,
        "height_lu": height_lu,
        "height_m": height_m,
        "mass_kg": mass_kg,
        "total_grain_estimate": total,
        "breakdown": breakdown,
        "rung_counts": rc,
    }
