"""spec_format.py -- the executable mathematical specification document
format (chimera.mathspec.spec.v1) and its validator.

mathspec lane wk-mathspec-core, phase 1. The format is BOUNDED to the first
supported class: ODE membranes with typed ports, coupled by declared
connections. Everything is validated structurally BEFORE anything runs:

  owned state vars + units            (exactly one owner per variable)
  parameters w/ domains + provenance  (measured | derived | synthetic)
  typed port inputs/outputs           (unit + sign convention + connection ref)
  evolution equations                 (restricted language, unit-checked)
  preconditions / invariants /        (predicate expressions, named codes)
  refusal conditions
  timestep + numerical-method         (declared admissible dt table, BEFORE
  assumptions                          any qualification run)
  required integration checks         (structural vs numerical-evidence)

Unit algebra: every declared unit decomposes to a dimension vector over
{length, mass, time, temperature}; + and - require equal dimensions; * and /
compose them. Offset-bearing units (degC) may be declared standalone but are
refused inside composition (E_SPEC_UNIT_OFFSET_COMPOSED). A dimension error is
a named refusal, never a warning.

This validator REUSES the frozen v2 port-contract law at the format level
(port ids, sign conventions, owner routing, exactly-one-ownership); the v2
CONTRACT instance itself is generated by spec_generate and validated by the
pinned PORT_CONTRACT_V2 (see spec_runtime). Nothing here validates physics
truth: synthetic provenance is declared as synthetic, and a MEASURED class
would require a store binding (E_SPEC_MEASURED_UNBOUND if absent).
"""
from __future__ import annotations

import math

import spec_lang
from spec_lang import ExprRefusal, parse, free_names, evaluate

# ---------- named refusal codes ---------------------------------------------------

E_SPEC_MALFORMED = "spec_malformed_document"
E_SPEC_SCHEMA_MISMATCH = "spec_schema_mismatch"
E_SPEC_DUPLICATE_ID = "spec_duplicate_id"
E_SPEC_UNKNOWN_MEMBRANE = "spec_unknown_membrane"
E_SPEC_OWNERSHIP_CONFLICT = "spec_ownership_conflict"
E_SPEC_STATE_NOT_OWNED = "spec_state_not_owned"
E_SPEC_UNIT_UNKNOWN = "spec_unit_unknown"
E_SPEC_UNIT_MISMATCH = "spec_unit_mismatch"
E_SPEC_UNIT_OFFSET_COMPOSED = "spec_unit_offset_composed"
E_SPEC_PROVENANCE_MISSING = "spec_provenance_missing"
E_SPEC_PROVENANCE_CLASS_INVALID = "spec_provenance_class_invalid"
E_SPEC_MEASURED_UNBOUND = "spec_measured_provenance_unbound"
E_SPEC_PORT_TYPE_MISMATCH = "spec_port_type_mismatch"
E_SPEC_PORT_SIGN_MISSING = "spec_port_sign_convention_missing"
E_SPEC_PORT_CONNECTION_UNKNOWN = "spec_port_connection_unknown"
E_SPEC_TRANSFER_TARGET_NOT_OWNED = "spec_transfer_target_not_owned"
E_SPEC_TRANSFER_MEMBER_INVALID = "spec_transfer_member_invalid"
E_SPEC_EXCHANGE_OWNER_INVALID = "spec_exchange_owner_invalid"
E_SPEC_DT_NOT_ADMISSIBLE = "spec_dt_not_admissible"
E_SPEC_METHOD_UNSUPPORTED = "spec_method_unsupported"
E_SPEC_INITIAL_STATE_DOMAIN = "spec_initial_state_domain"
E_SPEC_EXPRESSION_SLOT_INVALID = "spec_expression_slot_invalid"
E_SPEC_EVOLUTION_TARGET_INVALID = "spec_evolution_target_invalid"
E_SPEC_PUBLISHED_NOT_OWNED = "spec_published_not_owned"
E_SPEC_CONNECTION_MEMBER_INVALID = "spec_connection_member_invalid"
E_SPEC_CONSERVED_UNIT_MISMATCH = "spec_conserved_unit_mismatch"
E_SPEC_VALUE_NONFINITE = "spec_value_nonfinite"
E_SPEC_DOMAIN_INVALID = "spec_domain_invalid"
E_SPEC_ADMISSIBILITY_TABLE_INVALID = "spec_admissibility_table_invalid"
E_SPEC_CHECK_KIND_INVALID = "spec_check_kind_invalid"

SPEC_SCHEMA = "chimera.mathspec.spec.v1"
SUPPORTED_METHODS = ("explicit_euler",)
PROVENANCE_CLASSES = ("measured", "derived", "synthetic")
PORT_TYPES = ("scalar_real",)
CHECK_KINDS = ("structural", "numerical_evidence")

# dimension vector atoms
_L, _M, _T, _THETA = "length", "mass", "time", "temperature"

INTEGRATION_TIME = {_T: 1}  # dimension of seconds

CANONICAL_UNITS = {
    # atomics
    "m": {_L: 1},
    "kg": {_M: 1},
    "s": {_T: 1},
    "K": {_THETA: 1},
    # derived (SI coherent)
    "N": {_M: 1, _L: 1, _T: -2},
    "J": {_M: 1, _L: 2, _T: -2},
    "W": {_M: 1, _L: 2, _T: -3},
    "Pa": {_M: 1, _L: -1, _T: -2},
    "unitless": {},
}
OFFSET_UNITS = {
    # standalone-only: an offset may never enter composition
    "degC": {_THETA: 1},
}
OFFSET_K = 273.15  # degC -> K, mirroring tools/material_iface units.py

_TIME_UNIT = "s"


def canonical_unit(text: str) -> dict:
    """Parse a unit string into a dimension vector. Grammar: atoms joined by
    '*' (multiply) and '/' (divide), e.g. 'J/K', 'K/s', 'W', 'unitless'.
    Unknown atoms are refused by name; offset units refuse composition."""
    if not isinstance(text, str) or not text.strip():
        raise ExprRefusal(E_SPEC_UNIT_UNKNOWN,
                          "a unit must be a nonempty string", {"unit": text})
    num_part, _, den_part = text.partition("/")
    dims: dict = {}

    def mul(vec, sign):
        for atom, exp in vec.items():
            dims[atom] = dims.get(atom, 0) + sign * exp

    def atom_vector(atom):
        atom = atom.strip()
        if atom in CANONICAL_UNITS:
            return dict(CANONICAL_UNITS[atom])
        if atom in OFFSET_UNITS:
            raise ExprRefusal(E_SPEC_UNIT_OFFSET_COMPOSED,
                              f"offset unit {atom!r} may be declared "
                              f"standalone only, never composed", {
                                  "unit": text})
        raise ExprRefusal(E_SPEC_UNIT_UNKNOWN,
                          f"unit atom {atom!r} is not canonical", {
                              "unit": text,
                              "canonical": sorted(CANONICAL_UNITS),
                              "offset_standalone": sorted(OFFSET_UNITS)})

    n_terms = 0
    for term in num_part.split("*"):
        mul(atom_vector(term), +1)
        n_terms += 1
    if den_part:
        for term in den_part.split("*"):
            mul(atom_vector(term), -1)
            n_terms += 1
    if n_terms == 0:
        raise ExprRefusal(E_SPEC_UNIT_UNKNOWN, "empty unit", {"unit": text})
    return {k: v for k, v in dims.items() if v != 0}


def dims_equal(a: dict, b: dict) -> bool:
    return a == b


def compose_dims(a: dict, b: dict, op: str) -> dict:
    out = dict(a)
    if op == "*":
        for atom, exp in b.items():
            out[atom] = out.get(atom, 0) + exp
    elif op == "/":
        for atom, exp in b.items():
            out[atom] = out.get(atom, 0) - exp
    else:  # + or -
        if a != b:
            raise ExprRefusal(E_SPEC_UNIT_MISMATCH,
                              "addition of unequal dimensions", {
                                  "left": a, "right": b})
        return dict(a)
    return {k: v for k, v in out.items() if v != 0}


# ---------- AST unit inference -------------------------------------------------------

def infer_dims(node, scope: dict) -> dict:
    """Infer the dimension vector of a numeric AST. `scope` maps every free
    name to its dimension vector. Literals are unitless. Predicate nodes are
    refused in numeric slots (the caller checks the expression class first)."""
    kind = node.kind
    if kind == "num":
        return {}
    if kind == "name":
        if node.ident not in scope:
            raise ExprRefusal(spec_lang.E_EXPR_NAME_NOT_IN_SCOPE,
                              f"name {node.ident!r} not in the declared "
                              f"scope", {"name": node.ident})
        return dict(scope[node.ident])
    if kind == "unaryop":
        return infer_dims(node.operand, scope)
    if kind == "binop":
        ld = infer_dims(node.left, scope)
        rd = infer_dims(node.right, scope)
        return compose_dims(ld, rd, node.op)
    if kind == "call":
        arg_dims = [infer_dims(a, scope) for a in node.args]
        fn = node.func
        if fn == "abs":
            return dict(arg_dims[0])
        if fn in ("min", "max"):
            if arg_dims[0] != arg_dims[1]:
                raise ExprRefusal(E_SPEC_UNIT_MISMATCH,
                                  f"{fn} over unequal dimensions", {})
            return dict(arg_dims[0])
        if fn in ("sqrt", "exp", "log"):
            if fn == "sqrt":
                if any(v % 2 for v in arg_dims[0].values()):
                    raise ExprRefusal(
                        E_SPEC_UNIT_MISMATCH,
                        "sqrt of an odd-exponent dimension vector", {})
                return {k: v // 2 for k, v in arg_dims[0].items()}
            if arg_dims[0] != {}:
                raise ExprRefusal(
                    E_SPEC_UNIT_MISMATCH,
                    f"{fn} requires a unitless argument", {})
            return {}
    raise ExprRefusal(E_SPEC_EXPRESSION_SLOT_INVALID,
                      f"non-numeric AST node {kind!r} in a numeric slot", {
                          "kind": kind})


# ---------- the validator -------------------------------------------------------------

class SpecReport:
    def __init__(self, spec_id):
        self.valid = True
        self.errors: list = []
        self.spec_id = spec_id
        # resolution tables (filled on success; reused by spec_runtime)
        self.state_ids: dict = {}          # (membrane_id, var) -> state_id
        self.state_owner: dict = {}        # state_id -> membrane_id
        self.state_var: dict = {}          # state_id -> var
        self.var_dims: dict = {}           # (membrane_id, var) -> dims
        self.param_dims: dict = {}         # (owner_scope, var) -> dims
        self.param_values: dict = {}       # (owner_scope, var) -> float
        self.exchange_refs: dict = {}      # quantity_ref -> connection_id
        self.membrane_ids: list = []
        self.connections: list = []

    def refuse(self, code: str, detail: dict):
        self.valid = False
        self.errors.append({"code": code, "detail": detail})

    def summary(self) -> dict:
        return {"valid": self.valid, "spec_id": self.spec_id,
                "errors": self.errors}


def _name_unit_dims(unit_text: str, collector) -> dict:
    try:
        return canonical_unit(unit_text)
    except ExprRefusal as exc:
        collector.refuse(exc.code, dict(exc.detail, origin="unit_decl"))
        return {}


def _parse_slot(text, slot_id, expect_class, scope_dims, report,
                allowed_names: set):
    """Parse one expression slot; resolve scope + class + dimensions."""
    try:
        ast = parse(text)
    except ExprRefusal as exc:
        report.refuse(exc.code, dict(exc.detail, slot=slot_id))
        return None
    cls = spec_lang.expression_class(ast)
    names = free_names(ast)
    for n in sorted(names):
        if n not in allowed_names:
            report.refuse(spec_lang.E_EXPR_NAME_NOT_IN_SCOPE,
                          {"name": n, "slot": slot_id,
                           "allowed": sorted(allowed_names)})
    if expect_class == "numeric":
        if cls == "predicate":
            report.refuse(E_SPEC_EXPRESSION_SLOT_INVALID,
                          {"slot": slot_id,
                           "law": "a predicate cannot populate a numeric "
                                  "slot"})
        elif cls != "name" or (cls == "name" and
                               getattr(ast, "ident", "") in scope_dims):
            try:
                infer_dims(ast, scope_dims)
            except ExprRefusal as exc:
                report.refuse(exc.code, dict(exc.detail, slot=slot_id))
    else:  # predicate slot
        if cls == "numeric" or (cls == "name" and
                                getattr(ast, "ident", "") in scope_dims):
            report.refuse(E_SPEC_EXPRESSION_SLOT_INVALID,
                          {"slot": slot_id,
                           "law": "a numeric expression cannot populate a "
                                  "predicate slot"})
    return ast


def validate_spec(spec: dict) -> SpecReport:
    """Validate one spec document. Returns the report with resolution tables.
    ALL findings are reported (no first-error-only); valid=False refuses the
    document everywhere downstream."""
    if not isinstance(spec, dict):
        r = SpecReport(None)
        r.refuse(E_SPEC_MALFORMED, {"law": "a spec document is a JSON object"})
        return r
    spec_id = spec.get("spec_id")
    r = SpecReport(spec_id)

    if spec.get("schema") != SPEC_SCHEMA:
        r.refuse(E_SPEC_SCHEMA_MISMATCH,
                 {"schema": spec.get("schema"), "expected": SPEC_SCHEMA})
        return r
    if not spec_lang_free_of_placeholders(spec.get("spec_version")):
        r.refuse(E_SPEC_MALFORMED, {"spec_version": spec.get("spec_version")})

    # ---- authority + provenance classes ------------------------------------
    authority = spec.get("authority") or {}
    for field in ("authorization", "claims_scope"):
        if not str(authority.get(field) or "").strip():
            r.refuse(E_SPEC_MALFORMED, {"missing": f"authority.{field}"})

    # ---- global reference parameters ----------------------------------------
    global_dims: dict = {}
    for p in spec.get("global_parameters") or []:
        var = p.get("var")
        if not var:
            r.refuse(E_SPEC_MALFORMED, {"missing": "global_parameters[].var"})
            continue
        if ("global", var) in r.param_dims:
            r.refuse(E_SPEC_DUPLICATE_ID, {"kind": "global_parameter",
                                           "var": var})
        dims = _name_unit_dims(p.get("unit", ""), r)
        r.param_dims[("global", var)] = dims
        r.param_values[("global", var)] = _declared_value(p, "global", var, r)
        global_dims[var] = dims

    # ---- membranes ------------------------------------------------------------
    membranes = spec.get("membranes") or []
    if not membranes:
        r.refuse(E_SPEC_MALFORMED, {"law": "a spec declares >= 1 membrane"})
    for m in membranes:
        mid = m.get("membrane_id")
        if not mid:
            r.refuse(E_SPEC_MALFORMED, {"missing": "membranes[].membrane_id"})
            continue
        if mid in r.membrane_ids:
            r.refuse(E_SPEC_DUPLICATE_ID, {"kind": "membrane", "id": mid})
            continue
        r.membrane_ids.append(mid)

    # per membrane: state + parameters + scope
    membrane_scope: dict = {}   # mid -> {name -> dims}
    for m in membranes:
        mid = m.get("membrane_id")
        if mid not in r.membrane_ids:
            continue
        scope: dict = {}
        owned = m.get("owned_state") or []
        if not owned:
            r.refuse(E_SPEC_MALFORMED,
                     {"membrane_id": mid,
                      "law": "an ODE membrane owns >= 1 state variable"})
        for st in owned:
            var = st.get("var")
            if not var:
                r.refuse(E_SPEC_MALFORMED,
                         {"membrane_id": mid, "missing": "owned_state[].var"})
                continue
            if (mid, var) in r.var_dims:
                r.refuse(E_SPEC_DUPLICATE_ID,
                         {"kind": "state_var", "membrane_id": mid,
                          "var": var})
            dims = _name_unit_dims(st.get("unit", ""), r)
            r.var_dims[(mid, var)] = dims
            _validate_domain(st.get("domain"), r, mid, var)
            scope[var] = dims
        for p in m.get("parameters") or []:
            var = p.get("var")
            if not var:
                r.refuse(E_SPEC_MALFORMED,
                         {"membrane_id": mid,
                          "missing": "parameters[].var"})
                continue
            if (mid, var) in r.param_dims or var in scope:
                r.refuse(E_SPEC_DUPLICATE_ID,
                         {"kind": "name", "membrane_id": mid, "var": var})
            dims = _name_unit_dims(p.get("unit", ""), r)
            r.param_dims[(mid, var)] = dims
            r.param_values[(mid, var)] = _declared_value(p, mid, var, r)
            _validate_provenance(p.get("provenance"), r, mid, var)
            scope[var] = dims
        membrane_scope[mid] = scope

    # ---- connections: exchange + ports + transfer law -------------------------
    conns = spec.get("connections") or []
    if not conns:
        r.refuse(E_SPEC_MALFORMED, {"law": "the first class requires >= 1 "
                                           "typed connection"})
    for c in conns:
        cid = c.get("connection_id")
        if not cid:
            r.refuse(E_SPEC_MALFORMED,
                     {"missing": "connections[].connection_id"})
            continue
        if cid in r.exchange_refs.values() or any(
                x.get("connection_id") == cid for x in r.connections):
            r.refuse(E_SPEC_DUPLICATE_ID, {"kind": "connection", "id": cid})
            continue
        r.connections.append(c)
        members = c.get("members") or []
        for mid in members:
            if mid not in r.membrane_ids:
                r.refuse(E_SPEC_UNKNOWN_MEMBRANE,
                         {"connection_id": cid, "membrane_id": mid})
        if len(members) != 2:
            r.refuse(E_SPEC_CONNECTION_MEMBER_INVALID,
                     {"connection_id": cid,
                      "law": "the first class is a two-membrane connection",
                      "members": members})
        for p in c.get("parameters") or []:
            var = p.get("var")
            if not var:
                r.refuse(E_SPEC_MALFORMED,
                         {"connection_id": cid,
                          "missing": "parameters[].var"})
                continue
            key = (cid, var)
            if key in r.param_dims:
                r.refuse(E_SPEC_DUPLICATE_ID,
                         {"kind": "connection_parameter",
                          "connection_id": cid, "var": var})
            dims = _name_unit_dims(p.get("unit", ""), r)
            r.param_dims[key] = dims
            r.param_values[key] = _declared_value(p, cid, var, r)
            _validate_provenance(p.get("provenance"), r, cid, var)
        ex = c.get("exchange") or {}
        qref = ex.get("quantity_ref")
        if not qref:
            r.refuse(E_SPEC_MALFORMED,
                     {"connection_id": cid,
                      "missing": "exchange.quantity_ref"})
        elif qref in r.exchange_refs:
            r.refuse(E_SPEC_DUPLICATE_ID,
                     {"kind": "exchange_quantity", "quantity_ref": qref})
        else:
            r.exchange_refs[qref] = cid
        ex_dims = _name_unit_dims(ex.get("unit", ""), r)
        if not str(ex.get("sign_convention") or "").strip():
            r.refuse(E_SPEC_PORT_SIGN_MISSING,
                     {"connection_id": cid,
                      "law": "the ONE signed exchange quantity declares its "
                             "sign convention"})
        owner = ex.get("owner_membrane")
        if owner not in r.membrane_ids or (members and owner not in members):
            r.refuse(E_SPEC_EXCHANGE_OWNER_INVALID,
                     {"connection_id": cid, "owner_membrane": owner,
                      "members": members,
                      "law": "the exchange record is owned by a MEMBER "
                             "membrane (the v2 'owns' edge has no "
                             "connection vertices)"})
        # exchange expression scope: consumed published states + connection
        # parameters -- nothing else.
        ex_scope: dict = {}
        for cons in c.get("consumed") or []:
            fmid = cons.get("from_membrane")
            qv = cons.get("quantity_ref")
            if fmid not in r.membrane_ids:
                r.refuse(E_SPEC_UNKNOWN_MEMBRANE,
                         {"connection_id": cid, "from_membrane": fmid})
                continue
            if (fmid, qv) not in r.var_dims:
                r.refuse(E_SPEC_PUBLISHED_NOT_OWNED,
                         {"connection_id": cid, "from_membrane": fmid,
                          "quantity_ref": qv,
                          "law": "a connection consumes a PUBLISHED state "
                                 "of the member membrane"})
                continue
            pub = (m.get("published_states") for m in membranes
                   if m.get("membrane_id") == fmid)
            pub_list = next(pub, []) or []
            if qv not in pub_list:
                r.refuse(E_SPEC_PUBLISHED_NOT_OWNED,
                         {"connection_id": cid, "from_membrane": fmid,
                          "quantity_ref": qv,
                          "published": sorted(pub_list)})
            ex_scope[qv] = r.var_dims[(fmid, qv)]
        for var in (c.get("parameters") or []):
            if var.get("var"):
                ex_scope[var["var"]] = r.param_dims[(cid, var["var"])]
        if qref:
            _parse_slot(ex.get("expr", ""), f"{cid}.exchange", "numeric",
                        ex_scope, r, set(ex_scope))
        # transfer law
        tl = c.get("transfer_law") or {}
        if tl.get("applied_by") != "assembly":
            r.refuse(E_SPEC_MALFORMED,
                     {"connection_id": cid,
                      "law": "transfer_law.applied_by == 'assembly': the "
                             "assembly applies the transfers EXACTLY ONCE"})
        per = tl.get("per_membrane") or []
        if members and sorted(x.get("membrane_id") for x in per) != \
                sorted(members):
            r.refuse(E_SPEC_TRANSFER_MEMBER_INVALID,
                     {"connection_id": cid,
                      "law": "transfer_law declares EXACTLY ONE entry per "
                             "member membrane",
                      "declared": sorted(x.get("membrane_id") for x in per),
                      "members": sorted(members)})
        for row in per:
            mid = row.get("membrane_id")
            target = row.get("target")
            if (mid, target) not in r.var_dims:
                r.refuse(E_SPEC_TRANSFER_TARGET_NOT_OWNED,
                         {"connection_id": cid, "membrane_id": mid,
                          "target": target,
                          "law": "each member's transfer targets its OWN "
                                 "owned state only"})
                continue
            scope = dict(membrane_scope.get(mid) or {})
            if qref:
                scope[qref] = ex_dims
            scope["dt"] = dict(INTEGRATION_TIME)
            _parse_slot(row.get("expr", ""), f"{cid}.transfer.{mid}",
                        "numeric", scope, r, set(scope))
            # the transfer must carry the state's unit per unit time:
            try:
                tds = compose_dims(r.var_dims[(mid, target)],
                                   dict(INTEGRATION_TIME), "/")
                got = infer_dims(parse(row.get("expr", "")), scope)
                if got != tds:
                    r.refuse(E_SPEC_UNIT_MISMATCH,
                             {"slot": f"{cid}.transfer.{mid}",
                              "expected_dims": tds, "got_dims": got,
                              "law": "transfer expr has the dimensions of "
                                     "the state per second (it is "
                                     "multiplied by dt)"})
            except ExprRefusal as exc:
                r.refuse(exc.code, dict(exc.detail,
                                        slot=f"{cid}.transfer.{mid}"))
            le = row.get("ledger_entry") or {}
            if not str(le.get("entry_id") or "").strip():
                r.refuse(E_SPEC_MALFORMED,
                         {"connection_id": cid, "membrane_id": mid,
                          "law": "every transfer declares its ledger entry"})
            else:
                lscope = {"dt": dict(INTEGRATION_TIME)}
                if qref:
                    lscope[qref] = ex_dims
                _parse_slot(le.get("value_expr", ""),
                            f"{cid}.ledger.{mid}", "numeric", lscope, r,
                            set(lscope))
                try:
                    got = infer_dims(parse(le.get("value_expr", "")),
                                     lscope)
                    want = canonical_unit(le.get("unit", ""))
                    if got != want:
                        r.refuse(E_SPEC_UNIT_MISMATCH,
                                 {"slot": f"{cid}.ledger.{mid}",
                                  "declared_unit": le.get("unit"),
                                  "got_dims": got})
                except ExprRefusal as exc:
                    r.refuse(exc.code, dict(exc.detail,
                                            slot=f"{cid}.ledger.{mid}"))

    # ---- membrane evolution + predicates (after connections: q refs known) -----
    for m in membranes:
        mid = m.get("membrane_id")
        if mid not in r.membrane_ids:
            continue
        scope = dict(membrane_scope.get(mid) or {})
        for qref, cid in sorted(r.exchange_refs.items()):
            conn = next((x for x in r.connections
                         if x.get("connection_id") == cid), None)
            if conn and mid in (conn.get("members") or []):
                scope[qref] = _name_unit_dims(
                    (conn.get("exchange") or {}).get("unit", ""), r)
        published = m.get("published_states") or []
        for var in published:
            if (mid, var) not in r.var_dims:
                r.refuse(E_SPEC_PUBLISHED_NOT_OWNED,
                         {"membrane_id": mid, "quantity_ref": var,
                          "law": "a membrane publishes only its OWN state"})
        owned_vars = {st.get("var") for st in (m.get("owned_state") or [])
                      if st.get("var")}
        for evo in m.get("evolution") or []:
            target = evo.get("target")
            if target not in owned_vars:
                r.refuse(E_SPEC_EVOLUTION_TARGET_INVALID,
                         {"membrane_id": mid, "target": target,
                          "law": "evolution targets an OWNED state variable "
                                 "only"})
                continue
            slot = f"{mid}.evolution.{target}"
            ast = _parse_slot(evo.get("expr", ""), slot, "numeric", scope, r,
                              set(scope))
            if ast is not None:
                try:
                    want = compose_dims(r.var_dims[(mid, target)],
                                        dict(INTEGRATION_TIME), "/")
                    got = infer_dims(ast, scope)
                    declared = canonical_unit(evo.get("unit", ""))
                    if got != want or declared != want:
                        r.refuse(E_SPEC_UNIT_MISMATCH,
                                 {"slot": slot, "expected_dims": want,
                                  "got_dims": got,
                                  "declared_unit_dims": declared,
                                  "law": "evolution expr is d(state)/s"})
                except ExprRefusal as exc:
                    r.refuse(exc.code, dict(exc.detail, slot=slot))
        for slot_group, expect in (("preconditions", "predicate"),
                                   ("invariants", "predicate"),
                                   ("refusal_conditions", "predicate")):
            for row in m.get(slot_group) or []:
                rid = row.get("id")
                if not rid:
                    r.refuse(E_SPEC_MALFORMED,
                             {"membrane_id": mid,
                              "missing": f"{slot_group}[].id"})
                    continue
                if row.get("refusal_code") is not None and \
                        not str(row["refusal_code"]).strip():
                    r.refuse(E_SPEC_MALFORMED,
                             {"membrane_id": mid, "id": rid,
                              "law": "refusal_code must be a nonempty "
                                     "string when declared"})
                _parse_slot(row.get("expr", ""), f"{mid}.{slot_group}.{rid}",
                            expect, scope, r, set(scope))

    # ---- ports ------------------------------------------------------------------
    for m in membranes:
        mid = m.get("membrane_id")
        if mid not in r.membrane_ids:
            continue
        ports = m.get("ports") or {}
        for direction in ("inputs", "outputs"):
            for p in ports.get(direction) or []:
                pid = p.get("port_id")
                if not pid:
                    r.refuse(E_SPEC_MALFORMED,
                             {"membrane_id": mid,
                              "missing": f"ports.{direction}[].port_id"})
                if p.get("type") not in PORT_TYPES:
                    r.refuse(E_SPEC_PORT_TYPE_MISMATCH,
                             {"membrane_id": mid, "port_id": pid,
                              "type": p.get("type"),
                              "allowed": list(PORT_TYPES)})
                if not str(p.get("sign_convention") or "").strip():
                    r.refuse(E_SPEC_PORT_SIGN_MISSING,
                             {"membrane_id": mid, "port_id": pid})
                cref = p.get("connection_ref")
                if cref not in [c.get("connection_id")
                                for c in r.connections]:
                    r.refuse(E_SPEC_PORT_CONNECTION_UNKNOWN,
                             {"membrane_id": mid, "port_id": pid,
                              "connection_ref": cref})
                    continue
                conn = next(c for c in r.connections
                            if c.get("connection_id") == cref)
                if mid not in (conn.get("members") or []):
                    r.refuse(E_SPEC_PORT_CONNECTION_UNKNOWN,
                             {"membrane_id": mid, "port_id": pid,
                              "connection_ref": cref,
                              "law": "the port names a connection whose "
                                     "members include this membrane"})
                    continue
                ex = conn.get("exchange") or {}
                qref = ex.get("quantity_ref")
                p_dims = _name_unit_dims(p.get("unit", ""), r)
                if direction == "inputs":
                    if p.get("quantity_ref") != qref:
                        r.refuse(E_SPEC_PORT_TYPE_MISMATCH,
                                 {"membrane_id": mid, "port_id": pid,
                                  "law": "an input port carries the "
                                         "connection's exchange quantity",
                                  "expected_quantity": qref,
                                  "got": p.get("quantity_ref")})
                    elif p_dims != canonical_unit(ex.get("unit", "")) \
                            and r.valid:
                        # unit compatibility of the typed port
                        try:
                            want = canonical_unit(ex.get("unit", ""))
                        except ExprRefusal:
                            want = None
                        if want is not None and p_dims != want:
                            r.refuse(E_SPEC_UNIT_MISMATCH,
                                     {"membrane_id": mid, "port_id": pid,
                                      "port_dims": p_dims,
                                      "exchange_dims": want})
                else:
                    qv = p.get("quantity_ref")
                    if (mid, qv) not in r.var_dims:
                        r.refuse(E_SPEC_PUBLISHED_NOT_OWNED,
                                 {"membrane_id": mid, "port_id": pid,
                                  "quantity_ref": qv})

    # ---- assembly ------------------------------------------------------------------
    asm = spec.get("assembly") or {}
    if not asm.get("assembly_id"):
        r.refuse(E_SPEC_MALFORMED, {"missing": "assembly.assembly_id"})
    members = asm.get("members") or []
    if sorted(members) != sorted(r.membrane_ids):
        r.refuse(E_SPEC_MALFORMED,
                 {"law": "assembly.members lists every declared membrane",
                  "members": members,
                  "membranes": sorted(r.membrane_ids)})
    conn_ids = {c.get("connection_id") for c in r.connections}
    for cid in asm.get("connections") or []:
        if cid not in conn_ids:
            r.refuse(E_SPEC_UNKNOWN_MEMBRANE,
                     {"kind": "connection", "id": cid})
    cq = asm.get("conserved_quantity") or {}
    if cq:
        asm_scope: dict = {}
        for mid in members:
            asm_scope.update({v: d for (mm, v), d in r.var_dims.items()
                              if mm == mid})
        for (own, var), d in r.param_dims.items():
            asm_scope[var] = d  # assembly scope sees every declared parameter
        cq_dims = _name_unit_dims(cq.get("unit", ""), r)
        ast = _parse_slot(cq.get("expr", ""), "assembly.conserved",
                          "numeric", asm_scope, r, set(asm_scope))
        if ast is not None:
            try:
                got = infer_dims(ast, asm_scope)
                if got != cq_dims:
                    r.refuse(E_SPEC_CONSERVED_UNIT_MISMATCH,
                             {"declared_dims": cq_dims, "got_dims": got})
            except ExprRefusal as exc:
                r.refuse(exc.code, dict(exc.detail,
                                        slot="assembly.conserved"))
    # initial states
    case_ids = set()
    for case in asm.get("initial_states") or []:
        cid_ = case.get("case_id")
        if not cid_:
            r.refuse(E_SPEC_MALFORMED, {"missing": "initial_states[].case_id"})
            continue
        if cid_ in case_ids:
            r.refuse(E_SPEC_DUPLICATE_ID, {"kind": "initial_state_case",
                                           "case_id": cid_})
        case_ids.add(cid_)
        values = case.get("values") or {}
        for mid in members:
            for st in next((m.get("owned_state") for m in membranes
                            if m.get("membrane_id") == mid), []) or []:
                var = st.get("var")
                if var not in values:
                    r.refuse(E_SPEC_MALFORMED,
                             {"case_id": cid_, "membrane_id": mid,
                              "missing_value_for": var})
                    continue
                v = values[var]
                if not isinstance(v, (int, float)) or isinstance(v, bool) \
                        or not math.isfinite(float(v)):
                    r.refuse(E_SPEC_VALUE_NONFINITE,
                             {"case_id": cid_, "var": var, "value": v})
                    continue
                _check_domain(st.get("domain"), float(v), r, cid_, mid, var)

    # ---- numerics (declared BEFORE any run) ---------------------------------------
    nums = spec.get("numerics") or {}
    if nums.get("method") not in SUPPORTED_METHODS:
        r.refuse(E_SPEC_METHOD_UNSUPPORTED,
                 {"method": nums.get("method"),
                  "supported": list(SUPPORTED_METHODS)})
    dt = nums.get("dt_s")
    rows = nums.get("admissibility") or []
    if not rows:
        r.refuse(E_SPEC_ADMISSIBILITY_TABLE_INVALID,
                 {"law": "the admissible timestep/tolerance table is "
                         "declared BEFORE qualification; it is nonempty"})
    admissible_dts = []
    for row in rows:
        rdt = row.get("dt_s")
        if not isinstance(rdt, (int, float)) or isinstance(rdt, bool) \
                or rdt <= 0 or not math.isfinite(float(rdt)):
            r.refuse(E_SPEC_ADMISSIBILITY_TABLE_INVALID, {"dt_s": rdt})
            continue
        admissible_dts.append(float(rdt))
        if not (row.get("checkpoint_s") or []):
            r.refuse(E_SPEC_ADMISSIBILITY_TABLE_INVALID,
                     {"dt_s": rdt, "law": "declared checkpoints required"})
        for key in ("state_linf_tol", "conserved_drift_tol"):
            tol = row.get(key) or {}
            if not isinstance(tol.get("value"), (int, float)) \
                    or tol["value"] <= 0:
                r.refuse(E_SPEC_ADMISSIBILITY_TABLE_INVALID,
                         {"dt_s": rdt, key: tol})
    if isinstance(dt, (int, float)) and not isinstance(dt, bool):
        if float(dt) not in admissible_dts:
            r.refuse(E_SPEC_DT_NOT_ADMISSIBLE,
                     {"dt_s": dt, "admissible": sorted(admissible_dts),
                      "law": "the assembly timestep is a DECLARED admissible "
                             "value"})
    horizon = nums.get("horizon_s")
    if not isinstance(horizon, (int, float)) or isinstance(horizon, bool) \
            or horizon <= 0:
        r.refuse(E_SPEC_MALFORMED, {"numerics.horizon_s": horizon})

    # ---- qualification ---------------------------------------------------------
    qual = spec.get("qualification") or {}
    ref = qual.get("analytic_reference") or {}
    if not str(ref.get("class_id") or "").strip():
        r.refuse(E_SPEC_MALFORMED,
                 {"law": "qualification.declared analytic reference class "
                         "required"})
    for row in qual.get("integration_checks") or []:
        if row.get("kind") not in CHECK_KINDS:
            r.refuse(E_SPEC_CHECK_KIND_INVALID,
                     {"id": row.get("id"), "kind": row.get("kind"),
                      "allowed": list(CHECK_KINDS),
                      "law": "structural-compatibility checks are "
                             "DISTINGUISHED from numerical-evidence tests"})
    return r


def spec_lang_free_of_placeholders(version) -> bool:
    return isinstance(version, str) and bool(version.strip())


def _declared_value(p: dict, owner: str, var: str, r: SpecReport):
    v = p.get("value")
    if not isinstance(v, (int, float)) or isinstance(v, bool) \
            or not math.isfinite(float(v)):
        r.refuse(E_SPEC_VALUE_NONFINITE,
                 {"owner": owner, "var": var, "value": v})
        return None
    return float(v)


def _validate_provenance(prov, r: SpecReport, owner: str, var: str):
    if not isinstance(prov, dict):
        r.refuse(E_SPEC_PROVENANCE_MISSING, {"owner": owner, "var": var})
        return
    cls = prov.get("class")
    if cls not in PROVENANCE_CLASSES:
        r.refuse(E_SPEC_PROVENANCE_CLASS_INVALID,
                 {"owner": owner, "var": var, "class": cls,
                  "allowed": list(PROVENANCE_CLASSES)})
        return
    if cls == "measured" and not (str(prov.get("store_path") or "").strip()
                                  and str(prov.get("sha256") or "").strip()):
        r.refuse(E_SPEC_MEASURED_UNBOUND,
                 {"owner": owner, "var": var,
                  "law": "a measured parameter binds its pinned bytes "
                         "(store_path + sha256), like every consumed "
                         "constant in the declaration law"})
    for field in ("source", "derivation"):
        if not str(prov.get(field) or "").strip():
            r.refuse(E_SPEC_PROVENANCE_MISSING,
                     {"owner": owner, "var": var, "missing":
                      f"provenance.{field}"})


def _validate_domain(domain, r: SpecReport, mid: str, var: str):
    if domain is None:
        return
    if not isinstance(domain, dict):
        r.refuse(E_SPEC_DOMAIN_INVALID, {"membrane_id": mid, "var": var})
        return
    for key in ("min_exclusive", "min_inclusive", "max_exclusive",
                "max_inclusive"):
        if key in domain and (isinstance(domain[key], bool)
                              or not isinstance(domain[key], (int, float))):
            r.refuse(E_SPEC_DOMAIN_INVALID,
                     {"membrane_id": mid, "var": var, key: domain[key]})


def _check_domain(domain, value: float, r: SpecReport, case_id: str,
                  mid: str, var: str):
    if not isinstance(domain, dict):
        return
    bad = None
    if "min_exclusive" in domain and value <= domain["min_exclusive"]:
        bad = "min_exclusive"
    if "min_inclusive" in domain and value < domain["min_inclusive"]:
        bad = "min_inclusive"
    if "max_exclusive" in domain and value >= domain["max_exclusive"]:
        bad = "max_exclusive"
    if "max_inclusive" in domain and value > domain["max_inclusive"]:
        bad = "max_inclusive"
    if bad:
        r.refuse(E_SPEC_INITIAL_STATE_DOMAIN,
                 {"case_id": case_id, "membrane_id": mid, "var": var,
                  "value": value, "violated": bad})
