// Generated by GameCodeGenerator
#pragma once
#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "FlightComponent.generated.h"

UCLASS(meta = (BlueprintType, Category = "Flight"))
class CHIMERA_API UFlightComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	UFlightComponent(const FObjectInitializer& ObjectInitializer);

	UPROPERTY(EditDefaultsOnly, Category = "Flight")
	float FuelCapacityLiters;

	UPROPERTY(EditDefaultsOnly, Category = "Flight")
	float MaxSpeed;

	UPROPERTY(EditDefaultsOnly, Category = "Flight")
	float ThrustAcceleration;

	UPROPERTY(EditDefaultsOnly, Category = "Flight")
	float TurnRate;

	UPROPERTY(EditDefaultsOnly, Category = "Flight")
	float InertiaDamping;

public:
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	void InitializeFromShip(float FuelCapacityLiters, float ConsumptionRate, float QuantumFuelCost, float QuantumTravelTime);

protected:
	FVector CurrentVelocity;

public:
};
